### ISSUE TITLE
Option list is cliped inside container with overflow: hidden

### ISSUE THREAD

**Issue by faycelbouamoud** [jquense/react-widgets#1007]
Hello,
I tried to put the DropdownList component in a div container with overflow set to hidden and fixed height but the the option list is clipped.

Example:
https://codesandbox.io/s/compassionate-mclaren-nwmsd

**Comment by atomicpages** [comment]
Providing consumers the ability the mount the dropdown might be useful. I'm happy to do some investigation on this :+1:
