### ISSUE TITLE
Docs are out of date and don't mention that 5.0beta is the default install now

### ISSUE THREAD

**Issue by pdenya** [jquense/react-widgets#1015]
`yarn add react-widgets react-widgets-moment` installs the beta branch

Need to specify the version on installing but this isn't mentioned anywhere obvious. `yarn add react-widgets@4.4 react-widgets-moment@4.0`

**Comment by jquense** [comment]
hmm that shouldn't be the case, if i'll fix it

**Comment by jquense** [comment]
should be fixed now
