### ISSUE TITLE
Trim Spaces on Multi select search term

### ISSUE THREAD

**Issue by saivyas** [jquense/react-widgets#1016]
If we enter space as first character then search term, then Multiselect not searching relevant data

**Comment by jquense** [comment]
you can process the search term by controlling `searchTerm` and adding an `onSearch` handler to trim the value and pass it back to the input

**Comment by saivyas** [comment]
Thanks worked !!

Example `searchTerm={this.state.searchTerm}
							onSearch={(val: any) => {
								this.setState({ searchTerm: val.trim() });
								this.handleAutosuggest(val.trim());
							}}`
