### ISSUE TITLE
Dropdown animation choppy in latest Safari

### ISSUE THREAD

**Issue by mquinn-leverege** [jquense/react-widgets#1019]
The dropdown toggle animations (those on the demo page for React Widgets included) are choppy on the latest version of Safari and Mobile Safari (and also in Safari Technology Preview). The dropdown begins to animate normally, then skips back up to the vertical origin of the animation and continues almost as though it is repeating the animation twice.

![Example](https://user-images.githubusercontent.com/46567561/84080367-14fed180-a9aa-11ea-8373-d5fa0f6eac9d.gif)

**Comment by OlyAney** [comment]
I have the same problem with `DateTimePicker`
