### ISSUE TITLE
Multiselect input width clips wide searchTerm

### ISSUE THREAD

**Issue by jon-bloomerang** [jquense/react-widgets#1021]
![image](https://user-images.githubusercontent.com/8630010/85175834-5f077300-b246-11ea-9ca5-05304b715ab3.png)
Screenshot from the react-widgets main page, showing that searchTerm is unnecessarily clipped.

Looks like the problem is the "size" attribute on the input, which appears to be (searchTerm.length + 1). "size" is based on ch (the width of the zero character), so any searchTerm wider than the corresponding number of zeroes gets clipped.

Why does the input use "size" at all? I investigated a couple different workarounds, but none are satisfactory:

- Specifying a custom size (e.g. null, 0, 20) in inputProps. However, the code composes the internal "size" value on top of inputProps, so any custom value is overridden.
- Specifying CSS width in inputProps e.g. ${searchTerm.length}em. This works in theory but exacerbates the existing issue where the input width doesn't match searchTerm width, causing the input to wrap to the next line unnecessarily.
![image](https://user-images.githubusercontent.com/8630010/85176279-75fa9500-b247-11ea-8c20-810ea6cfeef0.png)

**Comment by jquense** [comment]
yeah, we should probably expose this. There are no real good workarounds short of trying to measure the text size which is itself a bad option. In practice `size` as length + 1  usually works  so it's often the right tradeoff. Happy to take a PR exposing some method or config to calculate the size here. Also interested in what like react-select does
