### ISSUE TITLE
unpkg modules

### ISSUE THREAD

**Issue by interspoerri** [jquense/react-widgets#1029]
Can react-widgets be used with [unpkg modules](https://unpkg.com/#query-params)?
e.g.

    <script type="module">
    import Multiselect from 'https://unpkg.com/react-widgets@4.5.0/dist/react-widgets.js?module';

Or named modules instead (`import {Multiselect} from ...`)

Related to #941

**Comment by jquense** [comment]
the dist build doesn't it's a flat bundle, might work with the normal modules tho

**Comment by interspoerri** [comment]
Thanks, that doesn't work either...

I'm actually interested in using this with unprocessed javascript directly in the processor, along with preact. Perhaps that needs ES6 modules support?

(Incidentally react-widgets work great with preact using webpack.)
