### ISSUE TITLE
Multiselect: keyDown overwrite

### ISSUE THREAD

**Issue by rakim3** [jquense/react-widgets#103]
It would be convenient if the `keyDown` handler could be customized through a prop passed to the component. For example, we are wanting to disable the deletion behavior on the “Delete”/“Backspace” keypress.

**Comment by jquense** [comment]
Thanks for the issue, 

I can see why it'd be useful to override the default onKeydown behavior, unfortunately changing it now would constitute a breaking change (changing the order of when the user passed `onKeydown` fires) so its out of the question until a major release, when i may reevaluate this. My instinct is tho that I will probably pass on it, as it adds a bunch of complexity for not a lot of benefit.

In the meantime tho, you can sort of get what you want by watching both the `onKeyDown` and `onChange` to not process certain changes if they were triggered by a Delete or Backspace. Admittedly this is kludgly as the events don't really fire in the correct order here (onChange before onKeydown)
