### ISSUE TITLE
Form submission with dropdown list without a value 

### ISSUE THREAD

**Issue by ssomlk** [jquense/react-widgets#1031]
Hi,

I am using the DropdownList and I want to know whether i can validate the dropdownlist so that a user cannot submit the form without having a selection in the dropdown list??

My form validation is handled by jquense/yup

Cheers.

**Comment by jquense** [comment]
You can do that, but form validation is beyond the scope of these components, as is displaying messages etc. I would suggest using a library like Formik or React Formal (my own)
