### ISSUE TITLE
Allowing cutom tags with multiselect

### ISSUE THREAD

**Issue by adshin21** [jquense/react-widgets#1036]
On the homepage, I see there is an option for creating a custom tag with MultiSelect component.
![image](https://user-images.githubusercontent.com/45573407/92286987-134f9600-ef26-11ea-9de3-3775768b0462.png)

But I am not able to use this as I find no docs for it.
Help, please.
I am using React 16.13.1 with Material UI.
Thank You.

**Comment by jquense** [comment]
It's not super obvious but the docs are here: http://jquense.github.io/react-widgets/api/Multiselect/#onCreate
