### ISSUE TITLE
Multiselect whitespace in Chrome

### ISSUE THREAD

**Issue by fivepapertigers** [jquense/react-widgets#1043]
Found a pretty strange alignment issue in Chrome that shows up after `4.4.9`, presumably due to #904. 

This is in chrome on a totally bare React app, using `4.4.8`
![image](https://user-images.githubusercontent.com/14054011/96304702-8ee33f00-0fca-11eb-95ca-d839ba54f00d.png)

And this is using `4.4.9` (and all the way up to up to `4.5.0`) 
![image](https://user-images.githubusercontent.com/14054011/96304791-bdf9b080-0fca-11eb-82ca-b7fd70f3850d.png)

FWIW, this is firefox on `4.5.0`:
![image](https://user-images.githubusercontent.com/14054011/96305154-6f98e180-0fcb-11eb-9b53-94dee974c1ae.png)

**Comment by Hyped-247** [comment]
I am having the same problem. Let me know if you were able to solve it. 

Mo,

**Comment by ocdi** [comment]
I am also having this issue in both Chrome and Firefox. Incidentally reverting the changes made in #904 actually result in the UI being correct. It might be that Firefox was wrong at the time but has normalised the layout to match Chrome. I tested this using Firefox 84.0.2. I'm going to downgrade back to 4.4.8

**Comment by jquense** [comment]
don't see this with v5
