### ISSUE TITLE
Comboboxes match text on valueField values

### ISSUE THREAD

**Issue by StickOnGit** [jquense/react-widgets#1045]
When text is typed into a Combobox, if the `valueField` for that Combobox is a string, the Combobox will match a data object on its valueField value. It does not appear to do a similar match using the `textField` value.

This can be reproduced on your demo page. Navigate to https://jquense.github.io/react-widgets/api/Combobox/#valueField and change each `id` in the `colors` array to a string, update the `defaultValue` to be a string, then use the provided Combobox and type any valid `id` into the textfield. The Combobox will update with the matching `name` text.

```
let { Combobox } = ReactWidgets;

let colors = [
  { id: '0', name: 'orange'},
  { id: '1', name: 'purple'},
  { id: '2', name: 'red' },
  { id: '3', name: 'blue' },
];

let widget = (
  <Combobox
    data={colors}
    valueField='id'
    textField='name'
    defaultValue={'1'}
  />
)

render(widget); // type any of the id strings into the textfield and see that the combobox will display the corresponding name
```

Apart from this being on the surface an odd way for a component to behave - ideally the user would not need or have special knowledge of any data option's `valueField` value - it can also lead to misleading situations where the `textField` and `valueField` are near matches, but not exact matches, and so the underlying component may not be behaving correctly. If a developer is counting on the correct `onChange` and `onSelect` handlers to fire the same when a user types the `textField` value instead of the `valueField` value then they would also be surprised to find that the component is not updating as expected.

Furthermore, looking at the duo values that are provided to the `onChange` handler, it isn't clear that a value provided by typing into the textfield is ever matched to a data object. Adding an `onChange` handler that logs to the console shows that the previous value will only come back as an object from the `colors` array when a user uses the dropdown menu to make a selection or presses `Enter`; typing a match on `textField` and/or `valueField` will provide the string that was typed but will not provide the matching object from the `data` array.

```
let { Combobox } = ReactWidgets;

let colors = [
  { id: '0', name: 'orange'},
  { id: '1', name: 'purple'},
  { id: '2', name: 'red' },
  { id: '3', name: 'blue' },
];

let widget = (
  <Combobox
    data={colors}
    valueField='id'
    textField='name'
    onChange={(next, last) => console.log({ next, last })} // the 'last' value will not be an object from the 'colors' array unless the mouse was used to select it, it will simply be the string that was last typed
    defaultValue={'1'}
  />
)

render(widget);
```

These create a situation where neither the user nor the consumer is getting quite the experience they may expect. As a developer, I would never expect a typed value to attempt a match on the Combobox's `valueField` values. I would also expect to inspect this object in a way where, if the typed value in a combobox did match the `nameField` of a data object, that object would be returned instead of just the string the user entered in order to get the Combobox into that state.

**Comment by jquense** [comment]
There are a few reasons for the current behavior, some of which are more technical than UX specific. There still good reasons for acting this way tho, but many of them are more specific to dev usage. it's totally reasonable to think the current behavior is confusing or annoying. Allowing both behaviors has been hard in v4, but in v5 it's customizable via a prop (if I'm remembering correctly, writing on a phone)

**Comment by jquense** [comment]
https://jquense.github.io/react-widgets/docs/Combobox#autoSelectMatches
