### ISSUE TITLE
DropDownList slow render when data is large

### ISSUE THREAD

**Issue by KingKuess** [jquense/react-widgets#1046]
I searched extensively for a solution but when data is too large the component can cause  RangeError: Maximum call stack size exceeded. 

Workaround:
-Provide a pre-sliced list so as not to overload the component
-Modify onSearch to modify the passed in pre sliced list from some large source list.

Suggested solution:
-Allow a max items prop to slice data within component:
-Default max to some number that doesn't cause render issues.
I.E:

if (open)
      data = Filter.filter(data, {
        filter,
        searchTerm,
        minLength,
        caseSensitive,
        textField: accessors.text,
      }).slice(0, maxItems) //this would be the change

**Comment by jquense** [comment]
this is something you can do oneselv or used react-widgets-virtualized for long lists
