### ISSUE TITLE
Placeholder doesn't show for Multiselect with selected items

### ISSUE THREAD

**Issue by dubrowgn** [jquense/react-widgets#105]
The current implementation hides the placeholder text when a Multiselect has selected items. This can be confusing for new users who load up a page where Multiselects are pre-populated with data, because there is no indication as to how to interact with the control.

My proposal is to always show the placeholder text. The MultiselectInput control already supports auto-sizing with a placeholder, so there shouldn't be any issues there.

**Comment by jquense** [comment]
Thanks for the issue,

I see where you are coming from on this, but I think the current behavior is more consistent with how placeholders work for inputs, which is they only show then the input is value-less. I realize that is somewhat of an arbitrary restriction in this case, but its a problem that needs to be addressed for any `<input/>` anyway so I'd rather the behavior at least be similar.

**Comment by dubrowgn** [comment]
It depends if you view the entire Multiselect as one whole input, or the MultiselectInput as its own nested input. In my mind it makes more sense for the MultiselectInput to behave as it's own input: showing the placeholder when empty and hiding the placeholder when not empty. The MultiselectInput behaving differently than all other inputs seems inconsistent and was surprising to me.

The reason it is such an issue for us, is because we are using it as a multi-select search box. Typically, if there is no placeholder in a Multiselct with data, the user can click the control and see the available options. In our case, the user clicks the control and sees an empty results list, as a search has not yet been executed. Without the placeholder prompting them to search, they reasonably assume there are no available options left to select from.

**Comment by jquense** [comment]
> ...the user can click the control and see the available options. In our case, the user clicks the control and sees an empty results list, as a search has not yet been executed

In that case I would use the [`messages`](http://jquense.github.io/react-widgets/docs/#/multiselect/messages) prop to set the `emptyList` or `emptyFilter` message to be something helpful :)

**Comment by dubrowgn** [comment]
Hmm, that would definitely help. Thanks for pointing that out!

It would still be very helpful to be able to show a placeholder with items selected. Placeholder hints like "type a person's name" are still relevant and useful when there are already people selected for example.
