### ISSUE TITLE
Issue with display of Calendar over table row in the react-table.

### ISSUE THREAD

**Issue by rahulmathews** [jquense/react-widgets#1056]
I am using `react-table` as a Table library.  I am trying to use `DateTimePicker` as a date-time picker as a `Cell`  displayed as a cell content. Everything is fine, but when I click on either the calendar or time icon, the calendar or time popup seems to display below the other component. I dont know whats wrong. I tried using the z-index to display it over the other `div`s, but no luck. Can you suggest a solution for this problem? Attaching a image for reference.

![Screenshot from 2021-01-08 18-05-58](https://user-images.githubusercontent.com/27402666/104016652-c1bd5d80-51dc-11eb-9c8f-af5b8e6877b4.png)
Please check the Manufacturing Date in the first row.

**Comment by jquense** [comment]
this is how absolutely positioned elements work unfortunately. In the near future i'd like to provide an alternative for these cases using popperJS, but until then you can create something yourself with the `popupComponent` prop
