### ISSUE TITLE
prevent autotarget item

### ISSUE THREAD

**Issue by StensenE** [jquense/react-widgets#1057]
When I search and hit enter in the Combobox, it always target first item from DropdownList and fire it of, instead of fire of the string in Combobox. I'm using filter="contains"
Is there a simple fix for it? I couldn't find anything in the documentation. 

In this scenario I want to search for "bergen" when hitting enter, but instead first item in DropdownList is firing instead.
<img width="1152" alt="dropdown" src="https://user-images.githubusercontent.com/22217945/104566164-8d6af680-564d-11eb-889e-c7882854c57e.png">

**Comment by jquense** [comment]
hitting enter to "search" isn't really the UX intended for these inputs, you can however control the focus behavior by setting `focusFirstItem` which is now `false` as the default in v5
