### ISSUE TITLE
DateTimePicker Widget: Double clicking on  Left/Right Chevron Arrows causes a transition issue

### ISSUE THREAD

**Issue by eloymazza-tc** [jquense/react-widgets#1062]
When user double click on Left/Right Chevron Arrows in order to change month/year, the calendar closes and open suddenly. 

The issue happens in https://jquense.github.io/react-widgets/api/DateTimePicker/  example indeed.

![calendarClosesOnDBClick](https://user-images.githubusercontent.com/78486926/109516522-0cde4900-7a87-11eb-97c6-89fb10f93625.gif)

**Comment by jquense** [comment]
should be addressed in latest version
