### ISSUE TITLE
Different tagComponent background colors in Multiselect  component

### ISSUE THREAD

**Issue by nemanja3** [jquense/react-widgets#1065]
Hello,

is there an option to have different colors on each tag ? is see there is a `<li>` container that has span and a div inside. When i change the bakcground color of an tagItem the color is applied only on the span and not the div. Is there a way to apply the color to the whole tag component?

![image](https://user-images.githubusercontent.com/26413661/111403539-6c666680-86cd-11eb-8a2c-f9bafc02bd99.png)

thank you

**Comment by markerikson** [comment]
Seems like the real issue here is that the `tagComponent` props only lets you customize the "item content" for the tag, and not replace the entire rendered tag itself.

**Comment by nemanja3** [comment]
![image](https://user-images.githubusercontent.com/26413661/112697852-c105a080-8e88-11eb-88bd-a7caa43bca12.png)

Yes thats the problem becouse tagComponent has 2 divs, one is for the content which you can color, the other one is for the "X" and you cant apply styles for that one. I think it can be an easy fix so the style that applyes to the content div applyes also to the "x" div.

**Comment by jquense** [comment]
v5 added the absurdly named `tagOptionComponent` to cover this
