### ISSUE TITLE
DropdownList not showing input value if autocomplete == "off" (v5)

### ISSUE THREAD

**Issue by olmobrutall** [jquense/react-widgets#1066]
The following code works: 

```TS
<DropdownList  data={getOptionLites()} onChange={lite => p.onChange(lite ?? null)} 
        value={lite}
        filter="contains"
        dataKey="value"
        textField="label"
        renderValue={a => p.onRenderItem!(a.item)}
        renderListItem={a => p.onRenderItem!(a.item)}
      />
```

But shows all the inline input/autofill stuff. For DropdownList with a few values if you set `autocomplete="off"` then the value is not shown once selected. 

It happens because there is not case where `inputValue` is shown when autoComplete == 'on'

https://github.com/jquense/react-widgets/blob/9fcefd1b028674585d73695c8c31ea6f6c896376/packages/react-widgets/src/DropdownListInput.tsx#L123

**Comment by jquense** [comment]
oops

**Comment by jquense** [comment]
should be fixed
