### ISSUE TITLE
Delete item from multiselect list

### ISSUE THREAD

**Issue by nemanja3** [jquense/react-widgets#1067]
Hello, is there an option to delete an item from the list?
There is an option to add a new with onCreate method. Is there a prop to be activated on true, that adds an "X" in every item row in a list so you can delete that item from the list ?

Example:
![image](https://user-images.githubusercontent.com/26413661/112615173-718c8980-8e22-11eb-885d-d31431dd9ad2.png)

Thank you

**Comment by jquense** [comment]
There is not, tho you could probably add one yourself with the itemComponent prop

**Comment by nemanja3** [comment]
i understand, didnt see that prop. Thank you !
