### ISSUE TITLE
Clear or reset combobox

### ISSUE THREAD

**Issue by Gaetanbrl** [jquense/react-widgets#1068]
Hi,

I create a combobox with object data. So i use `textFIeld` and `valueField` props.

Combobox load data from async request (api) and are used as filters to manage others data.
This works fine.

But now, i search to clean combobox text value when i click on a button "reset all", for each combobox in same parent component.

Is it possible ?

Thanks.

**Comment by jquense** [comment]
you can reset input values be controlling the `value` prop and setting it to `null` or `''` on click
