### ISSUE TITLE
When using DropdownList with datakey, both values are displayed

### ISSUE THREAD

**Issue by kris2kris** [jquense/react-widgets#1070]
Hello,

When using a datakey on DropdownList, datakey and textField are displayed.
You can see it on the documentation page https://jquense.github.io/react-widgets/docs/DropdownList/#dataKey

I fixed it with some CSS in my project, but it would be better to fix it directly here
`.rw-dropdown-list-input > *[tabindex="-1"] {
  color: $white
}`

**Comment by jquense** [comment]
should be fixed in latest patch version
