### ISSUE TITLE
renderListItem not found in types of Dropdownlist

### ISSUE THREAD

**Issue by djapal** [jquense/react-widgets#1072]
I'm trying to add `renderListItem` as property in a Dropdownlist component in a typescript file but typescript complains that this is not found.
I checked with version  `"react-widgets": "4.4.11"` and `"@types/react-widgets": "4.4.4"`

**Comment by jquense** [comment]
renderListItem isn't available in v4, its a v5 prop

**Comment by djapal** [comment]
tried with 5.0.3 still the issue is there. is there another version of `@types/react-widgets`? 4.4.4 doesnt include this property

**Comment by jquense** [comment]
v5 includes it's own type definitions

**Comment by djapal** [comment]
aaa great! thank you for the hint. I'll try it again (need to migrate some stuff!)
