### ISSUE TITLE
Pre version 5 documentation

### ISSUE THREAD

**Issue by jdhorner** [jquense/react-widgets#1073]
We're heavily invested in version 4 of react-widgets, so it will be a while before we can transition to version 5. Do you still have the documentation for the previous version? I don't see a way to access it via the [main docs page](https://jquense.github.io/react-widgets/docs/).

**Comment by jquense** [comment]
It's hosted anywhere, but it's all still in git. you can pull the tag your interested in or look through the gh-pages branch history
