### ISSUE TITLE
DatePicker will not update displayed value

### ISSUE THREAD

**Issue by albchu** [jquense/react-widgets#1074]
Hi there, I am trying to utilize `DatePicker` in the latest version of react-widgets 5. I am having trouble getting the displayed value to update once I select a new date. Here is a[ codesandbox example](https://codesandbox.io/s/react-widgets-datepicker-bug-og3eb) of this issue in action. Essentially here is all I'm doing:

```javascript
import "react-widgets/styles.css";
import DatePicker from "react-widgets/DatePicker";

import { useState } from "react";

export default function App() {
  const [date, setDate] = useState(new Date());

  return (
    <div className="App">
      <h1>ReactWidgets DatePicker Bug</h1>
      <h2>Current Date: '{date && date.toISOString()}'</h2>
      <DatePicker value={date} onChange={setDate} />
    </div>
  );
}
```

The dump of the `date` state shows that the value changes properly from the `onChange` but the input field does not update.

**Comment by jquense** [comment]
this seems to be an issue with StrictMode, likely due to the double render creating weirdness. I'm not sure what the right fix is here but i'll mess around

**Comment by albchu** [comment]
You're the best! Thanks Jason
