### ISSUE TITLE
DropdownList: disabled property does not work for an array of objects.

### ISSUE THREAD

**Issue by evpozdniakov** [jquense/react-widgets#1083]
It works fine for the case like in your example page:
![image](https://user-images.githubusercontent.com/1109345/122203822-561ba280-ce96-11eb-9c27-f0ddfdd856f2.png)

But if the data property is an array of objects like `{ id, name }` then there is no way to disable a particular item.

Here is an example:
```javascript
<DropdownList<{ id: string, name: string }>
  data={[{ id: 'one', name: 'One' }, { id: 'two', name: 'Two' }, { id: 'three', name: 'Three' }]}
  dataKey="id"
  disabled={[{ id: 'one', name: 'One' }, { id: 'two', name: 'Two' }]}
  open
  textField="name"
/>
```

The result:
![image](https://user-images.githubusercontent.com/1109345/122205011-acd5ac00-ce97-11eb-91c2-e61f8acf2341.png)

**Comment by jquense** [comment]
that is because it does a `===` comparison of the objects in the array, for performance reasons. You should use the actual instances of your data items

**Comment by evpozdniakov** [comment]
@jquense thank you, make sense!
