### ISSUE TITLE
Unable to set selected-bg with SASS module configuration.

### ISSUE THREAD

**Issue by AlexMayleRdn** [jquense/react-widgets#1092]
The background of the active element in a list seems to be controlled by the `$selected-bg` SASS variable. However, it is not part of the variables.scss file. When I try to override it like so

```
@use "~react-widgets/scss/styles.scss" with (
    $selected-bg: "#64A1E2"
);
```
I get
```
SassError: SassError: This variable was not declared with !default in the @used module.
   ╷
17 │     $selected-bg: "#64A1E2"
   │     ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jquense** [comment]
you are looking for `$list-selected-bg` at the top level

**Comment by AlexMayleRdn** [comment]
Thanks! That worked.

I don't understand, though. `$list-selected-bg` is not defined in the variables file?

**Comment by jquense** [comment]
they are defined in the list module and forwarded with a prefix: https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/scss/components.scss#L1
