### ISSUE TITLE
navigation with keybord

### ISSUE THREAD

**Issue by jirsik** [jquense/react-widgets#1097]
Hi, navigation in DropdownList  with keyboard shortcuts is not working in version 5.2.0
It is not working even for examples in the documentation, so it is not a problem with my implementation.
With 4.6.1 it was working fine.

**Comment by jquense** [comment]
not sure what you mean? it looks like it works fine in the documentation, just tried it.

**Comment by jirsik** [comment]
sorry, it was a problem with my monitor not displaying keyboard navigation
