### ISSUE TITLE
Dropdowns no longer set the first item to focused

### ISSUE THREAD

**Issue by AaronBuxbaum** [jquense/react-widgets#1100]
As of version ~5.3.0 (this works on ~5.2.0), the first item in a dropdown is no longer set to focused

before: `<div role="option" data-rw-option="" data-rw-focusable="" tabindex="-1" aria-selected="false" class="rw-list-option rw-state-focus" id="rw_10_listbox_active_option" data-rw-focused="">`

after: `<div role="option" data-rw-option="" data-rw-focusable="" tabindex="-1" aria-selected="false" class="rw-list-option">`

**Comment by jquense** [comment]
check that you don't have two versions installed accidentally

**Comment by AaronBuxbaum** [comment]
yup, that was it!
