### ISSUE TITLE
q: why 'react-widgets' package depends on '@types/classnames'?

### ISSUE THREAD

**Issue by ZuBB** [jquense/react-widgets#1106]
Can you explain what was the motivation to add '@types/classnames' as a runtime dependency for a 'react-widgets' package?

if you need types for that package -- that dependency has to be moved to "devDependecies" section. 

In the latest versions classnames package goes with its own version of types and it creates some confusion 

Do I miss something?

source commit https://github.com/jquense/react-widgets/commit/a02861767ea3f758837b2dedaa24e087e8e96d5c

**Comment by j2ghz** [comment]
> ah if they started including types then yeah we should remove the DT types

The [package](https://www.npmjs.com/package/@types/classnames) is now deprecated, can it be removed?
