### ISSUE TITLE
Combobox with placeholder does not expand properly in IE

### ISSUE THREAD

**Issue by nickknw** [jquense/react-widgets#112]
When a combobox is blank and has a placeholder value set, it starts to show weird expand/collapse behaviour in IE. It seems to act like each mousedown/mouseup is a full click event. Trying to expand the dropdown normally results in it very briefly popping down and then back up again as soon as you lift your finger off the mouse. 

A bit hard to describe, I have a screen recording that shows it. [Here it is](http://s000.tinyupload.com/index.php?file_id=81283478785646391895) (hosted on tinyupload). Let me know if there are better options for hosting short videos.

This is IE11 on Windows 8.

**Comment by jquense** [comment]
Oof this is ugly. I will have a fix for this soon, I.E fires an input event when setting/unsetting the placeholder which is triggering the popup toggle twice.

**Comment by nickknw** [comment]
Awesome, thanks!
