### ISSUE TITLE
DropdownList goesn't use messages from Localization

### ISSUE THREAD

**Issue by edwinvanderelst** [jquense/react-widgets#1122]
A app root I have this:
`<Localization messages={{ emptyList: 'Geen items'}}
 ...
</Localization`

The DropdownList doesn't use the message, but always displays the default text.

**Comment by jquense** [comment]
wanna send a PR to fix it?

**Comment by edwinvanderelst** [comment]
[https://github.com/jquense/react-widgets/pull/1123](url)
