### ISSUE TITLE
How do I use <Localization>?

### ISSUE THREAD

**Issue by jliang117** [jquense/react-widgets#1156]
This is version 5.8.4
I'm trying to add my custom date format to DatePicker using moment, and am not seeing the import for the Localization component in the documentation anywhere - is it a separate library? I thought it was the one included here https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/Localization.tsx
but wrapping my component with that provider errors.

**Comment by jliang117** [comment]
Nevermind, resolved

**Comment by CosmicBara** [comment]
How did you resolve this @jliang117 ?
