### ISSUE TITLE
Error when using with Webpack

### ISSUE THREAD

**Issue by BJTerry** [jquense/react-widgets#116]
I can't seem to get react-widgets to work at all when used with webpack. I have created a repo that doesn't work, but it basically just loads react-widgets into the page, so I have no idea what the problem is.

https://github.com/BJTerry/webpack-backbone-error
(Don't mind the name)

**Comment by jquense** [comment]
Hi there,

The problem is almost certainly that the bower version of react-widgets is being bundled, but that version is already 'bundled' and expects all its dependencies to be globals (react and globalize.js). To use react-widgets with webpack either install the npm version which is modular, or make sure that globalize and React are set up as externals in your webpack config.

**Comment by BJTerry** [comment]
react-widgets and react in that repository are both bundled with npm, if you examine the jsons. I just use bower for other things.

**Comment by jquense** [comment]
that's be your intent but that doesn't look like what's happening. looking at the  bundle in the repo link the react widgets bundled there is very clearly the bower package (notice it's minified, the npm one wouldn't be)

**Comment by BJTerry** [comment]
Thank you, it appears that was the hint I needed. If I just let webpack figure out what react-widgets to use, I guess it was deciding to use the bower version from the npm repository (since the bower version wasn't installed), but when I added an alias for react-widgets to 'node_modules/react-widgets/lib/index.js' explicitly it found the right version. I had thought that if you just imported 'react-widgets' it would import the file specified in node_modules/react-widgets/package.json's 'main' entry, but I am new to webpack so I must be mistaken on how these imports are resolved.

**Comment by BJTerry** [comment]
Ah, the problem was I was using the DirectoryDescriptionFilePlugin to resolve, and it searches for bower.json files, so it must be taking precedence over the default in npm packages. When I remove that I don't need the alias.

**Comment by jquense** [comment]
that's good to know, and luckily future releases to npm ignore the bower.json file so that should n't be a problem in the future :)
