### ISSUE TITLE
react-native support ? 

### ISSUE THREAD

**Issue by mydearxym** [jquense/react-widgets#117]
amazing work!
is this component support react-native?

**Comment by jquense** [comment]
Thank you :)

I don't think so, since they are UI components, they'd need to be written in the React native base components instead of the DOM--a whole port of the library, which is not on the radar

**Comment by mydearxym** [comment]
thanks for reply ~
just don't know how to use a ui lib in react-native ~

**Comment by brigand** [comment]
@mydearxym you need components that specifically target react-native for iOS; when Android support comes out you need components that specifically target Android. 

iOS, Android, and Web are three different platforms.

> "Write once, run anywhere" - Java



> "Learn once, write anywhere" - react-native

**Comment by mydearxym** [comment]
@brigand  yeah  i decide to  use webView in react-native to use those 3-part components ~
