### ISSUE TITLE
Accept component, function, or replacement token for localised strings

### ISSUE THREAD

**Issue by andru** [jquense/react-widgets#118]
Problem:

`createNew` message on `multiselect` is inflexible: it does not allow placement of the value within the localized text.  Likewise for `emptyFilter`.

e.g. Setting the `createNew` message to something like this is not currently possible:  `Add [text] as a new item` 

It seems like passing a component might be overkill, maybe a function or a replacement token?

e.g.

```
<Multiselect
messages={{
    createNew: value=>'Add '+value+' as a new item'
}} />
```

or

```
<Multiselect
messages={{
    emptyFilter: 'There are no items matching `%s`'
}} />
```

**Comment by jquense** [comment]
fair enough, I will probably just allow functions as alternatives to strings here, you can return a React Element though and it should just work...best of both worlds
