### ISSUE TITLE
How to swap Globalize.js for Momentjs?

### ISSUE THREAD

**Issue by mrozbarry** [jquense/react-widgets#119]
There is plenty of documentation describing the ability to swap these, but I have been strugging to figure out how to actually do it.

Here is what I have (in plain old javascript - I did some monkey patching from my production code to make this relatively clear, but I do realize the React.render() bound element is static here which isn't the case in the production code):

    $('.datetime').each(function(index, el) {
      dateObject = new Date()
      if (el.value) dateObject = moment(el.value, "MMM D, YYYY h:mm A").toDate()

      React.render(
        window.ReactWidgets.DateTimePicker({
          // The documentation says parse and format need to be passed as props,
          // however, there is no documentation outside of following through the code
          // to know what arguments are being passed and what a function should be
          // returning.
          parse: function(dateStr) { return moment(dateStr).toDate() },
          format: function(date) { return moment(date).format('MMM D, YYYY h:mm A') },
          editFormat: function(date) { return moment(date).format('MMM D, YYYY h:mm A') },
          defaultValue: dateObject,
          step: 60,
          onChange: function(date) { el.value = moment(date).format("MMM D, YYYY h:mm A") }
        }),
        document.getElementById('my_datetime_for_el')
      );
    }

The initial render is fine, but when I click to edit the field, I get a javascript error `Cannot read property 'format' of undefined` which seems to be coming from the internal format function on the component.

Why not use a global-type swap, like this:

    ReactWidgets.statics.dateToString = function(date) { /* return a String object */ }
    ReactWidgets.statics.stringToDate = function(dateStr) { /* return a Date object */ }

Now every component that uses Globalize for date time can start using ReactWidgets.statics.whicheverDateFunction and these functions are in a place that are easily overridable for other developers.

This would definitely stop this cat and mouse game of overridding all the smaller functions that may or may not use globalize.  Another smaller fix would be to give clearer documentation on what properties need to be overridden with what type of functions.

**Comment by jquense** [comment]
Hey there thanks for the issue. 

Yeah right now there is not a lot of clarity on how to fully swap out localization functions. I'm working on a broader more robust API to make the locale stuff feel fully pluggable. For now though you are on the right track, you can poke around this doc page I've been working on (unfinished) that demonstrates a little how to do it.http://jquense.github.io/react-widgets/docs/#/advanced but in general you just need to make sure all formats and parse functions are covered by props

formats functions pass 2 arguments: value, culture string if it exists 

parse should be the same. 

I'm sorry about the lack of documentation general,  I have been moving the API away from being fully dependent on Globalize.js but it isn't really the most ergonomic (but doable) API yet, for doing app wide replacement. I also don't have as many tests around that as I'd like so please report any bugs you run into

**Comment by mrozbarry** [comment]
Same issue with the provided code.  [This](https://github.com/jquense/react-widgets/blob/master/src/util/dates.js#L39) looks like the point of failure.

**Comment by jquense** [comment]
if its failing there, there is a format prop that isn't set to a function somewhere, if it was it should not get to the globalize call can you pause on exceptions and back up the stack to see what's failing?

**Comment by mrozbarry** [comment]
Well, I'm just going to go back to another datetimepicker for the time being.  We were using bootstrap-datetimepicker (which seems to be horribly broken), but have inter-dependencies with momentjs.  We're not able to justify both momentjs and Globalize.  We're going to settle with writing a few hacks around the bootstrap datetimepicker (which works for our purposes), and maybe check in on this projects after a while to see if there is better backend swapping support and more documentation.

**Comment by jquense** [comment]
well good luck to you, sorry it didn't work out this time around. You may want to also check out http://dubert.github.io/react-kronos/ which is another datepicker for react, in part based on this one, but uses momentjs

**Comment by mrozbarry** [comment]
Just to update, react-kronos suffers from my same concerns (lack of solid documentation being the biggest), plus it's in early infancy meaning that it may not be in a state that will remain consistent, and it doesn't have some of the features I want (mainly control over time granularity in the time picker).

I'm going to peek through this repo this weekend and perhaps make a pull request with some updates regarding hard-dependency on globalize, and perhaps some documentation.  No guarantees, though, since it's a Canadian holiday as well.

**Comment by jquense** [comment]
you might want to look at the 'localizer' branch here, which is most of the way done. I am hoping I can get it out the door relatively soon. it is functionally complete I am still just struggling to make sure the api is flexible and useful enough to do what most people might want. 

I mention it b/c I'm always glad to have PR's but I wouldn't want you to do a bunch a work to that could be made outdated by an upcoming branch merge. I also mention it because technically it just codified and collects most of what's needed into a single spot, which can be helpful for figuring out what formats to replace and what the arguments are, etc.

**Comment by wiredmax** [comment]
Just curious, when you say you're hoping to get it out of the door relatively soon you mean in many months or a few weeks?

**Comment by jquense** [comment]
@wiredmax very close, Its actually already in the current version but undocumented. I need to get a moment to update docs and and make sure the api works for a bunch of options before I commit to it and make it officially public.

**Comment by jquense** [comment]
All documented as of 2.7.0 http://jquense.github.io/react-widgets/docs/#/i18n

you can write your own moment localizer or use the one I wrote: https://github.com/jquense/react-widgets-moment-localizer

let me know how it goes

**Comment by wiredmax** [comment]
Awesome! That was fast! Thanks :+1: 

![yes](http://www.gifbin.com/bin/032010/1269602956_dr-mccoy-and-captain-kirk-approve.gif)
