### ISSUE TITLE
React Widgets looks off

### ISSUE THREAD

**Issue by komocode** [jquense/react-widgets#121]
Here's what it looks like right now 

![Image]
(http://i.imgur.com/DMQSRPg.png)

Here's my code:
http://pastebin.com/vCad9qNC

Most likely it looks like a CSS issue. But I'm not certain. Any ideas?

**Comment by jquense** [comment]
are you including the react-widgets css file? if not that's your problem otherwise something else in your stack overriding the styles.

**Comment by komocode** [comment]
Sorry if this is trivial, learning on the way.

I installed react-widgets via npm. Using gulp to run browserify tasks. Do I include this CSS file : /node_modules/react-widgets/dist/css/react-widgets.css?

**Comment by komocode** [comment]
Ok. I got it. Closed. Thanks.
