### ISSUE TITLE
Problem with the focus (DatePicker/TimePicker)

### ISSUE THREAD

**Issue by Antho2407** [jquense/react-widgets#122]
Hello, I am using your amazing plugin, but I've got one problem when I use it with Firefox OS. When I click on the button opening the DatePicker or the TimePicker, the mobile keyboard is showing. 

Could you help me with this ?

**Comment by jquense** [comment]
that sounds right, clicking on the picker focuses the input for typing in dates, which would trigger the keyboard. There may be a platform specific way to disable the keyboard on certain inputs but I am not familiar with Firefox OS
