### ISSUE TITLE
Support ReactLink (aka valueLink prop)

### ISSUE THREAD

**Issue by idolizesc** [jquense/react-widgets#123]
It's nice having controlled components via `value` and `onChange`, but it's even more convenient to be able to use [`valueLink`](https://facebook.github.io/react/docs/two-way-binding-helpers.html) to set state without having to define a new function for every single input component in the form.

Any chance of adding support for this? It should be a pretty straightforward addition (see [this component](https://github.com/olahol/react-tagsinput/blob/master/react-tagsinput.js#L111) for a nice way of supporting both easily) and it would bring these widgets closer in line with the standard React `<input>` widgets (which all support `valueLink`).

**Comment by jquense** [comment]
Hi there thanks for the issue. 

I've thought about supporting valueLink but at this point react is going to be depreciating it so I am not sure if it's worth it. I will check in with the react team to see when this is happening. if it's far off I'll reconsider it :)

**Comment by idolizesc** [comment]
AFAIK `valueLink` isn't being deprecated, but the mixin in `react/addons` may be deprecated in favor of something else.

**Comment by jquense** [comment]
This should in in `2.7.0` uncontrollable upstream supports this now so we do to now
