### ISSUE TITLE
error if I supply a default value for DatePicker

### ISSUE THREAD

**Issue by deezahyn** [jquense/react-widgets#124]
Getting an error if I supply this Date to DatePicker
2015-05-01T13:34:54.091Z

Thing is this is what the DatePicker's original output.  It's weird when you supply it with the same value you get from the widget it throws an error.

stack trace

```
Uncaught TypeError: dt.getTime is not a functiondateOrNull @ bundle.js:26810
```

**Comment by jquense** [comment]
Hi there, 

the date picker takes a Date object as a value not a string. Native inputs only work in string values, a limitation of html, react-widgets is specifically designed to work with typed values pickers: number pickers return numbers and date pickers return dates. if you want to use an iso string in the picker, convert it to a date before setting the value. 

for more info you can read the docs which also give the expected type of each prop.

**Comment by deezahyn** [comment]
I get it, here's the problem, if I save it to localstorage, the date object becomes a string and if I parse it it still returns a string.

updating the dateOrNull function to something like this:

```
function dateOrNull(dt) {
  if (dt) { dt = new Date(dt) }
  if (dt && !isNaN(dt.getTime())) return dt;
  return null;
}
```

Works.  I was wondering if the library should handle this scenario because this is a potential gotcha.  Also do you have any advice how I iterate over objects and check if its an actually a Date object instead of a string?

**Comment by jquense** [comment]
I don't think this is something the library should handle, there are already plenty of libraries and utilities that you can use for serializing and deserializing objects to localstorage. for this case though all you need to do is convert the string back to a date when you pull it out of localstorage. 

you can check if an object is a date or a string by using typeof: `typeof object === 'string' `
