### ISSUE TITLE
Dropdown/Multiselect: Function for result ordering

### ISSUE THREAD

**Issue by andru** [jquense/react-widgets#126]
An optional sort function, working similarly to the `filter` function, would be useful to allow for custom ordering of search results  e.g. by relevance score.

It could follow the same approach as [Immutable.Iterable.sort](http://facebook.github.io/immutable-js/docs/#/Map/sort).

While this can be achieved with a H.O.Component or Wrapper approach, doing so necessitates also pulling the filtering logic into the parent, since ordering results needs to happen after filtering. As far as I can see, that means it's not possible to take advantage of the built-in filters without getting hacky.

**Comment by jquense** [comment]
hmm I don't really want to be in the business of sorting the data, it's already unfortunate that I need to handle filtering in the components. In this case I'm not sure why sorting would need to come after filtering. It's more inefficient (if you have large data lists the sorting won't be your bottleneck anyway) but it shouldn't make technical difference, unless I'm missing something. 

A use case like sorting on filter relevance is probably going to be tightly bound to the implementation of your filter logic anyway, so if you did need to filter first it should be as simple as running the data through your filter function and using the result, no need to rewrite anything more. Sorry for the lack of code illustrations not near a computer this weekend but I'd be happy to try and clarify in a few days if my words aren't clear enough :)

**Comment by andru** [comment]
Fair enough.  It's certainly the prescence of filter functionality that makes me want sort functionality.  One without the other feels awkward,  but if you're already feeling like the filter is functionality you'd rather not implement then I can understand the logic.

In any use case where sorting is not static, sorting is more efficient after filtering.  In my use case, items are sorted based on a score calculated from their proximity to the searchTerm.

Given a searchTerm of "Pres", for example, "**Pres**s" would have a higher score than "Im**pres**sive", and so feature higher up in the list.  This makes keyboard navigation easier, since the most relevant results are closest to the input field and quicker to navigate to.

Feel free to close this if it's not something you're interested in implementing.

**Comment by jquense** [comment]
yeah I don't think I want to go the route of putting this in core just yet, I will keep thinking about it. I am always trying to balance making common widget tasks easy to do out of the box, but also want to make them easy to extend and compose which means, less in core, but the proper hooks. this is a good instance where putting filtering in the widget is making it tougher to iterate on that with sorting. 

that being said when I get access to a computer I'd be happy to sketch out a HoC that gets you there but requires really minimal reimplementing

**Comment by jquense** [comment]
So this should work fairly ok. You can use `componentWillReceiveProps` to cache the filtered and sorted data if computing it on every render is no good

```
// if you don't mind using internal api's otherwise its like 10 lines of code
var filterMixin = require('react-widgets/lib/mixins/DataFilerMixin');

class MyMultiselect extends React.Component {
  render(){
    return <Multiselect {...this.props} filter={false} data={this._data()}
  },

  _data(){
    return mySortFunction(
        filterMixin.filter.call(this, this.props.data, this.props.searchTerm))
  }
}

module.exports = uncontrollable(MyMultiselect, { searchTerm: 'onSearch' })
```

**Comment by andru** [comment]
Thanks for the code @jquense - more or less how I've implemented it.  Good to know about the filterMixin. Hadn't spotted that! :)
