### ISSUE TITLE
DateTimePicker unable to select day on the calendar.

### ISSUE THREAD

**Issue by cyrusbowman** [jquense/react-widgets#127]
When using the DateTimePicker in a scrollable div attempting to selecting dates when the input box in off the screen causes the scrollable div to scroll up (this is ok) but the date is not selected. This makes selecting dates on the lower half of the calendar impossible if you have a div smaller than the height of the calendar.

**Comment by jquense** [comment]
Hi there thanks for the issue

I am not sure I understand the problem, perhaps you could take a screenshot or gif?

**Comment by cyrusbowman** [comment]
Sorry for the slow response. [Here](http://i.imgur.com/tlncBoW.gifv) is a gif.

**Comment by jquense** [comment]
blaaah this regression iOS Safari's fault, well due to a change to solve a ridiculous bug in safari. I will see what I can do to fix it again.

**Comment by cyrusbowman** [comment]
Haha alright it seemed like a nasty one. I'm in chrome v43 for osx. I haven't tried in on v2.4.2 yet so maybe it's fixed? I was trying on the demo page.
