### ISSUE TITLE
Add way to highlight a date range to Calendar

### ISSUE THREAD

**Issue by davidtinker** [jquense/react-widgets#129]
Example:

    <Calendar highlightStart={startDate} highlightEnd={endDate}/>

Days (or months etc.) falling into the range would be rendered with 'rw-highlight' style. Very useful when indicating a date range using a part of Calendars (one for start, one for end).

**Comment by jquense** [comment]
Hi there. I have been meaning to add fine control over calendar rendering, will add something soon hopefully.

**Comment by davidtinker** [comment]
I could do a simple highlightStart={startDate} highlightEnd={endDate} PR if you like. That isn't totally flexible but it also keeps the PureRenderMixin working.

Tx for the cool widget btw.
