### ISSUE TITLE
Filtering Dropdown List spacebar bug.

### ISSUE THREAD

**Issue by cyrusbowman** [jquense/react-widgets#130]
When I'm filtering a dropdown list the space bar causes the page to scroll down and the space has no effect. Oddly the spacebar works when there are no results. [Here](http://i.imgur.com/yHZIQCM.gifv) is a gif.

**Comment by jquense** [comment]
What version or you on? I believe this was fixed in 2.6.1

**Comment by cyrusbowman** [comment]
I was on 2.6.0 sorry for the non-issue. Just updated. Good work! Thanks!
