### ISSUE TITLE
Typo in http://jquense.github.io/react-widgets/docs/#/

### ISSUE THREAD

**Issue by crispen-smith** [jquense/react-widgets#138]
I was going to submit a PR for this but couldn't see where it actually appears within the repo.

in the paragraph:

React-widgets offers a set of html form inputs, built from scratch with React. The suite is based on the excellent work done by Kendo UI Core, and jQuery UI, but built as true components, and not library wrappers. By building each widget entirely in React, it can leavage all of the benefits of the React ecosystem and philosophy. A big thanks to both of these libraries for solving most of the difficult problems already.

I believe the word "leavage" is meant to be leverage.

**Comment by jquense** [comment]
thanks for the heads up. If you want to PR (much appreciated) the file is in docs/pages/getting started.md
