### ISSUE TITLE
Number picker error when step is 0.1, the value `14.299999999999999` is not right.

### ISSUE THREAD

**Issue by luqin** [jquense/react-widgets#143]

**Comment by jquense** [comment]
this sounds like you are getting bit by the [quirks of the JavaScript Number type precision](http://yuiblog.com/blog/2009/03/10/when-you-cant-count-on-your-numbers/) Unfortunately "correcting" floating point math is beyond the scope of this library

**Comment by luqin** [comment]
Yes, so I hope that this library support decimals in the future

**Comment by luqin** [comment]
```
function accAdd(arg1, arg2) {
    var r1, r2, m;
    try {
        r1 = arg1.toString().split('.')[1].length;
    } catch (e) {
        r1 = 0;
    }
    try {
        r2 = arg2.toString().split('.')[1].length;
    } catch (e) {
        r2 = 0;
    }
    m = Math.pow(10, Math.max(r1, r2))
    return (arg1 * m + arg2 * m) / m;
}
```

**Comment by jquense** [comment]
I'd happily accept a pull request if it doesn't add to much code :)

**Comment by jquense** [comment]
Added `precision` prop in 2.7.2 to handle these cases

**Comment by luqin** [comment]
:+1:

**Comment by luqin** [comment]
@jquense :+1:
