### ISSUE TITLE
[feature request] slider bar

### ISSUE THREAD

**Issue by thom-nic** [jquense/react-widgets#144]
This seems like a common UI "widget" that would be convenient to have in a library like react-widgets.  

Here's the canonical example from Jquery UI: https://jqueryui.com/slider/#default

**Comment by jquense** [comment]
Hi there,

I have thought about adding a range input to continue with input parity on the html input types. That is mostly like the jquery ui slider, but I am not sure if/when i can get to it.

**Comment by thom-nic** [comment]
might also consider just wrapping an html5 `<input type='range'` in a nice react widget with events exposed.  Of course, only IE 10 support then :( http://caniuse.com/#feat=input-range
