### ISSUE TITLE
numberpicker doesn't change when value is set to undefined from a number

### ISSUE THREAD

**Issue by amarant** [jquense/react-widgets#146]
Hi,
when we set the value undefined to a numberpicker when it was previously a number it doesn't change to a blank input like when the value is set to null.
I've modified an example for [here](http://jquense.github.io/react-widgets/docs/#/numberpicker) : if I increase the first picker, and then increase the second one (that set the value of the first one to undefined) the input showed by the first one is unchanged. But when the onChange of the second picker change the first one to null instead of undefined it works.
Do you consider it a bug, or should undefined be different than null ?

````javascript
var NumberPicker = ReactWidgets.NumberPicker;

var Example = React.createClass({

  getInitialState() {
    return { value0: 1, value1: null };
  },

  render() {
    var change = (name, value) => this.setState({
        ['value' + name]: value
      });

    return (<div>
      <NumberPicker 
        value={this.state.value0} 
        onChange={change.bind(null, '0')}/>
      <NumberPicker 
        value={this.state.value1} 
        onChange={change.bind(null, '0', undefined)}/>
    </div>)
  }
});

React.render(<Example/>, mountNode);
````

Thanks.

**Comment by jquense** [comment]
So `undefined` means "I am not providing a value prop" whereas `null` means "I want the value to be empty`. 

The difference is that when you don't provide a value prop the widget is "uncontrolled", so it will try and manage the value itself, like normal React inputs. If you want the value to explicitly be empty use `null` :)

**Comment by amarant** [comment]
Ok thanks for the precisions.
