### ISSUE TITLE
Cannot select a date when the calendar is partially off screen

### ISSUE THREAD

**Issue by wgcrouch** [jquense/react-widgets#153]
It will set the focus and scroll the calender fully into view, but not select the date. If the calender is fully in view, a single click does select the date.

**Comment by jquense** [comment]
what version are you using? this was addressed recently

**Comment by wgcrouch** [comment]
I'm using 2.7.1, I'll test the latest version

**Comment by jquense** [comment]
great. I can't repo the behavior on the doc site, selecting a date on a partial displayed datepicker calendar works fine for me. Any more details

**Comment by wgcrouch** [comment]
I can replicate it on the doc site on Chrome 44 and 43 on Ubuntu, Firefox works ok though. 

Happens on a partially displayed calender, eg the one at the top of http://jquense.github.io/react-widgets/docs/#/calendar

**Comment by jquense** [comment]
ahh ok the just the calendar by itself. I will see what I can do
