### ISSUE TITLE
Why the size of a packed file is so big?

### ISSUE THREAD

**Issue by luokuning** [jquense/react-widgets#155]
I installed the ```react-widgets``` via npm, and used Browserify to build a ```DateTimePicker.browser.js``` for browser. As I have loaded ```react.js``` before, I ignore the ```react.js``` when pack ```DateTimePicker.js```:
```
browserify DateTimePicker.js --ignore react > DateTimePicker.browser.js
```
After that, it added a new file ```DateTimePicker.browser.js``` as expected, but I found its size is around  174KB. Why it is so big? Is that normal or I have missed something?

**Comment by jquense** [comment]
I would just inspect the output file and see what is in it. if it's that big you are probably also including react and globalize.js. you can see how big just the library is (with all widgets) by looking at the built file in the 'dist' folder. 

the only moderately large dependency the date picker has (besides react) is globalize.js which is needed for localization.

**Comment by brigand** [comment]
When checking size, use `NODE_ENV=production browserify ... | uglifyjs -m`, and then gzip it and use that size. The development unminified uncompressed size isn't very interesting.

**Comment by luokuning** [comment]
I sure did use ```--ignore react``` when built ```DateTimePicker.js``` to ```DateTimePicker.browser.js```, but  ```DateTimePicker.browser.js``` still has about 6000 lines code. And then I also add ```--ignore globalize```, the code reduce nearly 1200 lines, but still too heavy, I don't know what's wrong. After checking the home page of Browserify, got nothing.

**Comment by luokuning** [comment]
@brigand Indeed it is. But I think ```DateTimePicker.browser.js``` may contains some unuse code, so after uglifyjs processing it still has large size.

**Comment by brigand** [comment]
`--ignore react` seems to not be working as you expect. Try `-x react` instead. It gives 42,467 bytes gzipped.

**Comment by luokuning** [comment]
@brigand Thanks, but ```-x react``` works the same as ```--ignore react```.

**Comment by luokuning** [comment]
I used webpack to pack ```DateTimePicker.js```, but the filesize is still the same as Browserify(~ 130kB), the whole library ```react-widgets.js``` in 'dist' folder is  just 105KB. I don't know why, and  I'm going crazy...
