### ISSUE TITLE
uncontrollable 1.3.0 throws exceptions in react-widgets

### ISSUE THREAD

**Issue by maspwr** [jquense/react-widgets#156]
The update from uncontrollable `1.2.0` to `1.3.0` has affected our use of `DropdownList`. Specifically, a new call to `ReactUpdates.asap` is triggering an invariant violation which causes an exception to be printed to the console.

Abbreviated traceback until I reproduce in a non-minified build:

```
Uncaught Error: Invariant Violation: ReactUpdates.asap: Can't enqueue an asap callback in a context whereupdates are not being batched.
invariant
asap
setAndNotify
notify
close
(anonymous function)
```

I'll see if I can create a simple toy example, but it's just a `DropdownList` that throws this error when the `blur` event is triggered on it.

**Comment by jquense** [comment]
should be fixed, just rm and reinstall react-widgets and everything should work
