### ISSUE TITLE
DropdownList error at losing the focus

### ISSUE THREAD

**Issue by CarlosMela** [jquense/react-widgets#157]
I am not sure when I started to have this problem. Probably after updating react. After changing the value of a DropdownList and losing the focus I get the following error:
```
"Uncaught Error: Invariant Violation: ReactUpdates.asap: Can't enqueue an asap callback in a context whereupdates are not being batched."
```

The border keep the blue color from when it had the focus and my "onBlur" function doesn't get executed.

In my package.json:
```
    "react": "^0.13.3",
    "react-bootstrap": "^0.23.7",
    "react-router": "^0.13.3",
    "react-widgets": "^2.7.2",
```

**Comment by jquense** [comment]
Thanks for the update this is the same issue as #156 with a bug introduced in a downstream dep. should be fixed shortly

**Comment by jquense** [comment]
should be fixed, just rm and reinstall react-widgets and everything should work
