### ISSUE TITLE
DateTimePicker: Throwing Invariant Violation

### ISSUE THREAD

**Issue by hshansen7** [jquense/react-widgets#158]
I randomly started experiencing this when trying to select a date or time with the DateTimePicker. 
I also have already deleted and re-installed react-widgets.

![image](https://cloud.githubusercontent.com/assets/12817107/8531063/d1590d7a-23f2-11e5-8d5e-fdb3be492752.png)

**Comment by jquense** [comment]
how are you using react-widgets? the dist build or via npm and modules? It looks like there are two copies of react installed...

**Comment by hshansen7** [comment]
I'm currently using the widgets via npm and modules

**Comment by jquense** [comment]
try reinstalling, i made a change downstream taht should fix it

**Comment by hshansen7** [comment]
Thanks! It seems to be working now

**Comment by carlosrberto** [comment]
I've a similar issue with DropdownList and Combobox when I focus and click outside:

![Issue](https://photos-6.dropbox.com/t/2/AABzYHKzRddd2mw2wlxK7bKa4MGfjNMhqeR8FbPg3EJfmg/12/1747775/png/32x32/1/1436220000/0/2/Screenshot%202015-07-06%2017.53.36.png/CL_WaiABIAIgAyAEIAUgBiAHKAEoAg/80Og7MyaL8EMAAY-W51NbSAgTa5sDsSep0CpcUJC6q8?size=1280x960&size_mode=2)

**Comment by carlosrberto** [comment]
I've this problem with the latest version from npm, but the master version is ok

**Comment by jquense** [comment]
just removing and reinstalling  should should fix it
