### ISSUE TITLE
.rw-select should have a position top of 0 in css

### ISSUE THREAD

**Issue by reduxdj** [jquense/react-widgets#160]
in my datepicker the calendar is positioned below the component... adding a top 0 fixes this for me.

**Comment by jquense** [comment]
hi, could you provide an example? that seems to be a quirk of the css you have on your page, not a fault in the stylesheet (which works fine in the docs page)

**Comment by reduxdj** [comment]
Hmm, well I am using bootstrap, so i had to add a clear:both to rw-widget or my label with my element is overlapping, maybe adding that messes this up?

```cjsx
<div className="form-group">
          <label htmlFor="input-type"  className="control-label col-md-12">Gender</label>
          <DropDownList  defaultValue={"women"} data={genders}/>
        </div>
```

**Comment by jquense** [comment]
not sure... but i doesn't hurt to make the `top: 0` explicit so I will add it in.
