### ISSUE TITLE
DatePicker throws an error

### ISSUE THREAD

**Issue by reduxdj** [jquense/react-widgets#161]
2.71 of ReactWidgets
13.3 react with addons

<DateTimePicker defaultValue={new Date()} />
react-widgets.js:4 Uncaught TypeError: Cannot read property 'format' of undefined

If i remove the date property the component renders but when i make a selection the same error persists.

**Comment by jquense** [comment]
I need to better stack trace than that please. Are you using the dist build or the modules (with webpack/browserify). If you are using the dist build did you include globalize js before react-widgets on the page?

**Comment by reduxdj** [comment]
No, I just realized now that I was missing a localizer. Maybe it should throw an error that the localizer wasn't defined, that might have made it faster for me to realize.

**Comment by reduxdj** [comment]
..I am using the dist release with bower. I'm new to CJSX and kind of stuck with the brunch workflow so I just used the compiled code. I notice that the globalize file is not inside the /dist folder? 

Forgive me, I'm new to ES6 and learning it's conventions. I haven't figured out the best workflow for using libraries that use babel yet.

**Comment by jquense** [comment]
All the released code is compiled to es5, and the modules are CommonJS, so there is not need to use babel or anything like that to use the modular version. You need to do is use a bundler like browserify or Webpack to concat the files together, but there is plenty on the internet about that. And I think brunch already supports common js modules so you might not need anything else.

A localizer should not be undefined, there is a default one that is comes with the react-widgets but it requires globalize.js

globalize.js is not included because it is a third party dependency that you need to install yourself. [You need this version](https://github.com/jquery/globalize/tree/79ae658b842f75f58199d6e9074e01f7ce207468)

**Comment by jquense** [comment]
also globalize _should_ already throw if not included....

https://github.com/jquense/react-widgets/blob/master/src/util/configuration.js#L10

**Comment by reduxdj** [comment]
Interesting, I wasn't even doing anything with configuration. I'm almost there, I prefer using moment.js for my time formatting, I'm only doing US for localization.  

```coffeescript
dateLocalizer =
  formats:
    day: 'DD'
    month: 'mmm'
    decade: (value, culture, localizer) -> '2010-2019'

  parse:  (value, format, cultureStr) ->
    return new Date(value)
  format: (value, format, cultureStr) ->
    return moment(value).format('MM-DD-YYYY h:mm')
  firstOfWeek: (value,format,cultureStr) ->
    return "Mon"

configure.setDateLocalizer(dateLocalizer)
configure.setNumberLocalizer(numLocalizer)
```

Not exactly sure why I'm getting all 1969 for the bottom decade. I don't even see my decade function being called.

**Comment by reduxdj** [comment]
Is there anyway you can give a full example of the dateLocalizer with out the requirement for globalize please. I see there's a bunch of values, and you stubbed out the function in the docs, but a complete and working date localizer would be awesome to see to get going quickly?

**Comment by reduxdj** [comment]
Can't figure out how to do the MON,TUES,WED? what's the formatter for that?

![screen shot 2015-07-09 at 5 12 26 pm](https://cloud.githubusercontent.com/assets/322547/8609706/b966bbdc-265d-11e5-92a4-b026cd9d9b3b.png)
```coffeescript
dateLocalizer =
  formats:{
    default:  (value)  -> moment(value).format('MMMM Do YYYY, h:mm a')
    dayOfMonth: (value)  -> moment(value).format('D')
    month: (value) -> moment(value).format('MM')
    year: (value) -> moment(value).format('yyyy')
    date: (value)  -> moment(value).format('MMMM Do YYYY, h:mm a')
    time: (value) -> moment(value).format('h:mm a')
    footer: (value) -> moment(value).format('MMMM Do YYYY, h:mm a')
    header: (value) ->  moment(value).format('MMM Do YYYY') # the left right header
    firstOfWeek: 0

  }
  format: (value, format, cultureStr) -> moment(value).format(format)
  parse: (value) -> new Date(value)
  firstOfWeek: (value) -> new Date(value).getDay()
```

**Comment by jquense** [comment]
might be easier to just use:https://github.com/jquense/react-widgets-moment-localizer or at least you can use it as a reference

**Comment by reduxdj** [comment]
Awesome. thanks, looks like weekday was missing from the documentation.

**Comment by reduxdj** [comment]
BTW, this is a great library.

**Comment by jquense** [comment]
oo great, thanks for noticing, I'll add it.
