### ISSUE TITLE
DateTimePicker throws Invalid Variation on the client side when server rendering

### ISSUE THREAD

**Issue by andrerpena** [jquense/react-widgets#166]
I'm doing server rendering on my ReactJs app, meaning that I render in the server and then I render in the client again, to have all my event handlers set.

ReactJs is throwing an error because of DateTimePicker:

    Invariant Violation: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side:

I assume that's because DateTimePicker is trying to calculate something, like width or height, which cannot be done on the server, and that's making the `props` to look different when I re-render in the client.

Any idea?

**Comment by jquense** [comment]
I am not sure, there is nothing fancy or weird about the render of the date picker. AFAIK others have done server rendering without issue with react-widgets... perhaps there is an odd collision with your code?

**Comment by skdzines** [comment]
I'm having the exact same issue.  Were you ever able to figure out what was causing it for you?
