### ISSUE TITLE
DateTimePicker pre-populated - clearing input manually does not trigger onChange event

### ISSUE THREAD

**Issue by pvsrivathsa** [jquense/react-widgets#170]
I am using DateTimePicker to pre-populate with a date and later allow the user to edit it.

```
<DateTimePicker placeholder="Release Date" parse={AppDefaults.getLocaleDateFormat()} time={false}
                    value={AppDefaults.getDate(this.state.releaseDate)}
                    defaultValue={AppDefaults.getDate(this.state.releaseDate)}
                    format={AppDefaults.getLocaleDateFormat(true)} onChange={this.changeReleaseDate}
                    disabled={!this.props.editMode} culture={AppDefaults.getDateTimeCulture()} title="Release Date"/>
```

When I manually clear the component's text input and transfer focus on some other control, the `onChange` event is not getting triggered. But when I choose some date from the calendar and later clear the text input, the `onChange` event is getting triggered.

**Comment by jquense** [comment]
how are you clearing the value manually? also don't use `defaultValue` with `value`

**Comment by pvsrivathsa** [comment]
I am clearing the value by focussing on the text box, select all text and backspace. After doing this if I transfer focus to some other control, `onChange` is not happening

**Comment by jquense** [comment]
sorry for the delay, I can't repo the issue, could you put together an example I can test out? A fiddle or gist?
