### ISSUE TITLE
Support for 24-hour clock

### ISSUE THREAD

**Issue by mrlarssen** [jquense/react-widgets#171]
Hi!

Is it support for 24-hour clock in date picker? If not, is there any way you could support it?

**Comment by jquense** [comment]
Hi there. yup :) just change the formats to a 24 one for the relevant  props (format, timeFormat, etc)

**Comment by mrlarssen** [comment]
Thanks a lot :)

**Comment by jquense** [comment]
@mrlarssen yup you need to also set the `timeFormat` prop
