### ISSUE TITLE
Externs file for Google Closure Compiler

### ISSUE THREAD

**Issue by bensu** [jquense/react-widgets#173]
I'm putting together a ClojureScript wrapper for your library which needs an externs file. I'll start working on it soon. Are you interested in distributing it as part of your library?

**Comment by jquense** [comment]
I might be, but I will admit that I have no idea what that is (only use uglify). Could you give me the elevator pitch about what it is and how often I'd need to keep it updated, etc?

**Comment by bensu** [comment]
Elevator pitch follows:

> The Google Closure Compiler renames/shortens names. If the compiler is renaming code in A.js,
> which references B.js, without renaming B.js there will be a problem later: A.js references will be 
> renamed, while B.js names will remain intact. To solve it, one provides a list of B names (the extern 
> file) to the compiler while renaming A. Then, whenever the compiler finds any of the symbols in the 
> externs file, it leaves it unchanged.

The externs file should contain a list with any symbols that the library's users might reference. That might be a long list, but it will only change when you change your API. In the ClojureScript community we usually add them as needed, through issues and PRs. If your program doesn't work after going through the compiler you find the missing symbol and add it to the externs with a PR. A lot of the externs are kept [here](http://cljsjs.github.io/).

If you think your Js users might be interested in this, I'll hit keep them in sync, or make yours the canonical one. Otherwise, you can just add a section in your docs: "If using the Google Closure Compiler, the extern is in cljsjs"

**Comment by bensu** [comment]
Thanks for the widgets by the way, I really appreciate the effort you've put into making them modular/pluggable, and use a few dependencies as possible (i.e. i18n strategies).
