### ISSUE TITLE
Invariant Violation: addComponentAsRefTo

### ISSUE THREAD

**Issue by flipchart** [jquense/react-widgets#175]
Getting this error with version 2.7.4

Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

The ref it's complaining about is "valueInput" - which only appears in the react-widgets codebase (of the modules I'm using) React version 0.13.3

**Comment by jquense** [comment]
Hi there, 

The other, non obvious reason, errors of this sort can occur is if you have two instances of React in your app, You might want to make sure that whatever you are using to build/build is only including one instance, especially if you switch between importing react and react/addons,

If that doesn't work could you provide a code example that reproduces the error, so I can try and track it down?

**Comment by flipchart** [comment]
Wow. That was a pain to resolve, but thanks it was a duplicated React include
