### ISSUE TITLE
Disable input on DateTimePicker

### ISSUE THREAD

**Issue by sporto** [jquense/react-widgets#176]
I would like to disable the text input in the DateTimePicker component, still want the user to be able to click on the calendar and time pickers. Is there a setting for this I am missing?

**Comment by jquense** [comment]
Hi there, no there isn't anything you are missing that particular combination is not directly supported but you can fake it by wrapping the Component and in `componentDidMount` manually disabling the input. It's not a great option but its the best I can think of.

**Comment by sporto** [comment]
Thanks, I will try this. Please consider adding a props for this use case.

**Comment by jquense** [comment]
I will keep it mind for the future thanks :)
