### ISSUE TITLE
Support autofocus on Multiselect

### ISSUE THREAD

**Issue by saulshanabrook** [jquense/react-widgets#177]
First off, thank you for the amazing library. The Multiselect element has been a pleasure to use. I am doing something a bit unconventional with it (selecting different types depending on what has been selected before) and it has been a dream :+1: 

Would you support adding an `autoFocus` attribute to the element? I would be happy to write up a PR for it. It would simply pass that down to the `input`.

**Comment by jquense** [comment]
hi there, thanks for the kind words. I'd gladly accept a PR that passed `autoFocus` down, if possible tho it'd be great if while you were at that, also doing it for comboBox, numberpicker, and the the datepicker

**Comment by saulshanabrook** [comment]
Sure.

**Comment by jquense** [comment]
implemented as of 2.8.1
