### ISSUE TITLE
Datepicker without input component?

### ISSUE THREAD

**Issue by agmathew** [jquense/react-widgets#179]
Great library, thanks for your hard work! I was wonder if there was a way to use the date picker without the input element? Specifically, I'd like to trigger the date picker popup by clicking on a custom icon. Is this possible? If so, can you point me to an example?

**Comment by jquense** [comment]
if you want just the calendar part of the Dropdown you can use the Calendar component and create your own popup to hold it (which is what the datepicker does). Apart from that approach though there isn't a less DIY solution

**Comment by agmathew** [comment]
Got it. I was wondering if there was a way to use the built-in popover, but I ended up using React-Bootstrap's Overlay with the Calendar component without a problem. Thanks!

**Comment by jquense** [comment]
great glad that works :) if you do want to use the react-widgets one you can import Popup but its not technically part of the public api so beware :P
