### ISSUE TITLE
DropdownList needs token

### ISSUE THREAD

**Issue by dannyphillips** [jquense/react-widgets#181]
We are a large software company that uses yours selects extensively. We want to have a way of clearing the value on your DropdownList component. We would prefer to create a PR, rather than using a fork of your widgets. Are you open to us writing a PR to add this functionality as a token prop? We'd like to know how open you are to PR's before we spend the time coding it.

**Comment by nickknw** [comment]
I needed this functionality as well for our application, we were able to implement it with the existing customizable options of the dropdown list plus a wrapper component. Our implementation is a 'Clear Value' list item that appears at the start of the dropdown list and has special styling.

The wrapper dropdown list component has a 'clearValueOption' boolean prop. When that property is set to true I add a blank item to the beginning of the list and pass in a custom itemComponent renderer that looks like this:

```
var React = require('react'),
    _ = require('_');

var DropdownListItem = React.createClass({
    displayName: "dropdownListItem",

    propTypes: {

        /**
         * @property {String} text The text to render for this list item
         */
        text: React.PropTypes.string
    },

    /**
     * @override
     */
    render: function () {
        var text = this.props.text,
            props = {};

        // turn blank entry into a Clear Value list item
        if (_.isUndefined(text) || _.isNull(text) || _.isEmpty(text)) {
            text = "Clear Value";
            props.className = 'clear-value-option';
        }

        return (<span {...props}>{text}</span>);
    }
});

module.exports = DropdownListItem;
```
Hope that helps!

**Comment by dannyphillips** [comment]
We currently have a similar solution made, for the time being. However, we would like to add a prop to DropdownList to include it. We would like an icon to clear the selection, rather than another list option. See the mock, below: 
![screen shot 2015-08-19 at 1 17 39 pm](https://cloud.githubusercontent.com/assets/8366399/9367832/bb7bd862-4674-11e5-8556-60c2446007e9.png)

**Comment by nickknw** [comment]
Ahh I see, yeah that makes sense

**Comment by dannyphillips** [comment]
This library (http://jedwatson.github.io/react-select/) has a similar feature.

**Comment by jquense** [comment]
I everyone. I am open to this feature, however I tend to only want to include stuff in core that isn't easily done with a wrapper, as that leaves the base widgets simple and flexible. it seems to me that this could be accomplished outside of core without forking but I may be missing some of the intricacies of the problem. 

you can programmatically null out the DropdownList by setting the value to `null` and there isn't any hard coupling of the value to the DropdownList data. from my perspective it seems like adding a clear button would be a matter of some css and a wrapper? definitely let me know if I am miss understanding the issue or the limitations!

**Comment by dannyphillips** [comment]
That's true! It can be done with some CSS and styles. Just wanted to consider adding it as a prop, since it seems several people have been desiring this feature. What do you think?

**Comment by jquense** [comment]
I need to think a bit more about that...I am not sure how that might fit in with the other pickers/dropdowns. Not sure it makes sense to add it to one without the others but then you run into issues in browsers that add them automatically (like ie...) hmm.

the other issue is that we'd need to make a choice about what a "blank" value is, `null` is generally what folks use, but there are cases where `null` might be a legitimate value in the list and I don't want to eliminate that case for everyone. Perhaps we can use some other unique "empty" token, but that would be sort of ugly for folks controlling the dropdown needing to handle some special object that means "empty"...

**Comment by dannyphillips** [comment]
Yeah, we may have to be creative with how we define "empty" because there could be so many different use cases. Maybe the prop could be passed the `empty` token, so everyone could define it themselves? Like the following prop: ```clearValue={{value: null, name: '' }}```
*where `value` is the value of the "empty" token and `name` is what we render for the "empty" token

**Comment by jquense** [comment]
Sorry for the droping out here, life gets crazy sometimes!

I have thought more about this and I think the whole empty value issue is going to cause more issues than it potentially solves, and introduces a bunch of complexity that I don't think is easily generalizable. To that end I think it makes more sense to keep this in the hands of users, who can more readily apply some convention around what an "empty" value constitutes for their use cases
