### ISSUE TITLE
Combobox - expose focused item

### ISSUE THREAD

**Issue by kjell-gunnar-midtlyng** [jquense/react-widgets#182]
Hi, 
we need to bind several keys to select a value from the dropdown list (tab, plus, minus). For now we  find the focused item in the  dropdown list with CSS-selectors and "clicking" it. A hack-ish solution, but it works until someone changes the css-classes. 

Would it be possible to expose the focused item in the list when the dropdown is open in the state of the combobox?

**Comment by jquense** [comment]
I can't think of a good way of exposing that value...So for now I think we are going to just pass on this enhancement
