### ISSUE TITLE
Request to allow passing props to Calendar's dayComponent

### ISSUE THREAD

**Issue by agmathew** [jquense/react-widgets#183]
Here's my scenario: I would like to render a Calendar with special UI for each day depending on a user's schedule, for example adding a badge to each day based on a to do list. Currently, there's no clean way to do this because Calendar's dayComponent is only passed the label and date. It would be great if there was a way to pass custom props (the user's schedule data in my case) to Calendar. I'm imagining something like this:

    <ReactWidgets.Calendar dayComponent={DayComponent} dayComponentProps={...this.state.data} /> 

This will add a lot of flexibility to the component since right now we're limited to customizing the Calendar just based on the date and no external data. Thoughts?

**Comment by agmathew** [comment]
An alternative would be if the Calendar just passed its props to its DayComponents. Do you think that would be a cleaner option?

**Comment by jquense** [comment]
Hey there, thanks for the issue, sorry for the delayed response.

I don't really like the idea of `dayProps` as it makes optimizing the component wish pure render, much more difficult. Alternatively passing all the props as a lot of unknown complexity and introduces a lot of different opportunities for odd collisions. Especially in the of components that use the Calendar like like datepicker.

The path I suggest is to capture any external info you need in a closure, and then just pass the component in as you would normally. We use this approach [here](https://github.com/jquense/react-widgets/blob/master/src/SelectList.jsx#L97) ourselves in the SelectList

**Comment by kriegerd** [comment]
Hi @jquense. 
Sorry for reviving this old thread. I'm trying to implement something similar (even simpler) than what @agmathew originally posted, just to pass a list of dates to be highlighted.

I read your answer and followed your link but I still don't understand how to pass the closure for it to be available in the DayComponent's render method.

Thanks.

**Comment by leoi11** [comment]
@kriegerd I came across the same problem. Looking at the code it seems that this closure passing is not yet implemented for Calendar. What @jquense meant is that if someone were to implement it, he/she can use the approach used in SelectList.
Speaking of which, I wonder if this can be reopened as a feature request to pass in the closure?

**Comment by jquense** [comment]
You can already do this. There isn't any need to implement anything. Components are just functions so you can pass any function including  cladd methods as the component prop

**Comment by leoi11** [comment]
IMHO the cleanest approach is to have dayComponent as a nested component of Calendar, then to render Day Component, Calendar just renders this.props.children. What do you think @jquense?
Right now I still don't see how we could pass in a closure to dayComponent due to the outdated url above (it's pointing to master ln 97). May I ask a favor to provide a simple example if you have time @jquense, thanks!

**Comment by jquense** [comment]
```js
renderDayComponent = (props) => {
  const extraProps = this.props.myExtraProps;
  return <MyDayComponent {...props} {...extraProps />
}
render() {
  return <Calendar dayComponent={this.renderDayComponent} />
}
```

**Comment by leoi11** [comment]
thank you, @jquense!
