### ISSUE TITLE
How can I start date selection from Decade?

### ISSUE THREAD

**Issue by patgod85** [jquense/react-widgets#184]
In my application I want to set date of birth. More comfortable to open DateTimePicker with Decade-view pick the year then the month and finally the date. 
But initialView and finalView options do not alow to do so. 

First I set 
```
initialView="decade"
finalView="month"
```
it looks like that I need, but it does not work. In documentation such composition marked as incorrect.

How can I implement such functional?
Thanks

**Comment by jquense** [comment]
The props assume you will always go start at a more specific view, which is not what  you want:), There isn't really any way of achieving what you are looking for right now.

**Comment by patgod85** [comment]
Is there a way to call action like ```changeView``` in onToggle handler? Or emulate client's action somehow.

**Comment by jquense** [comment]
there is not as far as I can think of...
