### ISSUE TITLE
Position of DateTimePicker

### ISSUE THREAD

**Issue by patgod85** [jquense/react-widgets#185]
Hi
Is there a way to specify the position where DateTimePicker will pop up?
There are cases when input is in the bottom of page. Client click on button.rw-btn-calendar and DateTimePicker appears out of the screen.
I've to calculate the input position and manually set *top* option to shift the picker upper. It is not too clear solution.
Do I missed some option?
Thanks

**Comment by jquense** [comment]
it doesn't auto calculation position for you, but there is the `dropUp` prop that will apply styling to to open the dropdown upwards without you needing to hack in some `top` value. You could fairly easily wrap the DatePicker and add/remove the prop onToggle based on viewport position if you'd like

**Comment by patgod85** [comment]
Thanks

**Comment by patgod85** [comment]
Little amend
There is no information about ```dropUp``` here:
http://jquense.github.io/react-widgets/docs/#/datetime-picker
