### ISSUE TITLE
Howto? Limit number of selected values.

### ISSUE THREAD

**Issue by jamesjjk** [jquense/react-widgets#186]
Hi,

Is there anyway to limit the number of selected values without modifying the Multiselect component?

Thanks..

**Comment by jquense** [comment]
yeah, use the `value` and `onChange` props and only set the change the value when there are less than the number of items you want.

```js
<Multiselect
  value={this.state.value}
  onChange={items=> {
    if (items.length <= 3)
      this.setState({ value: items })
  }}
/>
```

**Comment by jamesjjk** [comment]
@jquense That is great thanks! It would be nice to disable the input itself too. I suppose could manually disable the element. Appreciate the response! great collection of components btw!

**Comment by jquense** [comment]
glad to help. You can control a lot of the actions of the Component, which will help get you towards that behavior. for instance you could also control `searchTerm` and `onSearch` in the same way as `value`, and only set `searchTerm` if the number of items is below the threshold, that will effectively make it readOnly

**Comment by jamesjjk** [comment]
Thanks! I though I would post up a gist with a solution for others: https://gist.github.com/jamesjjk/79a7b76a877d77baaa46
