### ISSUE TITLE
callbacks setstate cause error 

### ISSUE THREAD

**Issue by jamesjjk** [jquense/react-widgets#187]
Hi,

When calling setState from the onChange & onOptionLabelClick in both multi and non multi mode it resets the component. Is the component binding from the state or replicating state props to state? Makes it difficult to use this component as you cannot set state in the parent.

    onChange(val) {
      this.setState({ value: val });
    }

    render(){
      <Select
        options={this.props.options}
        onChange={this.onChange.bind(this)} />
    }

**Comment by jquense** [comment]
Hi there, I am not sure what your example is of, but you can either let the Select control the value or set it yourself. Take a look one of the many examples from the docs site: http://jquense.github.io/react-widgets/docs/#/selectlist/onChange

**Comment by jamesjjk** [comment]
Apologies  I replied to the wrong component! My mistake.
