### ISSUE TITLE
Calendar: no event for change month?

### ISSUE THREAD

**Issue by chrisbenseler** [jquense/react-widgets#188]
Is there any event triggered when the user changes the current month viewed in the calendar?
The only one I found at the docs is the onChange, when the user selects a date.

**Comment by patgod85** [comment]
+1

**Comment by patgod85** [comment]
By reading of sources I figured out that it's possible to use onNavigate prop:
```javascript
...
React.createClass({
    handleNavigate: function(date, slideDir, view){

    },

    render: function(){
        return (
            <Calendar
                onNavigate={this.handleNavigate}
            />
        );
    }
});
...
```

**Comment by jquense** [comment]
yup `onNavigate` I suppose its not documented if ya'll are here. Sorry about that, need to update the docs.

**Comment by chrisbenseler** [comment]
Thanks!
