### ISSUE TITLE
No key for Create element (Multiselect)

### ISSUE THREAD

**Issue by jamesjjk** [jquense/react-widgets#189]
Hi,

Just an FYI the component throws a (key missing) warning when rendering the Create "" element on a Multiselect. Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Multiselect. See https://fb.me/react-warning-keys for more information.

**Comment by jquense** [comment]
thanks!

**Comment by frueckmann** [comment]
Hi jquense,
i want ask because of the same problem. 
Is the warning (key missing) resolved?
thanks for answer
