### ISSUE TITLE
DateTimePicker: different results based on input type

### ISSUE THREAD

**Issue by insin** [jquense/react-widgets#190]
Using a DateTimePicker for date selection with `time={false}`, if you type in a valid date the resulting `Date` object has its time part zeroed out to midnight, but if you open the calendar and pick a date, it will have a time part with the time the component was initialised at.

This is a potential gotcha for people comparing the resulting `Date` objects directly in start date/end date scenarios.

**Comment by jquense** [comment]
related #172 

Yeah, one a few gotchas there :/ Unfortunately there really isn't much I can do b/c the behavior is coming from the localization strategy (globalize) I would just copy what they do but that just makes the linked bug even more of an issue, plus I don't want to copy Globalize for folks using moment. I appreciate the heads up though, maybe I can make a note of it in the docs.
