### ISSUE TITLE
sr-only class for notification span in MultiSelect?

### ISSUE THREAD

**Issue by cameront** [jquense/react-widgets#193]
https://github.com/jquense/react-widgets/commit/1f11e4d676e5a72341dc08d17e843bdcb368088d#diff-8189ce2b01bc85ca823e144f50fbe3aeR223

I think this may be a bootstrap defined class? Should this class be rw-sr instead? Or are clients expected to define this class themselves and/or pull in from bootstrap?

**Comment by jquense** [comment]
Ahh yes that is a bug. it should be rw-sr-only

**Comment by cameront** [comment]
great - thanks for the quick fix!
