### ISSUE TITLE
I am not sure how you set focus to the ComboBox when my react component mounts

### ISSUE THREAD

**Issue by jefferydutra** [jquense/react-widgets#195]
It looks as though you have a private method in the ComboBox that accomplishes this
focus: function () {    compat.findDOMNode(this).focus();  };

It does not seem to be documented if it is available.

**Comment by jquense** [comment]
you can use that tho it's also hidden behind uncontrollable so there is an additional ref you need to go through. 

I have proper `autoFocus` support sitting in master for a real solution I just haven't had a moment to release

**Comment by jefferydutra** [comment]
What additional ref do I need to go through? Assuming I have a ref to my ComboBox as comboBoxRef would my complete ref be: comboBoxRef.refs.input.focus()

**Comment by rkhayat** [comment]
I am wondering about this functionality, how can I focus the input? Is there a ref I can use?

**Comment by jquense** [comment]
There is a ref...but its better to use the `autoFocus` prop for setting focus. If you _need_ to do it programmatically you can do: `combobox.refs.inner.focus()` but that is technically a private api, so use appropriate caution.

**Comment by rkhayat** [comment]
The html5 spec states 'There must not be more than one element in the document with the autofocus attribute specified.' I have many components that need autoFocus.
ill try the following, thanks.
  ```componentDidMount() {
      combobox.refs.inner.focus()
 }```

**Comment by jquense** [comment]
`combobox` refers to your ref of the combobox, its a magic global variable.

also how can you have many components taht need autoFocus, only one thing can be focused at a time. Plus its react just move the autofocus prop to the component you want focused at any given time.

**Comment by rkhayat** [comment]
@jquense  what I means it, it will only trigger the first time, after that it seems to be ignored. I threw autoFocus prop and it works like a charm, thanks!
