### ISSUE TITLE
Multiselect: selectedItems, noneSelected, tagsLabel

### ISSUE THREAD

**Issue by cyrusbowman** [jquense/react-widgets#197]
Make selectedItems, noneSelected, and tagsLabel optional.

Currently "selected items:" is always displayed, "none selected" is displayed unless you pass an empty messages object to props. I don't want these in my UI so setting them to null or false on the messages object to turn them off would be great.

Thanks for all the good work!

**Comment by jquense** [comment]
this is actually just a bug, those labels are for screen readers but the styles are incorrect (bug) so they are showing, working on a release to fix it now.

**Comment by jquense** [comment]
fixed in 2.8.1
