### ISSUE TITLE
ComboBox - Embedded in bootstrap modal doesn't pop out

### ISSUE THREAD

**Issue by aikeru** [jquense/react-widgets#199]
Basically, when I use a bootstrap modal + the combo box widget, when I open the combo box, the rw-popup doesn't show above the modal - rather, it makes the modal content scroll or get larger.

Is there any easy CSS fix to this? :) Thanks for sharing these awesome widgets!

**Comment by jquense** [comment]
this sounds like a overflow issue with some style on the modal... whatever section has the scrollbar probably also needs `overflow: visible` as well. I also use them in bootstrap modals but don't have this issue maybe something else is changing the style?

**Comment by aikeru** [comment]
wow, thanks for the quick reply! I think you're right, and when I change the overflow of the modal container it seems to work ... silly me.
I'll close this issue, thank you!
