### ISSUE TITLE
Requesting gulp task for non-minified react-widgets.js

### ISSUE THREAD

**Issue by unphased** [jquense/react-widgets#200]
Our require.js build config isn't working properly with the format of the code generated in `/dist`.

This means I can still use `react-widgets.js`. It is minified, though. And I get this mysterious error the moment I interact with a DateTimePicker: 

<img width="701" alt="reactwidget" src="https://cloud.githubusercontent.com/assets/1542910/9917704/19541382-5c91-11e5-9189-3f7966bb45a3.png">

I am now stuck here then, because I cannot debug a minified script.

So it would be really great if I can build the `react-widgets.js` myself (unminified of course). I may just be blind but I can't find something corresponding to this in the gulpfile.

*edit* Actually maybe the config can be found in webpack config

**Comment by unphased** [comment]
Actually, so I found that I can just change the webpack config to not minify, but now the problem is the dist-build task just errors: 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: /Users/steven/Documents/react-widgets/src/configure.js: Missing options in babel config: `extra.externalHelperPlugin`
    at NodePath.Plugin.visitor.Program (/Users/steven/Documents/react-widgets/node_modules/gulp-babel-helpers/node_modules/babel-plugin-external-helpers/index.js:26:17)
    at NodePath.call (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/traversal/index.js:76:17)
    at Object.traverse [as default] (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/traversal/index.js:55:14)
    at PluginPass.transform (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/transformation/plugin-pass.js:51:27)
    at File.transform (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/transformation/file/index.js:621:12)
    at /Users/steven/Documents/react-widgets/node_modules/babel-core/lib/transformation/pipeline.js:168:19
```

**Comment by unphased** [comment]
Im using node v0.10.32, which may be a problem.

**Comment by jquense** [comment]
the missing gulp-babel is just an error in the build process, not the compiled code. 

The error in your original post looks like you aren't including the Globalize.js dependency anywhere.

**Comment by unphased** [comment]
Thanks for the quick response. Appreciate the advice. I will try some things to make Globalize load... 

So you reckon that the breakage from when I try to build is a problem with `gulp-babel-helpers`?

**Comment by jquense** [comment]
it's gulp-babel-helpers unfortunately the code for the released version hasn't been pushed to github yest and I'm traveling so I don't have access to that computer. it's a pretty dumb situation :P I'll fix it in a few days

**Comment by unphased** [comment]
OK cool. 

Right now I have been able to get a non-minified build of react-widgets.js built by using `gulp` inside the branch in which you took `gulp` out (heh...)... but now the browser is having this problem: 


<img width="600" alt="weird" src="https://cloud.githubusercontent.com/assets/1542910/9940392/aaf15a46-5d3d-11e5-9cd7-a5c3cc3e1c42.png">

I am pretty sure Globalize.js is being loaded...

**Comment by jquense** [comment]
using the 3.0.0 branch will have a bunch of things like this since I can break stuff and it's in alpha so no docs. best I can say is to look at the dev folder for a bit of an example. but essentially there is an initiation step for the localized. I'd try and stay on master if you can since the API is stable. 

Also if you want an u minimized build I might recommend just using the npm module and something like webpack or browserify. if only to debug

**Comment by unphased** [comment]
I just need a date picker, i gave up on that long ago because its abundantly *un*clear to me how to get a ES5 JS file that only has the date picker in it. 

I tried getting the npm module but `gulp dist-build` fails in there: `ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./lib/index.js` 

Yes I actually know the reason. The reason is `lib-clean` erased the freaking lib dir.

**Comment by jquense** [comment]
I am not sure why you are using trying to build a copy of the module using its build process at all. if you aren't doing development on it then the right thing to do is just follow the docs. there is not date picker only dist build. if you want modular build then you should require what you need from lib directly after a clean install from npm. you webpack or browserify to bundle up a concise build. if you want to use the built library then you get everything, and you need to include globalize.js yourself (per the docs). The recommended way to consume this however is using the commonJS modules in lib. 

I will be happy to fix the build you'll have to wait until I have a free moment

**Comment by jquense** [comment]
which is all to say that trying to build this after installing  it as a dependency is not supported at all, which is why it comes with compiled modules or a global build

**Comment by unphased** [comment]
OK. Well, again, I really appreciate your help, I have to move on and try another project that does not have the globalize.js dependency because that is what's breaking everything here.

Thanks

**Comment by jquense** [comment]
Ok good luck!
