### ISSUE TITLE
Combobox: Make toggle button optional

### ISSUE THREAD

**Issue by thuringia** [jquense/react-widgets#204]
Are you open to making the combobox's toggle button optional? At work, we need a combobox/autocomplete that looks like a regular input field and other than that react-widgets fits perfectly.
I'd gladly make a PR for it if this would make it into the project.

Thanks and keep up the great work!

**Comment by jquense** [comment]
I don't necessarily want the additional maintenance cost of another code path here (or extra styles)...is there any reason that ya'll can't just add a css rule that hides the toggle? Or do you really need it not to render?

**Comment by thuringia** [comment]
Setting the button to display: none would of course work as well…
Having it not render feels more clean and configurable, but I absolutely see your point.
Let me see what additions or changes we will need so satisfy or accessibility requirements, if we need to add more options, I'll add this one to the PR.
For now, we'll stick to the CSS solution.

Thanks for the quick reply!
