### ISSUE TITLE
babelHelpers.classCallCheck is not a function

### ISSUE THREAD

**Issue by jamalneufeld** [jquense/react-widgets#205]
When using browserify to compile the javascript it throws this error:

`Uncaught TypeError: babelHelpers.classCallCheck is not a function`

This happens in the `/lib/util/localizers.js` here:

    var DateLocalizer = function DateLocalizer(spec) {
      var _this2 = this;

      babelHelpers.classCallCheck(this, DateLocalizer);

**Comment by jquense** [comment]
what version are you using?

**Comment by jamalneufeld** [comment]
react-widgets: "2.8.0"
grunt-browserify: "4.0.1"
babelify: "6.3.0"

**Comment by jquense** [comment]
can you try upgrading to 2.8.1 and see if its still there?

**Comment by jamalneufeld** [comment]
Yeah, still happening.

**Comment by jamalneufeld** [comment]
Also happening here, even if I specifically load this module: `/lib/DateTimePicker.js` same error

**Comment by jquense** [comment]
not really sure what to tell you...does the lib/utils directory have a babelHelpers file? its there when I look at the tag

**Comment by jamalneufeld** [comment]
Just in case there's a typo somewhere, I see a `lib/util/` folder without an (s) and it does have a babelHelpers file in it.

**Comment by jquense** [comment]
I think something weird is happening in your bundling, if the file is there, and the files are requiring it, I am not sure why it wouldn't work.

**Comment by jamalneufeld** [comment]
Definitely weird. So what I'm seeing is that when I do this:
    
    var babelHelpers = require('./util/babelHelpers');
    var _react = require('react');
    console.log(babelHelpers);

I get `Object {}`. So the file is being loaded, it's creating an object. But it's empty

**Comment by jquense** [comment]
so it is UMD, maybe browserify is choosing the wrong import method?

**Comment by jamalneufeld** [comment]
So if I modify babelHelpers, make babelHelpers and object that is returned with module.exports, then it loads it properly. So yeah, I think it's a UMD issue.

**Comment by jquense** [comment]
one of your transforms is breaking it perhaps? I don't use Browserify very often so I couldn't troubleshoot it but I know generally browserify folks don't have trouble using this normally...

**Comment by jamalneufeld** [comment]
Doesn't seem like my transforms have really touched the library. One thing I see is that babelHelpers is setting itself to global, which might not be compatible with browserify. Any thoughts? I'm trying to see if I can nail it down to make it fully compatible.

**Comment by jquense** [comment]
its not actually setting it to global, it is shadowing the variable tho. browserify should be able to handle it  just fine...like I said tho I am not a browserify user generally so I am not quite sure where to go next, perhaps try the IRC room or gitter if there is one? I definately would be interested in fixing it though if it is a problem on my end

**Comment by jamalneufeld** [comment]
In the end I decided to give webpack a try, seems to work fine there. Thanks for looking into this though, must be a browserify issue.
