### ISSUE TITLE
Extend suggestion capability to DropdownList from ComboBox

### ISSUE THREAD

**Issue by ksespinola** [jquense/react-widgets#207]
Is there a reason you cant pass the `suggest` prop to `DropdownList` like you do `ComboBox`? Would you be open to me porting over the feature to the other component?

**Comment by jquense** [comment]
I am open to it, but I am not sure how would that work. there is no typing in a Dropdownlist to be able to suggest anything. Suggest only makes sense (to my mind) if you can type and select a value that isn't in the list, so the widget can suggest something from the list if you are close. In a dropdown, you can only select from the list so filtering gets you most of the way there.

**Comment by ksespinola** [comment]
When the filter prop is added to the component a search box appears in the list. I'd like to expose `suggested` there.

http://jquense.github.io/react-widgets/docs/#/dropdownlist/filter

**Comment by jquense** [comment]
I can see how that'd be helpful, but I think I want to pass, the suggesting stuff in the combobox is some of the more fragile and complex code in the suite and I don't want to have to maintain it twice. Selfish i know
