### ISSUE TITLE
Any support for data virtualization / large sets?

### ISSUE THREAD

**Issue by aikeru** [jquense/react-widgets#209]
If I want to load records in excess of, say 500 or 10,000 for example for the Combobox control, Kendo UI widgets have a feature they call "data virtualization" and "ui virtualization".

I know this is non-trivial to implement, but I was wondering if this is something you might have considered adding or have written any support for? :)

**Comment by jquense** [comment]
Hey there,

So I have gona back and forth on having this work of support in core here, and I have landed on not doing it. virtualizing lists is really non trivial and would  end up being a project in its own right.

However, we have this requirement at work as well, and one of the starting requirements of this widget library was that it should be easy to integrate virtual lists with it. To that end it is _really_ easy to drop in an existing library for virtualizing lists to react widgets (I recommend react-list).

Here is a gist of what we do, your mileage may vary: https://gist.github.com/jquense/3402adbda1f54a666cc9
