### ISSUE TITLE
[DateTimePicker] Invalid date format string error

### ISSUE THREAD

**Issue by fullvlad** [jquense/react-widgets#210]
Hello everyone!

I have a `DataTimePicker` in my code and I want to accept multiple input formats and the display format to be `mm:ss`. The field also needs to accept between `00:00` and `59:59`. Here is an example:

```
let parseFormats = ["mm:ss", "mm ss", "m:ss", "m ss", "mm-ss", "m-ss", "mm.ss", "m.ss", "ss", "s"];

[...]

<DateTimePicker
    onChange={this._updateField}
    parse={parseFormats}
    value={this.state.value} min={new Date(0)} max={new Date(1000 * 3599)}
    calendar={false} time={false} format={"mm:ss"}/>
```

But when I enter wrong formatted text (like `asdasda`) in the input I get:
```
Uncaught Invalid date format string 's'.
```

How can I accept all those formats between that interval and still not get an error at runtime?

**Comment by jquense** [comment]
It doesn't look like globalize accepts a single "s" as a valid format, I am sure that "ss" will cover that case as well

**Comment by fullvlad** [comment]
That was the problem, thank you very much @jquense!

**Comment by jquense** [comment]
glad to help
