### ISSUE TITLE
update to react 0.14

### ISSUE THREAD

**Issue by jsdmc** [jquense/react-widgets#211]
Hello there)
Thanks for nice components. That's exactly what I was looking for.
Currently it's not possible to use them together with react v0.14
Any plans to upgrade?

**Comment by jquense** [comment]
yup when 0.14 is released. for now there is a prerelease (3.0.0-alpha) that supports 0.14 but be warned it breaks stuff and there is no documentation yet

**Comment by jsdmc** [comment]
Aha, cool! Thanks
