### ISSUE TITLE
Uncaught TypeError: (this.globalize || e).format is not a function

### ISSUE THREAD

**Issue by mpbill** [jquense/react-widgets#212]
I am getting this error but I did include globalize on the page.  I am using reactjs.net in an asp.net mvc app.

    <div id="nightly_react">

    </div>
    <script src="~/bower_components/react/react.min.js"></script>
    <script src="~/bower_components/react-bootstrap/react-bootstrap.min.js"></script>
    <script src="~/bower_components/moment/min/moment.min.js"></script>
    <link href="~/bower_components/react-widgets/dist/css/core.css" rel="stylesheet" />
    <link href="~/bower_components/react-widgets/dist/css/react-widgets.css" rel="stylesheet" />
    <link href="~/bower_components/react-widgets/dist/css/variables.css" rel="stylesheet" />
    <script src="~/bower_components/globalize/dist/globalize.js"></script>
    <script src="~/bower_components/react-widgets/dist/react-widgets.js"></script>
    <script src="@Url.Content("~/React/jsx/NightlyReact.jsx")"></script>

**Comment by jquense** [comment]
you may be including the wrong version, it needs globalize 0.1.x and not the newer 1.0.0

**Comment by mpbill** [comment]
Thank you, I changed my globalize version to ~0.1 and now I am getting `Uncaught TypeError: this._date.clone is not a function`    is that an error with moment?
