### ISSUE TITLE
bug when mouse is pressed, but leaves the element

### ISSUE THREAD

**Issue by SimonErich** [jquense/react-widgets#213]
Using Chrome i could reproduce a strange behavior in the demo numberpicker as well.
When you press the "+" or "-" Buttons with your mouse and keep the mouse pressed, but leave the element (so it's not hovered anymore), the numberpicker won't stop to increase/decrease.
I guess it's a problem with the mouseover cancel event.

**Comment by jquense** [comment]
thanks, I am not sure if this is a bug in Reacts event system but its definitely not the right behavior.
