### ISSUE TITLE
itemRender prop

### ISSUE THREAD

**Issue by dubrowgn** [jquense/react-widgets#214]
Currently list controls such as `Combobox` have a prop for custom rendering of items called `itemComponent`. This is great, however it forces you to create a new component class for each type of data you want to use with a React-Widgets list control. For simple or one-off cases, this quickly becomes very tedious. What do you think about allowing for a custom `itemRender` function prop that takes an item and returns a component instance? 

For example:

```jsx
itemRender={ person => <span>{ person.lastName }, { person.firstName }</span> }
```

Instead of:

```jsx
class ListItem extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        var person = this.props.item;
        return <span>{ person.lastName }, { person.firstName }</span>);
    }
}

...

itemComponent={ ListItem }
```

**Comment by jquense** [comment]
Hi there, I get your concern however in React 0.14 stateless components will make it a moot point  since a function will be a valid component anyways. we will get that for free and still allow the more verbose component defs as well

**Comment by dubrowgn** [comment]
Oh awesome! I hadn't been following the development of 0.14. I guess it would be pretty redundant then. I'll move to the RC and see how it goes.

Thanks!
