### ISSUE TITLE
Why does onChange fire again after onSelect?

### ISSUE THREAD

**Issue by piercefrawley** [jquense/react-widgets#215]
Hi there, I'm having an issue with the Combobox where I am trying to null out the value prop passed into the Combobox after selecting a value. The reason for this is that the onSelect function is invoking this.change after calling notify(this.props.onSelect, data).

This is the current implementation:

```
_onSelect(data){
    this.close()
    notify(this.props.onSelect, data)
    this.change(data)
    this.focus();
  },
```

Would it be possible to change it to the function below so that this.props.onSelect is invoked after this.change?

```
_onSelect(data){
    this.close()
    this.change(data)
    notify(this.props.onSelect, data)
    this.focus();
  },
```

**Comment by jquense** [comment]
hey there,

In general I don't want to the change the order of the events, it makes more sense before to my mind and enables some patterns that way that i'd like to keep, also at this point that change would constitute a breaking one, so you'd have to wait for a major bump.

I think the best way to handle your use case tho is like this:

```js
render(){
  return <ComboBox 
     value={this.state.value} 
     onChange={this.handleChange} 
     onSelect={this.handleSelect} />
}
handleSelect(){
  this.selected = true
}

handleChange(value){
  if (this.selected) {
    this.selected = false;
    this.setState({ value : null })
  }
  else 
    this.setState({ value })
}
```
