### ISSUE TITLE
Bundling errors with React 0.14

### ISSUE THREAD

**Issue by insin** [jquense/react-widgets#222]
A bunch of internals have been moved to the [fbjs](https://github.com/facebook/fbjs) package:

```
ERROR in ./~/react-widgets/lib/DateTimePicker.js
Module not found: Error: Cannot resolve module 'react/lib/invariant'
 @ ./~/react-widgets/lib/DateTimePicker.js 11:25-55

ERROR in ./~/react-widgets/lib/DateTimePicker.js
Module not found: Error: Cannot resolve module 'react/lib/getActiveElement'
 @ ./~/react-widgets/lib/DateTimePicker.js 15:32-69

ERROR in ./~/react-widgets/~/uncontrollable/lib/uncontrollable.js
Module not found: Error: Cannot resolve module 'react/lib/invariant'
 @ ./~/react-widgets/~/uncontrollable/lib/uncontrollable.js 4:16-46

ERROR in ./~/react-widgets/lib/util/localizers.js
Module not found: Error: Cannot resolve module 'react/lib/invariant'
 @ ./~/react-widgets/lib/util/localizers.js 5:16-46
```

**Comment by jquense** [comment]
the 2.x.x line isn't going to work with 0.14, 3.0.0 is coming with support. you can use the 3.0.alpha's (react-widgets@next) if you need support right now.

**Comment by amarant** [comment]
The 3.0 alphas still have old peerDependencies :
>"peerDependencies": {
    "react": "^0.14.0-beta3",
    "react-dom": "^0.14.0-beta3"
  },

**Comment by insin** [comment]
react-widgets@3.0.0-alpha.5 installs without warning when I have react/react-dom 0.14.0 in mydependencies.

Putting this here for anyone else using the alpha. 

```js
var configureReactWidgets = require('react-widgets/lib/configure')
var globalize = require('globalize') // globalize@0.1.1
var globalizeLocalizers = require('react-widgets/lib/globalize-localizers')

configureReactWidgets.setLocalizers(globalizeLocalizers(globalize))
```

**Comment by jquense** [comment]
thanks @insin I am hoping to update docs and do a proper release this weekend, since there were a few other breaking localizer changes
