### ISSUE TITLE
Unable to use DateTimePicker

### ISSUE THREAD

**Issue by agile116** [jquense/react-widgets#223]
Hi,

I'm unable to use DateTimePicker component. It shows invalid date in the date popup. Any issues with the following implementation?
import DateTimePicker from 'react-widgets/lib/DateTimePicker';
import configure from 'react-widgets/lib/configure';
import momentLocalizer from 'react-widgets/lib/localizers/moment';
configure.setDateLocalizer(momentLocalizer(moment));

  <DateTimePicker format={'MM/DD/YYYY hh:mm A'} defaultValue={new Date()} culture='en'/>

**Comment by jquense** [comment]
are hi there!  you using the 3.0.0 beta? I'm not sure the moment localized works yet, tho it should. 

you don't need the configure.setDateLocalizer the localizers set themselves already... 

any further error or a stack trace would be helpful. and goes without saying betas are betas, consider using the 2.x line if you want a stable library

**Comment by agile116** [comment]
Thanks for you quick response. I'm using 3.0.0 beta. 2.x doesn't support react 1.4, right?
If I don't use configure.setDateLocalizer, it gave me localizer not set error.

**Comment by jquense** [comment]
it gives you the missing error if you just use `momentLocalizer(moment)`? can you set some break points on the moment localized and gather a bit more info about where it's failing? I'll take a look first this tomorrow but more context is helpful in case I can't repo the issue. 

thanks

**Comment by agile116** [comment]
sure, thanks.

**Comment by agile116** [comment]
I see the following stack when neither configure.setDateLocalizer(momentLocalizer(moment)); or momentLocalizer(moment) are set. But see invalid date on the popup when they are set.
![error](https://cloud.githubusercontent.com/assets/11846035/10421859/ba53ed3c-70e3-11e5-96ca-7e762593fc4a.png)

Uncaught Error: [React Widgets] You are attempting to use a widget that requires localization (Calendar, DateTimePicker, NumberPicker). However there is no localizer set. Please configure a localizer. 

see http://jquense.github.io/react-widgets/docs/#/i18n for more info.

get	@	localizers.js:159
getFormat	@	localizers.js:130
getFormat	@	DateTimePicker.js:515

**Comment by agile116** [comment]
any other things I need to do such as setup locale in moment.js except the below code? Please note that I got momentLocalizer from react-widgets/lib/localizers/moment.

import DateTimePicker from 'react-widgets/lib/DateTimePicker';
import configure from 'react-widgets/lib/configure';
import momentLocalizer from 'react-widgets/lib/localizers/moment';
momentLocalizer(moment);

**Comment by jquense** [comment]
ok figured it out, fixed and released as `beta.1`

this is the correct setup for it, which you seem to already have

```js
import DateTimePicker from 'react-widgets/lib/DateTimePicker';
import momentLocalizer from 'react-widgets/lib/localizers/moment';

momentLocalizer(moment);
```

**Comment by agile116** [comment]
Thanks, I'll try it out tomorrow. :)

杨小林

**Comment by kolima** [comment]
@jquense Thanks, update resolves this issue.

**Comment by 9o** [comment]
Where is moment defined?

**Comment by JWDobken** [comment]
import moment from 'moment';
