### ISSUE TITLE
React 0.14.0 Compatibility

### ISSUE THREAD

**Issue by sikhote** [jquense/react-widgets#224]
Thanks for the great plugin, it's been simple and very useful to work with.

I am seeing a console error with React 0.14.0 that was recently released:

`react default.initializeTouchEvents is not a function`

Is there a potential work-around planned?

If it helps, some [other modules] (https://github.com/JedWatson/react-tappable/issues/45) are having this issue too.

**Comment by jquense** [comment]
the current stable version just doesn't support 0.14, you can use the 3.0.0 beta `npm i react-widgets@next` if you are anxious to get on react 0.14, but it is still in beta.
