### ISSUE TITLE
webpack  errors 

### ISSUE THREAD

**Issue by ichbinedgar** [jquense/react-widgets#227]
Hi,
I was going to try to use your library, but I received some errors from webpack. I've installed the required loaders (css-loader, style-loader, file-loader, url-loader) and I'm using babel-loader as the loader that translates my jsx files. 
These are the errors when I tried to use the date picker: 
```javascript
DateTimePicker = require('react-widgets/lib/DateTimePicker')
```
The console output:
```
ERROR in ./~/react-widgets/lib/DateTimePicker.js
Module not found: Error: Cannot resolve module 'react/lib/getActiveElement' in C:\Users\user\Documents\app\node_modules\react-widgets\lib
 @ ./~/react-widgets/lib/DateTimePicker.js 15:32-69

ERROR in ./~/react-widgets/~/uncontrollable/lib/uncontrollable.js
Module not found: Error: Cannot resolve module 'react/lib/invariant' in C:\Users\user\Documents\app\node_modules\react-widgets\node_modules\uncontrollable\lib
 @ ./~/react-widgets/~/uncontrollable/lib/uncontrollable.js 4:16-46

ERROR in ./~/react-widgets/lib/util/localizers.js
Module not found: Error: Cannot resolve module 'react/lib/invariant' in C:\Users\user\Documents\app\node_modules\react-widgets\lib\util
```
this is my configuration:
```
module.exports= {
  entry: "./app-client.js",
  output: {
    filename: "public/bundle.js"
  },
  module: {
    loaders: [
      { test: /\.css$/,  loader: "style-loader!css-loader" },
      { test: /\.less$/, loader: "style-loader!css-loader!less-loader" },
      { test: /\.gif$/, loader: "url-loader?mimetype=image/png" },
      { test: /\.woff(2)?(\?v=[0-9].[0-9].[0-9])?$/, loader: "url-loader?mimetype=application/font-woff" },
      { test: /\.(ttf|eot|svg)(\?v=[0-9].[0-9].[0-9])?$/, loader: "file-loader?name=[name].[ext]" },
      {
        exclude: /(node_modules|app-server.js|api|config.js|routes)/,
        loader: 'babel'
      }
    ]
  },
  resolve: {
   extensions: ['', '.js', '.jsx']
  }
};
```

Do you know if I missing something?

Thanks

**Comment by jquense** [comment]
The current stable version of React isn't compatible with react 0.14, either downgrade to react 0.13.x or you can use the 3.0.0-beta if you are interested :)

**Comment by ichbinedgar** [comment]
ohh ok, thanks!

**Comment by ichbinedgar** [comment]
Ok, I used the beta. I've installed the react-widgets-moment-localizer. And the date picker element is being displayed, but when I click on the calendar or time icon I received the following errors in the console :(  
```
bundle.js:64973 Uncaught TypeError: undefined is not a function

Uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.1.2.2.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

**Comment by jquense** [comment]
you shouldn't actually be using the moment localizer package at this point (there is one in `lib/localizers/moment`) Although I don't think it should cause an issue.

More than likely though this error is build related, or some other issue with upgrading to react 0.14

**Comment by ichbinedgar** [comment]
ok, thanks. I used it, because i got this error:
Uncaught Error: [React Widgets] You are attempting to use a widget that requires localization (Calendar, DateTimePicker, NumberPicker). However there is no localizer set. Please configure a localizer.

**Comment by jquense** [comment]
ya sure like this: https://github.com/jquense/react-widgets/blob/master/dev/configure-moment.js

**Comment by ichbinedgar** [comment]
Great! that fixed it! :+1: 
```
var localizers = require('react-widgets/lib/localizers/moment');
localizers(moment);
//use the widgets
var DateTimePicker = require('react-widgets/lib/DateTimePicker');
```

**Comment by jquense** [comment]
i'm glad :)
