### ISSUE TITLE
Add possibility to disable selection of the first element in the list by default

### ISSUE THREAD

**Issue by smashercosmo** [jquense/react-widgets#228]
In Combobox and Multiselect the first element in the list is focused by default. So when you hit enter this element is selected. But sometimes you need for example to create custom tag by default or just hit enter and trigger some event with input value, that you've just typed. This is Google search behaviour: you type something, you get the list of options, then you can just hit enter and perform a search or you can press up or down arrows and start choosing options.

**Comment by smashercosmo** [comment]
@jquense any response on that, please?

**Comment by jquense** [comment]
Sorry I'm traveling so I haven't had time to look at this. my first response is to pass on this since it adds a level of complexity I don't want to maintain. I do think tho that exposing the selected and focused items with a proper API is reasonable. Probably letting those values be controlled like value/onChange

**Comment by smashercosmo** [comment]
@jquense so, could you then give a rough example of how this feature could be implemented with these new APIs?

**Comment by Xurma2** [comment]
@smashercosmo hi! 
How did you decide this question?
@jquense

**Comment by jquense** [comment]
right now any lower API for the focused items are on hold until I come up with a better way of managing them internally. In general tho I think that the current is the right one, if only because that's what a11y guidelines say should happen

**Comment by smashercosmo** [comment]
Hm... so google search bar behaviour is wrong from the a11y perspective?

**Comment by jquense** [comment]
these arent search bars they are alternatives to the `select` tag which carries very specific a11y semantics. the main difference tho is selecting something from a list vs suggestions for Un structured text to autofill in a text box. To meet your need I think we probably need a proper autocomplete widget

**Comment by smashercosmo** [comment]
Hey @jquense do you have any plans to address this in some way in the upcoming v4?))

**Comment by jquense** [comment]
not in particular,  tho v4ay put us in a better place for adding those Apis but I'm nit sure yet. it's not a super high priority tho over fixing bugs and the like :)

**Comment by RaviAtTTN** [comment]
Hey @jquense  I want a default behaviour "to create a new tag on clicking enter" rather than selecting the first element matched. How can I do this?
