### ISSUE TITLE
DateTimePicker format no longer appears to work in beta1

### ISSUE THREAD

**Issue by thecaddy** [jquense/react-widgets#229]
```
<DateTimePicker
          format={'yyyy-MM-dd'}
          value={value}
          time={options.time}
          calendar={options.calendar}
          max={options.max}
          onChange={this.handleCh

ange}
          ref={fieldRef}
        />
```

![screen shot 2015-10-15 at 11 31 09 am](https://cloud.githubusercontent.com/assets/1521981/10523651/4f4f8812-7330-11e5-9670-30b7b87e8c9a.png)

I remove the format field and things look fine:

![screen shot 2015-10-15 at 11 33 07 am](https://cloud.githubusercontent.com/assets/1521981/10523687/8a6bb998-7330-11e5-892b-cbe0b3c97996.png)

**Comment by jquense** [comment]
That is going to depend on what localizer you are using. Are you using moment or globalize, and what version?

**Comment by thecaddy** [comment]
I'm using the moment, ` "moment": "~2.10.3"`,  I tried the moment formatting and had the same results. 

http://momentjs.com/docs/#/displaying/format/

I grabbed the code from one of the earlier issues.

```
import DateTimePicker from 'react-widgets/lib/DateTimePicker';
import momentLocalizer from 'react-widgets/lib/localizers/moment';

momentLocalizer(moment);
```

**Comment by jquense** [comment]
so reading the moment docs: `'yyyy-MM-dd'` is not a valid format, you meant: `'YYYY-MM-DD'` the patterns are case sensative

**Comment by thecaddy** [comment]
I tried using the moment formatting as indicated above and got a similar result:

![screen shot 2015-10-15 at 2 46 28 pm](https://cloud.githubusercontent.com/assets/1521981/10528515/8b12eb44-734b-11e5-8154-57f8a2f09b24.png)

![screen shot 2015-10-15 at 2 46 03 pm](https://cloud.githubusercontent.com/assets/1521981/10528517/8da8c662-734b-11e5-8fa7-a4a4fc7f29bb.png)

**Comment by jquense** [comment]
k I'll take a closer look, thanks for the report

**Comment by jquense** [comment]
So I can't repo that behavior. I tried your configuration about and it worked fine...my only thought is that you have something configured oddly. You can use this as a reference (https://github.com/jquense/react-widgets/blob/master/dev/configure-moment.js) but it looks like you may have something that is breaking it further in your code...are you you wrapping the component is it setting format?

**Comment by thecaddy** [comment]
I went through your example and you're absolutely right.  I was missing a config sorry about that.  Thanks for the quick response!
