### ISSUE TITLE
Combobox widget gives an error in IE8

### ISSUE THREAD

**Issue by codeshiny** [jquense/react-widgets#231]
I'm running webpack in production mode and it causes the combobox widget to throw an exception in IE8. The exception is 'Exception thrown and not caught'.
It only happens when using production and not debug.
Is there anything I can do?

**Comment by jquense** [comment]
not that I know of... any chance you can track Down the issue a little further, I'd happily fix it but redoing these bugs is not super feasible for me St the moment

**Comment by jefferydutra** [comment]
I am also having the same issue, I will try and track it down further

**Comment by bensu** [comment]
After some investigation I found that the error is triggered by the function `babelHelpers.classCallCheck`  with the error `"Cannot call class as a function"`. I know it is probably not enough to reproduce, but I couldn't trace the stack up in IE8 to see which class is being called as a function.
