### ISSUE TITLE
`onBlur` event on the input element for DateTimePicker

### ISSUE THREAD

**Issue by webmasterkai** [jquense/react-widgets#232]
Passing an onBlur to DateTimePicker does nothing. I expect it to be called when the `<input />` element loses focus. Is there another way I should use?

**Comment by jquense** [comment]
hey there, what version are you using? the onBlur prop should be called (https://github.com/jquense/react-widgets/blob/v2.8.2/src/DateTimePicker.jsx#L352)

**Comment by webmasterkai** [comment]
Thanks for the quick response. I'm not sure what I was doing wrong but it's working as expected now. Sorry for the trouble.
