### ISSUE TITLE
Autocomplete/Aria-autocomplete Doesn't Prevent Autocomplete in ComboboxInput

### ISSUE THREAD

**Issue by piercefrawley** [jquense/react-widgets#237]
When typing into the combobox, I've noticed that my previously cached searches are being displayed by the browser's autocomplete regardless of value of `aria-autocomplete` or ComboboxInput's `autocomplete='off'`. Below is an example. Do you have a way of preventing this?

![screen shot 2015-10-26 at 4 29 01 pm](https://cloud.githubusercontent.com/assets/3795505/10745491/72369cf8-7bff-11e5-848b-182091bc00cf.png)

**Comment by jquense** [comment]
thanks for the report, definitely a bug!

**Comment by adros** [comment]
Just a quick workaround, until this is fixed:

In your `render` method add ref

    <Combobox ref="combobox"

In your `componentDidMount`:

    componentDidMount: function() {
        ReactDOM.findDOMNode(this.refs.combobox.refs.inner.refs.input).setAttribute("autocomplete", "off");
    },
