### ISSUE TITLE
_react2.default is undefined

### ISSUE THREAD

**Issue by codemeasandwich** [jquense/react-widgets#240]
Am trying to use your widgets with RequireJS be am getting the following WebPack/'babelHelpers' error: 
"TypeError: _react2.default is undefined" on line 766 in react-widgets.js"

Any fix?
Thanks

**Comment by jquense** [comment]
you configuration is probably wrong, I don't know anything about require js but the code does work, so it should be a build issue on your end

**Comment by MiaranaDIY** [comment]
hey how can i include this to index.html?

doing this <script src="/static/js/react-native-bootstrap-slider.js"></script>
i got the same error on Firefox console: 

TypeError: _react2.default is undefined
 react-native-bootstrap-slider.js:126:1 

Please point me out whats wrong, Big Thanks
