### ISSUE TITLE
NumberPicker: strange behavior inside Semantic UI button

### ISSUE THREAD

**Issue by newsiberian** [jquense/react-widgets#241]
Hello, my goal is to repeat the following button:
![add_to_cart_btn](https://cloud.githubusercontent.com/assets/11130487/10802430/ab56c130-7dde-11e5-89a8-c52980d7e117.jpeg)

I'm using Semantic UI and my code looks like this:
```
<div className="ui basic segment">
  <button className="ui fluid big green button">
    <NumberPicker />
    <T>addToCart</T>
  </button>
</div>
```
But in the DOM it becomes:
![add_to_cart_btn_code](https://cloud.githubusercontent.com/assets/11130487/10802609/9f993188-7ddf-11e5-8585-f1982c877027.jpeg)

and it looks like:
![add_to_cart_btn_bad](https://cloud.githubusercontent.com/assets/11130487/10802615/ad319d62-7ddf-11e5-973d-4ba5426301c4.jpeg)

Is there a way so solve this?

**Comment by newsiberian** [comment]
It looks like I hastened with this issue, because it can be avoided by using `div` instead of `button` tag. But I'll leave the issue closing at your discretion.

**Comment by jquense** [comment]
the problem is you are trying to put a complex input inside a button tag, which is neither semantic or valid html
