### ISSUE TITLE
bugs in isomorphic javascript: different rendering result between server and client

### ISSUE THREAD

**Issue by imyzf** [jquense/react-widgets#244]
I'm using react-widgets to build isomorphic web app. But it seems there are some bugs.

First, it's different in sever rending and browser rending. Its result string has same props but in different  order.
![image](https://cloud.githubusercontent.com/assets/8298849/10988150/e86dcaae-8474-11e5-8591-515af948f76d.png)

```html
<!-- browser -->
<input aria-expanded="false" tabindex="0" aria-haspopup="true" aria-owns="rw_1_cal" value="2015-11-04" aria-busy="false" role="combobox" id="rw_1_input" type="text" class="rw-input" data-reactid=".1yzhykx02yo.2.0.0.0.0.0.0">

<!-- server -->
<input id="rw_1_input" tabindex="0" role="combobox" aria-expanded="false" aria-busy="false" aria-owns="rw_1_cal" aria-haspopup="true" value="2015-11-04" type="text" class="rw-input" data-reactid=".1yzhykx02yo.2.0.0.0.0.0.0"/>
```

We find out it's because of `BabelHelpers._extend`. It will have different result order between server and browser. Then we deleted `Object.assign` just using the function after it, the problem gone.

```javascript
// require this before require react-widgets
require('react-widgets/lib/util/babelHelpers')._extends = function(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];

    for (var key in source) {
      if (Object.prototype.hasOwnProperty.call(source, key)) {
        target[key] = source[key];
      }
    }
  }

  return target;
};
```

However, there is another problem.
![image](https://cloud.githubusercontent.com/assets/8298849/10988304/3be7a708-8476-11e5-9879-a5bc70221af9.png)

the number in the id will reset to `1` every time in browser, but always increased in server.

**Comment by jquense** [comment]
Hi there, thanks for the bug reports

two things. You need to provide your own `id` on the server to keep them static across the environments. This is due to a bug in how React handles this stuff.

If `Object.assign` is unstable, then your server enivornemnt is either weird, or polyfilling it incorrectly. In either case there is nothing I can do about it because I don't own the babelHelpers, and I can't control your env's implementation of Object.assign

**Comment by imyzf** [comment]
Thanks! I'm using babel-core/register to compile es6. I'm going to find out more about our environment.
