### ISSUE TITLE
DropdownList should allow the use to use Space to open the menu.

### ISSUE THREAD

**Issue by hjnilsson** [jquense/react-widgets#248]
To be consistent OS-level dropdown, hitting Space when a DropdownList is focused, should open up the dropdown and allow the user to select an option with up/down arrows. Confirm selection with Enter and cancel it with Escape.

**Comment by jquense** [comment]
late reply but, the dropdown does do most of that already, the only thing it doesn't is allow opening via the space key, which will be in the next release.

Thanks!

**Comment by hjnilsson** [comment]
Excellent! Thank you, indeed the components are of very high quality. :)

**Comment by jquense** [comment]
should be fixed
