### ISSUE TITLE
Required property onRequestClose isn't used anywhere in Popup component

### ISSUE THREAD

**Issue by smashercosmo** [jquense/react-widgets#249]
Can't understand the purpose of [this](https://github.com/jquense/react-widgets/blob/master/src%2FPopup.jsx#L43) prop. May be it should be removed?

**Comment by jquense** [comment]
meh, yeah its a relict from a time when the Popup handled closing itself when you clicked outside it, slowly that was all replaced by the parent closing onBlur. It could be removed but its not hurting anything.

**Comment by smashercosmo** [comment]
I'll submit the PR then?

**Comment by jquense** [comment]
sure
