### ISSUE TITLE
DateTimePicker: onBlur to include the current value ?

### ISSUE THREAD

**Issue by slybridges** [jquense/react-widgets#254]
Hello :wave:

I'm trying to use the `DateTimePicker` along with [redux-form](https://github.com/erikras/redux-form).

I've noticed that if you select a Date using the DatePicker, it properly triggers an `onChange` event with the new value. However, once the DatePicker field looses focus, the `onBlur` event that is triggered doesn't contain that value anymore (namely, `e` being the triggered event,` e.tartget.value = ""`).

The problem is that `redux-form` updates its form values on `onChange`, but also on `onBlur`, i.e.field value is updated to `""` when loosing the focus.

How could I get the `onBlur` event to include the `e.target.value` field properly filled (or just replace `e` by the date value, similar to what is done with `onChange`) ?

Thanks!

**Comment by jquense** [comment]
Hey there,

I don't actually think I can address this without some sort of solution that targets redux-form fairly specifically, which isn't a good option. I'm not actually sure why the target value is blank, it may be related to how React seems to recycle the event targets on synthetic events, or maybe I am just doing something a bit wonky. In any case fixing it won't really solve your issue b/c the value would be a string vs a Date in `onChange`, passing the date value directly doesn't seem appropriate in a blur either.

If you ask nicely perhaps @insin can help you out though, he has used the datepicker with redux-form in the past.

**Comment by slybridges** [comment]
Thanks for the quick reply @jquense !

For now, I'm just not passing the `onBlur` function from `redux-form` to the DateTimePicker component and that seems to work alright. But I'd be interested in how you did it @insin.

Also, I've noticed that DateTimePicker doesn't update the `value` attribute in the DOM, which I think is the reason why it is not picked up by `onBlur` ?

**Comment by insin** [comment]
I did the same thing, just avoided passing `onBlur` on.

**Comment by slybridges** [comment]
Thanks @insin.
I'm closing this since, not passing `onBlur` from `redux-form` seems to do the trick here.

**Comment by mvandiest** [comment]
It would be nice if the onBlur event emitted the same event signature as onChange as this would bring it more in line with a true input. What I ended up doing with redux and [redux-form](http://erikras.github.io/redux-form) was the following:

``` node
_handleInputBlur(e) {
    this.setState({isFocused: false});

    // note: field is a redux-form field
    let { field: { onBlur } } = this.props
    onBlur(this.refs.picker.props.value)

    if (this.props.onBlur) this.props.onBlur(e);
}

...

// note: field is a redux-form field
let { field } = this.props
let inputElement = <DateTimePicker
      ref='picker'
      {...field}
      onBlur={this._handleInputBlur}
 />
```

It would be nice to have parity for onBlur and onChange as exists in the standard <input />

**Comment by jquense** [comment]
the next version will persist the event so it's not useless and will probably solve the immediate issue for you. 

 in terms of changing the onBlur signature that most likely won't happen. I don't think "parity" with onChange makes sense in this context. onChange broadcasts a change in value and so passes the value as the argument. onBlur is broadcasting lose of focus, it doesn't really have anything to do with the value, since the value never changes on blur. I am more of the opinion that the redux-form API is at fault here if it requires the value to be passed to onBlur in order to do validation. it already has the current value it should just validate that.

**Comment by slybridges** [comment]
Hi @mvandiest,

If you want `onBlur` to be passed the value, you may also just use:
```javascript
let { field: { value, onBlur, ...props } } = this.props
let inputElement = <DateTimePicker
      {...props}
      value={value}
      onBlur={() => onBlur(value)}
 />
```

**Comment by rszczypka** [comment]
Hi @slybridges,
I'm also trying to integrate react widgets Combobox and DateTimePicker with redux-form but I can't get it to work together. I tried with your suggestion but I'm not sure if I'm doing it right? At the moment the `getValue` function from redux-form is not called at all when changing or blurring the Combobox.

What I have atm:
```javascript
import React from 'react';
import { reduxForm } from 'redux-form';
import messages from 'utils/messages';
import 'react-widgets/lib/less/react-widgets.less';
import Combobox from 'react-widgets/lib/Combobox';

const fields = [
  'nameInput',
  'typeInput'
];

class AddEvent extends React.Component {

  render() {
    const {
      fields: {
        nameInput,
        typeValue,
        onBlur,
        ...typeInput
        },
      valid,
      handleSubmit,
      asyncErrors,
      submitting
      } = this.props;

    const eventTypesList = ['Birthday party', 'Conference talk', 'Wedding'];

    return (
      <form onSubmit={ handleSubmit }>        
        <div
          className='form-group'>
          <label htmlFor="name">{messages.EVENTNAME}*</label>
          <input { ...nameInput }
            className="name form-control"
            required
            autoFocus
            type = "text"
            disabled = { submitting }
            placeholder = { messages.EVENTNAME }
            name = "name"
          />
        </div>
        <div className="form-group">
          <label htmlFor="type">{ messages.EVENTTYPE }*</label>
          <Combobox { ...typeInput }
            value={ typeValue }
            onBlur={ () => onBlur(typeValue) }
            data = { eventTypesList }
            required
            disabled = { submitting }
            placeholder = { messages.EVENTTYPE }
            suggest
          />
        </div>

        <button
          className="btn btn-primary" type="submit"
          disabled={ !valid || submitting }
        >{ submitting ? messages.SUBMITTING : messages.ADD_EVENT_TITLE }</button>
      </form>
    );
  }
}

AddEvent.propTypes = {
  fields: React.PropTypes.object.isRequired,
  asyncErrors: React.PropTypes.array.isRequired,
  handleSubmit: React.PropTypes.func.isRequired,
  submitting: React.PropTypes.bool.isRequired,
  valid: React.PropTypes.bool.isRequired
};

export default reduxForm({
  form: 'addevent',
  fields,
  validate: addEventValidation
})(AddEvent);


```

**Comment by slybridges** [comment]
Hi @rszczypka,
I think you have a problem in your props fields spread in your `render()`.
It should be something like
```javascript
    const {
      fields: {
        nameInput,
        typeInput,
        // onBLur is tied up to a field and '...typeInput' doesn't make sense here
        },
      valid,
      handleSubmit,
      asyncErrors,
      submitting
      } = this.props;
```

Then for your combobox, you would do
```javascript
        <Combobox { ...typeInput }
            value={ typeInput.value }
            onBlur={ () => typeInput.onBlur(typeInput.value) }
            data = { eventTypesList }
            required
            disabled = { submitting }
            placeholder = { messages.EVENTTYPE }
            suggest
          />
```

I don't use `Combobox`and haven't tried this code but it should at least guide you to where you want to go.

**Comment by rszczypka** [comment]
Hi @slybridges,
Thank you for your help! This is exactly what I need.

**Comment by pryscilacardoso** [comment]
I want to make a datepicker validation when the user finishes filling and changing the field. Can someone help me? I use "onBlur" but it only triggers the event when the user opens the calendar, when it closes or changes the field, the event does not happen.

Thanks.

**Comment by xhinodread** [comment]
https://github.com/YouCanBookMe/react-datetime/issues/174#issuecomment-262728866

<datetime inputProps={{onBlur: ev => console.log('Do whatever', ev) }} />
