### ISSUE TITLE
Export propTypes and defaultProps along with components

### ISSUE THREAD

**Issue by smashercosmo** [jquense/react-widgets#256]
In our app we create higher order components for react-widgets components and we want to use the same propTypes and defaultProps (extended with new ones) for them. So if they were exported, we could just import them without any copypasting.

**Comment by jquense** [comment]
Hey there, 

why don't you just use propTypes and defaultProps of exported components? seems like exporting them separately again is unnecessary?

**Comment by smashercosmo** [comment]
@jquense oh, yes, I don't know, why this solution didn't come to my head :) Thx. Closing.
