### ISSUE TITLE
Calendar: Animation always slides from right to left when updating value prop.

### ISSUE THREAD

**Issue by tjanne** [jquense/react-widgets#260]
Expected behaviour:

Slide left to right when updated value is less than the current date.
Slide right to left when updated value is greater than the current date.

**Comment by jquense** [comment]
hi there,

Sorry I am not sure what you are seeing but it does slide left to right when navigating into the past and right  to left when going into the future

**Comment by tz-johannes** [comment]
Sorry, I should have been more specific!

The animation works correctly for the arrow buttons and key shortcuts, but not when updating the value directly (for example by passing a new prop). You can reproduce the bug by clicking a date belonging to the previous month in the widget. (Example: go to December & then select the 29th or 30th of November by clicking on the date)

**Comment by tz-johannes** [comment]
It looks like updating state.slideDirection in componentWillReceiveProps should fix it.
