### ISSUE TITLE
[Feature request] Calendar: Display a date without setting value

### ISSUE THREAD

**Issue by tz-johannes** [jquense/react-widgets#261]
To display a specific date in the calendar widget I have to select it (by setting the "value" prop). I want to set & update the displayed dates without having to select a date. Ideally, I would like to be able to set a value, but display another.

My current use case:

I have two linked calendars that should display two consecutive months. Navigating in one updates the other, using onNavigate to update the values. I would like to do this without having to actually select a date in each calendar.

![image](https://cloud.githubusercontent.com/assets/3470434/11475369/6a96e98c-977d-11e5-8af7-cc25faa15eb8.png)

**Comment by jquense** [comment]
This actually should be a relatively easy change to make, good idea.

**Comment by jquense** [comment]
This is ahrder then I initially suspected, but still on my list of good enhancements
