### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by garretto** [jquense/react-widgets#263]
I forked my own version of this to support the calendar widget in IE8. Using Babel + Webpack + React with polyfills. 

Using a getter in localizers.js causes problems. I just removed this code:
```javascript
['formats', 'parse', 'format', 'firstOfWeek', 'precision'].forEach(function (name) {
   return Object.defineProperty(dummy, name, {
     enumerable: true,
     get: function get() {
       throw new Error('[React Widgets] You are attempting to use a widget that requires localization ' + '(Calendar, DateTimePicker, NumberPicker). ' + 'However there is no localizer set. Please configure a localizer. \n\n' + 'see http://jquense.github.io/react-widgets/docs/#/i18n for more info.');
     }
   });
});
```

And in Popup.js, changed line 153 too:
```javascript
var height = (_domHelpersQueryHeight2['default'](content) || 0) + (isNaN(margin) ? 0 : margin);
```

These two fixes make it work fine.

**Comment by jquense** [comment]
Thanks for the heads, up

I have fixed the Popup issue, and surrounded the `defineProperty` call in a guard so it only runs in DEV mode (which is already not supported in ie8)
