### ISSUE TITLE
DateTimePicker: How to clear date from calendar popup?

### ISSUE THREAD

**Issue by saikatguha** [jquense/react-widgets#266]
Is there a way to unset the date from the calendar popup?

I am currently using a hack where I set the footerFormat to "[Clear]", and in my onChange method look for a value within a few seconds from the current datetime (since the footer value is hard-coded to new Date() when the component is rendered). This is quite fragile since if the user selects the footer after keeping the calendar open for longer than my buffer.

Maybe there can be a way to either: 
1) pass a custom footer value (e.g., = null), or 
2) get some indication that the user clicked the footer in the onChange, or

**Comment by jquense** [comment]
There is now way to unset the date from the calendar popup but clearing the date in the datepicker is easy enough and accomplishes the same thing, you can also create a wrapper and some css to overlay a X button if you are so inclined

thanks!
