### ISSUE TITLE
fs.readydirSync is not a function

### ISSUE THREAD

**Issue by ibrown-gaikai** [jquense/react-widgets#268]
Using browserify, gulp, babelify I am not able to include CLDR and load into globalize.

const Globalize = require('globalize');
const GlobalizeLocalizer = require('react-widgets/lib/localizers/globalize');
const CLDR = require('cldr-data');

    Globalize.load(CLDR.entireSupplemental());
        Globalize.load(CLDR.entireMainFor("en"));
        Globalize.locale('en-US');
        
        GlobalizeLocalizer(Globalize);

The entireSupplemental() method above eventually uses fs which is an empty object. Is there something I can do to fix this? I tried brfs, but haven't had any luck

The specific error is _fs.readdirSync is not a function. This is thrown in the jsonFiles method within the CLDR entireSupplemental method.

Thank you.

**Comment by jquense** [comment]
this is more of a globalize.js issue, you should try their issue tracker, and documentation but it doesn't look like you are setting it up correctly.

**Comment by ibrown-gaikai** [comment]
How would one set this up? Could you post an example?

**Comment by jquense** [comment]
the globalize doc page has a few examples that I've used in the past just check there :)
