### ISSUE TITLE
Entering negative value to NumberPicker

### ISSUE THREAD

**Issue by adros** [jquense/react-widgets#273]
How do you enter negative number in NumberPicker? 

Trying to type '-1' in your sample (http://jquense.github.io/react-widgets/docs/#/numberpicker), but the '-' does not even appear.

I have to type '1' first, then go back (e.g. with left arrow) and type '-'. 
(pasting from clipboard works ok, up/down buttons works ok)

**Comment by jquense** [comment]
Good catch, fixed locally will be out as soon as I address your other issue

**Comment by adros** [comment]
I have checked version 3.1.4 and the problem still occures.

**Comment by jquense** [comment]
Oops must not of merged those changes, sorry about that
