### ISSUE TITLE
Decimal separator problems in NumberPicker 

### ISSUE THREAD

**Issue by adros** [jquense/react-widgets#274]
I am trying to use NumberPicker with globalize and 'sk' locale, which have ',' as decimal separator. And it seems to be impossible to type number with more than one decimal places.

Everything is alright after typing '1,' but when I go on and type next number, the comma changes to dot (e.g. after typing '2' -> '1.2'), and I cannot type anything else.

**Comment by jquense** [comment]
thanks for the heads, up, this is due to some shortcuts I took dealing with localizers values...I'll have it fixed soon :)

**Comment by jquense** [comment]
late to close, this has been fixed in oe of the recent releases
