### ISSUE TITLE
combobox w/ multiple || selectlist or dropdownlist w/ filter

### ISSUE THREAD

**Issue by rkhayat** [jquense/react-widgets#275]
Hello,

I love your suite of widgets, they are coming in handy! I have come across a use case where I need to load 3000 records in a multiselect w/ filter etc. I reached for the multiselect you provide but it's more of a 'tag' system (which I like, but not what we need). The combo box (having a 'contain' filter) was my next go-to, but it doesn't have a multiple option. The selectlist has the multiple option but no filter.

Would you recommend I extend the selectlist (or dropdownlist ) to include a filter or the combobox to have multiple?

I was thinking of extending the selectlist, having a component that passes it a string (from an input) and it would filter it's state down. I see one possible issue, the selectlist takes an array of values, and as you filter and select an item, clearing the filter should keep the checked items. (This comes naturally with your combobox)

What do you recommend? thanks!

**Comment by rkhayat** [comment]
Update : I was able to throw together an input driven SelectList, I will share once I hashed out all the bugs.

**Comment by jquense** [comment]
I'd be glad to see what you've put together when its ready. I am a bit unsure what type of UX you are looking for here though, is there an example of something? I am guessing you'd like something like http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/ ?

**Comment by rkhayat** [comment]
UX I am looking for - https://github.com/skratchdot/react-bootstrap-multiselect
The component is a react wrapper for bootstrap-multiselect, it works great but has a problem with setting state.

**Comment by rkhayat** [comment]
I am very close to having all the functionality, I will post code when complete. Thanks! React Widgets is easy to work with!
