### ISSUE TITLE
Set daily min/max for time in DateTimePicker 

### ISSUE THREAD

**Issue by MarianArlt** [jquense/react-widgets#276]
Sorry if I'm missing a simple configuration here, cause I did search the tracker and the files for some hints on this but I'm still clueless.
Is there a way to define a recurring min/max time on the DateTimePicker? I set the usual `min` property to a `new Date(someYear, someMonth, someDay, someHour)` but the logic behind this only applies the hour set here to the very specified day. Which is, well, quite logic.

I would need something to specify a sort of opening hour, I think this is a major common use case. Say you can pick a date from today on until today plus one year, but only between 10am and 6pm daily. If this is already available maybe it would be worth mentioning in the documentation.
Sorry for the trouble.

**Comment by jquense** [comment]
there isn't a way of setting the min/max time separate from from date, but I can see why you'd want that. I'd be happy to take a PR that adds `timeMin` and `timeMax` that take precedents over the normal min and max props if your up for it. should be relatively straight forward I think.

**Comment by MarianArlt** [comment]
Could this be a feature request? I don't see where I'd start with this (apparently in TimeList.jsx but sadly I'm really not qualified enough for contributing T_T).

I was asking myself if it would not be just easier to use the time from the already existing min/max to define this (which I suspected from reading the docs) but I think for backend event planners or such implementations it is well justified to work the way it does.

Kudos and thumbs up for your great work!

**Comment by jquense** [comment]
sure :) I only suggest a PR b/c I am not sure when I'd get to it, but no problem if you don't feel up for it

**Comment by MarianArlt** [comment]
Take your time, every library/plug-in programmer more than deserves it. Maybe somebody else chimes in :+1:

**Comment by svenl77** [comment]
+1 for this feature! 

I'm also trying to use it for opening hours. Most of the time there is a break in opening hours. Shop opens from 8am to 12am and from 2pm to 9pm.

Is this possible some how?

**Comment by jquense** [comment]
its not currently, but like I mention above I am open to a PR adding this if it means a lot to you.

**Comment by svenl77** [comment]
thanks for your quick response ;)

**Comment by Panczo** [comment]
+1 from me, this feature would help me a lot :)`

**Comment by MitchWeiss** [comment]
I would love to see this as well. I use separate fields for selecting date and time and in this case it's possible to set min and max times which stay constant no matter which date is chosen. 

```
<DateTimePicker
  calendar={false}
  step={60}
  placeholder="Select a time"
  min={moment().hour(7).minute(0).toDate()}
  max={new Date(2126,5,5,16,1)}
```

In this case the available hours are 7am to 4pm

**Comment by Doff3n** [comment]
+1. I expected this to be the case

**Comment by LuisRodriguezLD** [comment]
Hello. 

Has this been implemented? I can't find it
