### ISSUE TITLE
When "caseSensitive" is false, adding a term should not be suggested

### ISSUE THREAD

**Issue by vzaidman** [jquense/react-widgets#279]
![www](https://cloud.githubusercontent.com/assets/5188459/12143528/f9c7f9ec-b489-11e5-852e-24585fa20809.png)

**Comment by jquense** [comment]
Sorry there, what exactly is your problem or feature request? the above seems to be the current behavior, which seems right

**Comment by vzaidman** [comment]
That is correct in case there is difference between "aaa" and "AAA", but there is none in my case, hence the "caseSensitive" property is set to false.

**Comment by vzaidman** [comment]
maybe another property should be added: "createTermFilter" with the default of the "filter" property or "startsWith".

**Comment by jquense** [comment]
ok got it! will fix soon I hope
