### ISSUE TITLE
Add the "onCreate" feature to "DropdownList" as implemented in "Multiselect"

### ISSUE THREAD

**Issue by vzaidman** [jquense/react-widgets#280]
the code im using without this feature:

```javascript
const data = [...this.props.data],
  addTermOption = {[valueField]: currentSearchTerm, [textField]: currentSearchTerm + ' (Add Term)'};

if(onCreate && currentSearchTerm && !_.some(data, {[textField]: currentSearchTerm})){
  data.unshift(addTermOption);
}
...
<DropdownList {...this.props}
          data={data}
          onChange={(newValue)=>{
            if(addTermOption === newValue){
              this.props.onCreate(currentSearchTerm);
            }
            else{
              this.props.onChange(newValue)
            }
          }} />
```

**Comment by jquense** [comment]
Hi there,

I think this is the sort of thing that makes sense to be implemented outside of the core widgets here, as you are doing. Since such a feature is a bit harder to make work in a more general way for a dropdown list

**Comment by vzaidman** [comment]
now i struggle with the filter filtering the option i add.
It works now but it is very very ugly and adds lots of code to the component using this controller.

**Comment by jquense** [comment]
@vzaidman  instead of recreating the logic each time just create your own Dropdown and use that

```js
class MyDropDown extends React.component {
  render() {
    //do logic here
    return <DropdownList {...updatedProps} />
  }
}
```

**Comment by vzaidman** [comment]
I still hope you change your mind about this one. thanks. :)
