### ISSUE TITLE
Bug: select list disables all items when only some are disabled

### ISSUE THREAD

**Issue by rogierschouten** [jquense/react-widgets#281]
- Go to the docs for SelectList
- Select 'Is Multiple"
- Under "Disable Values", select "Orange"

unexpected result: all checkboxes are disabled

**Comment by jquense** [comment]
not seeing that at all...following the above on the docs page results in only orange doing disabled.

any other details?

**Comment by rogierschouten** [comment]
Darn... I reloaded the page and now I cannot reproduce it either. Let's close this until I have a reliable reproduction.  Thanks for the quick response though.
