### ISSUE TITLE
globalizeLocalizer - Invalid `locale` parameter

### ISSUE THREAD

**Issue by willdady** [jquense/react-widgets#282]
I'm getting the following error when calling globalizeLocalizer. 

`Uncaught locale: E_INVALID_PAR_TYPE: Invalid `locale` parameter (undefined). a string expected.`

The following works fine running webpack dev server however fails when running a built version. If I comment out `globalizeLocalizer(Globalize);` the app starts up as expected.

```
var Globalize = require('globalize');
require("globalize/dist/globalize-runtime/number");
require("globalize/dist/globalize-runtime/date");
var globalizeLocalizer = require('react-widgets/lib/localizers/globalize');
Globalize.locale('en');
globalizeLocalizer(Globalize);
```

Not sure what's going on here. Any help would be appreciated.

**Comment by jquense** [comment]
can you provide a better stack trace, that error is inside globalize itself so I'm not sure what is triggering it from my code. thanks!

**Comment by willdady** [comment]
No sure if that helps. I disabled webpack's 

```

**Comment by willdady** [comment]
Not sure if that helps :\

```
var Globalize = require('globalize');
require("globalize/dist/globalize-runtime/number");
require("globalize/dist/globalize-runtime/date");
var globalizeLocalizer = require('react-widgets/lib/localizers/globalize');
Globalize.locale('en');
try {
  globalizeLocalizer(Globalize);
} catch (e) {
  console.log(e.stack);
}
```

```
locale: E_INVALID_PAR_TYPE: Invalid `locale` parameter (undefined). a string expected.
    at createError (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:261:11)
    at validate (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:296:10)
    at validateParameterType (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:312:3)
    at validateParameterTypeString (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:328:3)
    at new Globalize (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:367:3)
    at Globalize (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:363:11)
    at Object.<anonymous> (http://localhost:8000/main.0929a8c47a7214fdf401.js:17:4)
    at __webpack_require__ (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:72:30)
    at webpackJsonpCallback (http://localhost:8000/vendor.0929a8c47a7214fdf401.js:43:20)
    at http://localhost:8000/main.0929a8c47a7214fdf401.js:1:1
```

**Comment by jquense** [comment]
Ooof it's not great... any chance of turning on source maps and maybe stepping through? I'm still having a hard time guessing where it might be throwing I nmy code :/

**Comment by willdady** [comment]
Did some more investigating and this bit of weirdness is happening which is causing the error.

```
var Globalize = require('globalize');
var globalizeLocalizer = require('react-widgets/lib/localizers/globalize');
console.log(globalizeLocalizer === Globalize); // true
Globalize.locale('en');
globalizeLocalizer(Globalize);
```

For some reason `require('react-widgets/lib/localizers/globalize');` is importing Globalize and not `globalizeLocalizers`.

**Comment by jquense** [comment]
how are you setting up globalize? my hunch is that there is insufficiently specific regex being used by webpack, either in your config or in some plugin your using.  I. e. it's just matching  on the word globalize

**Comment by joerm** [comment]
How did you end up solving this?

**Comment by willdady** [comment]
@joerm I ended up having to change:

`var globalizeLocalizer = require('react-widgets/lib/localizers/globalize');`

to

`var globalizeLocalizer = require('react-widgets/lib/localizers/globalize.js');`

Something strange going on with Webpack. Didn't really look much further into it. To be honest I've had nothing but trouble getting globalize working. For the time being I've switched to using the Moment localizer due to #296

**Comment by jquense** [comment]
Mostly likely somewhere in the webpack config is some loader configured like: `{ test: /globalize/`, which is over matching not just hte globalize package, but also the localizer require: `'react-widgets/lib/localizers/globalize'`. IF there isn't a specific thing thats configured that way its probably a bug in the Globalize webpack plugin or config setup.

Overall, I hope to provide a better onboarding docs for the newer version of Globalize since its really terrible to configure and my attempts to try and address that upstream have been fairly fruitless.

**Comment by joerm** [comment]
@willdady and @jquense Thanks.  I found a few quirks with the globalize plugin in compile (i.e. production) mode that were difficult to troubleshoot.  In the case of the react-widgets, I wasn't able to unblock myself and routed around.  I hope to try again in a few months!

**Comment by harel** [comment]
I had the same problem where I'd get this error when production is true in Globalize webpack plugin. Following the notes here, I removed (my unused) react-widgets and that resolved it (to make room for other problems though). It seems like when react-widgets is installed, it does indeed create another conflicting globalize instance (i could hit 2 in the console).
