### ISSUE TITLE
Moment error:  Invalid determine the date

### ISSUE THREAD

**Issue by Xurma2** [jquense/react-widgets#285]
```
this.setState({
    startDate: Moment().subtract(29, 'days'),
    endDate:   Moment()
});
<DateTimePicker
			defaultValue={this.state.endDate.toDate()}
			format={"MM DD YYYY"}
			time={false}
onChange={this.handleChangeEnd}

	handleChangeEnd(endDate, str) {
		this.setState({
			endDate: Moment(endDate)
		});
	},
								/>
```
Then i pass in input DEC212006 and in state i see follow

![image](https://cloud.githubusercontent.com/assets/5157416/12213129/2476fbba-b684-11e5-9fe4-5e23dc8b990a.png)

**Comment by jquense** [comment]
You can't pass a moment object the Datepicker, I believe that the error is fairly clear the defaultValue prop must be a `Date` object

**Comment by Xurma2** [comment]
@jquense i update questions

**Comment by jquense** [comment]
It still looks like you are passing a moment as the value.

**Comment by Xurma2** [comment]
@jquense 
The question is not that. And that's why when I give a date - DEC212006
On the way out, I get completely different

**Comment by jquense** [comment]
Can you provide some code that demonstrates your issue then?

Specifically how you are passing values, what values you are passing and what culture you are using.

Can you reproduce the issue on the docs site?

thanks!
