### ISSUE TITLE
Multiselect: Setting disabled value disabled all unselected values

### ISSUE THREAD

**Issue by tarnelope** [jquense/react-widgets#286]
Steps to Reproduce:
1. Go to Multiselect docs
2. Select a few names in the main Multiselect field
3. Select 1 name in the **Disable Multiselect Values** field

Unexpected behavior: All unselected options are now disabled so user can no longer add new values to the main Multiselect field. Let me know if more information is needed. Thank you.

**Comment by jquense** [comment]
thanks for the heads up

**Comment by tarnelope** [comment]
Thanks for the fast response! Is there a delay before the fix is accessible? The disabling of all unselected values is still occurring in the docs and my app. Additionally, once a `disabled` value has been set, all unselected options remain disabled even if I empty the `disabled` array.

Expected: Only Rosetta Morales is disabled
Observed: All unselected values are disables
![react-widgets](https://cloud.githubusercontent.com/assets/3513997/12298629/5805ebae-b9d0-11e5-9aea-03ae765c38f9.gif)

I suspect that the `rw-state-disabled` class is being applied to all options as long as `disabled:       CustomPropTypes.disabled.acceptsArray` is not false. I'm not very familiar with the source code so I could be completely wrong on this. Let me know if you have any questions for me or if I can help in some way. Thanks again.

**Comment by jquense** [comment]
I just haven't actually pushed the new version to npm or the docs site yet, should be soon

**Comment by tarnelope** [comment]
Oh my apologies! Thank's so much. I really appreciate it.
