### ISSUE TITLE
Calendar: Selected date displayed.

### ISSUE THREAD

**Issue by cyrusbowman** [jquense/react-widgets#289]
When you select a date at the beginning or end of a month (30th of dec), the same day will appear in the neighboring month with a border around it (30th of jan).

#### Example:
![calendarbug](https://cloud.githubusercontent.com/assets/2474343/12315919/9969ece8-ba4e-11e5-9bc6-d1dc8079145a.gif)

Thanks for all the hard work!

**Comment by jquense** [comment]
hi there, 

that is the focus outline, it's on every month and regardless of where in the month you select something. it's there so keyboard users know where the keyboard "cursor" is for selecting a date. you can use the arrow keys to see it move around
