### ISSUE TITLE
Required prop `parse` was not specified in `NumberPickerInput`

### ISSUE THREAD

**Issue by willdady** [jquense/react-widgets#293]
Not sure why I'm getting this error while attempting to use NumberPicker. Not sure if this is related to globalize (as it's been the cause of problems for me lately), localization is setup as follows.

```
var Globalize = require('globalize');
var globalizeLocalizer = require('react-widgets/lib/localizers/globalize.js');
Globalize.locale('en');
globalizeLocalizer(Globalize);
```

Skimming over the source code for NumberPicker it looks like it does in-fact pass `this.props.parse` to NumberInput which would explain the error. Does that mean providing a **parse** prop to NumberPicker is required? The documentation doesn't say it's a required field. I'm a bit stuck here.

**Comment by willdady** [comment]
UPDATE: I tried reverting back to 3.1.3 and I no longer get the error. Switched back to 3.1.6 and can confirm I get the error again. So something broke between then and now. 

This makes sense as I was sure this was working in the past but did a fresh `npm install` last night.

**Comment by jquense** [comment]
Yeah the problem is just the incorrect propType warning, I just forgot to remove the required flag after making a change there. nothing should actually be wrong or broken
