### ISSUE TITLE
Font paths not working with webpack

### ISSUE THREAD

**Issue by niijv** [jquense/react-widgets#295]
Really like your widgets!

I tried using them in webpack project and for the style I just have
```css
@import "~react-widgets/lib/less/react-widgets";
```
in my `main.less` file.
The webpack config is setup as recommended in your docs, but webpack throws this error:
```
ERROR in ./less/main.less
Module build failed: Error: Cannot find module "../fonts/rw-widgets.eot?v=4.1.0"
...
ERROR in ../~/css-loader!../~/less-loader!./less/main.less
    Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/rw-widgets.eot in C:\somepath\static\less
```

The curious thing is that it is looking relative from where I am starting webpack and not relative from your `variables.less`.

Could my setup be wrong?

**Comment by jquense** [comment]
sorry for the delay... I believe that webpack looks for for stuff (even the module files) relative to the publicPath of your webpack config. Generally we just copy the font files over , but I would really like a way for this to Just Work, hmmm.

**Comment by niijv** [comment]
Thanks for the reply!
Ok, that was what I did so far (copying everything into my own project), was just not sure if that is the go-to solution right now.

**Comment by vladra** [comment]
@niijv @jquense 
also encountered same issue, and was going to copy scss files to my project. But actually it is very easy to solve. In `variables.scss` you have 2 variables that are defining path to image and font folder.

To make it work you can do something like this (in case you are using webpack):

```
$rw-font-path: '~react-widgets/lib/fonts';
$rw-img-path: '~react-widgets/lib/img';

@import '~react-widgets/lib/scss/react-widgets';
```

Now it will use correct path to fonts and img folders.

**Comment by jquense** [comment]
> Maybe it is good to add this to readme, cause it's confusing otherwise

Agree! PR?

**Comment by vladra** [comment]
Sure. Take a look #433

**Comment by niijv** [comment]
Good to know, thanks!

**Comment by VapiSoft** [comment]
I have the same problem:
But I can;t find the module: variables.scss
Where is it?
The error:
ERROR in ./node_modules/react-widgets/dist/fonts/rw-widgets.svg?v=4.1.0
Module build failed (from ../node_modules/file-loader/index.js):
TypeError: Cannot read property 'fileLoader' of undefined

**Comment by VapiSoft** [comment]
OK, I found the variables.scss in the scss folder(as expected),
But.
I still received the error, but because the error changes to a different file every time I tries, I thought that I need to add lines for all the extentions.
Also, what does this means: $rw-font-path ?
Eventually, I don't know how to solve this.
