### ISSUE TITLE
exception using NumberPicker

### ISSUE THREAD

**Issue by pdeva** [jquense/react-widgets#299]
Using react-widgets 3.1.6 with typescript.

```
import NumberPicker from 'react-widgets/lib/NumberPicker';

//in code

<div>
  <NumberPicker defaultValue={null}/>
<div>
```

I get this exception in the console:
![2016-01-19_1614](https://cloud.githubusercontent.com/assets/3190176/12436212/0d923f30-bec8-11e5-807f-b989d012bafe.png)

**Comment by vomchik** [comment]
You need set a localization.
More details here https://jquense.github.io/react-widgets/docs/#/i18n
