### ISSUE TITLE
DateTimePicker server-side rendering

### ISSUE THREAD

**Issue by devnomad** [jquense/react-widgets#304]
@jquense I just noticed a warning in my browser console:

*Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:*
```
 (client) .1.0.2"><div style="-webkit-transform:tr
 (server) .1.0.2"><div style="transform:translateY
```

The server-side rendered html is:

```html
<div
  style="transform:translateY(-100%);position:absolute;"
  class="rw-popup rw-widget" data-reactid=".4yz1f7cw00.1.0.0.0.0.0.0.1.0.2.0">
</div>
```

And the DateTimePicker code is just ```<DateTimePicker />```.

I'm not sure, but it may be related to commit https://github.com/jquense/react-widgets/commit/406c795 around ```src/Popup.jsx:L125```.

I have no idea how to reproduce since I'm using DateTimePicker on another page (with the same markup) without the issue... Also I double-checked that v3.1.5 isn't affected by this, but v3.1.6 and v3.1.7 are.

**Comment by jquense** [comment]
thanks for the heads up. Let me see if I can figure something out there

**Comment by frankleng** [comment]
@jquense running into the same issue. any ideas so far?

**Comment by smashercosmo** [comment]
Also relevant for Multiselect

**Comment by devnomad** [comment]
@jquense many thanks!
