### ISSUE TITLE
Maybe envify should be a dependency? 

### ISSUE THREAD

**Issue by jonasfj** [jquense/react-widgets#308]
I'm using this in a browserify project:
https://github.com/taskcluster/taskcluster-tools

Currently upgrading and finding that:
```js
  "browserify": {
    "transform": [
      "envify"
    ]
  }
```
causes me browserify to want to run `envify` when I include this in my project. Is that intended?

**Comment by jquense** [comment]
yes per: https://github.com/jquense/react-widgets/pull/271. Though it does look like it should be including envify as a real dependency and not a devDep, which is (I am assuming) why its erroring out on you.

**Comment by jonasfj** [comment]
Yeah, making `envify` a dependency in my project solved it...

But since you have `"main": "lib/index.js",` which is already compiled with babel/browserify.
Okay, I'm no browserify expert..


Making `envify` a dependency would certainly work fine :)
