### ISSUE TITLE
onBlur/onFocus missing from docs

### ISSUE THREAD

**Issue by vdh** [jquense/react-widgets#310]
I feel like [this previous issue](https://github.com/jquense/react-widgets/issues/254) with `onBlur` should be mentioned somewhere in the docs, because I had a hell of a time tracking this down when the `DropdownList` component started causing mysterious errors inside the bowels of `redux-form` :cry:

The component docs are missing documentation for `onFocus` or `onBlur`, so I had to inspect the source code just to find out that it was reacting to those handlers.

Perhaps `event.persist()` should be used to maintain event data? As mentioned in [this react bug about missing event data](https://github.com/facebook/react/issues/2850).

**Comment by jquense** [comment]
we try not to clutter the documentation with redocumenting Dom events, and try not to prevent/prohibit responding to plain ol DOM events. the assumption can be if it's a normal event it should work. 

the event.persist thing is a separate and good idea,  however I need to first confirm that approach won't have performance or memory leak issues

**Comment by vdh** [comment]
I don't quite understand, the documentation details how the widgets handle `onChange`, wouldn't it be beneficial to add a brief section mentioning that the widgets also handle `onBlur`/`onFocus`? I know it's meant to be completely transparent, but if we're encountering errors like this one it deserves at least a mention, right?

**Comment by jquense** [comment]
that error is fixed in the next version, thnks!
