### ISSUE TITLE
Does the DatePicker support range selection?

### ISSUE THREAD

**Issue by wzup** [jquense/react-widgets#312]
It is unclear if the DatePicker supports range selection. No dedicated props, no relevant examples, no "range" word in whole documentation. Does it support date range?

**Comment by jquense** [comment]
they lack of documentation is is indicative of it not supporting range selection. if you want to select two dates you can use two pickers together and enforce the rules about which can we greater or less than the other.

**Comment by richard-flosi** [comment]
I think it would make sense to add a `range` prop to the DateTimePicker which would give you an additional set of Date/Time buttons on the left side of the input box for selecting the start date and the existing buttons the right side could be used for selecting the end date.

I'm sure sure what makes sense in right-to-left languages or what kind of support you'd want for that.

Displaying the currently selected range could be `2016-01-01 - 2016-02-01` where the dates are separated by a dash or maybe some configurable `rangeSeparator` prop.

This maybe we something I'll be creating for a project I'm working on. Is there any interested in including this functionality in the DateTimePicker component?
