### ISSUE TITLE
Multiselect docs (pages - .md) don't mention `allowCustom`

### ISSUE THREAD

**Issue by nafg** [jquense/react-widgets#313]
http://jquense.github.io/react-widgets/docs/#/multiselect lets you toggle it but the list of props doesn't include it.

**Comment by jquense** [comment]
hi there, it's not mentioned because there isn't an `allowCustom` prop. the functionality is Ena led by providing an onCreate handler which is documented

**Comment by nafg** [comment]
Okay thanks. That occurred to me but it didn't sound like it from the documentation for onCreate -- it could be made more explicit that the default is to do nothing. Also I would think it should be called onBeforeCreate or something else that doesn't sound like it's an event that describes something that occurred regardless. Also perhaps the "allow custom" checkbox could be labeled "custom onCreate" or something? Am I the only one that assumed the demos let you play directly with the props?

Anyway thanks for a great library!
