### ISSUE TITLE
Cannot find module 'envify' from '...\node_modules\react-widgets'

### ISSUE THREAD

**Issue by wzup** [jquense/react-widgets#314]
Trying to build vendors bundle with browserify I've received this error:
```
Cannot find module 'envify' from '...\node_modules\react-widgets'
```

Why? How to solve?

Here is my gulp task to build vendor bundle:

```
   var vendors = ['jquery',
        'react',
        'react/addons',
        'react-dom',
        'moment',
        'react-intl',
        'react-widgets/lib/DropdownList'
];
    var b = browserify({
        debug: true,
        noParse: vendors,
        transform: ['babelify'],
        require: vendors
    });
    b.bundle()
        .on('error', function(err) {
            console.error(err.message);
            this.emit('end');
        })
        .pipe(source('vendors.js'))
        .pipe(gulp.dest('./public/js'));
```

UPD:

Here is your `package.json`:
1)
![widgets_package json - sublime text unregistered 2016-02-07 20 20 19](https://cloud.githubusercontent.com/assets/3880497/12872241/74edec6e-cdd8-11e5-9db1-46e8815f7b5c.png)

2)
![widgets_package json - sublime text unregistered 2016-02-07 20 21 05](https://cloud.githubusercontent.com/assets/3880497/12872243/855e8572-cdd8-11e5-89c8-a65f30ad2ae7.png)

Being specified as `devDependencies` it is not either installed or smth. So the solution might be somewhere here, I think.
More readings for you https://github.com/rackt/react-router/issues/105

**Comment by jquense** [comment]
dup #308
