### ISSUE TITLE
setState on unmounted component in Popup.js (3.1.7)

### ISSUE THREAD

**Issue by ferrannp** [jquense/react-widgets#319]
Hi!

So with the DateTimePicker open, if I for example click in a link that changes the route (so it unmounts the component that was holding the DateTimePicker), Popup.js will try to setState an throw:

```javascript
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Popup component.
```

Lines that are failing are:

(anonymous function)	@	Popup.js:192
nextCallback	@	Popup.js:253

Which are this inside the close function (192):
```javascript
_this2.animate(el, offset, duration, 'ease', function () {
  return _this2.setState({ status: CLOSED }, function () {
  _this2.props.onClose();
});
```

And from setNextCallback function (253):
```javascript
if (active) {
  active = false;
  _this3.nextCallback = null;
  callback(event);
}
```

I think something like this will resolve the problem:
```javascript
_this2.animate(el, offset, duration, 'ease', function () {
if (_this2.isMounted()){
  return _this2.setState({status: CLOSED}, function () {
     _this2.props.onClose();
  });
}
```

Although React claims this to be an anti-pattern: https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

So it might be possible to have a better solution that my suggestion.

On the other hand, I saw that https://github.com/jquense/react-widgets/blob/master/lib/Popup.js is different in the repo than in the one that is downloaded with npm (3.1.7). So... maybe this is already solved but not released?

**Comment by jquense** [comment]
this should be fixed in the next release, thanks!
