### ISSUE TITLE
Canonical method to reset a widget exposed as a functional component?

### ISSUE THREAD

**Issue by sawan** [jquense/react-widgets#324]
Hi,

Is there a standard way to clear/reset a widget when it is defined like this?

```javascript
const DatesComponent = ({isEnabled, minDate, maxDate, onChange}) => (
    <div>        
        <DateTimePicker id="birth-date"
                        name="birth-date"
                        format="D/MM/YYYY HH:mm"
                        editFormat="D/MM/YYYY HH:mm"
                        min={minDate}
                        max={maxDate}
                        onChange={onChange}
                        disabled={!isEnabled}
        />       
    </div>
)
```

This is hooked up to a Redux store. When the ```isEnabled``` flag is toggled in the store, I would like the widget to reset to its default state and clear any values.

**Comment by jquense** [comment]
you should also control the value, along with passing an onChange. when you want to reset the value set it to null.

**Comment by sawan** [comment]
Doesn't work, I can confirm that the controlled value in the code below, ```chosenDate```, is being set to ```null``` but the widget does not reset. It does become disabled due to the ```isEnabled``` flag being toggled, but the previously chosen value is still displayed in the the widget.

```javascript
const DatesComponent = ({isEnabled, minDate, maxDate, chosenDate, onChange}) => (
    <div>        
        <DateTimePicker id="birth-date"
                        name="birth-date"
                        format="D/MM/YYYY HH:mm"
                        editFormat="D/MM/YYYY HH:mm"
                        min={minDate}
                        max={maxDate}
                        onChange={onChange}
                        disabled={!isEnabled}
                        value={chosenDate}

        />       
    </div>
)
```

**Comment by jquense** [comment]
Hi there,

I've tested the above and am not getting the same behavior as you, setting the value explictily to `null` definately does empty the widget, and unsets any selected value, in every test I've tried. if you can put together a repo in a  fiddle or the docs site i'll happily reopen!

**Comment by sawan** [comment]
Hello,

Works as you said, I think I had it confused with another controlled value.

Thank you for looking into it.
