### ISSUE TITLE
<label for=...> What is the proper way to add a label to widget?

### ISSUE THREAD

**Issue by mattez** [jquense/react-widgets#326]
Hi, what is the proper way to add a label to widget?
Thank you.

**Comment by nmaves** [comment]
You should use the htmlFor instead of the for attribute.

**Comment by mattez** [comment]
Thanx for a reply.
And how you find out what is the value of _htmlFor_ when widget's _id_ is generated by _React Widgets_?

**Comment by nmaves** [comment]
You don't have to worry about that.  How about you try it first :)

`
<label htmlFor="firstName">First Name</label>
<input id="firstName"/>
`
