### ISSUE TITLE
[DropdownList] missing bottom border

### ISSUE THREAD

**Issue by nmaves** [jquense/react-widgets#330]
Strange but it seems to only happen on the first filtered dropdown on the page. I can reproduce this with my own local application as well.  Not sure if this is a browser issue but I get the same results in both Chrome and Safari on a Mac.

Even on your demo site you can see this 
![react_widgets](https://cloud.githubusercontent.com/assets/367750/13325854/d3b4014a-dba0-11e5-8df4-6cb0dc92da22.png)

But the second one on the page has the bottom border.

![react_widgets](https://cloud.githubusercontent.com/assets/367750/13325879/f65028a0-dba0-11e5-948a-5a980f82aaf7.png)

**Comment by jquense** [comment]
I think its probably do to pixel rounding/snapping for `em` sizes :/ Feel free to PR something if you want :)

**Comment by nmaves** [comment]
Any ideas on where to start?

**Comment by jquense** [comment]
well that input has a borderless input inside of a div styled to look like an input (to add the icon) It seems at some line-height/font-sizes the height of the  inner input is calculating larger then its wrapper. I'd check on the height settings and em calculations there I think

**Comment by nmaves** [comment]
Any thoughts on my quick fix?

**Comment by MakarovAV** [comment]
Still broken for me atm (version 3.4.6).
