### ISSUE TITLE
Select List keyboard / mouse focus behavior

### ISSUE THREAD

**Issue by cascada-io** [jquense/react-widgets#333]
as discussed on reactiflux, Select List should:

- when tabbed into:
  * focus the first unchecked item when there is no value, otherwise focus the first checked value (currently focuses the widget)

- when clicking a list item other than the first:
  * focus the clicked input (currently focuses the first input)

**Comment by jquense** [comment]
this will be the next thing I fix.  thanks for the reminder :)
