### ISSUE TITLE
Issues with Combobox textField accessor

### ISSUE THREAD

**Issue by jlevycpa** [jquense/react-widgets#335]
Thanks for the awesome components!

I'm having some very strange issues when trying to pass a function to the textField prop of the Combobox component. My data is an array of objects like this:
```
[{firstName:'john',lastName:'smith'},
{firstName:'tom',lastName:'hanks'},
{firstName:'steve',lastName:'martin'}]
```

When I simply access one field in my textField function, it works fine:
```
<Combobox
  filter="contains"
  data={[{firstName:'john',lastName:'smith'},{firstName:'tom',lastName:'hanks'},{firstName:'steve',lastName:'martin'}]}
  textField={(item) => {
    return item.firstName;
  }}
  valueField='firstName'
/>
```
If I do `return item.lastName` it works fine as well.

However, if I do `return item.firstName+item.lastName` the combobox loads with `NaN` in the text field and a blank dropdown list. Even if I try to manipulate a single string such as `return item.firstName+'!'` I have the same result.

If I do what I really want, which is `item.firstName+' '+item.lastName` then I get `undefined undefined` in the text field and a blank dropdown. 

Something very strange is happening here. Any thoughts would be greatly appreciated!

**Edit:**  I forgot to mention that I also tried `item.firstName.concat(item.lastName)` and that errors out with `Uncaught TypeError: Cannot read property 'concat' of undefined` in the console.

**Comment by jquense** [comment]
glad you like them.

The reason you are getting weird results is that `item` in the textField isn't always an item in the list. Combobox also allows typed values, so when the value _isn't_ something in the list its just the string of what the user has typed in. Also remember that value could be `null` as well.

```
<Combobox
  filter="contains"
  textField={(item) => {
    return typeof item ==='string' ? item : (item.firstName + ' ' + item.lastName);
  }}
  valueField='firstName'
/>
```

**Comment by jlevycpa** [comment]
Thanks for the quick reply!

The typed value is probably the root of my problem. I don't really want to allow typed values. I just want to use the text field to filter the results. Maybe I would be better off with a component like [react-select](https://github.com/JedWatson/react-select) that is designed for this use case. I'll probably go that direction, so feel free to close this issue if you prefer.

That said, I'm still interested in understanding what's happening here just to satisfy my own curiosity (and improve my skills). It sounds like you are saying that sometimes the function is called with `item` as a string instead of an object, so calls like `item.firstName` would fail. But that's not the behavior I'm seeing. What I'm seeing is that returning `item.firstName` works, so each `item` must be an object with a `firstName` property. But why would returning `item.firstName+'!'` fail where `item.firstName` works?

**Comment by jquense** [comment]
I trying those cases on the doc site and it worked fine, I only saw the behavior you were seeing when having those textFields and typing.

ultimately though I think you want the DropdownList with filter enabled. which only let's you search and select items in the list. hace you tried that one instead? 

if you really want to use the combo box and also want limit to list values you can do that by creating a very light wrapper around it controlling `value` and `onChange` and only accepting values in the list
