### ISSUE TITLE
[ Feature request ]: possibility to pass props to widget's input element

### ISSUE THREAD

**Issue by markortiz** [jquense/react-widgets#337]
currently we are supporting ie9, and a `placeholder` is a must for our clients.
we have already a function that can generate ie9 `placeholder`.

However, for some reasons, ie9 cannot read or get `placeholder` attribute so out work around is to add `data-placeholder` attribute for all components that need `placeholder`.

I'm thinking if we can have something like `inputProps` that will let us put props on the `input` component of `dropdown`, `combobox` and `multiselect`.

is it possible?

**Comment by smashercosmo** [comment]
Agreed, inputProps would be very useful, because currently we have to do some dirty things like:
```javascript
componentDidMount() {
    const input = ReactDOM.findDOMNode(this.refs.multiselect.refs.inner.refs.input);
    input.setAttribute('autocapitalize', 'off');
    input.setAttribute('type', 'search');
}
```

**Comment by smashercosmo** [comment]
I think, that issue should be renamed to "Feature request: possibility to pass props to widget's input element". Something like that.

**Comment by jquense** [comment]
gonna add this where relevant in v4
