### ISSUE TITLE
SelectList won't trigger when highlighted

### ISSUE THREAD

**Issue by tomByrer** [jquense/react-widgets#34]
http://jquense.github.io/react-widgets/docs/#selectlist
It is handy that you will highlight (gray background) an item when you mouse over it.  However, you can not select/click unless you click the mouse directly over the name or button/box.  The highlight in the blank area gives a false impression.
Fx35 (dev channel)

Thanks for your lib; I may use it soon!

**Comment by willdady** [comment]
I agree with @tomByrer. This feels broken an unintuitive and would be better if labels were set to block by **default**. I suspect less-savvy users may be confused why nothing happens on click. I get that the fix is trivial I just think it's a more sensible default.

**Comment by mattez** [comment]
I agree with @willdady.
It feels broken. Not good UX.
It should be set _display: block;_ **by default**.
Really. For sure.
