### ISSUE TITLE
Accented 'Â' character in Datetime picker in production 

### ISSUE THREAD

**Issue by MitchWeiss** [jquense/react-widgets#349]
I have just done my first test deployment to AWS and I am getting an 'Â' in the Datetime picker where there should be a blank space. Any idea's why this might be occurring? It works fine when run locally. 

![screen shot 2016-03-26 at 2 25 05 pm](https://cloud.githubusercontent.com/assets/3953906/14057804/f80de49a-f35e-11e5-9cca-327507c8b8bb.png)

**Comment by jquense** [comment]
looks like some encoding/utc issue with your fonts perhaps? We aren't using anything special so I don't think its react-widgets specific

**Comment by MitchWeiss** [comment]
Yep it was a UTC issue. Adding `<meta charset="utf-8" />` into my `<head>` seemed to fix the problem
