### ISSUE TITLE
Timeformat with window of time

### ISSUE THREAD

**Issue by MitchWeiss** [jquense/react-widgets#351]
I would like my Timepicker to display times in the dropdown with a 1 hour window ie '2pm - 3pm', '3pm-4pm' etc

The selected time can be stored as the start time of the window. Is it possible to change the timeformat to do this?

**Comment by jquense** [comment]
sure, you can either provide a function as the `timeFormat` which formats and returns a string of the time range. Or provide a `timeComponent` that does something similar

**Comment by MitchWeiss** [comment]
Awesome! Providing a function worked perfectly. Thanks for the quick response. 

For anyone else looking for the same functionality, this is how I format my times:

```
timeFormat={ (val) => { 
  return `${moment(val).format("ha")} - ${moment(val).add(1, 'hour').format("ha")}`
  }
}
```
