### ISSUE TITLE
Use renderFoo instead of fooComponent

### ISSUE THREAD

**Issue by taion** [jquense/react-widgets#352]
Many components here take a `fooComponent` prop to render a parameterized child, especially in list contexts.

Many APIs now use a `renderFoo` hook for this sort of thing. I've found this to generally be a better API – in the worst case, the extra verbosity is minimal (since you're rendering something like a functional component, so an actual function works just as well), and it's more flexible (you're not bound to specific prop names, for example).

As such, I think it'd make sense to cut the components here over to using `renderFoo` callbacks.

**Comment by jquense** [comment]
Honestly, I don't really understand why folks go with the render approach now that you can define a component as a plain function.

The problem with renderFoo approaches is that if you want stateful components then you now have to define a new component and then: `renderItem={props => <Item component {...props />}` which is more verbose. It was definately more work for the simple cases pre 0.14. but since you can just do: `itemComponent={props => <span />}` and it be valid now I don't see as much value in changing the current behavior.

**Comment by taion** [comment]
Where this comes up is that I'm writing code that looks like:

```js
function LabelWrapper({ item }) {
  return (
    <Label label={item} />
  );
}
```

to follow Relay conventions of naming props after item types (because it reflects the fragment name).

I feel like this would be slightly cleaner as

```js
function renderLabel(item) {
  return <Label label={item}>;
}
```

In other words, it doesn't add much value for me to define an extra component there just to rename a prop.

The other place this comes up is in the context of providing an API to override e.g. https://github.com/jquense/react-widgets/blob/v3.2.0/src/MultiselectTagList.jsx#L69-L93. Since some of those props like `key` and `item` are in some sense special and need to be handled appropriately, I think it makes more sense to pass those through as positional arguments.

**Comment by jquense** [comment]
Yeah I get it, but there are more then the item prop passed in, so the api would end up passing a `props` object anyway, which doesn't end up making it any simpler...unless i'm missing something?.

**Comment by jquense** [comment]
I mean I see both ends, at this point tho, the cost of breaking that API just isn't worth it to me I think.

**Comment by taion** [comment]
The other place where this would simplify usage is for getting extra data into item components.

I have an example where I'm using `<Calendar>`, and I want to highlight some special dates. Right now, I'm doing this by exporting context from the component rendering the `<Calendar>` with special dates, then picking this up from the day component.

If the API were instead `renderDay`, then I could just close over the set of days to highlight, which would let me avoid using React context here, which would be sort of nice.
