### ISSUE TITLE
Support for React v15.0.0

### ISSUE THREAD

**Issue by martin-svk** [jquense/react-widgets#354]
Can we have a support for freshly released [react v15.0](https://github.com/facebook/react/releases/tag/v15.0.0)? Currently `react-widgets` only accepts `"react": "^0.14.0"` as a peer dependency. Thanks.

**Comment by brigand** [comment]
Opting to not have a peer dependency is probably for the best, or at least update it to allow 16.0 once you've eliminated any warnings with 15.0.

**Comment by jquense** [comment]
fixed as of the latest version
