### ISSUE TITLE
Unable to enter zero after decimal point in NumberPicker

### ISSUE THREAD

**Issue by janslow** [jquense/react-widgets#355]
It's not currently possible to enter a number such as '2.01' in the NumberPicker, as the component replaces '2.0' with '2' as soon as you type it.

This can be reproduced on the (demo site)[http://jquense.github.io/react-widgets/docs/#/numberpicker] under Chrome (49.0.2623.112) and Firefox.

**Comment by jquense** [comment]
thanks for the heads up

**Comment by janslow** [comment]
Thanks for the really quick response.
