### ISSUE TITLE
v3.3.0 NPM package

### ISSUE THREAD

**Issue by janslow** [jquense/react-widgets#356]
Is `react-widgets@3.3.0` meant to exist? It doesn't appear to be tagged in the repository, but it exists in the NPM registry.

Due to semantic versioning, if you install `react-widgets@latest` and save it to package.json, it will set the version as `^3.2.4`, but if you run `npm update` it will update it to `react-widgets@3.3.0`, which is older.

**Comment by jquense** [comment]
uh, I have no idea...thats weird let me check

**Comment by taion** [comment]
I saw it briefly as well. Or it ended up in my `package.json` somehow.
