### ISSUE TITLE
Calendar max date breaks when declaratively set to null

### ISSUE THREAD

**Issue by danbahrami** [jquense/react-widgets#357]
Is anyone else seeing an issue when declaratively setting the Calendar max prop to null?

Here is an example use case, I'm writing a wrapper component that accepts moment objects instead of date objects as min/max props.

```
<Calendar
    min={(this.props.min) ? this.props.min.toDate() : null}
    max={(this.props.max) ? this.props.max.toDate() : null}
/>
```

In the case of no max prop passed to the wrapper component the next month button is visible and active, the onNavigate event is firing but the calendar is not panning right to the next month. If I pass no max prop at all to Calendar it works fine.

**Comment by jquense** [comment]
thanks for the issue, are you able to reproduce this on the doc site? my first thought is that null is just not a valid value for max, try undefined instead.

**Comment by danbahrami** [comment]
No problem, I can reproduce on the docs by passing null, you are correct that passing undefined works fine though. I can fix my end but possible consider gracefully falling back if null is passed, especially as react propType validation doesn't raise any warning or error when null is passed.

**Comment by jquense** [comment]
seems reasonable to fallback, the reason it doesn't work is that that's now handled by defaultProps.

I should set isRequired there so it does warn if you null it out.

**Comment by danbahrami** [comment]
I'm not sure making it a required prop makes sense, what if I don't want to supply a max date at all?

**Comment by jquense** [comment]
then it will be `undefined` and the defaultProps will be used

**Comment by danbahrami** [comment]
Ah, yes, good point. ok, thanks for your help.
