### ISSUE TITLE
clipping of combobox in Ag grid

### ISSUE THREAD

**Issue by Miteshdv** [jquense/react-widgets#358]
Hi ,
 I was using react-widget combobox in Ag grid , but the issue is the list popup of combo gets clipped inside the cell of grid.

Work around by ag grid is given as 

https://www.ag-grid.com/angular-grid-editing/index.php

But to do is i need to access the popup and change the x and y and z coordinates pls help

Thanks

**Comment by jquense** [comment]
popups are absolutely positioned next to their widgets so even if had access to the popup (which isn't exposed)  I don't think that work around would work anyway.

**Comment by Miteshdv** [comment]
So what can be done now ? any idea or solution please.

**Comment by Miteshdv** [comment]
So u mean

style: {
        ...child.props.style,
        ...offset,
        position: this.isTransitioning() ? '**absolute**' : undefined
      },

The absolute value is making the popup next to input .. can we do something so that popup appears on top of ag-grid

**Comment by jquense** [comment]
overflow doesn't work in the way you'd want in this case in HTML. the only way to make the cell not clip the popup is to set `overflow: visible` on the cells but that may break the grid styling. Other then that the only way to do it is to use some sort of fixed positioning which is just not supported by these widgets.

**Comment by Miteshdv** [comment]
So u mean i should drop idea of using combobox and ag grid

**Comment by jquense** [comment]
I mean that you can't position the popup relative to the Grid, I have no idea how ag-grid works or whether the combobox would work with it otherwise. You can try adjusting the styles of the grid cells to allow overflow, other than that I have no idea. Thanks!

**Comment by Miteshdv** [comment]
:) Thanks

**Comment by Miteshdv** [comment]
Ok, so i have fixed it by setting overflow of the cell as visible as the cell had only combobox involved so it worked well. Thanks

**Comment by dholakiyaankit** [comment]
@jquense `overflow:visible` is the solution unless we have library fix.
