### ISSUE TITLE
Control the height of the popup

### ISSUE THREAD

**Issue by LeoIannacone** [jquense/react-widgets#359]
Hi,

in mobile (whey the keyboard is showed) my popup goes behind the keyboard, so the user is a bit confused and result is not really good.

How can I control that height?

**Comment by jquense** [comment]
css! I believe the max-height is set to `200px` you can adjust it to your needs using LESS or just plain css and a selector

**Comment by LeoIannacone** [comment]
Got it! Thanks a lot!!
