### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by shapkarin** [jquense/react-widgets#360]
Can I use browserify to load component? 

```javascript
var ReactWidgets = require('react-widgets/dist/react-widgets.js')
var NumberPicker = ReactWidgets.NumberPicker;
```

app.js:4466 Uncaught TypeError in console:
```javascript
app.js:4466 Uncaught TypeError: Cannot read property 'apply' of undefined
```

**Comment by jquense** [comment]
yes but don't require them from `/dist` that is a global build for using in a script tag. import from `react-widgets` or `'react-widgets/lib/NumberPicker`

**Comment by shapkarin** [comment]
the same error...
```javascript
var NumberPicker = require('react-widgets/lib/NumberPicker')
```

**Comment by jquense** [comment]
I don't think the error is on the ReactWidgets side, something may be messed up with your build config. If you do think its a bug, please provide more info so I can reproduce it thanks!

**Comment by shapkarin** [comment]
Ok. 
I use grunt to compile or 'npm start' and see the same error. 

grunt:
```javascript
browserify: {
    dist: {
      files: {
        'output/build/app.js': 'jsx/app.jsx'
      },
      options: {
        transform: ['reactify']
      }
    }
  }
```

npm:
```json
"scripts": {
    "start": "watchify jsx/app.jsx -v -t [ babelify --presets [ react ] ] -o output/build/app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

Please help.

**Comment by jquense** [comment]
I don't see anything strikingly odd, but I also don't ever use browserify, sorry there isn't much I can do to help.

**Comment by foxhound87** [comment]
I got the same issue with version 3.4.4 using webpack.

`Uncaught TypeError: Cannot read property 'apply' of undefined`

`decimalChar @ localizers.js?9bf2:127`

```javascript
return (_numberLocalizer5 = _numberLocalizer).decimalChar.apply(_numberLocalizer5, arguments);
```

**Comment by Grimfri** [comment]
Some error
`Uncaught TypeError: Cannot read property 'apply' of undefined`
`localizers.js:127`

**Comment by nik-kor** [comment]
create a new issue https://github.com/jquense/react-widgets/issues/504
