### ISSUE TITLE
Issue with text field state when using redux.

### ISSUE THREAD

**Issue by ColadaFF** [jquense/react-widgets#361]
Hi there,

I've been trying to use some of the components of this library, especially ComboBox, but I tried to connect all the state from the component to redux, the thing is; the ComboBox component has the attributes `value` and `onChange` that are the default I use to set or update the values, but on these components the `value` prop is not "linked" to the text field, so, when I try to update the state, the state do update, and the value on the `value` prop is updated as well, but the text field data remains the same, this is especially tragic since I'm trying to use a cascade select, so the one ComboBox is dependent of another one, but if update one, the other one `data` and `value` changes but the text field keeps the state of the last thing selected, is there any way I can accomplish this? 

I mean, like some prop I can control on the component that has the text inserted on the field.

Thanks.

**Comment by jquense** [comment]
hi! I'm not sure what you mean by the "text field", setting the value prop will completely control what the combo box displays and which item is selected. I'm not sure what other text you are trying to specify here.
