### ISSUE TITLE
NumberPicker does not follow precision attribute when typing

### ISSUE THREAD

**Issue by alawatthe** [jquense/react-widgets#362]
The documentation for the [numberpicker component states](jquense.github.io/react-widgets/docs/#/numberpicker/precision):

> Specify how precise the value should be when typing, incrementing, or decrementing the value. When empty, precision is parsed from the current format and culture.

So, when I set the precision to ```2``` I should not be able to enter numbers (via typing) with more than two digits after the decimal point, right? Or am I misunderstanding the precision argument?

Currently I am able to enter more than two decimal digits. I believe, the reason for this is, that the change function https://github.com/jquense/react-widgets/blob/master/src/NumberPicker.jsx#L251-L256 does not call the round function like the step function does.

**Comment by jquense** [comment]
Precision is actually jsut used for step, increments, and really only exists the handle floating point number rounding issues, when say incrementing by `0.1`. It isn't (currently) useful for limiting input. To do that I that you should just set a minimum, or map the value in `onChange`

**Comment by alawatthe** [comment]
Isn't this something we could implement? I could have a look at it tomorrow... :-)
