### ISSUE TITLE
Open DropdownList above if not enough space below

### ISSUE THREAD

**Issue by catchin** [jquense/react-widgets#363]
The HTML <select> element opens the selection popup above the element's position if not enough screen space is available below. Could this also be implemented in the DropdownList component?

**Comment by jquense** [comment]
its not something that I intend to implement in core here, as there are a ton of edge cases to consider and its a tough thing to generalize. You can however implement it your self as a wrapper component or mixin, where you do the check and set `dropup` to `true' or `false` based on where you want to display the popup
