### ISSUE TITLE
Moment.js format tokens don't work in DateTimePicker

### ISSUE THREAD

**Issue by evpozdniakov** [jquense/react-widgets#364]
I've configured ```momentLocalizer``` as described, but wasn't able to use time format tokens like ```A``` or ```a``` which display AM/PM. By occasion I found that ```tt``` can be used, however it is not documented.

BTW, I like very much your library, great job!

**Comment by jquense** [comment]
Sorry for the big delay here. I think you must have moment configured wrong or maybe an older version? react-widgets doesn't have any logic around the formats it just passes them through to moment
