### ISSUE TITLE
DropdownList value persisting after rerender (undesired)

### ISSUE THREAD

**Issue by stephenburgess8** [jquense/react-widgets#366]
Hi. Thanks for your library. I am using your DropDownList. Overall things are working well. However there is one issue.

I have a search results page. Each individual search result is a Google Material Design style card. Each card has one of your DropdownList components which is passed an array of JS objects. Within the card, I'm rendering the DropdownList like:

```
<DropdownList data={ links }
              onSelect={ selectLink }
              placeholder={ this.state.placeholder }
              textField='title'
/>
```

The links array is regenerated for each card on every render. It is formed like:

```
let links = Object.keys(searchResult.links).map(key => ({ 
    title: key,
    links: searchResult.links[key],
    id: searchResult.id,
    external_id: searchResult.external_id,
    filename: searchResult.filename
}))
```

My search results are paged. So when I click to the second page, the search results page rerenders. As part of render the links array is regenerated for every search result.

When I select the second page of my search results, the page rerenders. The links array is regenerated. The problem is that if I previously selected an option for one of the cards in the search result, the card renders with that option still selected. So, there's a rerender with a new links array being passed into the DropdownList, but the previously selected option shows up as the label of the dropdown triggering button.

In some cases, the options in the array may be different. Even if they are, the selected option from the last page will be present on the triggering button label but not in the dropdown. If I select a new option from the DropdownList, this old value will go away as expected.

I am trying to resolve the issue of the previously selection option showing up as the label for the trigger button when a rerender is triggered as a result of new props. I'm hoping you may be able to shine some light on this bug. Thank you.

**Comment by jquense** [comment]
What you are seeing what happens when components own their own state, i.e. are uncontrolled. Since the components aren't unmount/remounting when the data changes their internal state is maintained. Its actually a feature that the value displayed doesn't need to be in the data array, so I don't want to change that.

The best way to address it is to control `value` on each dropdown and reset it to whatever value you'd like when the data array changes. The really hacky way of handling it without controlling the values is to set a `key` on the dropdown and change it when the data changes, that will force an remount.

**Comment by stephenburgess8** [comment]
Thanks for your prompt reply. I would like the value to be placeholder. I used the prop `defaultValue={ placeholder }` and I still have the same behavior. The value field is only controlled through the `defaultValue`. I want the default behavior to be the placeholder. Is there any way to make the value reset to the placeholder value?

**Comment by jquense** [comment]
defaultValue just sets the initial value, its the same thing you are doing now. you want to use `value` and `onChange` like you would a controlled html input
