### ISSUE TITLE
Combobox javascript error Uncaught TypeError: Cannot read property 'isSuggesting' of undefined

### ISSUE THREAD

**Issue by amoenk** [jquense/react-widgets#367]
In componentWillReceiveProps in Combobox.js, calls to this.refs.input.isSuggesting sometimes fails because this.refs.input is not defined. 

The text input has been referred as input in render, however, componentWillReceiveProps can apparently fire before render has been called, thus leaving refs empty.

**Comment by jquense** [comment]
ref #309.

I wish this was reproducable, it seems like a React bug,  or maybe something to do with hot-relaoder or something like that :/

**Comment by amoenk** [comment]
You should be able to reproduce it using something like this. I've found that this happens if there are props updates prior to the combo being realized in the browser DOM, for instance, if your parent component has an update immediately after it does its own render, before react flushes its batched changes to the browser DOM. 
```
componentDidMount() {
    setTimeout(() => this.setState({fakeStateObj: {}}));
}
render() {
   return (<Combobox ... />);
}
```

Should be a simple fix - just guard against this.refs.input being NULL in componentWillReceiveProps.

**Comment by jquense** [comment]
i'll give that a shot, while an easy fix it's definitely not something that should happen, so I want make sure I understand where and what the problem is

**Comment by amoenk** [comment]
Any word on the status of this issue? These errors are still filling up my logs.

**Comment by jquense** [comment]
no update, PR's welcome!

**Comment by amoenk** [comment]
For sure! PR created.
