### ISSUE TITLE
isRtl inverts calendar days

### ISSUE THREAD

**Issue by santiagopuentep** [jquense/react-widgets#379]
Using the isRtl property makes the calendar days go from right to left also, looking mirrored.

**Comment by jquense** [comment]
Sorry, I don't think I understand the issue, don't you want the days to go right to left, when specifying right-to-left? In any case that logic is not in RW it's how the browser flips it when you turn on rtl

**Comment by santiagopuentep** [comment]
Yes, that would be the issue. With right to left what I wanted is to have the button to the left of the input, but it also changes the calendar days to go from sunday to the right to saturday to de left.

I think those two should be separate settings.

**Comment by jquense** [comment]
I don't know that it makes sense to have those be seperate RTL is a culture/language concern not really a presentational one. In any case that logic is handled by the browser.
