### ISSUE TITLE
Documentation problems

### ISSUE THREAD

**Issue by santiagopuentep** [jquense/react-widgets#380]
There are some missing documentated props and one important one with the wrong example.

The `value` prop has an example that shows `defaultValue` being used. This is very confusing.

Also, non documented props like `placeholder`, `dropUp` or `autoFocus` would be very helpful to have them documented because most of the programmers are not going to read the code and use them.

I hope it helps.

**Comment by jquense** [comment]
thanks for the feedback, `value` and `defaultValue` are the same thing, the just indicate whether you will be controlling the value yourself or letting the component do it. This is inline with how React documents inputs.

`placeholder` and `autoFocus` are html attributes and are just passed through to the components, it doesn't make sense to document every single html attribute avialable to inputs as there are 100s. `dropUp` is indeed undocumented and should be!

**Comment by santiagopuentep** [comment]
Sorry, I didn´t know this component passed the props to the input field inside it. I´m no expert in React and maybe I´m stating the obvious but I think that saying that in documentation would be helpful for non advanced React programmers.

Thanks again!
