### ISSUE TITLE
DatePicker widget setting the min date, the widget looks odd

### ISSUE THREAD

**Issue by rramakr** [jquense/react-widgets#381]
Hi,

We are using the DatePicker widget in our App.  When we set the Min date for the widget as current date, the past dates are white spaces.

Is there a way to show the past dates as disabled so that the widget UI look and feel is good.
<img width="1440" alt="screen shot 2016-05-09 at 2 54 26 pm" src="https://cloud.githubusercontent.com/assets/11774845/15129533/0444b8be-15f7-11e6-82b4-4ac3b7095ece.png">

Is there a way or props I can set to format the past date when min date prop was set.

Thanks & Regards
Rejiesh

**Comment by wiktor256** [comment]
The empty cells have the class 'rw-empty-cell'. You can create a custom style like this:

    .rw-empty-cell {
      text-align: center;
      padding: 6px;
    }

    .rw-empty-cell:before {
      content: '-';
      position: relative;
      left: 3px;
    }

<img width="314" alt="screen shot 2016-05-11 at 8 46 11 pm" src="https://cloud.githubusercontent.com/assets/6200063/15200921/7939f954-17b9-11e6-893f-22a565696d92.png">

**Comment by rramakr** [comment]
Thank you for replying.
Is there a way to show the Date in Disabled status instead of the special character which again will be odd.

**Comment by jstrimpel** [comment]
@wiktor256 would you accept a PR that displays the dates disabled that are below the min date?
