### ISSUE TITLE
DateTimePicker can't go to previous month if current value > max

### ISSUE THREAD

**Issue by amagee** [jquense/react-widgets#384]
Reproducible on demo page http://jquense.github.io/react-widgets/docs/#/datetime-picker?_k=jsvqv5
1. Select a particular date on the `DateTimePicker` widget.
2. Set the widget's `max` value to be before the date currently selected.
3. Open the calendar.
4. Try to use the previous month button.

The calendar scrolls to the previous month but then scrolls back to the current month. However clicking the title bar of the calendar to select a month works.

**Comment by jquense** [comment]
Not actually much I can do about this :/ I'd suggest not getting into this situation by moving the max and or the selected date to be within range

**Comment by luisfuertes** [comment]
@jquense If the value is null or you delete it, the calendar will open in the current month causing the bug again
