### ISSUE TITLE
SCSS Compilation Error

### ISSUE THREAD

**Issue by Tref** [jquense/react-widgets#385]
I am using this library in the context of a Rails application using Sass-rails -v 5.0.1 where I am importing the SCSS files individually. When I go to compile core.scss I am getting the following error from the prepended & in front of the following selector on line 141:

```
&.rw-state-disabled {
  @include state-disabled();
  opacity: 1;
}
```
With the following error:

```
Base-level rules cannot contain the parent-selector-referencing character '&'.
```

Wondering if anyone else has had this error and if it is an error with my compiler version. I'm going to attempt a bump up to sass-rails 5.0.4 or 6 beta and see if this fixes the issue.

This seems to be related to https://github.com/jquense/react-widgets/issues/368

**Comment by gilbarbara** [comment]
I'm having this error too with version 3.4.5 using `webpack 2.2` with `sass-loader 5.0` and `node-sass 4.5`
