### ISSUE TITLE
Can we have a vertical scrollbar for Multiselect when selected many values from list?

### ISSUE THREAD

**Issue by stellatse** [jquense/react-widgets#391]
Can we have a vertical scrollbar for Multiselect when selected many values from list?
if the selected value list is large, the multiselect input box will unlimitedly enlarge, can we make it a max height for that?

**Comment by jquense** [comment]
I don't want to do that by default because I tend to think that that's not great UX even for a large number of items.  However,  I think it should be fairly straightforward to do via css yourself if you like that paradigm in your own code.
