### ISSUE TITLE
Messages (emptyList, ...) were allowed to be functions but not anymore in propTypes validations

### ISSUE THREAD

**Issue by tomyf** [jquense/react-widgets#395]
Since this commit : https://github.com/jquense/react-widgets/commit/79ab4080d6076b8f4c8450b5470848b6565e6d0f

I don't understand why messages as function would be deprecated.

**Comment by jquense** [comment]
In what places did you use a function? Messages have never actually supported being functions as far as I know (there is no code to call those functions)

**Comment by tomyf** [comment]
It has been working really great in version 3.2.x (I do not have the specific version at the moment).

I used them as : 
```javascript
<Combobox
	valueField='value' 
	textField='label' 
	data={this.props.list} 
	filter='contains'
	value={this.props.value} 
	onChange={this.onChange} 
	busy={this.state.busy}
	messages={{ // Localization for messages in the component
		emptyFilter: () => getMsg('global_empty_combo'),
		emptyList: () => getMsg('global_empty_combo')
	}}
	duration={0}
/>
```

It's not a problem since I've replaced these functions with a custom component, but I find it more verbose than using a function.
Plus, using a function that would return a string / node may also be a "hook" feature for people who wants to use it this way (not sure how or why though).

Thanks,
Thomas

**Comment by jquense** [comment]
I'm not sure honestly, I was fairly certain the above never worked. Why use a function and not just call getMsg yourself and pass the result to messages?

**Comment by tomyf** [comment]
It did work well :) 

This was used in order to load dynamically the message when it was displayed, so the user locale could change and the message was updated dynamically. Not the best way to do it, yet it is simple and worked great with our application.

**Comment by jquense** [comment]
I'll look back through and add it back, I think it was unintentional removal

**Comment by tomyf** [comment]
Thanks for your time :+1:

**Comment by shinzui** [comment]
I just upgraded and I am also seeing this error. Is it possible to revert the removal? The docs still show it as valid. 

![image](https://cloud.githubusercontent.com/assets/519/18862934/b23c0516-8443-11e6-872a-9ebfd986819f.png)

**Comment by shinzui** [comment]
Would you accept a pull request to fix this?

**Comment by jquense** [comment]
fixed in v4
