### ISSUE TITLE
DropdownList breaks server rendering

### ISSUE THREAD

**Issue by smashercosmo** [jquense/react-widgets#397]
I get this message on the second page refresh
```
warning.js?37cd:44Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) true" aria-owns="rw_1__listbox" aria-bus
 (server) true" aria-owns="rw_2__listbox" aria-bus
```
with every new refresh aria-owns attribute (server) increases number in the middle. So for the third refresh it is "rw_3__listbox" and so on. Is it a react-widgets bug or I'm doing something wrong?

**Comment by jquense** [comment]
Id's are generated automatically to provide necessary a11y roles and attributes, the downside is that they don't match when rehydrating on the client from SSR. Luckily they will use `id` you give them instead of the generated id's, so if you provide `id` to each input they will work fine 👍

**Comment by smashercosmo** [comment]
Yeah, I think that I already knew that, but lost this information somewhere in my head) Thanks for bringing that back.  This time I'll try not to forget)
