### ISSUE TITLE
placeHolder not working on DropdownList?

### ISSUE THREAD

**Issue by ljovanovic** [jquense/react-widgets#398]
Has anyone been able to get this working?  I'm not able to get this working with any of the examples.

Here's an example I've tried:

var DropdownList = ReactWidgets.DropdownList, colors = ['orange', 'red', 'blue', 'purple'];
var widget =
      <DropdownList
        placeHolder="Test Placeholder"
        onSelect={() => alert('selected!')}
        onChange={() => alert('changed!')}
        data={colors} />

ReactDOM.render(widget, mountNode);

Thank you

**Comment by jquense** [comment]
`placeholder`not `placeHolder`

**Comment by ljovanovic** [comment]
Confirmed....thank you.

**Comment by srinadhareddy625** [comment]
place holder is not working. my code is like


<div class="col-md-8">
<p-dropdown [options]="killmodeList" [(ngModel)]="selectedKillMode" 
                           placeholder="Select Kill Mode"
 [style]="{'width': '250px'}" appendTo="body" (keydown.enter)="killProcess()"></p- dropdown>                                                          
</div
