### ISSUE TITLE
global include is not workiing

### ISSUE THREAD

**Issue by enkhchuluun** [jquense/react-widgets#399]
i've wasted my 4 hours on just make it work with NumberPicker

I've tried with Global Build (just including react-widgets scripts and css on my html), but it constantly gives error.

Finally i've just make that work with webpack.

----------------
require('react-widgets/dist/css/react-widgets.css');

var React = require('react');
var ReactDOM = require('react-dom');
var ReactWidgets = require('react-widgets');
var numberLocalizer = require('react-widgets/lib/localizers/simple-number');
var NumberPicker = ReactWidgets.NumberPicker;

numberLocalizer();

var AppView = React.createClass({
      render: function () {
        return (
          <div className="row">
          	<div className="col-md-6">
	            <p>Hello, React! heheheh</p>
	            <NumberPicker defaultValue={1} min={0} max={100} step={5} />
            </div>
            <div className="col-md-6">
	            <p>Hello, React! heheheh</p>
	            <NumberPicker defaultValue={1} min={0} max={100} step={5} />
            </div>
          </div>
        );
      }
    });

ReactDOM.render(<AppView/>, document.getElementById('app'));
----------------

Could you make the doc sourcd code copy/pastable? it really annoying.
And people not using webpack, can't use your example code!!.

**Comment by jquense** [comment]
what ever does it give you? Also not sure what you mean ppl not using webpack can't use the example code...

**Comment by enkhchuluun** [comment]
this code gives following error. 

<!DOCTYPE html>
<html>
<head>
    <script src="/admin/plugins/react/react.js" type="text/javascript"></script>
    <script src="/admin/plugins/react/react-dom.js" type="text/javascript"></script>
    <script src="/admin/plugins/react-widget/react-widgets.js" type="text/javascript"></script>
    <script src="/admin/plugins/react-widget/react-widgets-simple-number.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>

</head>
<body>
<div id="testNum"></div>

<script type="text/babel">

    var NumberPicker = ReactWidgets.NumberPicker

    var AppView = React.createClass({
      render: function () {
        return (
          <div>
            <NumberPicker defaultValue={1} />
          </div>
        );
      }
    });


      ReactDOM.render(
        <AppView />,
        document.getElementById('testNum')
      );
</script>


</body>
</html>


**chrome dev console error:**
react.js:19368 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `AppView`.

Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `AppView`.
