### ISSUE TITLE
React widgets causes page scrolling to jump

### ISSUE THREAD

**Issue by dubert** [jquense/react-widgets#40]
This is a difficult bug to reproduce but I was able to do it on the demo page. 

react-widgets@2.0.1 works fine, so I've had to revert to it for now. But with react-widgets@2.2.0, sometimes focusing on a widget or interacting with it causes the page to jump, occasionally outside of the view, which makes the feature unusable. Here is a [video](http://cl.ly/ZSRw) of me reproducing it.

**Comment by jquense** [comment]
@dubert I've already caught it and fixed it in master, should be a patch release going out later today. Thanks for the heads up
