### ISSUE TITLE
Popup direction for Dropdown, Combobox, Date & Time Picker, etc.

### ISSUE THREAD

**Issue by darkadept** [jquense/react-widgets#400]
Is it possible to specify a direction for widgets like the Date & Time Picker?

Since my control is near the bottom of the screen I need it to scroll up instead of down.

**Comment by jquense** [comment]
the `dropUp` prop...which I see I have _still_ not documented, ugh.

**Comment by darkadept** [comment]
Found it!

You can specify the `dropUp` boolean prop.

`<DateTimePicker dropUp={true}/>`

Found it by looking at the source: https://github.com/jquense/react-widgets/blob/master/src/DateTimePicker.jsx
(search for //popup)

(And @jquense just replied as I was typing this!) Thanks!
