### ISSUE TITLE
Typo in example on GettingStarted docs

### ISSUE THREAD

**Issue by chevin99** [jquense/react-widgets#401]
On this page */docs/components/pages/GettingStarted.md*, there is this example:

```
<script>
  var DropdownList = ReactWidgets.DropDownlist;
​
  ReactDom.render(<DropdownList/>, document.getElementById('app-root'))
</script>
```

But `ReactWidgets.DropDownlist` should be `ReactWidgets.DropdownList`.  I couldn't figure out why it wouldn't work but that was it so I thought I'd let you know 😄

**Comment by jquense** [comment]
thanks for the heads up
