### ISSUE TITLE
Use native datepicker on iOS/Android

### ISSUE THREAD

**Issue by MitchWeiss** [jquense/react-widgets#402]
I am using the datepicker and it's working really well on desktop but on mobile the experience isn't quite as slick. The calendar is a little small and the keyboard opens up over the top of it. 

Mobile browsers have a great built-in datepicker, so I'm wondering if its possible to use the native date picker on iOS/Android (maintaining the min/max values) and use the react-widget calendar on desktop?

**Comment by jquense** [comment]
you can use the native one when ever you'd like. I can't however control it's behavior but I'm fairly certain that it already respects min and max. It's up to you to decide when to use what. You might want to check out react-formal src code for the date I put which wraps native inputs but allows using date objects directly

**Comment by MitchWeiss** [comment]
Ok thanks, I will take a look at react-formal and see if I can find a way to determine when to use the widget or native implementation.
