### ISSUE TITLE
Recent rebuild broke SCSS files

### ISSUE THREAD

**Issue by vdh** [jquense/react-widgets#403]
The recent rebuild commit: https://github.com/jquense/react-widgets/commit/d48da53b1b55367533bc6d24935020764afe0a8c

Broke `lib/scss/mixins.scss`, amongst other Sass files :(

It looks like this rebuild commit was also included in the 3.3.2 release on NPM, which makes it differ in functionality from the 3.3.2 tag in Github.

**Comment by jquense** [comment]
oops sorry about that

**Comment by mattdell** [comment]
I'm having the same issue

**Comment by PurpleBracket** [comment]
major issues with sass styles. anyone got it fixed?

**Comment by jquense** [comment]
should be fixed. Let me know if anything is still wrong
