### ISSUE TITLE
Multi Select | IE 11 | Copy Paste of multiple items at one go.

### ISSUE THREAD

**Issue by vichu1988** [jquense/react-widgets#405]
I am using Multi-select in a form where the input normally is sourced from a seperate excel sheet and the issue occures in IE11 when there is multiple rows of data being copied and entered into the input box. 

Issue seems to be a generic IE11 issues common with input[type='text'] boxes. Simillar to issue [here](http://www.coderanch.com/t/118796/HTML-CSS-JavaScript/Copy-Paste-EXCEL-HTML-Text).

The need is to be able to make the input rendered optional between input and textarea as that could potentially eliminate the issue in IE. 

Could you potentially include a way to get that as a prop.

IE11 !! i know right!

**Comment by jquense** [comment]
hi there, I'm fairly certain that I can't allow rendering as textarea, since it would break the ability to style the input correctly, and its incorrect for a11y reasons as well...

Can you not process the data yourself onPaste and avoid the issue with IE?

**Comment by vichu1988** [comment]
I am sorta bending over to get the IE11 to recognise CR/LF and handle the issue but like you said it can be handled without Text area. Thanks Jason.
