### ISSUE TITLE
Multiselect allows first disabled value to be selected via `return`

### ISSUE THREAD

**Issue by bral** [jquense/react-widgets#406]
```
var Multiselect = ReactWidget.Multiselect;
var colors = [‘orange’, ‘red’, ‘blue’, ‘purple’];

var Example = React.createClass({
  render() {
    return (<div>
      <Multiselect
        disabled={colors.slice(1,3)}
        data={colors}
        defaultValue={[“orange”]} />
    </div>)
  }
});

ReactDOM.render(<Example/>, mountNode);
```

Using the above code, which can be tried on the demo page, the widget is allowing a disabled value to be selected by hitting `return` if the value is the first in the dropdown list. Selection is not allowing by clicking.

**Comment by ittus** [comment]
Is it correct behaviour? After selected, `red` and `blue` are disabled and can't remove from selected list. I think `disabled` here means can't delete items from selected list.

**Comment by jquense** [comment]
fixed in v4
