### ISSUE TITLE
IE8 incompatibility (unsupported removeProperty method on style)

### ISSUE THREAD

**Issue by vladimir-rovensky** [jquense/react-widgets#41]
Hey guys

I came across a problem in IE8 when I tried using the Combobox component. The code tries to modify CSS properties via the removeProperty method (see src/util/dom.js, method called css) which is not supported in IE 8 (see e.g. http://help.dottoro.com/ljopsjck.php).

This causes an exception that prevents the Combobox  from closing.

Could you tweak the method to use something else in IE8? Based on a short search, removeAttribute method could work.

**Comment by jquense** [comment]
hey there thanks for the heads, up I'll have it fixed soon, i need to finally just get the tests running up on saucelabs in an actual ie8 environment
