### ISSUE TITLE
combo box - how to hide button, change style of itemComponent

### ISSUE THREAD

**Issue by cindyloo** [jquense/react-widgets#412]
hi there-
am struggling to understand how to update the styles. I am using the inline style and setting <Combobox style={myinlinestyle}  However, targeting internal widgets doesn't appear to work. How do I tell the Combobox button to hide itself, for example without telling the whole combobox to? Or the itemComponent to have a listStyleType: 'none.' ?  I am new to react-bootstrap so could use a good link - I haven't found the help I am looking for.  thanks.

**Comment by jquense** [comment]
Hi there, 

You won't be able to style all the internal bits of the widgets with just inline styles, this is a general limitation of inline styles over plain css.

If you want to completely them and style the components, you'll need to use css, either the one included with the project, which you tweak, or you can use SASS or LESS and edit the styles via the theme variables.

**Comment by cindyloo** [comment]
ok.. would you mind elaboratiing on the latter: so I would need to change the css or scss in the widget folder itself (that did work but seemed wrong to me) versus override them?

how do I edit the styles via theme-variables? is this a SASS/LESS thing or a bootstrap thing? if a bootstrap thing, could you point me to where to learn about this.. thank you!

**Comment by jquense** [comment]
as a clarification, this project doesn't have anything to do with bootstrap, apart from the fact that the included "default" theme is bootstrap-esque.

You should override the styles in your project according to the general strategy for either LESS or SCSS. But in general you have your own `.less` (or scss) file, import react-widgets.less file and redefine any of the variables you want after that. which lets you override the things you want. for things that aren't covered via the variables, you use normal css and selectors to change stuff.
