### ISSUE TITLE
AMD module definition broken in latest rebuild

### ISSUE THREAD

**Issue by billderose** [jquense/react-widgets#413]
On this [line](https://github.com/jquense/react-widgets/blob/master/dist/react-widgets.js#L6), it should read `define(['react', 'react-dom'], factory)`. @jquense If there's any easy fix, im happy to submit the PR myself, but I'm just starting to use the library and am not familiar with the build process. Thanks for the awesome library!

**Comment by erikthinkiq** [comment]
@billderose's proposed change fixed AMD for me as well.

**Comment by erikthinkiq** [comment]
Note to anyone finding this issue, this is still broken in 3.4.8, but fixed in 4.0.0-rc.8.
