### ISSUE TITLE
Datepicker icon is not appearing 

### ISSUE THREAD

**Issue by mukeshkumarc** [jquense/react-widgets#414]
I have imported all file in react but I am not getting date selecting icon 
code : 
```
import DateTimePicker from 'react-widgets/lib/DateTimePicker';
import momentLocalizer from 'react-widgets/lib/localizers/moment';
import 'react-widgets/lib/less/react-widgets.less';
import Moment from 'moment';
......
  constructor() {
    super();
    momentLocalizer(Moment);
  }
......
<DateTimePicker time={false} defaultValue={new Date()}/>
......
```
![rsz_screenshot_from_2016-07-09_162938](https://cloud.githubusercontent.com/assets/5524889/16707615/a4f5296c-45f2-11e6-88a1-d00a9457a34a.png)

**Comment by jquense** [comment]
does look like the styles are working at all. something is probably wrong with your webpack setup pehaps
