### ISSUE TITLE
Unclear on how to contribute in regards to the build script

### ISSUE THREAD

**Issue by vdh** [jquense/react-widgets#419]
I'd like to help out with some PRs, but I'm uncertain about the generated files. Should PRs include regenerated files, or only the changes to source files?

I've tried cloning a fresh copy of the repo and running `npm install` then `npm run build`, but it always results in changed files. Even when run on a rebuild commit like d92fe25 where I'd normally expect the build output to be identical, it still generates some slight differences in the JS code. I assume I must have a slightly different version of some library from the machine that does the official build, but I have no idea which one.

**Comment by jquense** [comment]
In generally its better to not include the generated files in PR's; they get rebuild during a release and are there so folks can pin to versions from github.
