### ISSUE TITLE
Focus on inputs

### ISSUE THREAD

**Issue by andriibuts** [jquense/react-widgets#422]
Hello.

We are using your widgets in our project and they work great on the desktop.

But there are several problems on mobile devices: when a user interacts with some widget, it focuses the input field inside of it, even if it is not necessary. This forces the keyboard to show on mobile devices.

It would be great to focus input only if the user actually  clicks on the input field and don't do that if the user just clicks on the 'calendar' or 'time' button in the Date Time Picker of clicks on 'up' or 'down' buttons in the NumberPicker.

Thank you.

**Comment by jquense** [comment]
long time coming but: Unfortunately we can't take that approach and still maintain accessibilty standards for most components. not to mention technical issues surrounding that approach. If you click a native number picker buttons the input is focused, this needs to happen in case the user decides they are going to type the number in instead. I'd like to have better story for mobile but at the moment it's tough.

**Comment by andriibuts** [comment]
Thanks for the answer.

Maybe it would be better to use `input[type="number"]` for **NumberPicker** so the keyboard would be corresponding to the purpose.
