### ISSUE TITLE
Dropdown List Select on Tab Key Pressed

### ISSUE THREAD

**Issue by L3V147H4N** [jquense/react-widgets#423]
It would be nice to be able to select an item by pressing tab in the Dropdown List and Combo Box

**Comment by jquense** [comment]
tab is generally "move focus" I'm not sure adding a selection semantic to it as well makes sense in this context.

**Comment by L3V147H4N** [comment]
yes I mean, it could select and move focus, also because pressing enter is also associated with form submit

**Comment by L3V147H4N** [comment]
It does not need to be default behavior, but it could be an addition

**Comment by jquense** [comment]
For now I think i'm going to pass on this. IF we did want this sort of behavior I think we'd need to change how selection worked over all, not just what happens on tab.
