### ISSUE TITLE
Multiselect, remove items on blur

### ISSUE THREAD

**Issue by L3V147H4N** [jquense/react-widgets#424]
When using the Multiselect Component you can type anything but onBlur the text remains in the input field

![image](https://cloud.githubusercontent.com/assets/5846479/17043132/1dcac40a-4f8a-11e6-81c6-1dee3594792e.png)

**Comment by L3V147H4N** [comment]
is this solved?

**Comment by jquense** [comment]
yup. should be in next release

**Comment by L3V147H4N** [comment]
:+1:

**Comment by MrBemd** [comment]
I tried the new release (3.4.5), but the text still remains in the input field. Do I have to add a specific property to activate this behaviour?

**Comment by Bublikus** [comment]
onBlur: () => props.input.onBlur()
instead of:
onBlur: props.input.onBlur
