### ISSUE TITLE
(Usability) Starting the Date Picker with upper (final) view and drill down to the (initial view) date/time

### ISSUE THREAD

**Issue by kromit** [jquense/react-widgets#426]
I have a usability problem with the date time picker.

I my case I always have to set different year, month and date. The current approach requires the user to click 2 times on the header every time to go to the upper view:  "month" ->"year"->"decade". Many user do not understand this.

The desired view order on click would be "month" ->"year"->"decade" in this case. Is there any way to achieve this?

**Comment by jquense** [comment]
sorry not sure I understand the question here, What are you trying to achieve?

**Comment by kromit** [comment]
I am trying to prevent the header clicks. To reproduce you can simple open the default date picker and click 2 times on the calendar header. You can see the "decade" view. I want this view shown as the first view. So every further selection opens the previous view.

**Comment by jquense** [comment]
sounds good to me, but does the initialView not allow this already?

**Comment by kromit** [comment]
Nope. `initialView` opens up as the first view, but it closes directly when you select a value and a previous view does not open up.  If our date is say  "2001-11-22" and you select "2002" from "decade" `initialView`then the chooser closes and leaves you with "200**2**-11-22" without a chance to select the month and date.

Look here: https://jquense.github.io/react-widgets/docs/#/datetimepicker/initialView
It is not possible to select the date.

I think one way to work around this would be to have something like this
`viewList = {["month","year","decade"]}`
So the user would always start with the left and end with the right view.

**Comment by facto** [comment]
@jquense I have the same requirement and I'm willing to submit a pull request if it's something you're open to.

Braindump of some ways to do this:

* Allow `initialView` to be higher than `finalView`. This would allow starting the picker at, say, "decade" then progressing to "month". I think this is the most straightforward way.
* Implement another prop, called `progression` or `viewList` or something else, that takes an array. If this is present, it would start at the view specified by the first element and proceed to the last as the user selects. There would need to be checks in place to ensure it is a valid progression and doesn't go outside the bounds of `initialView` and `finalView`. This option seems unnecessarily complicated to me and I think would be confusing to use.

Thoughts?

**Comment by facto** [comment]
I realize now I may have misunderstood the requirements of the initial poster. My suggestion would not solve their problem exactly. But it would allow for a progression that does not require clicking the header, which can be confusing to users.

**Comment by jquense** [comment]
I think both of y'all requirements are met by the new behavior in v4, it's nit in the most recent beta but it essentially allows you to both specify which views are allowed and what the start view is (regardless of the ultimate 'bottom' view)

**Comment by facto** [comment]
Cool! Any chance you could provide a sample usage, which props to pass, etc.?

**Comment by DarthJonathan** [comment]
Any updates on this?
