### ISSUE TITLE
Does react-widgets support to import the 'react-widget' less file directly and re-value a variable, then it take effect on the webpage control without any css compiling?

### ISSUE THREAD

**Issue by ZhangScott** [jquense/react-widgets#432]
Hi Jason.

I am developing the 3rd party web control, and using the 'react-widget'. Currently I would like to customize my control via overwriting the less variables, other than overwriting css directly, it makes more succinct in code. My question is that is it possible to import the 'react-widget' less file directly and re-value a variable, then it take effect on the webpage control without any css compiling?

Additionally, I have tried @import '../../../node_modules/react-widgets/lib/less/bootstrap-theme.less'; and set the variable value, but it does not take effect. Did I miss some important steps?

Thanks,
Yuxiong

**Comment by jquense** [comment]
this is both possible and encouraged. if you are have trouble doing so I'd make sure your import is correct and you are setting the right variables.
