### ISSUE TITLE
Warning with React 15.3.0

### ISSUE THREAD

**Issue by maps82** [jquense/react-widgets#437]
There are minor warnings together with react 15.3.0: 

``warning.js?8a56*:44Warning: You are manually calling a React.PropTypes validation function for the `format` prop on `DateTimePickerInput`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.``

**Comment by microdou** [comment]
The warning also comes from `value` prop on `Multiselect`

**Comment by jquense** [comment]
yup! just had a new baby tho so might be a bit. PR's welcome

**Comment by microdou** [comment]
@jquense Congratulations!

**Comment by jonathanredtag** [comment]
So this squills fork commit fixes the 15.3.0 warning?

**Comment by arnogeurts** [comment]
That is what is supposed to do, but it is still work in progress

**Comment by maps82** [comment]
I know you are working on 4.0, but it would be nice to have another 3.x release working with react 15.3. I submitted a PR #444 with an additional fix, based on @arnogeurts Fix.

**Comment by jonathanredtag** [comment]
Awesome! When will this be in NPM for update? Thanks
