### ISSUE TITLE
Css refactoring

### ISSUE THREAD

**Issue by skulden13** [jquense/react-widgets#438]
Hello!

We are using your widget. Thanks you for your great job!
But I noticed, that the widgets css isn't quite good and we can try to improve it.

1) https://github.com/jquense/react-widgets/blob/master/src/less/bootstrap-theme.less
I think, here is better to include the bootstrap via npm and just override needed variables.
Also, here we can use some mixins from bootstrap code. https://github.com/jquense/react-widgets/blob/master/src/less/mixins.less#L80

2) I noticed you're using FontAwesome for icons. Maybe better way is to use original namespaces? `fa fa-caret-down` instead of `rw-caret-down`. Some sites have been already using FontAwesome and it will be double loading.
https://github.com/jquense/react-widgets/blob/master/src/less/icons.less#L26

3) Also, I noticed an extend using. Maybe, it's better to avoid it?   
https://github.com/jquense/react-widgets/blob/master/src/less/selectlist.less#L7

4) Also, an unnecessary nesting exists in code. We can try to avoid it. https://github.com/jquense/react-widgets/blob/master/src/less/datepicker.less#L106
That selectors are hardly overridden and very complex. He we can simply use `.rw-off-range { ... }` 

5) We can avoid using a vendor prefixes by implementing the autoprefixer plugin. It helps to reduce the code. https://github.com/jquense/react-widgets/blob/master/src/less/core.less#L36

6) What about the moving that code to appropriate files?https://github.com/jquense/react-widgets/blob/master/src/less/core.less#L373-L376
It solves issue, when someone needs only a some of the components, but not all of them. E.g. he wants to use the Datepicker or the Combobox and no needs other components and css for them.

What you think about that changes? Let me know.

Thanks!

**Comment by skulden13** [comment]
Oh, I see. The legacy code maintenance and refactoring is complicated.
Btw, v4 is a good news!

Maybe, this will be useful link for your future refactoring. This is one of the good approaches for UI component building. https://github.com/suitcss/suit/blob/master/doc/STYLE.md.

Thanks for the feedback!

**Comment by jquense** [comment]
feel free to check out what the code looks like in the v4 branch, or try it by installing react-widgets@next
