### ISSUE TITLE
Warning with react 15.3

### ISSUE THREAD

**Issue by Xurma2** [jquense/react-widgets#443]
> warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the `finalView` prop on `Calendar`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by schinsue** [comment]
This is also for DateTimePicker.

**Comment by lochstar** [comment]
Seems to be resolved in 3.4.4.

**Comment by erikthinkiq** [comment]
I'm getting this warning when creating a DateTimePicker using the latest React (15.3.1) and the latest React Widgets (3.4.4) in the function customPropType.

**Comment by thekarel** [comment]
I see the warning with React Widgets 3.4.4 and React 15.3.1
