### ISSUE TITLE
DateTimePicker editFormat is not used for edited date parsing

### ISSUE THREAD

**Issue by kromit** [jquense/react-widgets#450]
I have the following `DateTimePicker`

```
 DateTimePicker
         time={false}
         format={'DD. MMMM, YYYY'}
         editFormat={'DD.MM.YYYY'}
         {...fields.myDate}
/>
```

When using dropdowns the da is set correctly.
When changing the date manually the date resets to wrong values.
i.e.: Manually entered `02.03.2004` resets to `02.01.2003`

**Comment by jquense** [comment]
I tried this locally and it was working, are you sure you aren't handling the value oddly in your code?

**Comment by kromit** [comment]
yes I am sure, because I've checked the incoming value of the `onChange`. It is correct on dropdown selection but messed up on manual input.
