### ISSUE TITLE
NumberPicker step with callback

### ISSUE THREAD

**Issue by Binck360** [jquense/react-widgets#452]
I would like to extend the NumberPicker so that I can determine the step size based on the current value and whether we're going up or down. The way I would like to implement it is to change the step prop to also allow function in the form:

```
function nextStep(currentValue, isUp) {
    return [nextValue];
}
```

That way the client component can opt-in and have full control on the stepping logic.

What do you think?

**Comment by jquense** [comment]
hi there. you have all this info without needing a callback already. if you control `value` with onChange you can also change the step when the value changes

**Comment by Binck360** [comment]
Hi, indeed we could but the problem with that solution is that you cannot distinguish between pressing the stepper button / keys and manually entering a value outside of the step. So say you give a step value of 5 the user would not be able to enter a value like 3.

Maybe I'm missing something :smile: 

See #453

**Comment by jquense** [comment]
that's true, though I think the more general solution then is to add that information to the onChange event or add an onSelect event. that way folks can do things in response to spinner clicks apart from just changing the step

**Comment by Binck360** [comment]
Ok fair enough, I'll make the changes in the pull request
