### ISSUE TITLE
Cannot clear DropdownList/Multiselect values (using MobX)

### ISSUE THREAD

**Issue by foxhound87** [jquense/react-widgets#456]
Using MobX for state management, the UI is not updated when I clear the values to empty string/array from a button. MobX should re-render the component with the empty values, but the last values are still displayed.

**Comment by jquense** [comment]
if you are setting any value besides `undefined` to `value` it should work, do you have a reproduction I can look at?

**Comment by foxhound87** [comment]
I'm using react-widget for the demo of this repo:
https://github.com/foxhound87/mobx-react-form

If it's not annoying to run the demo, you can follow few simple steps reading `/demo/README.md`.

When you click the reset/clear buttons (which calls the methods reset/clear in `/src/Fields.js`) the values should change. 

thanks for your help.

**Comment by jquense** [comment]
you aren't controlling the inputs, thats why they aren't resetting. `defaultValue` works the same way for the widgets as it does for the html form inputs `input`

**Comment by foxhound87** [comment]
you just made me realize that I wasn't using `value` but `defaultValue` . 
Now it works! Thanks for the support!
