### ISSUE TITLE
escape key should not kick off search

### ISSUE THREAD

**Issue by schutterp** [jquense/react-widgets#46]
I've put some DropdownList components into a react-bootstrap modal and an error is thrown when the escape key is pressed while a DropdownList component is closed and has focus.

TypeError: "Cannot read property 'next' of undefined" is thrown in the component's `search` method.

The search method sets a timeout that expects the component to have a `refs.list` but `refs.list` does not exist because the modal has already closed and the modal and all of it's contents were removed from the DOM.

I'm thinking the escape key should do nothing when the dropdown list is in a closed state. What are your thoughts?

**Comment by jquense** [comment]
Hmm that's interesting, the list should exist even when its closed (hidden but in the DOM). But this issue that definitely seems like the ref is missing. I'll take a closer look thanks for reporting!
