### ISSUE TITLE
In ComboBox, when filtering is on, input cursor keeps jumping to the end

### ISSUE THREAD

**Issue by TianqiZhang** [jquense/react-widgets#461]
I've been using ComboBox, and I noticed that when filtering is on, the input cursor keeps jumping to the end when I input. Every time I press a key, it jumps to the end, which makes it impossible to insert anything in the middle.

**Comment by ingro** [comment]
Any progress/workaround for this one? Thank you.

**Comment by jquense** [comment]
fixed in v4
