### ISSUE TITLE
Multiselect Feature request: Keyboard shorcut Tab

### ISSUE THREAD

**Issue by tonilaukka** [jquense/react-widgets#463]
- Tab should select item, update the list and leave Multiselect open.

I was able to do this feature by wrapping Multiselect in a MultiselectContainer that takes care of the state, but since ListItem doesn't include focused prop I was forced to search to DOM for correct class.

**Comment by jquense** [comment]
tab is generally for moving focus, changing the semantics of it will break the ability to navigate a form with just a keyboard.  the Enter key already handles this, if you want to keep the popup open after select you can use the same wrapper strategy to control open/onToggle to have custom logic there

**Comment by tonilaukka** [comment]
Tab is generally for moving focus, but tab is also for completion and in context where you're filtering/searching the list and Multiselect is open you wan't to complete the search. When multiselect is closed then tab should move the focus to next element.

**Comment by jquense** [comment]
I hear you generally however, tab is _always_ for moving focus in html forms, to such an extent that it's behavior to do is is specced and required, for proper accessibility.  `Enter` on the other hand is not specced, but by convention submits forms _with only one input in them or no submit button_ The most correct action to use here is Space, like a native `<select>`, but that's not possible since it provides a printed character. 

Overall either choice can override a default choice but in this case enter is the lesser of the two evils, so we'll maintain the current behavior

**Comment by tonilaukka** [comment]
I here you on specs and understand your point. Although the spec also states about widgets: "The actual keys are up to the developer, but best practices recommend using the same key bindings that are used to control similar widgets in common GUI operating systems...". And in our case users expect desktop like behavior. I see Google has adopted this also in Inbox and other apps that use Material Design.

That aside. Is there a other way to get the focused element in item list than searching the DOM for correct class?

`const focusedElement = document.getElementsByClassName('rw-list-option rw-state-focus');`

In our use case Enter dispatches an action with the selected items. I wan't the user to be able to select multiple items before dispatching that action. Tab enables the user to select focused item, empties the search term and updates the list.

**Comment by jquense** [comment]
there isn't a way to get the current focused item. The longer term goal is to expose that state as controllable like open or value, but its more complicated than i was hoping and currently blocked byt some other less than ideal architectural stuff. Unfortunately I think the way you are doing it is the best option for now if you need that info.

**Comment by tonilaukka** [comment]
OK. Thanks for the info and awesome repos. ;)
