### ISSUE TITLE
v4 beta - css change

### ISSUE THREAD

**Issue by ArtanisAce** [jquense/react-widgets#464]
Hi @jquense,

I created the issue https://github.com/jquense/react-widgets/issues/428, that is by the way solved in this new beta version! But somehow, my css has changed on my project and dropdowns and fonts don't get overwritten by the custom style scss files I have, do you know how this could happen?

Thanks, great work with the repository! :)

**Comment by jquense** [comment]
i'm not sure but I don't think it's something wrong with the css structure, make sure you are requiring it in the right order?

**Comment by ArtanisAce** [comment]
Hi jquense,

I have seen that the structure of the rw components has changed quite a bit, aswell as some classes; so I just refactored the CSS I had to overwrite default rw styles. Will close the issue, thanks! :)
