### ISSUE TITLE
SelectList seems to be generating one extra blank item

### ISSUE THREAD

**Issue by melinath** [jquense/react-widgets#465]
I've set up a SelectList in my redux-form powered component, but I'm running into a problem. The values being sent to ReduxForm always include one blank string in addition to the actual value. I.e. 
```
[
    "",
    {<MyObject1>},
    {<MyObject2>},
]
```

This is with 3.4.4. I've confirmed that the `data` attribute being passed in to provide the options is correct (there's no weird third option). There's also no third rendered list. To me this looks like it's intended to be a "blank" option, but I'm having trouble finding a place in the code where that might be added - and besides, there's no reason I can see for it to be selected.

This is a multiple select list (which was probably obvious but just to be explicit.)

**Comment by melinath** [comment]
Okaaaaay... why was this closed? I just ran into this again and upgraded to 3.4.5 to try to fix it. It didn't fix it. Is this fixed on 4.0 beta? Help?

**Comment by melinath** [comment]
Update: Not fixed in 4.0.0-beta.3, at least.

**Comment by jquense** [comment]
sorry, I can't do much without a production, but I've never seen this behavior myself. I would think that it's related to how reduce form injects props.  there is no "blank" option code in the widgets so it's not that :/

**Comment by melinath** [comment]
@jquense thanks for the update. I'll see if I can make a test case tomorrow. I imagine you're right that it's a bug in our code.

**Comment by melinath** [comment]
Unfortunately this seems to be a heisenbug. I can no longer reproduce it. :-/
