### ISSUE TITLE
readOnly input in DateTimePicker will be disabled calendar button

### ISSUE THREAD

**Issue by tclyit** [jquense/react-widgets#466]
I'm new to react-widgets DateTimePicker and wondering if this can have an option readOnly for calendar input. As I see in the code, if I provide readOnly proptype then this will be disabled also calendar button.

In line 203, the calendar button take readOnly value as disabled.

disabled={!!(disabled || readOnly)}

**Comment by jquense** [comment]
not quite sure what you're looking for but you can disable the calendar by passing `calendar={false}`

if you are wondering whether you can disable text input and only allow the buttons, that is not possible right now out of the box

**Comment by tclyit** [comment]
The idea is to allow user to select date in calendar but not typing or editing date in input box.
I do appreciate very much for your prompt reply.

**Comment by MitchWeiss** [comment]
Slightly hacky, but in ```componentDidMount()``` I do the following to set the input to readOnly without disabling the calendar

```
const widgets = document.getElementsByClassName("rw-input");
for (let i=0; i<widgets.length; i++) {
  widgets[i].readOnly = true;
}
```
