### ISSUE TITLE
DateTimePicker calendar is messed up when a timezone is set

### ISSUE THREAD

**Issue by dmt0** [jquense/react-widgets#467]
I know that timezones are not officially supported by the widget, but it would be great if there was no undefined behavior when one is set.

When I'm setting timezone in a component like so:

```
 Moment.tz.setDefault(newProps.fields.timezone.value)
```

to anything other than Eastern, the calendar behaves funny. Weeks row goes from Sat to Fri and dates are off by one (e.g. when selecting 21st, 20th get selected)

![screen shot 2016-09-20 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/2717746/18686191/0e012a52-7f49-11e6-8524-1b3e19c764d6.png)

**Comment by jquense** [comment]
I'm not actually sure there is anything I can do about this. The widget needs to create Date objects internally, and I think that's where it looses the TZ info. I don't use moment TZ though some I'm not really sure what might be causing the issue. IF you'd like to pin it down to some specific places where the code is actly badly i might have a better sense about how to fix it

**Comment by lorinkoz** [comment]
@dmt0 Any workaround?

**Comment by siropkin** [comment]
See workaround here: https://github.com/jquense/react-widgets/issues/515
