### ISSUE TITLE
Option to change the input type?

### ISSUE THREAD

**Issue by mattdell** [jquense/react-widgets#469]
I've got a requirement from my client to have all inputs on their site use the HTML5 type attributes which would allow for the use of native controls on mobile devices. This is fine for most of the inputs but I'm using this library for the DatePickerInput component. I've looked through the code and in Input.js there is...

```
  Input.prototype.render = function render() {
    var _props = this.props;
    var className = _props.className;
    var disabled = _props.disabled;
    var readOnly = _props.readOnly;
    var value = _props.value;
    var tabIndex = _props.tabIndex;
    var _props$component = _props.component;
    var Component = _props$component === undefined ? 'input' : _props$component;

    var props = _objectWithoutProperties(_props, ['className', 'disabled', 'readOnly', 'value', 'tabIndex', 'component']);

    return _react2.default.createElement(Component, _extends({}, props, {
      type: 'text',
      tabIndex: tabIndex || 0,
      autoComplete: 'off',
      disabled: disabled,
      readOnly: readOnly,
      'aria-disabled': disabled,
      'aria-readonly': readOnly,
      value: value == null ? '' : value,
      className: (0, _classnames2.default)(className, 'rw-input')
    }));
  };
```

@jquense how would you feel if I were to add a prop to DateTimePicker to allow us to specify the input type as date?

**Comment by jquense** [comment]
that won't work really, you will get all the extra buttons for the date input including the calendar or time buttons, individual to the same buttons from the datetime picker. 

if you want to conditionally use the native e inputs on mobile I suggest conditionally rendering them instead of the widget in those situations
