### ISSUE TITLE
IE8 incompatibility (dropdowns dont close)

### ISSUE THREAD

**Issue by vladimir-rovensky** [jquense/react-widgets#47]
Hello guys

The current version (2.2.4) doesn't seem to work in IE8, there's an exception in util/dom/css.js line 36, causing dropdowns not to close.

Strangely enough, the code is different in src and in libs - in src it looks like the issue is fixed, but not in libs. Furthermore, the 2.2.4 commit modified a ton of files in libs, but not css.js. I didn't look at the build process, but this seems like maybe some build step was omitted or something.

Could someone please look into this?

**Comment by jquense** [comment]
Hi there, 

thanks for the heads up, sorry about the regression, the issue is in that the transpiler started outputting non ie8 safe code due to a simplification I made. I'll have it fixed and updated in a few
