### ISSUE TITLE
How I can change shortcuts in multiselect?

### ISSUE THREAD

**Issue by Xurma2** [jquense/react-widgets#470]
I need remove `delete` and `backspace`;
Delete only by x button

**Comment by jquense** [comment]
the widgets respect `preventDefault()` in event handlers so if you want to short circuit the keyboard behavior, you can add an `onKeyDown` and prevent default for the right keys.

I would caution that tho, that will make it much harder for anyone to use the widget without a mouse, which is bad for productivity and accessibility
