### ISSUE TITLE
Alt-*  browser shortcuts don't work when DateTimePicker has focus

### ISSUE THREAD

**Issue by theprash** [jquense/react-widgets#471]
The Alt-Left, Alt-Right and Alt-Home shortcuts at least don't work when DateTimePicker has focus. [This bit of code](https://github.com/jquense/react-widgets/blob/v3.4.4/lib/DateTimePicker.js#L444) looks suspect:

``` javascript
    if (e.key === 'Escape' && open) this.close();else if (e.altKey) {
      e.preventDefault();
```

**Comment by jquense** [comment]
working in v4. may be fixed in v3

**Comment by theprash** [comment]
Thank you!

cc @jpb12
