### ISSUE TITLE
itemComponent aka timeComponent not working

### ISSUE THREAD

**Issue by AgamlaRage** [jquense/react-widgets#472]
Hi,

I use **react-widgets@3.4.4** and I notice that the options **timeComponent** aka **itemComponent**, is not working.
I can't set a custom format to my timelist items like in your demo.

[http://jquense.github.io/react-widgets/docs/#/datetime-picker?_k=pberim](http://jquense.github.io/react-widgets/docs/#/datetime-picker?_k=pberim)
![sans titre](https://cloud.githubusercontent.com/assets/15155827/19009437/400376bc-8774-11e6-96e2-05e2b28055a1.png)

To be really sure, I downloaded the react-widget git to try this demo in local.
Same result, I was unable to use this options.

There are missing code in **src/TimeList.jsx**
The declaration of **itemComponent** is well made, but the props is not passed to the child component **<List/>**

I'm not familiar with push/pull request, then sorry for that.

**Here is the changes I made in the demo to make it works :** src/TimeList.jsx
- **line74** `let { value, onSelect, itemComponent } = this.props; // add itemComponent`
- **line80** `itemComponent={itemComponent} // add new props to <List/> declaration`

**Here is the changes I made in my app to make it works :** node_modules/react-widgets/lib/TimeList.js
- **line94** `var itemComponent = _props.itemComponent; // add itemComponent`
- **line101** `itemComponent: itemComponent // add new props to <List/> declaration`

**Comment by brandonfancher** [comment]
I second this.
