### ISSUE TITLE
DropdownListInput - placeholder is not shown for empty value

### ISSUE THREAD

**Issue by ondrejkralik** [jquense/react-widgets#474]
We use `DropdownListInput` as a field which is not required.
Placeholder works well for this component **except case that the value has an empty key and an empty title** (this means that user wants select "nothing")

Example of use:

```
const _options = [
    { key: '', title: '' },`
    { key: 'one', title: 'One' },
    { key: 'two', title: 'Two' }
];

<DropdownList
     data={_options}
     value={this.state.value}
     valueField="key"
     textField="title"
     onChange={this.handleOnchange.bind(this)}
/>
```

I improved logic of code which shows placeholder in [my repo](https://github.com/ondrejkralik/react-widgets/commit/e16e367c5845c68c3a6a44d96f7d36da86531d1a).
I'm not sure if it is good enough for PR, so I'm writing only this issue.

**Comment by jquense** [comment]
in retrospect I think that this isn't a bug but the more correct behavior. in your case a value is selected, even tho the shown value is  and empty string. To support this case i'd actaully clear the value onChange and the value is your "empty" data item.
