### ISSUE TITLE
react-widgets + webpack + bower = moment is not defined

### ISSUE THREAD

**Issue by evpozdniakov** [jquense/react-widgets#475]
First of all, react-widgets worked properly as node module. Then we decided to move from npm to bower.  It didn't go well. We're unable to make `momentLocalizer` working properly.

![image](https://cloud.githubusercontent.com/assets/1109345/19132888/a704ac0c-8b23-11e6-9edf-ee9ee2976cd6.png)

Here you are the line of code, producing the error.
https://github.com/jquense/react-widgets/blob/master/dist/react-widgets-moment.js#L50

We tried to make `moment` library global, but it didn't fix the issue.

May be we are trying to use wrong file? May be we should use
https://github.com/jquense/react-widgets/blob/master/lib/localizers/moment.js
instead of
https://github.com/jquense/react-widgets/blob/master/dist/react-widgets-moment.js
?

**Comment by jquense** [comment]
you have the right file, it expects that `window.moment` be there make sure you set it to the window global before you load the localizer script

**Comment by evpozdniakov** [comment]
We tried `ProvidePlugin` to  make moment available in every module.

	new webpack.ProvidePlugin({
		'moment': 'moment',
	})

It fixed the previous error, but gave another:

![image](https://cloud.githubusercontent.com/assets/1109345/19152100/55c56bda-8b9e-11e6-97ec-6f30728767a1.png)

**Comment by jquense** [comment]
The bower build is really meant for folks including the library in a script tag, old school. Hence the `main` points to the compiled `dist/` files which expect globals of all it's dependencies. If you are using modules and webpack (but not npm??), require the library directly from `lib`. I can't say know that any of that will work though, as we really only support distributing common js modules via npm.

**Comment by evpozdniakov** [comment]
There is a way to make it working, but it requires a few changes.

1. Wrap current code into helper function used in react-widgets.js (lines 2 - 11)

2. Replace piece of code
	var module = __webpack_require__(1);
	var args = [moment];
	if (typeof module === 'function') {
		module.apply(null, args || [])
	}
by
	module.exports = __webpack_require__(1);
	var args = [window.moment];
	if (typeof module.exports === 'function') {
		module.exports.apply(null, args || [])
	}

3. Use webpack ProvidePlugin:
	new webpack.ProvidePlugin({
		'window.moment': 'moment',
		'window.ReactWidgets': 'react-widgets',
	}),
