### ISSUE TITLE
When widget get unmounted, it still trying to setState() after close animation

### ISSUE THREAD

**Issue by chaintng** [jquense/react-widgets#476]
I programatically unmount the DropDown widget after user select using `onChange` property.

However, i got error in my Chrome console stating that

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Popup component.`

It's because there is an attempt when animation is closing trying to`setState()`.
It starts from this function
https://github.com/jquense/react-widgets/blob/master/src/util/dom/animate.js#L66

to this function
https://github.com/jquense/react-widgets/blob/master/lib/Popup.js#L248

Please advise

**Comment by jquense** [comment]
dup #428
