### ISSUE TITLE
what should onSearch return

### ISSUE THREAD

**Issue by Jan-Jan** [jquense/react-widgets#477]
1st thanks for react-widgets!

This is actually two questions in 1:

1) What should I return from `onSearch=` function? I tried an array of objects, but that doesn't work, I tried an object with key data for the array... (I test the array, it works fine if I pass it in via `data=`. I also tried using `data={this.state.data}`, and having the `onSearch` update the `state.data`, but that also didn't work)

2) Can I still use `onSearch` with Promises? If so any recommendations?

**Comment by Jan-Jan** [comment]
The error msg I see is `The filter returned no results`

**Comment by jquense** [comment]
onSearch doesn't return anything, it is a callback with the current value of the searchTerm, it doesn't change or adjust the data.

Filter behavior/logic is managed by the `filter` prop which accepts a function (see the docs). It doesn't support async filtering.

**Comment by Jan-Jan** [comment]
So I tried using searchTerm to change the data that I'm feeding the component `<Multiselect data={this.state.data}`, but that didn't work. Should I proceed with that?

**Comment by jquense** [comment]
something like this probably
```js
class MyMultiselect extends React.Component {
  search = (searchTerm) => {
     this.setState({ data: runMySearch(this.state.data, searchTerm) });
  };
  render() {
    return (
      <Multiselect
         data={this.state.data}
         onSearch={this.search}
         filter={false}
      /> 
  }
}
```

**Comment by Jan-Jan** [comment]
Thank you very much. I had all of that, but not `filter={false}`. It made all the difference.
