### ISSUE TITLE
NumberPicker: If min attribute is set there is no possibility to reenter value

### ISSUE THREAD

**Issue by novak-p** [jquense/react-widgets#478]
Hello,

if the NumberPicker has set min value and value is changed under min value, there is not possible to reenter same value.

For example:
_min=2015, value=2020 => Press backspace in input, the value looks like 202, press 0 again - nothing is happen._

You can try it in your example here: http://jquense.github.io/react-widgets/docs/#/numberpicker/min?_k=y7prya

**Comment by jquense** [comment]
should be fixed (or fixed in v4)
