### ISSUE TITLE
Dropdown open animation removal / change duration

### ISSUE THREAD

**Issue by Aidurber** [jquense/react-widgets#479]
Hi, 

I would like to remove the animation for the dropdown or even reduce the duration it takes to open. 

Where in the code can I find this? I will be more than happy to create a PR, adding another prop the developer can override. 

Unless you can think of a way of doing this without modifying the existing API?

**Comment by jquense** [comment]
`<DropdownList duration={0} />` should work

**Comment by Aidurber** [comment]
Ahh, thanks @jquense, much appreciated!
