### ISSUE TITLE
DatePicker - cannot clear value

### ISSUE THREAD

**Issue by vladimir-rovensky** [jquense/react-widgets#48]
Hello

I stumbled upon a bug in the datepicker's behavior:
1) Start with a datepicker with no value.
2) choose a date using the dropdown calendar.
3) immediately clear the value in the text input box (without leaving the text input).

From now on, the datepicker keeps displaying the value picked in 2) and the user cannot clear it (when I clear the text input, onChange does not get called).

Can be reproduced on the DOC page demos.

**Comment by jquense** [comment]
Thanks for the issue,

I have been able to reproduce this, so I'll see what I can do to get it fixed quickly. It seems that the only problem is going from `null -> select a date -> erase date without losing focus`. You can break the weird state by selecting a new date from the dropdown, as an immediate work around
