### ISSUE TITLE
DateTimePicker closes when reaches the last month

### ISSUE THREAD

**Issue by andrepcg** [jquense/react-widgets#481]
I came across a bug when you define a max date to DateTimeInput and the component is very deep in the components tree.

I don't know exactly how it occurs but the only thing that I can do to reproduce the bug is put it deeper inside the components. The exact bug is related to onBlur that is activating when I press the right arrow in the month _before_ the last one.

i.e. max date is set to October 20 2016. If I navigate to september by clicking the left arrow (not on the keyboard) then to august then back to september, everything works fine. As soon as I navigate from September to October the calendar closes and it is related to the Timeout/Focus mixins (they are the ones who call `close()`).

GIF: http://g.recordit.co/KL7UWGzoy3.gif

**Comment by brandonfancher** [comment]
I'm running into the same problem.
