### ISSUE TITLE
No Event for User Typing into Multiselect

### ISSUE THREAD

**Issue by BigPrimeNumbers** [jquense/react-widgets#482]
Is there a way to get an event to fire each time the user enters a character into the `Multiselect`? Right now it appears that the `onChange` event only fires when the user types something and then presses the `Enter` key.

Because of this, there does not be a way to programatically clear plain text in the field without refreshing the page.

**Comment by jquense** [comment]
onSearch is what you want I think

**Comment by BigPrimeNumbers** [comment]
Unfortunately, `onSearch` never seems to fire for me. My use for the widget is to simply make pills out of words in a string that are separated by a delimiter (for which it works great, making the words much more readable!). Initially the code for my component is: 

```javascript
               <Multiselect
                    id={this.props.id}
                    ref={this.props.id}
                    disabled={this.props.disabled}
                    value={this.props.value}
                    placeholder={this.props.placeholder}
                    onChange={this.onChange}
					autoComplete={this.props.autoComplete}
					autoCorrect={this.props.autoCorrect}
					autoCapitalize={this.props.autoCapitalize}
					spellCheck={this.props.spellCheck}

			        onBlur={this.props.onBlur}
			        onFocus={this.props.onFocus}
	                theme={this.props.theme}
			        delimiter={this.props.delimiter}
			        valueField={this.props.valueField}
			        textField={this.props.textField}
			        data={this.props.data}
			        groupBy={this.props.groupBy}
			        tagComponent={this.props.tagComponent}
			        itemComponent={this.props.itemComponent}
			        groupComponent={this.props.groupComponent}
			        readOnly={this.props.readOnly}
			        isRtl={this.props.isRtl}
			        messages={this.props.messages}
                />
```
And adding `onSearch` does nothing to capture the user typing, though it does works well for my other purposes. I just need a way to alert its parent component when its content is changing through typing (again, hitting `ENTER` after typing fires the `onChange` event, and works as expected).

**Comment by jquense** [comment]
not sure why its not firing for  you, you might be spelling it wrong?

adding `onSearch={v => console.log(v)}` to any of the documentation examples (you can try it) prints every letter as it's typed to the console.

**Comment by BigPrimeNumbers** [comment]
Is there anything in the component's declarations - either missing or added - that I've got above that could prevent it from firing? I tried setting both the `searchTerm` and `defaultSearchTerm` in conjunction with using `onSearch` as well, and it still doesn't fire :/

**Comment by BigPrimeNumbers** [comment]
This widget also doesn't have a state, and displays only what is passed in from `props`. When `onChange` fires, it updates its parent component which then passes the new value back down to the widget, though I don't see how that would preclude `onSearch` from firing. There is also no array for the widget to search through in my current use, as it only displays a string in pill form (like I mentioned before). Could that break something possibly?

**Comment by jquense** [comment]
I mean i don't see `onSearch` in your component above. it's definitely firing, if it wasn't you wouldn't see the text change in the widget.

**Comment by BigPrimeNumbers** [comment]
Yep it's not in the original implementation (which is what is above, though I can toss it into the code to example to be more clear), but in my tests I've added it, the `searchTerm`, and `defaultSearchTerm` in different combinations to attempt to get it to fire, but to no avail.

**Comment by BigPrimeNumbers** [comment]
At some point recently I changed something somewhere that causes `onSearch` to fire now, which is a step in the right direction. The problem is, I still don't seem to have a way to clear text that has been typed into the `Multiselect` field, but not yet turned into a pill. 

E.g. a user is typing something into the field, stops and decides to reset the form, clicking a button I've created that clears all fields. All fields then are sent empty props (and their states' cleared) and this removes anything in them, except the `Multiselect` field (even though its state has been cleared, as well as its value props); any text that had been inputted remains.

**Comment by jquense** [comment]
set `searchTerm` to an empty string

**Comment by BigPrimeNumbers** [comment]
That did it. Thanks for the help!

**Comment by jquense** [comment]
np, glad you got it sorted!

**Comment by AndreyPatseiko** [comment]
<MultiSelect 
          filter={false}
          onSearch={() => {}}
          searchTerm=''
    />
