### ISSUE TITLE
React PropTypes Warning

### ISSUE THREAD

**Issue by erikthinkiq** [jquense/react-widgets#483]
I'm getting this warning when creating a DateTimePicker using the latest React (15.3.2) and the latest React Widgets (3.4.4) in the function customPropType. Same issue as closed issue #443.

react.js:20478 Warning: You are manually calling a React.PropTypes validation function for the `value` prop on `DateTimePicker`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

printWarning    @   react.js:20478
warning @   react.js:20502
checkType   @   react.js:13184
(anonymous function)    @   react-widgets.js:3747

**Comment by eriklharper** [comment]
This issue went away for me once I upgraded `react-widgets` to `3.4.5`.  I'm running React `15.4.2`
