### ISSUE TITLE
Confusion about valueField in DropdownList

### ISSUE THREAD

**Issue by jole78** [jquense/react-widgets#484]
I'm using the DropdownList component with a structure that looks like this:

` const categories = [{key:"some_key", value:"some value"}...]`

Now I'm using this together with redux-form like this:

````javascript
				<Field
					name="title"					
					component={DropdownList}
					data={categories}
					valueField='key'
					textField={item => capitalize(item.value)} />
````

I was expecting that when onChange is fired I'd get back the valueField (the value of the 'key' prop) but actually I'm getting the whole model which is a bit confusing or am I doing something wrong here??

Looking here http://redux-form.com/6.0.0-alpha.15/examples/react-widgets/ it's working like expected...but maybe that's an older version perhaps (I'm on 3.4.4)

**Comment by jquense** [comment]
change is always fired with the whole model (if possible), `valueField` is a way to tell the widget how to identify models, (like primary key), it's not always necessary, but allows you to set `value` just an `id`, or another object, without needing referential identity with something in `data`.

If you are only interested in that key however, i'd suggest mapping to it in your onChange when defining the Field input (like `onChange={ item => props.onChange(item.key)}`)

**Comment by jole78** [comment]
OK, so that works (thanks for that)...but look here http://redux-form.com/6.0.0-alpha.15/examples/react-widgets/ 

There it works like expected...has that behavior changed? To me it would be nice if I could do that decoratively instead of needing to override onChange and basically building it myself. 

This is what I ended up with:
````javascript
import React from 'react'
import {DropdownList} from 'react-widgets'

const FormFieldDropdownList = (props) => {
	const {input, valueField} = props

	function handleChange(item) {
		let value = item

		if(valueField) {
			value = item[valueField]
		}

		input.onChange(value)
	}

	
	return (
		<DropdownList {...props} {...input} onChange={handleChange} />
	)
}

export default FormFieldDropdownList
````

**Comment by jquense** [comment]
I tend to think it is declarative :P but moreso I don't know that complicating the API more is helpful _here_ since most serious use of the widget set will involve having app specific wrappers anyway. Generally in apps i use them, I create local wrappers (even just re-exports) for this sort of thing, since its unlikely the core set will be able to meet _every_ need of a user. 

per the form, the behavior hasn't changed, I've not actually ever used redux-form some i'm not sure, but maybe it automatically extracts keys called `'value'`?

**Comment by jole78** [comment]
Point taken and I basically agree. Maybe documenting this would help others in the future then...as a recommended best practice. Closing issue

**Comment by fgiarritiello** [comment]
@jole78 Did you find a solution to this without using the handleChange. I'm running into the same problem

**Comment by jole78** [comment]
@fgiarritiello nop, doing it with an onChange handler
