### ISSUE TITLE
Invalid Date or Time results in DateTimePicker being blank

### ISSUE THREAD

**Issue by pbromley** [jquense/react-widgets#485]
If the input has a defaultValue set then changing the value to something valid e.g.

```
10/17/2016 16:45
```

works and the input shows the new value (10/17/2016 16:45)

However if i try an invalid date

```
10/32/2016 16:45
```

or an invalid time

```
10/17/2016 16:65
```

The input field becomes blank. 

Ideally I think the input should show the last 'good' date, or at least behave as though the input has not been completed e.g.

```
10/17/2016 16:
```

on exit of the field jumps back to

```
10/17/2016 16:00
```

I've tried this locally and on the docs site using Chrome. Locally i'm on v3.4.1

**Comment by KevinNorth** [comment]
I'm running into this problem as well. In addition, once the invalid date is blanked out, selecting another time or date from the widget's popup doesn't work - the text field is left blank after clicking on a date. To get the DateTimePicker to work again, I have to type in a valid date first.

**Comment by jquense** [comment]
ya'll can check the issues for this one in the past, but the tldr is that the current behavior of `null`ing invalid dates isn't likely to cahgne for a lot of technical reasons; the main one being that the input **cannot** know if parsing failed or if `null` was the intended value.

on an individual level you have more knowledge about what and how the dates are being parsed. You can get the behavior you want with a custom parse function or localizer extension. @KevinNorth  the broken behavior your seeing seems different, if you can provide a repo it may be a bug.

**Comment by KevinNorth** [comment]
@jquense Thanks for gettingback to me. I'll look at my own code some more, and if, once I've isolated the problem, it appears to be a bug in React Widgets (as opposed to something silly I'm doing :P), I'll open an issue.
