### ISSUE TITLE
Calendar remove zeros

### ISSUE THREAD

**Issue by jrock17** [jquense/react-widgets#487]
Is there an easy way to remove the zeros in the calendar display?

So instead of "01  02  03..." it just shows at "1  2  3...".

I'm using Moment for localizations but I couldn't figure out any way to format the calendar view.

**Comment by jquense** [comment]
I think you want to change the `dateFormat` prop. you can check the moment docs for witch token doesn't add the leading zeros

**Comment by jrock17** [comment]
Thanks!

dateFormat={"D"}

...worked like a charm.
