### ISSUE TITLE
Bower build?

### ISSUE THREAD

**Issue by uberllama** [jquense/react-widgets#49]
Hey there. Was wondering if you could supply a browser version of this library. I use rails-assets to gemify asset packages so right now using this lib would require manual download and packaging without version control. Cheers.

**Comment by jquense** [comment]
I am a bit reticent to do this...the React ecosystem is pretty standardized around just using npm and commonJS modules. I am unsure of the additional maintenance burden dealing with a bower build you add, but I am not familiar enough with bower to make a judgement off the top of my head. I do want to be helpful tho, and make it as easy as possible to consume this react-widgets. 

Let me take a look around at how others are handling bower packages in the react community and I'll get back to you.

**Comment by uberllama** [comment]
Much appreciated. For the record, large libs like reflux and react-bootstrap do provide bower builds.

**Comment by jquense** [comment]
ya I have seen that! Though in this case I have css to deal with along with a duplication concern with needing to webpack everything up first. It doesn't seem like a big deal as i'm looking at it, but I need to play around with it.

**Comment by austinking** [comment]
Off topic, but `jspm install npm:react-widgets` works out of the box.

**Comment by uberllama** [comment]
We've actually forked this repo as we wanted to utilize moment.js, so we also did our own bower build. Cheers.

**Comment by jquense** [comment]
@uberllama glad you got it working independently. This may not be relevant to you anymore but I think I have it all sorted out so there should be "official" bower support as of the next release.

**Comment by uberllama** [comment]
Awesome. It would be nice if we could merge the forks somehow to choose between globalize/moment, but I'm not sure if that's doable.

**Comment by jquense** [comment]
That is a larger issue, The reason I went with Globalize is that it also included data for localizing/globalizing dates AND numbers (for the number picker). Moment.js is great, but its not tiny and it only does dates (I also am reticent to return, or take as an input a non-native object type, as it can introduce weird compat issues), so it's not likely i'll switch in the near future. 

However, I'd be more than willing to talk about how we can make react-widgets more conducive to use with Moment.js. I'd be very interested to hear what stumbling blocks lead to the fork if you ever want to spare the time in an issue.
