### ISSUE TITLE
Use Globalize message api for localizing react-widgets' messages

### ISSUE THREAD

**Issue by Doff3n** [jquense/react-widgets#492]
The globalize api has a messages api:
https://github.com/jquery/globalize/blob/master/doc/api/message/load-messages.md

It would be great if the messages in the Globalize's messages/en.json would be auto loaded into the react-widgets library.

**Comment by jquense** [comment]
hi there. Something like this is beyond the scope of react-widgets. We only provide messages for english (since its the only language i speak) by default, but all messages are exposed and customizable. You can use the globalize message API to provide them in your app.
