### ISSUE TITLE
onFocus/onToggle issue with DateTimePicker

### ISSUE THREAD

**Issue by jamesmcglinn** [jquense/react-widgets#494]
When using `onFocus`, `onToggle`, and the `open` prop to control the `DateTimePicker`'s behaviour, it works as expected when clicking on the input field or using `tab` to focus. `onFocus` is triggered and the `DateTimePicker` opens as expected, and when clicking out or using `tab` to blur `onToggle` is triggered and the `DateTimePicker` closes.

However when clicking the calendar or time icon to open the `DateTimePicker`, both `onFocus` and `onToggle` are triggered (in non-deterministic order) causing the `DateTimePicker` to open then close immediately.

Is it possible to use `onFocus`, `onToggle`, and the `open` prop but retain the ability to click on the calendar or time icon to open the `DateTimePicker`?

**Comment by jamesmcglinn** [comment]
Checking for a button DOM element in `target.nodeName` appears to work:

```
handleFocus: function(e) {
  if (!(e.target instanceof Node && e.target.nodeName === 'BUTTON')) {
    this.setState({
      open: 'calendar'
    });
  }
}
```

**Comment by MV88** [comment]
@jamesmcglinn  You saved my day, thanks a lot.  (my case was similar with the Combobox component)
