### ISSUE TITLE
@import error with webpack when testing (with Mocha)

### ISSUE THREAD

**Issue by cdmcmahon** [jquense/react-widgets#496]
I am using Mocha to write tests for my application. Any time I try to test a component that uses a widget from this library I am presented with the following error message:

```
<path_to_my_app>/app/node_modules/react-widgets/lib/less/react-widgets.less:1
(function (exports, require, module, __filename, __dirname) { 
@import "./variables.less";
                                                              
^

SyntaxError: Unexpected token ILLEGAL
```

I have the following loaders in my `webpack.config.js`:

```
loaders: [
      { test: /\.js$/, exclude: /(node_modules|bower_components)/, loader: 'babel' },
      { test: /\.json$/, loader: 'json' },
      { test: /\.css$/,  loader: 'style-loader!css-loader' },
      { test: /\.less$/, loader: 'style-loader!css-loader!less-loader' },
      { test: /\.gif$/, loader: 'url-loader?mimetype=image/png' },
      { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff' },
      { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file-loader?name=[name].[ext]' },
      { test: require.resolve('trackjs'), loader: 'exports?trackJs'}
    ]
```

I get no such errors when actually *running* my application, simply when trying to test components that eventually reach this import.

**Comment by jquense** [comment]
no idea...maybe you need to adjust the paths for the less-loader? I'm honestly not sure, what hat cause something like this, but it seems to be mocha related i guess?

**Comment by cdmcmahon** [comment]
I was able to find a similar issue over [on the less-loader repository here, actually](https://github.com/webpack/less-loader/issues/55).

**Comment by cdmcmahon** [comment]
Can you clarify for me what you were suggesting there about adjusting the paths for the less-loader? I appreciate the help

**Comment by cdmcmahon** [comment]
I think you're correct with regards to this not being a react-widgets issue so closing is the right call. For my sanity, could you clarify what your quick suggestion was earlier? I don't need an essay I just didn't understand quite what you meant. Any help is appreciated; this has been quite the frustrating and longstanding issue.

**Comment by jquense** [comment]
if I recall correctly LESS has a concept of "paths" which are directories it looks in to resolve imports. I'm not sure if its still relevant in the webpack context but you can google around maybe on that

**Comment by cdmcmahon** [comment]
Ah, okay. Never worked with LESS personally, but this certainly gives me an avenue to explore. Thanks for your help!

**Comment by jquense** [comment]
you might also try the Sass or plain css if you don't want to use the less, as another option

**Comment by cdmcmahon** [comment]
Wait, can you clarify? Is there a way to install/use react-widgets via npm and defer to the Sass or css options? Or are you referring to importing the styles manually?

**Comment by jquense** [comment]
react-widgets gives you 3 ways to consume the styles. You can just import the whole css file `dist/react-widgets.css` or the sass or less versions of the uncompiled files.

You can import or consume them however you'd like, webpack is just the "simplest" if you already have an app using webpack
