### ISSUE TITLE
Multiselect style display table

### ISSUE THREAD

**Issue by khieu** [jquense/react-widgets#497]
I just started to use react-widgets especially the Multiselect component. When Import the Component and the css with 
```
import 'react-widgets/lib/less/react-widgets.less';
import Multiselect from 'react-widgets/lib/Multiselect';

```
the Multiselect box takes a whole block on the screen. Inspecting the element showed that there's a _display:table_ in .rw-multiselect-wrapper . I wonder if this is a bug, if not then what's they way to work around this and make the multiselect display on 1 line by default and only expand if the options don't fit in the line ?

Thanks.

**Comment by jquense** [comment]
> make the multiselect display on 1 line by default and only expand if the options don't fit in the line

this is the default/normal behavior you can see on the docs site. you might have a conflicting style issue perhaps?

**Comment by khieu** [comment]
@jquense you are right, it was a conflicting style issue in my project ! 😄  Thanks a lot.
