### ISSUE TITLE
[v4] Suggestion: Fully customizable tagComponent in Multiselect

### ISSUE THREAD

**Issue by huan086** [jquense/react-widgets#498]
I would like to customize the background-color, color and border of the tags.

The tagComponent is currently wrapped in `<li>` with it's style.  It would be great if I could inherit from MultiselectTag, customize it, and use it in Multiselect.

**Comment by huan086** [comment]
![multiselect](https://user-images.githubusercontent.com/1448788/27826130-8cf7828e-60e4-11e7-8547-414466b7591d.png)

**Comment by MrJadaml** [comment]
What was the resolution here to be able to customize the tagComponent? -- background and X icon in-all

Currently we have our own Tag component, but the provided prop just appears to wrap around our own, not replace it.

```
const tag = option => <Tag name={option.item} />;

<Multiselect tagComponent={tag} {...rest} />
```

**Comment by MrAkblt** [comment]
i agree, `tagComponent` should be able to control all of 'li' or maybe a new prop can be added like `valueComponent`

**Comment by markerikson** [comment]
Yeah, would love to see this added! Any reason why it was closed?
