### ISSUE TITLE
Linked demo page is 404

### ISSUE THREAD

**Issue by winkler1** [jquense/react-widgets#50]
http://jquense.github.io/react-widgets -- not working

**Comment by jquense** [comment]
im sorry where is that the link located? Its not working because its not correct. The correct doc link is http://jquense.github.io/react-widgets/docs

**Comment by winkler1** [comment]
http://screencast.com/t/aYhMq0y85

**Comment by jquense** [comment]
That's really odd my view doesn't have that link in the description at all...thanks for the heads up
