### ISSUE TITLE
onSearch callback in DropdownList is called even when searchTerm value is NOT changed

### ISSUE THREAD

**Issue by martin-svk** [jquense/react-widgets#500]
Hello, from docs:

**onSearch:**
> Called when the value of the filter input changes either from typing or a pasted value. onSearch should be used when the searchTerm prop is set.

But it fires `onSeach` also when the list just has some initial data and you open it and select a value.
This should result only in calling `onSelect` and `onChange` right?

Thanks

**Comment by jquense** [comment]
the searchTerm is cleared when you select an item which is why it's called. it's a bit noisy tho it fires even if they value is already empty
