### ISSUE TITLE
Multiselect uneven sizes

### ISSUE THREAD

**Issue by Jaikant** [jquense/react-widgets#505]
I am reasonably new. I am using multiselect and I would like the display to look a little bit more even.
Here is what I am seeing - 

<img width="831" alt="screen shot 2016-11-25 at 8 17 42 am" src="https://cloud.githubusercontent.com/assets/3472565/20613242/ff467fb2-b2e7-11e6-9df9-b9cc43a5db39.png">

Can anyone please suggest how to make this look even? I am using redux-form with react-widgets.

**Comment by jquense** [comment]
looks like you have some conflicting styles, that's not what it should look like :P

**Comment by Jaikant** [comment]
@jquense  Thanks for your super quick reply. You are right, it is to do with the style bundled with redux-form.
