### ISSUE TITLE
Feature request: DropdownList should avoid going off-screen

### ISSUE THREAD

**Issue by hjnilsson** [jquense/react-widgets#507]
Right now, the DropdownList component will extend outside the screen if you put it on the bottom of a page. It would be great if the component could detect that the dropdown would go outside the screen, and offset itself vertically to avoid it (like native `<select>` elements do).

You can see the problem here: https://www.bufdir.no/Statistikk_og_analyse/Barnefattigdom/?map=16323&region=Norge (Dropdown is in the lower right on desktop, last option is never visible on-screen)

**Comment by martin-svk** [comment]
What is the current state of this? I have similar problem.

**Comment by jquense** [comment]
Screen edge detection is not a straightforward problem in the general case, especially given how the dropdowns are absolutely, not fixed, positioned. As such i'm not going to try and include such logic in the core library. The widgets do however have a `dropUp` prop which will change the direction the popup opens. You can create your own wrappers that calculation the screen edge in a way that makes sense for your app, and apply that prop as appropriate
