### ISSUE TITLE
After entering an invalid date in DateTimePicker, the DateTimePicker stops changing values

### ISSUE THREAD

**Issue by KevinNorth** [jquense/react-widgets#508]
The following code demonstrates what I believe is a bug:

```
import DateTimePicker from 'react-widgets/lib/DateTimePicker';
import Moment from 'moment';
import momentLocalizer from 'react-widgets/lib/localizers/moment';
import React from 'react';

const parse = function (date) {
  return new Date(date);
};

const BuggyDatePicker = (props) => {
  momentLocalizer(Moment);

  return (
    <DateTimePicker
      parse={parse}
      {...props}
    />
  );
};

BuggyDatePicker.displayName = 'BuggyDatePicker';

export default BuggyDatePicker;

// Render the `BuggyDatePicker` in a React app to see its buggy behavior
```

What happens is that, if a user types an invalid date into the `DateTimePicker`, the text field attached to the component clear out, as expected. But if the user then clicks on the Calendar button and clicks on a date from the popup calendar, the text field does not update with the selected value. Trying to select another date will not work until the user manually types a valid date into the text field again.

In fact, the example for the `parse` prop at https://jquense.github.io/react-widgets/docs/#/datetimepicker demonstrates the same behavior for me. The first `DateTimePicker`, `<DateTimePicker parse={formats} />`, works as expected, allowing the user to select a valid date from the calendar after typing in an invalid date. However, the second `DateTimePicker`, `<DateTimePicker parse={str => new Date(str)}/>`, exhibits the same buggy behavior as my example above.

I am using Chrome 53+.

**Comment by jquense** [comment]
what's happening is that your `parse` function is returning an `InvalidDate` object that is being used as the value from then on. Ideally i should handle that, but in the meantime you're `parse` function should return `null` when the date is bad non `InvalidDate`

**Comment by KevinNorth** [comment]
That seems like it's the problem. Using this function for my `parse` prop made my instance of `DateTimePicker` work like I expected:

```
const defaultParse = function parse(date) {
  const parsedDate = new Date(date);

  if (isNaN(parsedDate)) {
    // isNaN(date) is a convention to determine whether a Date is invalid.
    // See http://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript
    return null;
  }
  return parsedDate;
};
```

Thank you responding to my issue!
