### ISSUE TITLE
Server Side Rendering: Multiselect

### ISSUE THREAD

**Issue by davide-ganito** [jquense/react-widgets#51]
Hi,
i have a server/client checksum problem when i use the Multiselect component.
I am using the component like this:

var data = [
{ id : "1", name : "foo", ...other props },
{ id : "2", name : "bar", ...other props}]

<Multiselect data={data} valueField="id" textField="name" />

On the client is everything ok but if I checkout the source html sended by the server I have noticed that all the objects, and not just the name, is printed inside the selection list.

This issue make React to re-render everything client side.
Do you know which could be the cause?

Thanks!

**Comment by jquense** [comment]
Hi there,

Could you maybe post some more code illustrating the issue? I'm having a hard time grasping what exactly the problem you are having is. What is the "selection list"? an example of the markup the server produces might be helpful as well
