### ISSUE TITLE
UTC, daylight-saving-time

### ISSUE THREAD

**Issue by gabor** [jquense/react-widgets#510]
hi,

i need to have the user to pick an UTC date+time, but the user is not in the UTC time-zone.

my current approach is to just fake it, i mean, create a Date object in the user's time-zone that has the same hour/minute/month/etc. values as the UTC date+time, and convert back-and-forth.

example:
i want the date-picker to default to "2016-04-04T12:00:00Z". i simply convert that timestamp to "2016-04-04 12:00:00" in local time zone, and feed it to the date-time-picker. now let's say the user picks the timestamp "2016-05-05 13:10:10". i take it and convert it to "20216-05-05T13:10:10Z". it works fine generally.

the problem is, that some timestamps just does not exist in certain timezones.
for example, in central-european-time the following timestamp:
"2016-03-27T02:30:00" does not exist.
the reason is that on that date, at 2hours in the morning, the time moved to 3hours in the morning, effectively the time between 2 and 3 is skipped.

it means, that if i create a date-object in the browser in that time-zone:
`new Date(2016,2,27,2,30)`, i get an object saying "3:30" instead of "2:30". so, in my fake-utc-mode, the user cannot pick the "2016-03-27T02:30:00Z" utc timestamp, because the date-picker will switch to "3:30" automatically.

any idea how to handle this?

**Comment by nzjoel1234** [comment]
I am doing the same thing as you.

An additional problem I am getting (which could possibly be handled by providing a timezone prop to the picker) is that the current date and time which are selected by default are in the local timezone instead of UTC (or whatever timezone I am using for display)

**Comment by gabor** [comment]
@jquense closing this means it is not going to be implemented, or it is already implemented, or something else?

**Comment by jquense** [comment]
This is up to you and the localizer, the date picker has no opinion about timezones, if you want to control more specifically which date is used for default causes, control currentDate. I'm open to making this more straightforward but it's not a priority for me, but happily take a PR
