### ISSUE TITLE
MultiSelect input overlaps border at reduced screen size

### ISSUE THREAD

**Issue by Flamenco** [jquense/react-widgets#512]
Using chrome at 90% zoom, the multi-select text input cuts of the containing border.

<img width="1171" alt="screen shot 2016-12-12 at 9 54 20 pm" src="https://cloud.githubusercontent.com/assets/819940/21126035/e8594f18-c0b7-11e6-91ed-2662e27f3b70.png">

<img width="1168" alt="screen shot 2016-12-12 at 9 54 37 pm" src="https://cloud.githubusercontent.com/assets/819940/21126036/e85df3b0-c0b7-11e6-8aa3-cc2e0d3893fd.png">

See screenshots for issue and my workaround.

**Comment by jquense** [comment]
this should be fixed in the v4 betas, thanks
