### ISSUE TITLE
value before minDate, user can not navigate between months

### ISSUE THREAD

**Issue by markusv** [jquense/react-widgets#513]
Hi,

when the user enters a invalid date (before the min date set) the user can not navigate between months (with the arrow buttons at the top) anymore. Can be reproduced with this:

`<DateTimePicker
              time={false}
              calendar={true}
              min={new Date("Sun Oct 01 2016 00:00:00 GMT+0200 (CEST)")}
              editFormat="DD.MM.YYYY"
              format="DD.MM.YYYY"
              value={new Date("Sun Sep 15 2016 00:00:00 GMT+0200 (CEST)")}
            >
            </DateTimePicker>`

enter a invalid date manually by typing 01.10.2016. Open the calendar. The dropdown now shows october month. Navigate to the next month (with the arrow button at the top). After the slide animation october months is again displayed. This continues until user sets a valid date. Should be december.

**Comment by jquense** [comment]
same advice as https://github.com/jquense/react-widgets/issues/384 don't set a value before the min date.
