### ISSUE TITLE
React 15.4.1

### ISSUE THREAD

**Issue by kirillkostko** [jquense/react-widgets#514]
Hi @jquense ,

After React 15.4.1 update I start getting warnings like this:

```
Warning: Unknown prop `meta` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Widget)
    in Widget (created by DateTimePicker)
    in DateTimePicker (created by Uncontrolled(DateTimePicker))
    in Uncontrolled(DateTimePicker) (created by ChildBridge)
    in ChildBridge (created by MessageTrigger)
    in MessageTrigger (created by MessageListener)
    in MessageListener (created by ChildBridge)
    in ChildBridge (created by Binding)
    in Binding (created by Field)
    in Field (created by FormTextField)
    ...
```

If you want I can look into this.

**Comment by jquense** [comment]
`react-formal` is the problem there I think. or maybe react-formal-inputs anyway

**Comment by kirillkostko** [comment]
I believe this particular problem is here https://github.com/jquense/react-widgets/blob/master/src/Widget.jsx#L29-L41

**Comment by jquense** [comment]
the widgets have to pass through any probs you add that it doesn't know about, otherwise lots of html attributes will never make it to the DOM nodes. In this case `meta` should never be passed to the widget, its the problem of `react-formal-inputs` which should not pass through that prop

**Comment by kirillkostko** [comment]
What's the solution in this case?

**Comment by jquense** [comment]
> react-formal-inputs which should not pass through that prop

☝️

**Comment by kirillkostko** [comment]
Sorry Jason, I didn't understand you. Should it be fixed in your library here https://github.com/jquense/react-formal-inputs/blob/master/index.js#L8 or I can do fix in my application?

**Comment by jquense** [comment]
it can be fixed in both places. in your app you can wrap the inputs you use and make sure they don't pass through `meta`. in any case this isn't the right repo for this issue :)

**Comment by kirillkostko** [comment]
You are right! Thank you!
