### ISSUE TITLE
inconsistency date time picker today's date does not match, highlighted date

### ISSUE THREAD

**Issue by jaybe78** [jquense/react-widgets#515]
Hi,

I got some weird issue using date time picker widget. First of all the today's date displayed at the bottom of the popup calendar, is different from the highlighted number within the calendar(one day before).
Also when I select a date within the calendar, the input text displays my selection minus one day.
![image](https://cloud.githubusercontent.com/assets/3605098/21229915/177b4916-c2db-11e6-8e39-6212e639cbed.png)

Is that issue related to localizer ??
I'm importing moment as localizer
```
import moment from 'moment'
import momentLocaliser from 'react-widgets/lib/localizers/moment'
momentLocaliser(moment);
```

Any idea what's going on ?

**Comment by jquense** [comment]
I'm not sure there, looks like maybe a moment bug?

**Comment by ewal** [comment]
I'm experience the exact same thing with `react-widgets v3.4.4` and `moment-timezone v0.5.3`.

**Comment by imnot2** [comment]
i have same bug when i use this code of 
`moment.tz.setDefault('America/New_York')`

like below picture

![k u d8g q7iz0 ehi_qt z8](https://user-images.githubusercontent.com/4587852/35275704-9258c602-007b-11e8-8574-4fb57fdddc5d.png)

Today is 2018-01-23,but calendar selected day is 2018-01-22;
when i clicked 17th day, the calendar showed 16th day;

version list of i used in below
"moment": "^2.20.1",
"react-widgets": "^4.1.0",
"react-widgets-moment": "^4.0.4",

**Comment by lorinkoz** [comment]
@imnot2 Any workaround?

**Comment by siropkin** [comment]
@lorinkoz did you found workaround?

**Comment by siropkin** [comment]
I tried different workarounds of this issue but at the end most workable variant I created you can find below.
The main idea of this variant is to show the wanted TZ inside the input field, but display local TZ inside the calendar and timeList.
I would be grateful for your feedback.

![image](https://user-images.githubusercontent.com/39134915/114672428-cfb7d880-9d0d-11eb-98af-e8cc48276c77.png)
![image](https://user-images.githubusercontent.com/39134915/114672444-d3e3f600-9d0d-11eb-8e7e-be8897c98cb7.png)


```
import React, { useState, useMemo, useCallback } from 'react';
import moment from 'moment-timezone';
import DateTimePickerOrigin from 'react-widgets/lib/DateTimePicker';

const DateTimePicker = (props) => {
  const {
    tz, // <-- tz you want to display, eg 'Etc/UTC'
    min,
    max,
    value,
    onChange,
    ...tail
  } = props;

  const [localTz] = useState(moment.tz.guess());

  const fixedParse = useCallback(
    (dateStr) => (dateStr ? new Date(dateStr) : null),
    [],
  );

  const fixedFormat = 'MMM D, YYYY HH:mm z';

  const fixedTimeFormat = useCallback(
    (date) => {
      if (localTz !== tz) {
        return `${moment.tz(date, localTz).format('HH:mm z')} (${moment.tz(date, tz).format('HH:mm z')})`;
      }
      return moment.tz(date, localTz).format('HH:mm');
    },
    [tz, localTz, fixedFormat],
  );

  const fixedDateFormat = useCallback(
    (date) => String(date.getDate()),
    [],
  );

  const fixedYearFormat = useCallback(
    (date) => String(date.getFullYear()),
    [],
  );

  const fixedMonthFormat = useCallback(
    (date) => monthShortNames[date.getMonth()],
    [],
  );

  const fixedDayFormat = useCallback(
    (date) => dayShortNames[date.getDay()],
    [],
  );

  const fixedMin = useMemo(
    () => (min === null ? undefined : min),
    [min],
  );

  const fixedMax = useMemo(
    () => (max === null ? undefined : max),
    [max],
  );

  return (
    <DateTimePickerOrigin
      {...tail}
      parse={fixedParse}
      format={fixedFormat}
      timeFormat={fixedTimeFormat}
      dateFormat={fixedDateFormat}
      yearFormat={fixedYearFormat}
      monthFormat={fixedMonthFormat}
      dayFormat={fixedDayFormat}
      min={fixedMin}
      max={fixedMax}
      value={value}
      onChange={onChange}
    />
  );
};
```
