### ISSUE TITLE
[onChange] click date ,time change

### ISSUE THREAD

**Issue by yangguixue** [jquense/react-widgets#520]
![image](https://cloud.githubusercontent.com/assets/22880233/21712011/17bb701e-d42d-11e6-88c3-a6972c1fda81.png)
![image](https://cloud.githubusercontent.com/assets/22880233/21712042/4ee24efa-d42d-11e6-8a67-8488ee357ed0.png)
![image](https://cloud.githubusercontent.com/assets/22880233/21712070/7deba49e-d42d-11e6-8536-73a61b9aff0d.png)
![image](https://cloud.githubusercontent.com/assets/22880233/21712101/a0c9218a-d42d-11e6-827c-4eb9f0e5c0b9.png)

all about code

import momentLocalizer from 'react-widgets/lib/localizers/moment';
import numberLocalizer from 'react-widgets/lib/localizers/simple-number';
import DateTimePicker from 'react-widgets/lib/DateTimePicker';

momentLocalizer(moment);
numberLocalizer();

constructor(props) {
    super(props);

    this.state = {
      channel: { schedule: [], app: 'uni', expiration: 12 },
      openingAt: new Date(),
    };
  }

  handleChange = (name, value) => {
    const channel = this.state.channel;
    const openingAt = new Date(value);
    if (this.props.channel._id) {
      const _id = channel._id || this.props.channel._id;
      channel._id = _id;
      channel.app = this.props.channel.app;
      channel.expiration = this.props.channel.expiration;
      channel.schedule = this.props.channel.schedule;
    }
    channel[name] = value;
    this.setState({ channel, openingAt });
  }

<DateTimePicker
      defaultValue={this.state.openingAt}
       value={this.state.openingAt}
       onChange={(event, value) => this.handleChange('openingAt', value)}
/>

**Comment by jquense** [comment]
the first argument of onChange is the date value not the event. you should be passing that back into the picker not the string value
