### ISSUE TITLE
Feature Request: Multiselect - Maximum selected

### ISSUE THREAD

**Issue by akraines** [jquense/react-widgets#527]
I am trying to limit how many items can be selected from a list, and I don't see that it is available as part of the API. Is there a simple work around? Can this be added easily?

**Comment by jquense** [comment]
you can do it yourself fairly easily luckily! If you provide value and onChange you can not accept changes when the value is more than you'd like.

**Comment by akraines** [comment]
Thanks for the quick response and your excellent library.
I just realized the same thing myself using the disabled prop:
Here's the code:
```
let maxSelected=3;
 let getDisabled = (newVal)=>{
            if (maxSelected && newVal && newVal.length>=maxSelected) {
                let disabled = _.difference(options,newVal);
                return disabled;
         }    
     }
        
        return <div className='row'>
             <Multiselect key={key'}
                data={options}
                textField={textField}
                disabled={getDisabled(value)}
                valueField={valueField}
                onChange={value => handler(value)} />
        </div>
```
