### ISSUE TITLE
How remove empty fields message?

### ISSUE THREAD

**Issue by Xurma2** [jquense/react-widgets#528]
![image](https://cloud.githubusercontent.com/assets/5157416/22328501/345450c0-e3ef-11e6-8166-89dfca16807a.png)

I set 
`messages={{
            emptyList: null,
            emptyFilter: null
}}`

But anyway I see an empty field

**Comment by jquense** [comment]
not sure what youre trying for here...

**Comment by Xurma2** [comment]
@jquense  I want to remove the empty list.
That is, if all the messages that have been disabled list did not show up.
Now shows one empty field

**Comment by jquense** [comment]
you can't not provide a message there. In those cases you'd have to manually control `open` and not let it open when the list is empty. It should be pretty straightforward to do that.
