### ISSUE TITLE
Unable to highlight text to copy-paste from documentation

### ISSUE THREAD

**Issue by james246** [jquense/react-widgets#529]
Highlighting snippets of code from the documentation in order to copy them is difficult as the background colour for highlighted text seems to be transparent within the snippet editor (CodeMirror?).

I tried a quick workaround of setting `::selection { background: white; }` to see if that would help, but to no avail.

To reproduce, try going to the [Getting Started](http://jquense.github.io/react-widgets/docs/#/getting-started?_k=kmy8hb) page, and highlighting the snippet of code under the `Setup` > `Webpack` section. If I click and drag to highlight those 4 lines, I'm not seeing any visual feedback that the text is being highlighted and hitting CMD+C doesn't copy the text. Some fields seem to be highlight-able, such as the first snippet (with the `require` statements) on the [DateTimePicker page](http://jquense.github.io/react-widgets/docs/#/datetime-picker?_k=lcejur)

Attempted with Chrome 55 and Firefox 51 on OS X 10.11

**Comment by jquense** [comment]
fixed in an upcoming update to the docs
