### ISSUE TITLE
[DateTimePicker] Suggestion: Add posibility to show dates that are not in min-max range

### ISSUE THREAD

**Issue by afilenko** [jquense/react-widgets#532]
## DateTimePicker
It might be more user-friendly to show dates which are not in [min..max] range in different style instead of showing empty cells. 
A few thoughts on implementation: 
1. A flag can be used to determine whether to display out-of-range dates of just empty cells as it's done currently.
2. By default current behavior will be applied and empty cells are shown.
3. Out-of-range dates appearance should be customizable.

If you find this suggestion acceptable, I could implement corresponding changes.

**Comment by jquense** [comment]
thanks for the issue. you can check out the v4 betas where showing the dates is the default behavior now
