### ISSUE TITLE
"duration" not being used for navigation transitions

### ISSUE THREAD

**Issue by vpatil** [jquense/react-widgets#534]
If I create a DateTimePicker with animation duration 0

```<DateTimePicker duration={0}/>```

 the duration is honored for the initial display of the calendar, but navigating between months etc. falls back to the default 250ms animation.

I think this is because `Calendar.propTypes` doesn't include `duration`.

Is there supposed to be some other way of affecting the slide animation duration for navigation?

**Comment by jquense** [comment]
fixed in the v4 branch, added `calendarDuration` prop to the DateTimePicker
