### ISSUE TITLE
Multiselect onDeselect event

### ISSUE THREAD

**Issue by ou-di** [jquense/react-widgets#535]
I'm trying to extend the logic of the way options are updating in dropdown, and I'm missing onDeselct event. Wouldn't it be useful to have this event in the props?

**Comment by Racheldelman** [comment]
+1 This would be very useful!

**Comment by jquense** [comment]
I don't think there is probably a lot of value in a separate event here. onChange should work, you can check if the value is less than the previous one. in the v4 betas there is even additional data on the event to tell you what was removed

**Comment by Racheldelman** [comment]
@jquense I have list of objects so its would be helpful not to have to loop through and compare them. Also any idea what the timeline is for v4?

**Comment by Racheldelman** [comment]
and thanks for the quick response! this library is great!
