### ISSUE TITLE
using Calendar with Moment is not working

### ISSUE THREAD

**Issue by andresmijares** [jquense/react-widgets#536]
I'm trying to use the Calendar with a moment instance but I get the following warning

```
warning.js:36 Warning: Failed prop type: Invalid prop `value` of type `Moment` supplied to `Calendar`, expected instance of `Date`.
    in Calendar (created by Uncontrolled(Calendar))
    in Uncontrolled(Calendar) 
```

Any way to make em work together?

**Comment by jquense** [comment]
the Calendar only accepts real Date objects. so you'll have to convert your moment instances to Dates before passing them in `moment.toDate()`
