### ISSUE TITLE
Add .min files to /dist

### ISSUE THREAD

**Issue by sylvain-hamel** [jquense/react-widgets#537]
Please add compressed (`.min`) files to the package.

**Comment by jquense** [comment]
That is someone you should do as part of your build step. the global dist files should already be minified

**Comment by sylvain-hamel** [comment]
FYI: I link to https://unpkg.com/react-widgets@3.4.6/dist/react-widgets.js without any build process. This why I'd like your package to include the min file. But this is just a nice to have.

**Comment by jquense** [comment]
ah ok so its broken in v3. v4 is minified however: https://unpkg.com/react-widgets@4.0.0-rc4/dist/react-widgets.js

**Comment by sylvain-hamel** [comment]
thanks
