### ISSUE TITLE
number picker buttons don't have class names

### ISSUE THREAD

**Issue by tswaters** [jquense/react-widgets#538]
I'm trying to style the number picker a bit but I've noticed that the increment and decrement buttons don't have class names.  I can roll right now with :first-child and :last-child but it's obviously not ideal.

Would you accept a PR that adds class names to the  increment/decrement buttons for ease of styling?

**Comment by jquense** [comment]
Sounds reasonable to me. you might want to make it against the v4 branch tho

**Comment by jquense** [comment]
feel free to submit a PR
