### ISSUE TITLE
React PropTypes Warning

### ISSUE THREAD

**Issue by erikthinkiq** [jquense/react-widgets#539]
I'm getting this warning when creating a DateTimePicker using the latest React (15.4.2), the latest React Widgets (3.4.5), and the latest moment (2.17.1) in the function customPropType. Same issue as closed issues #443 and #483.

A simple demo with the warning is attached.

Warning: You are manually calling a React.PropTypes validation function for the `finalView` prop on `Calendar`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

printWarning	@	react-15.4.2.js:3640
warning	@	react-15.4.2.js:3664
checkType	@	react-15.4.2.js:2674
finalView	@	react-widgets-3.4.5.js:5137
[react-proptypes-warning.zip](https://github.com/jquense/react-widgets/files/765303/react-proptypes-warning.zip)

**Comment by erikthinkiq** [comment]
This is now fixed using React Widgets 3.4.6.

**Comment by bigkrp** [comment]
@erikthinkiq i see that in src deprecated was fixed, but in lib - didn't
https://github.com/jquense/react-widgets/blob/master/lib/Widget.js#L60-L65

and when i install react-widgets i have warnings
![default](https://cloud.githubusercontent.com/assets/11586744/25420467/dc62fdb8-2a60-11e7-806f-b5d0590de020.JPG)

**Comment by erikthinkiq** [comment]
@bigkrp The warning I was seeing had to do with DateTimePicker, which I no longer see starting with 3.4.6. I'm using the file dist/react-widgets.js. I'd open a new issue regarding Combobox.
