### ISSUE TITLE
DatePicker Animation crashing when component is unmounted

### ISSUE THREAD

**Issue by vladimir-rovensky** [jquense/react-widgets#54]
Hey again

I'm having a weird problem with the DatePicker that I can't quite pinpoint. Some of my unit tests keep failing with the React invariant violation: getDOMNode(): A component must be mounted to have a DOM node. 
I tried to debug this as far as I could and it happens in ReplaceTransitionGroup's _tryFinish method, which tries to acquire the DOM node of an element that is unmounted. In general, I think the problem is that the animation can finish after the component has been unmounted, resulting in this error.

Do you think I'm doing something wrong? If not, would it be possible for the ReplaceTransitonGroup to check for the unmounted state prior to whatever it is trying to do with the DOM node?

As a side note, it seems like the DateTimePicker does not pass its duration property to the underlying Calendar component, which might be related to the issue I'm having (we always use 0 durations for animations), but it might not be the only problem.

Any help/suggestions would be most welcome.

**Comment by jquense** [comment]
Hey there thanks for the report.

I am pretty sure your right, and this a classic "timeout fires after the thing has been removed" bug. I should have been paying more attention to :P. I'll add a check and you should be good to go.

To your side note, a quick glance and test on the docs site indicates that duration is being passed down just fine. Unfortunately a duration of zero doesn't actually solve the issue b/c while its not animating over time the animation callback is still getting called async: `setTimeout(cb, 0)` so it can still suffer this bug.

**Comment by vladimir-rovensky** [comment]
Hey there

We're definitely on the right track here, but there's still an error, even if I apply your fix locally. This time it happens in _handleDoneLeaving (again in ReplaceTransitionGroup), which tries to setState after the component has unmounted. Could we add one more check in _handleDoneLeaving?

Many thanks for your work on this project BTW, I appreciate the effort you're putting into this.

**Comment by jquense** [comment]
Glad you are enjoying the library, I've added an additional check, let me know if that finally solves it?

**Comment by vladimir-rovensky** [comment]
Works nicely now, thanks again!
