### ISSUE TITLE
Webpack 2 error

### ISSUE THREAD

**Issue by dmt0** [jquense/react-widgets#548]
Trying to build with Webpack 2, getting error:

    Couldn't find preset "jason" relative to directory "/Users/ds/projects/web/node_modules/react-widgets"

for each of the react-widget modules.

Was able to mitigate it by adding babel-preset-jason to my own dependencies.

**Comment by jquense** [comment]
you shouldn't be compiling this module, exclude node_modules from your Babel loader config

**Comment by dmt0** [comment]
right, except webpack 2 does not support exclude option in loader...

**Comment by jquense** [comment]
sure it does, that hasn't changed from v1 luckily
