### ISSUE TITLE
Awesome fonts failed to decode in Meteor+react

### ISSUE THREAD

**Issue by JWDobken** [jquense/react-widgets#552]
I want to use this package with meteor in react.
Included `import 'react-widgets/dist/css/react-widgets.css';` to get the styling, and this works.

However, I am not able to get the awesome-icons.
Instead, I get the warning:

    Failed to decode downloaded font: http://localhost:3000/fonts/rw-widgets.ttf?v=4.1.0
    OTS parsing error: invalid version tag

Does anyone knows how to include these?

**Comment by KapilGahlot** [comment]
1. Create a public folder in your project folder, which has client, server, imports and other folders.
2. copy fonts and img folders from "your project folder/node_modules/react-widgets/dist/" to your public folders above.  After restart of your server, you should not see the warnings you have mentioned.

**Comment by FBosler** [comment]
Hey Joost, did you manage to get react-widgets working in a meteor/react app? I am trying to do the same thing, but getting tons of weird errors!
Do you have slack?
