### ISSUE TITLE
Not selecting data item on delete in Combobox

### ISSUE THREAD

**Issue by smashercosmo** [jquense/react-widgets#553]
What's the purpose of not selecting data item on delete? I'm talking about these line
https://github.com/jquense/react-widgets/blob/master/src/Combobox.jsx#L323

I would expect that whenever value matches item, then this item should be passed to the onChange callback.

From the docs:
> If the value is one of the data members that item will be returned. In the case of a value not being found in the data array the string value of the Combobox will be returned.

**Comment by jquense** [comment]
there is a technical reason but it's escaping me right now. If I remember correctly its related to the autosuggest behavior. Sorry i don't have much of a better answer! I'm a bit to afraid to mess with the combobox at this point :P it needs a full rewrite

**Comment by smashercosmo** [comment]
Ok, hoping this will be addressed in v4 :)

**Comment by jquense** [comment]
sadly it probably won't :/ but if you want to jump in ;) I'm always happy to have help

**Comment by smashercosmo** [comment]
Jump in v3 or v4? :)
