### ISSUE TITLE
Android keyboard covers multiselect options dropdown

### ISSUE THREAD

**Issue by mchandleraz** [jquense/react-widgets#555]
I'm working on a project that's using react-widgets, and in both our app and the Docs, the dropdown created from clicking in the Multiselect gets covered by the keyboard on a Samsung S2 tablet. This happens using both a web browser, and within our Cordova app.

I'm going to dig into the source and see if I can come up w/ a solution, so you may see a PR for this soon.

**Comment by jquense** [comment]
This should be a matter of styling. Admittedly the default styles aren't super mobile friendly.
