### ISSUE TITLE
ComboBox should allow having no focused item

### ISSUE THREAD

**Issue by brooksrbrown** [jquense/react-widgets#557]
- Setup a ComboBox with suggest and filter='contains'
- Type a string that is contained in some of the items, but doesn't match any exactly.
- Hit enter.
Instead of submitting the text you typed, it submits the first item in the filtered list. Not completely sure, but I don't think this is the desired behavior for most applications. Better would be to have no focusedItem until the user arrows down.

Looking at the code, there appears to be no support for not having a this.state.focusedItem.

**Comment by jquense** [comment]
Hi there, we always focus the first item for the sake of accessibility, and that's probably not going to change. There is no "submit" action on inputs, only "select". Enter will select the focused item. When typing a value there isn't any action to perform, as you type the value is already "submitted" as the input value, same as how you don't hit enter in a textbox to "commit" the typed value. There is another issue covering this if you want to read more.

**Comment by brooksrbrown** [comment]
Thanks for your response! Why does no initial focus cause an accessibility issue? I imagine a screen reader would still list the drop down options. My use of submit was incorrect. I meant select. My problem with the behavior of ComboBox is how it works in the context of a form where Enter is typically used to submit. However, ComboBox uses it to make a selection instead. Unless a user has chosen a drop down option, enter should submit the value they have typed, and in this case, it doesn't.
