### ISSUE TITLE
NumberPicker hides the decimal unless focused

### ISSUE THREAD

**Issue by zeroasterisk** [jquense/react-widgets#558]
Even when using your example: http://jquense.github.io/react-widgets/docs/#/numberpicker

If I enter `12.34` and then click off an input _(blur)_then the float disappears... it's still there, but not visible.
![ss1](https://puu.sh/vaW6x/a1f9e437c6.png)
![ss2](https://puu.sh/vaW6H/d105d0a563.png)

I am doing this with your simple-number localizer and I've tried setting `precision=2`

    import numberLocalizer from 'react-widgets/lib/localizers/simple-number';
    numberLocalizer();

All I want here, is the decimal to show up.  Without it, these inputs can't be used for, say, costs, or anything with a decimal... users wont know to click on an input to see the full value.

**Comment by jquense** [comment]
you need to change the format to one that shows the decimal places you want.

**Comment by zeroasterisk** [comment]
got it - sorry - you do have this documented, but I couldn't find it on my first 3 searches for it :/ 

thanks a bunch!
