### ISSUE TITLE
external taglist for multiselect?

### ISSUE THREAD

**Issue by dwick** [jquense/react-widgets#56]
I'd like to be able to render the taglist externally on a multiselect component.  Would you be open to a PR for this feature?

**Comment by jquense** [comment]
I'm not quite sure what you mean by externally. Could you expand or maybe illustrate what you have in mind?

**Comment by dwick** [comment]
Sure.. styles a bit out of whack, but here's a quick example:

![screen shot 2015-03-03 at 11 11 49 pm](https://cloud.githubusercontent.com/assets/823747/6479481/bf9a95c2-c1fa-11e4-93ee-2ebf45edbf85.png)

Basically what i'd like to be able to do is set a container for the taglist that isn't the multiselect itself.

**Comment by jquense** [comment]
gotcha. I have actually had this need also. I think it would be tough to structure a PR that would work well in this case, and I don't think that this sort of thing makes a lot of sense in the library proper. But I do want to make sure the widgets are flexible and extensible enough that stuff like this is enough enough to do yourself. In this case I think we are already there, provided you feel comfortable using a technically private component.

This is a bit of an oversimplification, you may have to cover some edge cases, but you can easily wrap this pattern up into a few components in your own code to reduce some of the wiring needed to get it working.

```js
var Multiselect = require('react-widgets/lib/Multiselect');
var TagList = require('react-widgets/lib/MultiselectTagList');

var App = React.createClass({

  getInitialState(){
    return {
      data: list,
      values: [],
    }
  },

  render(){
    var self = this;

    function onChange([value]){
      self.setState({
        values: self.state.values.concat(value), 
         // remove the value from the data list so it can't be re-selected
        data:   self.state.data.filter( v => v !== value)
      })
    }

    function onDelete(val){
      self.setState({
        values: self.state.values.filter( v => v !== val),
        data:   self.state.data.concat(val)
      })
    }

    return (<div>
            <Multiselect data={this.state.data} value={[]} onChange={onChange} />
            <TagList value={this.state.values} onDelete={onDelete} />
      </div>)
  }
})
```

The above is written in es6 you can [look here to see the compiled version](https://babeljs.io/repl/#?experimental=true&playground=true&evaluate=false&loose=true&spec=false&code=var%20Multiselect%20%3D%20require('react-widgets%2Flib%2FMultiselect')%3B%0D%0Avar%20TagList%20%3D%20require('react-widgets%2Flib%2FMultiselectTagList')%3B%0D%0A%0D%0Avar%20App%20%3D%20React.createClass(%7B%0D%0A%0D%0A%20%20getInitialState()%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20data%3A%20list%2C%0D%0A%20%20%20%20%20%20values%3A%20%5B%5D%2C%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%2C%0D%0A%0D%0A%20%20render()%7B%0D%0A%20%20%20%20var%20self%20%3D%20this%3B%0D%0A%0D%0A%20%20%20%20function%20onChange(%5Bvalue%5D)%7B%0D%0A%20%20%20%20%20%20self.setState(%7B%0D%0A%20%20%20%20%20%20%20%20values%3A%20self.state.values.concat(value)%2C%20%0D%0A%20%20%20%20%20%20%20%20%20%2F%2F%20remove%20the%20value%20from%20the%20data%20list%20so%20it%20can't%20be%20re-selected%0D%0A%20%20%20%20%20%20%20%20data%3A%20%20%20self.state.data.filter(%20v%20%3D%3E%20v%20!%3D%3D%20value)%0D%0A%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20function%20onDelete(val)%7B%0D%0A%20%20%20%20%20%20self.setState(%7B%0D%0A%20%20%20%20%20%20%20%20values%3A%20self.state.values.filter(%20v%20%3D%3E%20v%20!%3D%3D%20val)%2C%0D%0A%20%20%20%20%20%20%20%20data%3A%20%20%20self.state.data.concat(val)%0D%0A%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20(%3Cdiv%3E%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CMultiselect%20data%3D%7Bthis.state.data%7D%20value%3D%7B%5B%5D%7D%20onChange%3D%7BonChange%7D%20%2F%3E%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CTagList%20value%3D%7Bthis.state.values%7D%20onDelete%3D%7BonDelete%7D%20%2F%3E%0D%0A%20%20%20%20%20%20%3C%2Fdiv%3E)%0D%0A%20%20%7D%0D%0A%7D))

**Comment by dwick** [comment]
that works perfectly, thanks for the quick response!
