### ISSUE TITLE
Use input type "number" for NumberPicker

### ISSUE THREAD

**Issue by hongyuan1306** [jquense/react-widgets#562]
The NumberPicker component uses` <input type="text" >` as the underlying input control. While this works fine on the desktop, on a phone, normally I would like the numeric keypad to appear whenever the control has focus.

Having `<input type="text"> `makes it very annoying to enter a number using this component as one has to switch input method first.

My question is, why not use `<input type="number">` as the underlying input control? And is there a way that I can override the default input type?

**Comment by jquense** [comment]
You can't use non text types for these inputs because those types have special UI and styles. These inputs are custom versions of those native types which recreate and add semantics on top of the input. Using number type would break and clash with all that.

**Comment by hongyuan1306** [comment]
Hi,

I now understand your considerations in choosing `<input type="text">` for the NumberPicker control. While it make perfect sense with a desktop browser, I would try to argue for the use case for using this control in mobile browsers.

I am trying to use this control in a warehouse application in which a user scans a QR-code on a package and then inputs the package weight on a mobile platform. With current implementation of NumberPicker when the control gets focus, an alphabet keyboard is displayed:

![b](https://cloud.githubusercontent.com/assets/10390407/25262871/e0a564c8-268d-11e7-8580-b262b69d4e5f.jpg)

The user has to switch keyboard before he is able to enter a number, which would be very annoying. So I changed the NumberInput to make the input type 'numeric'. Now the control works flawlessly as I expected:

![a](https://cloud.githubusercontent.com/assets/10390407/25262975/ad05a08c-268e-11e7-9b29-ace288b8d23b.jpg)

I think the purpose of a NumberPicker is to allow the user to enter a numeric value as easy as possible, with or without a spinner, and whether on a desktop or on a mobile device. So it would be important for the browser to pop up a correct keyboard on the mobile device, which afaik can only be realized with `<input type="number">` . The visual negative side effects can usually be eliminated by CSS, the keyboard behavior however seems to be changed only with the input type.

I would suggest adding an `inputType` property to NumberPicker, which defaults to 'text' and can optionally take the value of 'number'.

If you agree, I can make a PR for your review.

**Comment by jquense** [comment]
> The visual negative side effects can usually be eliminated by CSS, 

This isn't true actually, the default chrome on the inputs cannot be removed or changed. I understand you point here but I'm not going to break the inputs on desktop to get the right keyboard on mobile. If you is a deal breaker for you I might suggest rendering a native number input on mobile instead of using react-widgets input

**Comment by hongyuan1306** [comment]
Of course it is easier said than done to remove all possible side effects of `<input type="number">` on so many different browsers. And it is perfectly understandable to ensure a smooth user experience for the desktop users of the library. So I will take your suggestion to user a custom input widget, or just fork the library for the existing functionalities.

On the other hand, just for your information, several of the major UI frameworks like Sencha ExtJS modern and Grommet are all using `<input type="number">`  for their numeric input widgets. See example:

http://examples.sencha.com/extjs/6.2.0/examples/kitchensink/?modern#form-panel
http://grommet.github.io/docs/number-input

So I think the difficulties are not insurmountable either. :-)
