### ISSUE TITLE
Include value in HTML output for SelectList and ComboBox

### ISSUE THREAD

**Issue by melinath** [jquense/react-widgets#565]
Currently, value is not included in HTML output. This is causing issues for us in testing our frontend with selenium, since there's no simple way for us to, say, loop through the list of checkboxes and mark the ones matching a list of values we want to be checked. Instead we have to either pass in a list of _display_ values (which doesn't necessarily correspond to anything useful) or override every SelectList component to have a textComponent prop that includes the value as an attribute on some standard (for us) element.

We have had a similar problem with Combobox.

**Comment by jquense** [comment]
Late response, but that's all up to React and how it decides to flush values to the DOM. I believe that for `value` it's intentional they they only update the property and not the attribute, but you'd have to bring it up with them.
