### ISSUE TITLE
Add ability to set today's date

### ISSUE THREAD

**Issue by nzjoel1234** [jquense/react-widgets#567]
I would like to be able to set today's date (i.e. the bold date in the calender)

This is because I am letting user select a datetime in a different timezone - I am able to do this by converting a date before display and then modifying the output of onChange. (Similar to this https://github.com/jquense/react-widgets/issues/510)

Looks like this should be a fairly trivial change (add a today prop to the calender and datetimepicker and use that instead of `new Date()`. @jquense can you see any problems with this?

**Comment by jquense** [comment]
No pro blew if you want to send a PR
