### ISSUE TITLE
The time is not editable when open DateTimePicker with option 'time'

### ISSUE THREAD

**Issue by macoto-liu** [jquense/react-widgets#568]
if use DateTimePicker like this

<DateTimePicker open='time' ..../> then the time won't be editable
![image](https://cloud.githubusercontent.com/assets/10680110/25480758/312df020-2b18-11e7-98f9-083d0846855d.png)
**this image is got from the official website examples**

but if I set open='calcendar' it will be editable.

Can we support edit time manually when open with `open='time'` ?

**Comment by macoto-liu** [comment]
I want to be able to change the time value manually  instead of picking from the dropdown.

**Comment by jquense** [comment]
Why can't you do that? Works fine for me just type into the text input and change the time

**Comment by macoto-liu** [comment]
If you see the screenshot above, if there are three options closed, calendar, timelist. 

if you select the time list, the input won't be editable. 

Are you able to change the time ?

this is the website I tried from.
https://jquense.github.io/react-widgets/docs/#/datetimepicker/onSelect?_k=pcia4y

**Comment by jquense** [comment]
Yup, works fine. Even on that example in the docs

**Comment by macoto-liu** [comment]
it's strange on my browser. I'm using macos+chrome.

I just tried in firefox again, I only can delete the characters in the input, but can't type/add characters.

**Comment by macoto-liu** [comment]
![image](https://cloud.githubusercontent.com/assets/10680110/25486876/7944fc4c-2b30-11e7-9e55-34a39c5b9b2c.png)

This is the gif how it looks on my browser. the `Calendar` option looks good. but iafter selecte Time List, I only able to delete the characters.

**Comment by jquense** [comment]
very weird, I see that as well on desktop, but not mobile or other browsers.

**Comment by AgamlaRage** [comment]
Any news on this ?

**Comment by AgamlaRage** [comment]
Same issue in the new version 4.1.3

**Comment by jquense** [comment]
Its not released yet
