### ISSUE TITLE
ReferenceError: window is not defined while pre-redenering

### ISSUE THREAD

**Issue by rosieks** [jquense/react-widgets#569]
It looks like localizers doesn't work with pre-rendering on server-side. I receive error `window is not defined` when I import localizer for moment

**Comment by jquense** [comment]
you have a stack trace? localizers don't reference the `window` at all

**Comment by rosieks** [comment]
My stack trace is not useful in this case but I found that while localizers themselves doesn't reference window then after webpack they do that: 
https://github.com/jquense/react-widgets/blob/master/dist/react-widgets-moment.js#L138

**Comment by jquense** [comment]
yes those files are built for a browser. require them from `react-widgets/lib/localizers/moment` instead

**Comment by rosieks** [comment]
Thanks, now it works
