### ISSUE TITLE
Localization in v4

### ISSUE THREAD

**Issue by olzraiti** [jquense/react-widgets#572]
Hey,

I'm trying to migrate to v4 since in #559 it was said that v3 isn't supported anymore.

I'm using the DateTime widget, and I'm getting this error:

```
Failed prop type: [React Widgets] You are attempting to use a widget that requires localization (Calendar, DateTimePicker, NumberPicker). However there is no localizer set. Please configure a localizer.

see http://jquense.github.io/react-widgets/docs/#/i18n for more info.
```

There isn't a moment localizer anymore in v4. (in v3 you could import `momentLocalizer` from the lib folder). In v4 there is a file `lib/utils/localizers.js`, but I can't find any documentation how to setup localization for v4 and whether that file is relevant.

**Comment by jquense** [comment]
check out the v4 documentation: https://github.com/jquense/react-widgets/blob/v4/packages/docs/components/pages/i18n.md the localizers are the same they have just been moved to a seperate npm package

**Comment by olzraiti** [comment]
Thanks! :)
