### ISSUE TITLE
React-Widgets styles not working with webpack

### ISSUE THREAD

**Issue by dpresence** [jquense/react-widgets#575]
Hello, I am a newbie to react and trying to use react widgets datetimepicker and it will not work with webpack unless I put the img and fonts folders in my project directories. Below is my code.
Kindly take a look pls, been trying all the solutions I could find online for weeks @jquense 

//scss file

@import "~react-widgets/lib/scss/react-widgets.scss";
@import "../../../styles/variables";

//webpack.config.js

...

module.exports = {

  entry: [
    'react-widgets-webpack!./node_modules/react-widgets-webpack/react-widgets.config.js',
    'webpack-hot-middleware/client',
    'tether',
    'font-awesome-loader!./'+app_config.relpaths.styles+'/font-awesome.config.js',
    bootstrapDevEntryPoint,
     path.resolve(PATHS.app, 'index.js')
  ],

  output: {
    path: PATHS.build,
    filename: 'js/bundle.js',
    publicPath: 'http://'+project_config.host+':'+project_config.port+'/' 
  },

  devtool: '#cheap-module-eval-source-map',

  stats: {
    colors: true,
    reasons: true
  },

  // We can now require('file') instead of require('file.jsx')
  resolve: { extensions: ['', '.js', '.jsx', '.scss'] },

  plugins: [
    new ExtractTextPlugin("styles.css"),
    new webpack.HotModuleReplacementPlugin(),
    // Avoid publishing files when compilation fails
    new webpack.NoErrorsPlugin(),
    // BS4 need tether
    new webpack.ProvidePlugin({
      "window.Tether": 'tether'
    }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.DefinePlugin({
      __PKGVERSION__: JSON.stringify(process.env.npm_package_version,'0.0.0'),
      __VERSIONHASH__: JSON.stringify(VERSION,'-nogithash-'),
      __CLIENT__: true,
      __SERVER__: false,
      __DEVELOPMENT__: JSON.stringify(process.env.NODE_ENV || 'development') === 'development',
      __DEVTOOLS__: true // true  // <-------- DISABLE redux-devtools HERE
    })
  ],

  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loaders: ['babel'],
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        loader: sassLoaders.join('!')
      },
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader!postcss-loader'
      },
      {
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'less-loader']
        })
      },
      {
        test: /\.less$/,
        loader: 'style-loader!css-loader!less-loader'
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader?limit=10000&name=[name]-[hash].[ext]&mimetype=application/font-woff'
        //loader: 'file-loader'
      },
      /*{
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$/,
        loader: 'file'
      },*/
      {
        test: /\.gif$/,
        loader: 'url-loader?mimetype=image/png'
      },
      {
        test: /\.(ttf|eot|svg|gif)(\?[\s\S]+)?$/,
        loader: 'url-loader?limit=10000&name=[name]-[hash].[ext]'
      },
      {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader?name=[name].[ext]'
      }
    ]
  },

  postcss: [autoprefixer],

};

**Comment by jquense** [comment]
Follow the instructions here: https://github.com/jquense/react-widgets/blob/master/docs/components/pages/GettingStarted.md#webpack there is an additional note about the font and images

**Comment by dpresence** [comment]
Thanks that worked perfect, one more issue please.
I am using the datetimepicker as a component in a redux form and it works well only that when I implement a date object that counts every second for the placeholder, when I select a date and try to clear the field the selected date keeps overriding the placeholder. Here is the code:
Kindly take a look @jquense 
. . . 
constructor(props){
super(props)
this.tick() = this.tick.bind(this);
this.state = {currentTime: new Date()};

}

componentDidMount(){
const interval = setInterval(this.tick, 1000);
this.setState({
interval: interval
});
console.log(this.state.time);
}

componentWillUnmount(){
clearInterval(this.state.interval)
}

tick(){
setInterval(() => {
this.setState({
currentTime: new Date()
})
}, 1000)
}
render() {
    const { input: { value, onChange }, showTime } = this.props;

    return (
      <fieldset>
        <DateTimePicker
          placeholder={placeholder}
          onChange={moment(this.state.currentTime).format('DD MMM YYYY HH:mm:ss')}
          defaultValue={null}
          format='DD MMM YYYY HH:mm:ss'
          time={showTime}
          value={!value ? null : new Date(value)}
        >
        </DateTimePicker>
      </fieldset>
    );
  }
}

**Comment by web2wire** [comment]
Spent awhile this evening trying to get these widgets working with basic unejected webpack config (from create-react-app) and node-sass but no joy. This, and several other issues, refer to this link, https://github.com/jquense/react-widgets/blob/master/docs/components/pages/GettingStarted.md#webpack, which no longer exists. Can anyone point me at a current version?

**Comment by jquense** [comment]
first page of the docs: http://jquense.github.io/react-widgets/

**Comment by web2wire** [comment]
Thanks for this. Could never get it working unfortunately (styling conflicts with bootstrap v4?) so had to use a different picker.

**Comment by mstruensee** [comment]
I have this working with webpack and bootstrap 4 (reactstrap) ... what does your webpack and sass import  look like?

**Comment by Pnickolas1** [comment]
@mstruensee I believe I am running into similar issues you did. What changes did you make to get this working? (I am using reactstrap, react 16 and react-widgets v 4.4.3). All of the CSS in react-widgets seem to be broken currently.
