### ISSUE TITLE
DateTimePicker Quarter Calendar.

### ISSUE THREAD

**Issue by mharocsc** [jquense/react-widgets#576]
I've been using the DateTimePicker, specific on 'month' view (for day selection) and on 'year' view (for month selection) but now I need a quarter selection (Q1, Q2, Q3, Q4). I wonder if there's a way to change the view to this kind of timescale?

**Comment by jquense** [comment]
There isn't anything for quarters, theoretically it wouldn't be to much trouble to add, but I don't ave a need for such a thing so it's not likely unless you want to PR something.
