### ISSUE TITLE
Calendar with moment.js

### ISSUE THREAD

**Issue by fabiocba** [jquense/react-widgets#578]
Hello, I'm trying to use the calendar widget, but without success due to localization. I've read the docs but it seems there is no moment localizer on lib directory to import as described on the docs example:

```
var Moment = require('moment')

var momentLocalizer = require('react-widgets/lib/localizers/moment')

momentLocalizer(Moment);
```

I've noticed though localizer.js has been moved to lib/util, but still no success importing a moment localizer. Similarly it also happens when setting a Number localizer.

I've managed to bundle my code using this:
`var numberLocalizer = require('react-widgets/lib/localizers/simple-number')`

However, Firefox gives me this warning when loading my app: 

> Error: [React Widgets] You are attempting to use a widget that requires localization (Calendar, DateTimePicker, NumberPicker). However there is no localizer set. Please configure a localizer. 
> 
> see http://jquense.github.io/react-widgets/docs/#/i18n for more info.

I've installed react-widgets via npm, which in turn got the ^4.0.0-rc.6 version. Are the docs up to date? 

Thanks in advance.

**Comment by jquense** [comment]
oops no this should be the latest version, but a prerelease. You can use tho if you want, the localizers have moved to a new package `react-widgets-localizer-moment.

I pushed a new release so reinstalling will give you v3.4.7

**Comment by fabiocba** [comment]
Thanks a lot!
