### ISSUE TITLE
NumberPicker with format - handling change

### ISSUE THREAD

**Issue by Incanus3** [jquense/react-widgets#583]
I'm trying to use `NumberPicker` to enforce correct number format. I tried with both `simple-number` and `globalize` localizers and they both behave the same. When I specify format with no fractional part, e.g. using `maximumFractionDigits: 0` with `globalize` and then try to enter a number with fractional part, e.g. 0.5, the number is correctly rounded on focus loss, but the onChange handler is still called with the 0.5 (the `aria-valuenow` attribute of the input), which should be disallowed by the format specification. Similar thing happens when I specify e.g. `maximumFractionDigits: 3` - when I enter the fourth fractional digit, the input value is correctly rounded on focus loss, but the `onChange` handler is still called with the 'unrounded' number.

Is this a bug, or am I using it wrong? In the latter case, how should I approach this problem. Do I need to re-parse the value in the `onChange` handler? If so, the format option doesn't seem to bring much value.

**Comment by jquense** [comment]
Hi there. It's not a bug, formats are purely a localization function, e..g they are related to the _string_ representation of the number. They don't affect the actual number value itself. Put another way, its analogous to date formatting. An input may display "Jan 2013", or "12 Jan 04", but the underlying value, the `Date` object, is always the same.
