### ISSUE TITLE
Cancel close on DropdownList item selection

### ISSUE THREAD

**Issue by grovesNL** [jquense/react-widgets#586]
I'm trying to use `DropdownList` to create a filter. The idea is similar to `Multiselect` but instead the user toggles checkboxes on and off to make each dropdown list item active as a filter.

So in my case the component looks something like this (you can paste this in the [editor](https://jquense.github.io/react-widgets/docs/)):
```
const DropdownList = ReactWidgets.DropdownList,
  colors = [
    { value: "orange", show: true },
    { value: "red", show: false },
    { value: "blue", show: false },
    { value: "purple", show: true },
    { value: "black", show: true },
    { value: "gray", show: false },
    { value: "white", show: true },
    { value: "beige", show: false },
    { value: "cyan", show: true },
    { value: "green", show: false },
    { value: "yellow", show: true }
  ];

function toggle(value) {
  const color = colors.find(color => color.value === value);
  color.show = !color.show;
  ReactDOM.render(createWidget(), mountNode);
}

const createWidget = () =>
  <DropdownList
    onSelect={event => console.log(event)}
    data={colors}
    itemComponent={({ item }) =>
      <div
        onClick={event => {
          toggle(item.value);
          event.stopPropagation(); // I want to remove this and implement it correctly
        }}
      >
        <input type="checkbox" defaultChecked={item.show} />
        {" "}
        <span>{item.value}</span>
      </div>}
  />;

ReactDOM.render(createWidget(), mountNode);
```

I've looked around but can't see any way to accomplish this using various combinations of `open`/`onToggle`/`onSelect` props. What I've ended up doing for now is calling `event.stopPropagation` during `onClick` but it's not a very good solution.

Let me know your thoughts. I'd be happy to help with a PR if this isn't supported but you think it would be useful.

**Comment by jquense** [comment]
Hi there, sorry for the delayed response. There isn't really a better way of doing this with `itemComponent` (intentionally) but there are a lot more advanced API's for this sort of thing by changing the `List` component. I'd look at the source code for the SelectList it uses the same List as the Dropdown list with some tweaks, so it's essentially exactly what you want i think.

**Comment by grovesNL** [comment]
@jquense Thanks, I'll take a look
