### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead.

### ISSUE THREAD

**Issue by zerkms** [jquense/react-widgets#587]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by jquense** [comment]
Duplicate, check the other issues thanks!

**Comment by zerkms** [comment]
I hope you don't apply the https://github.com/jquense/react-widgets/pull/580 though. `create-react-class` and should be used as a last resort, switching to the ES2015 classes is a recommended way to do it.
