### ISSUE TITLE
DateTimePicker initialView does now work on v4

### ISSUE THREAD

**Issue by jrwm** [jquense/react-widgets#588]

**Comment by jquense** [comment]
That's correct, `initialView` has been removed and replaced. You can specify all the calendar views you want to use with `views` as an array of views in order. the first view in the list will be the equivalent of initialView in v3

**Comment by jrwm** [comment]
Thank you. I can make PR with a mention in the docs, if you think it is a good idea ...

**Comment by jquense** [comment]
sure 👍
