### ISSUE TITLE
Typescript/ES6 syntax for importing localizers?

### ISSUE THREAD

**Issue by sheam** [jquense/react-widgets#590]
Can someone help me out with the syntax for importing the momentLocalizer?

`import * as momentLocalizer from 'react-widgets/lib/localizers/moment';` does not seem to work, because no module is exported.

I also tried a hack
```
import {Moment} from 'moment';
declare let require: any;
var momentLocalizer = require('react-widgets/lib/localizers/moment');
momentLocalizer(Moment);
```

But the compiler complains I am using Moment as an instance when it is a type.

I do have the @types/react-widgets installed.

Any tips appreciated.

**Comment by danielpoulson** [comment]
This worked for me
import momentLocalizer from 'react-widgets/lib/localizers/moment';

**Comment by vahmur** [comment]
Sheam, i have same issue. I spent day trying to resolve it. Have you found a solution yet?

**Comment by jquense** [comment]
`import momentLocalizer from 'react-widgets/lib/localizers/moment'` should be the correct way

**Comment by emauricio** [comment]
Hi there, do you have a working example for this, i tried but i can't manage to make it work
react  - 15.6.1
"react-widgets": "^4.1.2",
 "react-widgets-moment": "^4.0.5",
    "@types/react-widgets": "^3.2.33",
    "@types/react-widgets-moment": "^4.0.1"
always get this error
im using redux as well but i guess this is not related with that 
`Uncaught Error: [React Widgets] You are attempting to use a widget that requires localization (Calendar, DateTimePicker, NumberPicker). However there is no localizer set. Please configure a localizer. `

**Comment by vahmur** [comment]
so.. i using require... 8(
let momentLocalizer = require('react-widgets-moment');
momentLocalizer();
