### ISSUE TITLE
Using DateTimePicker On Mobile Devices

### ISSUE THREAD

**Issue by simon-online** [jquense/react-widgets#592]
Hi,

When using the DateTimePicker on a mobile device if you press the date or time picker buttons the keyboard pops up over top because the text input field is given focus. This makes it difficult to use on mobile as you have to keep hiding the keyboard before you can use the date picker or time picker.

I think it would be an improvement to give focus to the DateTimePicker instance itself rather than the text input field when the date or time picker buttons are pressed. Similar to how focus() works on the DropdownList. Then the keyboard won't pop up on mobile when you press the date or time picker buttons it will only pop up when you touch the actual text input field. You could also make any open date or time picker automatically close when you give focus to the actual text input field.

Thanks

**Comment by jquense** [comment]
I'd like to make this experience better, but I can't think of a way to do it without moving the focus to the solely to outer div, which would require manually implementing typing logic for desktop users for the input since it's no longer focused. Happy to take a PR tho

**Comment by simon-online** [comment]
I don't think it's necessary to be able to type in the text input field when the date picker or time picker is open because a user likely wants to use the date picker or time picker to set the input value. I think the text input field only needs focus when the user directly gives focus to the actual text input field.

So basically the way I think it should work is when the date picker or time picker is open (by pressing the date or time picker buttons) then the outer div solely has focus (no typing or focus for the text input field) and when the text input field is directly given focus it automatically closes any open date or time picker and just lets the user type a value into the text input field.

**Comment by DavidCasillasRivero** [comment]
Sorry to open this old thread, but has been there any advance on this? I can not see any open issue, but there are at least three closed issues reporting the same thing. Has anybody send a pull request or propose a workaround to overcome this? Seems the owner is not going to put this subject on the roadmap.

**Comment by simon-online** [comment]
Hi David, there are other much better UI libraries with great support for mobile devices.

For example the Material-UI Date / Time pickers already have sensible behaviours on mobile:
https://material-ui.com/components/pickers/

Or you could check out this article on the Top 5 React Frameworks / UI Component Libraries:
https://devias.io/blog/top-5-react-ui-component-libraries-frameworks
