### ISSUE TITLE
rc.10/IE11 bug: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by erikthinkiq** [jquense/react-widgets#594]
Using the minified version (packages/react-widgets/dist/react-widgets.js) of the latest release candidate (4.0.0-rc.10) breaks in IE11 on the line `var i=Object.assign||function(e)...` with the message "Object doesn't support property or method 'assign.'"

**Comment by jquense** [comment]
Thanks for the bug report, do you think you could provide a stack trace using the unminified versions?

**Comment by huan086** [comment]
Must have been due to this
https://github.com/jquense/react-component-managers/issues/1

**Comment by erikthinkiq** [comment]
@huan086's suggestion for using https://www.npmjs.com/package/babel-plugin-transform-object-assign should fix the issue.

Using the non-minified version of v4.0.0-rc.13, here's the IE11 stacktrace from just loading the react-widgets library:
`o [Line: 7043, Col: 13], react-widgets.js`
`Anonymous function [Line: 7053, Col: 17], react-widgets.js`
`Anonymous function [Line: 4482, Col: 13], react-widgets.js`
`t [Line: 12, Col: 13], react-widgets.js`
`Anonymous function [Line: 9394, Col: 9], react-widgets.js`
`t [Line: 12, Col: 13], react-widgets.js`
`Anonymous function [Line: 15, Col: 9], react-widgets.js`
`Anonymous function [Line: 4, Col: 5], react-widgets.js`
`Anonymous function [Line: 2, Col: 300], react-widgets.js`
`Global code [Line: 1, Col: 109], react-widgets.js`


The error is in `Object.assign` in the function below:
`function o(e, t) {`
`    var n = t.propTypes,`
`        o = t.contextTypes,`
`        a = t.childContextTypes,`
`        u = t.getChildContext,`
`        l = r(t, ["propTypes", "contextTypes", "childContextTypes", "getChildContext"]);`
`    return n && (e.propTypes = i({}, e.propTypes, n)), o && (e.contextTypes = i({}, e.contextTypes, o)), a && (e.childContextTypes = i({}, e.childContextTypes, a)), u && ! function() {`
`        var t = e.prototype.getChildContext;`
`        e.prototype.getChildContext = function() {`
`            return i({}, t && t.call(this), u.call(this))`
`        }`
`    }(), Object.assign(e.prototype, l), e`
`}`
