### ISSUE TITLE
is there a property to make Combobox automatically open when the text field gets focused?

### ISSUE THREAD

**Issue by jedwards1211** [jquense/react-widgets#595]
I want a control that, like a dropdown, opens when I click anywhere on it, but can also suggest as I type.  Is there a property for `Combobox` to do this or would I have to hack something together?

**Comment by jquense** [comment]
no specific property for that but the api allows it. You should control the `open` prop and toggle it to open in `onFocus` (don't forget to add onToggle as well)

**Comment by jedwards1211** [comment]
Controlling the `open` prop would be way more work than I want to do, so would you accept a PR for something like an `openOnFocus` property?

**Comment by jedwards1211** [comment]
Actually I guess writing a wrapper to control `open` with local state would be easy

**Comment by jquense** [comment]
> Actually I guess writing a wrapper to control open with local state would be easy

exactly yeah
