### ISSUE TITLE
Warning: Multiselect: isMounted is deprecated.

### ISSUE THREAD

**Issue by bigkrp** [jquense/react-widgets#597]
I have warning for Multiselect
Warning: Multiselect: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
![2](https://user-images.githubusercontent.com/11586744/27679848-9723cad6-5cc2-11e7-8d7b-2fffcef29755.PNG)

I see in trouble in FocusMixin
![default](https://user-images.githubusercontent.com/11586744/27679799-77835c8c-5cc2-11e7-9ab9-fa5778fab5b6.PNG)

But when i check in lib/mixins/FocusMixin on github
https://github.com/jquense/react-widgets/blob/master/lib/mixins/FocusMixin.js#L64

There are correct using inst._mounted instead isMounted()

I use react-widget 3.4.8

**Comment by dmason30** [comment]
@jquense Also getting this on DropdownList

**Comment by jquense** [comment]
wow what a dumb warning...grr so many deprecations. This shouldn't be an issue in v4, which i'd suggest upgrading too if you can

**Comment by dmason30** [comment]
@jquense Is there a non-rc v4?

**Comment by dmason30** [comment]
@jquense v4.0.0-rc.10

![image](https://user-images.githubusercontent.com/20278756/27689434-0d23ff90-5cd6-11e7-8c30-d34b7701b59d.png)

**Comment by jquense** [comment]
you have some old or stale dependencies somewhere rc.10 definitely works

**Comment by dmason30** [comment]
I removed and readded it fine, duration={0} no longer seems to prevent the slide down animation ?

**Comment by jquense** [comment]
if you have v4 bugs please open up a separate issue thanks!

**Comment by dmason30** [comment]
#598 created, I will wait for an official v4 release :)

**Comment by ericvilleneuve** [comment]
@jquense v3 would be fine regarding the deprecation warnings if the the latest commit (with PR #580) was published to npm.

**Comment by jquense** [comment]
ah yes, sorry thought that had been done

**Comment by dmason30** [comment]
@jquense So do you intend to do a 3.4.9 soon, since the PR is already in?

**Comment by jquense** [comment]
I'm nit in a bug rush, they are depreciation warnings and not bugs. When I get a chance I'll release a new version

**Comment by kaflan** [comment]
Warning: DropdownList: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

**Comment by mvirbicianskas** [comment]
sooo, when is the v4 release planned? or is it tbd? :( react 16 is in beta now, it's not very far away from official release, I'm pretty certain there will be some breaking changes with react-widgets :(
