### ISSUE TITLE
[4.0.0-rc.10] duration not being applied (DropdownList)

### ISSUE THREAD

**Issue by dmason30** [jquense/react-widgets#598]
The `duration` prop does not seem to be getting applied in the `DropdownList`.
In `3.4.8` passing `duration={0}` would make appear instantly rather than the `slide-down` animation. 

Below is a sandbox to replicate:
[![Edit Krgx1LYMG](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/Krgx1LYMG)

**Comment by jquense** [comment]
I realized that the reason is, this prop doesn't exist anymore. The animation is handled completely by css. I want to make the API better for this tho, but in the meantime you can override the css 
```
.rw-transition-slide .rw-popup-animation-box {
  transition: none;
}
```

**Comment by dmason30** [comment]
Here is the sandbox example with the css fix showing the animation disabled:

[![Edit react-widgets DropdownList animation (css fix)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xGzX5QXoJ)

**Comment by jquense** [comment]
fyi the selectors changed in the newest rc, check out https://github.com/jquense/react-widgets/blob/v4/packages/docs/components/pages/Migration4.0.md for details

**Comment by dmason30** [comment]
@jquense I don't think this is issue worthy but with `4.0.0-rc.15` if you have transition: none then the drop shadow of the popup displays for a second:

[![Edit react-widgets DropdownList animation (css fix)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3P6wY6Qr)

**Comment by jquense** [comment]
ahh good catch, thanks!
