### ISSUE TITLE
Focus on Multiselect

### ISSUE THREAD

**Issue by ojame** [jquense/react-widgets#60]
![multiselect](https://cloud.githubusercontent.com/assets/2898239/6589863/a092aaa0-c7fb-11e4-9bfe-029d0eaac653.gif)

A little hard to understand with no visible clicks in the gif, but basically if you select an option via mouse click, then you have to lose focus on the input and then reclick the input to show the popup again.

I've spend a little bit looking into this to solve it for you, but the focus logic is a little hard for me to follow:

```
  _focus(focused, e){
    if (this.props.disabled === true)
      return

    this.setTimeout('focus', () => {
      if (focused)
        this.refs.input.focus()

      else
        this.refs.tagList && this.refs.tagList.clear()

      if (focused !== this.state.focused){
        focused
          ? this.open()
          : this.close();

        this.notify(focused ? 'onFocus' : 'onBlur', e)
        this.setState({ focused: focused })
      }
    })
  },
```

From what it looks like, `focused` and `this.state.focused` are both `true` when the user clicks the input the second time. I _assume_ a third var might be required?

Not sure, sorry mate!

**Comment by jquense** [comment]
Its actually less complicated than all that, there used to be an onClick handler that made sure it was open, but I removed thinking I was handling it in the focus logic (and to avoid having to check if the user clicked on a tag vs empty space in the wrapper element). Ultimately I think it was a small regression and we need to add the onClick back
