### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by FBosler** [jquense/react-widgets#600]
I tried to follow the documentation, but there is no "react-widgets/lib/localizers/globalize". This should really be described in a bulletproof way, as not getting this right makes it impossible to use the components....

http://jquense.github.io/react-widgets/docs/#/i18n?_k=wvvb7s

**Comment by jquense** [comment]
https://unpkg.com/react-widgets@3.4.8/lib/localizers/globalize.js

there is definitely that file. I think the beta version got added to latest by accident on npm is your issue

**Comment by jquense** [comment]
fixed the tags

**Comment by FBosler** [comment]
jquense could you explain what that means? how do I have to install the package then?

**Comment by FBosler** [comment]
got it. had to do npm install react-widgets@3.2.4 --save (you should fix your current version then)

cheers

**Comment by jquense** [comment]
Yeah, and the current version I fixed
