### ISSUE TITLE
German locale displays day incorrectly und isRtl={true} 

### ISSUE THREAD

**Issue by FBosler** [jquense/react-widgets#602]
German day abbreviations are Mo., Di., Mi., Do. (with a dot). When isRtl={true} it gets displayed like this .Mo, .Di, .Mi ...

**Comment by jquense** [comment]
Hi there, German isn't a right to left language so I wouldn't expect that to work right.

**Comment by FBosler** [comment]
I thought the isRtl is the property for where the buttons are located, am I wrong?

**Comment by jquense** [comment]
That's part of it but primarily it changes the read direction of text, it's for languages like Arabic, where you read from the right to the left.

**Comment by FBosler** [comment]
Gotcha
