### ISSUE TITLE
DropdownList selection returns an object instead a value

### ISSUE THREAD

**Issue by cacharrin** [jquense/react-widgets#603]
Based on this example found in the [docs](http://jquense.github.io/react-widgets/docs/#/dropdownlist/valueField), in the *valueField* example:

```
var DropdownList = ReactWidgets.DropdownList;
var colors = [
  { id: 0, name: 'orange'},
  { id: 1, name: 'purple'},
  { id: 2, name: 'red' },
  { id: 3, name: 'blue' },
];

var widget =
    <DropdownList
      valueField='id' textField='color'
      data={colors}
      defaultValue={1}/>

ReactDOM.render(widget, mountNode);​
```

When I changed selection on the dropdown, the **value** property is set to the object value like
```
value = {
  id: 2,
  name: 'red'
}
```

Shouldn't the correct value be only **2**? 
Because i'm specifying ```valueField='id'```

I'm using `redux-form` to create my form, then i can initialize form with `color=2` but when i submit my form i got `color={ id: 2, name:'red' }` if the field was changed, otherwise i got `color=2`

**Comment by cacharrin** [comment]
I just realized that:

This example returns the correct value (only the color value, not the object):
http://redux-form.com/6.0.0-rc.1/examples/react-widgets/

But this example returns the object:
http://redux-form.com/6.6.1/examples/react-widgets/

I know the examples comes from `redux-form`, but I think the problem could be a change in the `react-widgets` code between both versions.

Any help would be appreciated :)

**Comment by jquense** [comment]
The behavior you are seeing is correct. The value is the item in the data array. The valueField allows you to specify an 'id' for cases where you may only have the identifier first. If you are only interested in the value field I'd suggest extracting it from the dataitem in the onChange event

**Comment by cacharrin** [comment]
Ok, thank you for your help.

**Comment by kailashvele** [comment]
Can anyone of you put an small example? Thank You.

**Comment by Fabitosoft** [comment]
Hey I got it. Just try to put onBlur={()=>{}} with nothing and onChange={e => input.onChange(e[valueField])}.

`const renderCombobox = ({input, data, valueField, textField, placeholder, onSelect, meta: {touched, error, warning}}) => {
    return (
        <Fragment>
            <Combobox {...input}
                      data={data}
                      placeholder={placeholder}
                      valueField={valueField}
                      textField={textField}
                      onChange={e => input.onChange(e[valueField])}
                      onSelect={onSelect}
                      onBlur={(e) => {
                      }}
            />
            {touched && ((error && <span className='form-field-error'>{error}</span>) || (warning &&
                <span>{warning}</span>))}
        </Fragment>
    )
};`

You will realise that, onChange will return de value that you need (valueField), but, if you don't change onBlur, onBlur will replace de value by the text on your field. With this change, you will get what you need.
