### ISSUE TITLE
React Widgets 4.0.0-rc.15 DateTimePicker has no dates in DateTimePiker

### ISSUE THREAD

**Issue by olmobrutall** [jquense/react-widgets#604]
Not sure if this version is a mistake, because i don't see it in the source code, it's also published as non-beta somehow. 

The thing is that he numbers in the DateTimePicker are gone: 

![image](https://user-images.githubusercontent.com/720953/28125587-48d7400a-6727-11e7-8947-ffe1231aa3e6.png)

Thanks for your work :)

**Comment by jquense** [comment]
Can you post some code reproducing it? I don';t see this problem on any of the stuff i've tested...

arg why does npm keep publisging this as latest!!

**Comment by olmobrutall** [comment]
It's the same environment than the last bug: https://github.com/jquense/react-widgets/issues/593
I'm using webpack and typescript, but don't think that makes any difference. 

I'm also having bad experiences with npm, maybe time to give yarn a chance...

**Comment by jquense** [comment]
You might have some dependency mismatched, maybe try nuking node_modules?

**Comment by jquense** [comment]
Ugh sorry this is definately my fault. fix incoming

**Comment by huan086** [comment]
@jquense could you put out a new rc release?
