### ISSUE TITLE
Cannot use react-widgets because of missing localizer

### ISSUE THREAD

**Issue by pumpadump** [jquense/react-widgets#606]
I cannot import the momenLocalizer from react-widgets it seems these components are missing?

`import momentLocalizer from 'react-widgets/lib/localizers/moment';
Module not found: 'react-widgets/lib/localizers/moment'
`

**Comment by jquense** [comment]
this was an issue with a beta being pushed to npm as latest. it's fixed. please reinstall and the files will be there.

**Comment by pumpadump** [comment]
thanks that fixed it for me

**Comment by jdmunro** [comment]
This problem also seems to occur in the current RC: `react-widgets@4.0.0-rc.16`
