### ISSUE TITLE
[v4] rc.15 - Calendar - Unknown props duration, onAnimate

### ISSUE THREAD

**Issue by jamesperi** [jquense/react-widgets#607]
Hey there! I pulled rc.15 from NPM and I'm seeing this error with the Calendar..

![calendar_issue](https://user-images.githubusercontent.com/4944422/28249495-af022340-6a0b-11e7-9229-1f747a3e513b.png)

> Unknown props `duration`, `onAnimate` on \<div\> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by TransitionGroup)
>     in TransitionGroup (created by SlideTransitionGroup)
>     in SlideTransitionGroup (created by Calendar)

I see they gets passed into here:

[Calendar.js#L321](https://github.com/jquense/react-widgets/blob/v4/packages/react-widgets/src/Calendar.js#L321)

Thanks

**Comment by dmason30** [comment]
Please search before you create issues, this was discussed here: #598 

A migration guide has been written:
https://github.com/jquense/react-widgets/blob/v4/packages/docs/components/pages/Migration4.0.md

**Comment by jamesperi** [comment]
I did search :), The issue seems to have been a transient one and seems to have been fixed in

commit [23a948617a3b46ba66de8c91d280e1a1b862588e](https://github.com/jquense/react-widgets/commit/23a948617a3b46ba66de8c91d280e1a1b862588e#diff-c2a73ba0215a476508e8af372622aa61L321)

Appreciate the link to the guide. thanks again.
