### ISSUE TITLE
DateTimePicker crashes Safari  with TypeError: null is not an object (evaluating 'date['get' + method]')

### ISSUE THREAD

**Issue by nik-kor** [jquense/react-widgets#610]
Maybe relates to https://github.com/jquense/react-widgets/issues/549 but

> .... generally js crashes are due to infinite loops ...

but I think it's different

**Env:**

* Safari - Version 10.1.1 (12603.2.4)
* react-widgets 3.4.8
* date-arithmetic 3.1.0

**How to repro:**

* Click on time picker
* Error occurs here https://github.com/jquense/date-math/blob/master/index.js#L205
because `date` is null.

Works fine in chrome.

**Comment by ajsantander** [comment]
Getting same thing here. Also happens when you enter an invalid date via text.

**Comment by cacharrin** [comment]
I'm having the same issue! Any workaround?
