### ISSUE TITLE
Multiple Multiselect in Single form

### ISSUE THREAD

**Issue by kailashvele** [jquense/react-widgets#613]
Hi, 

How to work with multiple multiselect with onCreate feature in a single form as the implementation specified in the document applies to only single instance of Multiselect.

Also if you can provide more than string as Parameter or custom parameter option to onCreate method then it will be simple to have multiple instances of Multiselect.

I have searched for this but couldn't find anything hence posting here.

Thanks in advance. :)

**Comment by jquense** [comment]
Hi there, the example in the docs demonstrates how to respond to the multiselects events to add a new tag. _How_ you create tags for each instance is going to depend on how your app is structured and how you save items, whether you need to save anything on there server, etc. So it's tough provide an example that is closer to "real life"

**Comment by kailashvele** [comment]
Suppose I have two multiselect and when I create a new tag it should be added to respective state key but in onCreate method just provides the new string and not the data property to identify in which state key I should add that tag.

**Comment by jquense** [comment]
You can use use two different `onCreate` handlers

```
<Multselect onCreate={this.addTagTolistA} />
<Multselect onCreate={this.addTagTolistB} />
```
