### ISSUE TITLE
Support for Partial Dates?

### ISSUE THREAD

**Issue by dahjelle** [jquense/react-widgets#617]
I know this is a bit obscure, but I'm working on an application where the user may not know the full date. In other words, they might be entering someone's birthdate, but they only know the month but not the day or the year.

Is there, by any chance, a way to support this in `react-widgets`? I'm fine localizing to US-only dates in this case.

**Comment by jquense** [comment]
There isn't any built in support but the API is flexible enough to implement such a thing via formats and custom parse functions. I don't think there is a good general solution there so we won't be trying to implement it in the library but Id be happy to answer questions about using the apis!

**Comment by dahjelle** [comment]
Is there a way to tweak the UI to, for instance, add checkboxes to indicate "Unknown year" or "Unknown month" or some such? I realize those could be part of the wrapper UI, but it seems that they would fit best into the calendar view itself.

That said, we'll do some experimenting with the parsing and formatting and a wrapper UI to see if we can get what we need. Thanks!

**Comment by dahjelle** [comment]
I suppose another approach (thinking out loud here) is to have 3 date pickers that can be cleared, and use the `initialView` and `finalView` properties to have one **only** for year, one **only** for month, and one **only** for day. Then one could pull those values together, and make sure that they are clearable for when the user doesn't know the full date. A little clumsy for entering full dates, so perhaps it's optional.

Anyhow, thanks! I think I have enough direction now to move forward.
