### ISSUE TITLE
open above when element as at the bottom of the screen.

### ISSUE THREAD

**Issue by tswaters** [jquense/react-widgets#621]
This applies to:

- datetime picker
- multiselect
- combo box
- dropdown list

i.e., any of the widgets that show a dropdown

When the element is at the bottom of the page, it drops down further showing a scrollbar that wasn't there before.  

Typically when using native controls -- specifically a `<SELECT>` -- it the element is at the bottom of the page, the option list will appear above the element, not below.

**Comment by jquense** [comment]
We don't do any screen edge detection for a variety of reasons but there is the dropUp prop which will change the opening direction of the popup

**Comment by tswaters** [comment]
Oh hey, that'll work... thanks!
