### ISSUE TITLE
Missing localizers folder in build

### ISSUE THREAD

**Issue by rockyasante** [jquense/react-widgets#622]
hey guys, am I missing something , I cannot find  the folder in your npm folder.

I am trying to use the datetime picker and it seems your own docs refers a link which does not exist.

var globalizeLocalizer = require('react-widgets/lib/localizers/globalize')

Stuck , thanks

**Comment by jquense** [comment]
what version are you using?

**Comment by jamesperi** [comment]
Hey there, 

I have this issue as well, I just pulled v4.0.0 and there is no 'localizers' directory in lib

regards,
Jim Peri

**Comment by jquense** [comment]
in v4 the localizers have moved to seperate packages. Please see the documentation pages for details

**Comment by jamesperi** [comment]
forgive my ignorance, is this [Localization](http://jquense.github.io/react-widgets/localization/) the correct documentation, it says latest: v4

and the description for the simple number localizer is described as:

```
var numberLocalizer = require('react-widgets/lib/localizers/simple-number')

numberLocalizer();
```

Regards, 
Jim Peri

**Comment by jquense** [comment]
sorry that one isnt updated. the other ones are tho, its the sample deal the package is `react-widgets-simple-number`

**Comment by jamesperi** [comment]
ok, understood, I was confused because when I tried to import "react-widgets-simple-number" I had a webpack error related react-widgets-simple-number/localizers.js and the import statements inside. it doesn't looks to be babelified :P
