### ISSUE TITLE
issue while installing v4

### ISSUE THREAD

**Issue by goravbhootra** [jquense/react-widgets#623]
Hi,

I tried installing v4 branch using

`npm install --save https://github.com/jquense/react-widgets/tarball/v4`

but getting following issue:

> Can't install https://github.com/jquense/react-widgets/tarball/v4: Missing package name

tried installing using other #branch options as well but got same issue.

1. How do I install v4 branch?

1. Is there any timeline for v4 branch release?

Thanks.

**Comment by jquense** [comment]
I'm not sure where you are getting that install url, but you can install v4 like you would a normal npm package. `npm i react-widgets@4.0.0-rc.16` for that latest prerelease
