### ISSUE TITLE
Unable to set tabIndex prop

### ISSUE THREAD

**Issue by naody** [jquense/react-widgets#630]
I'm using SelectList and it appears I'm unable to override tabindex. It always defaults to "-1" even after passing `tabIndex` prop.  Since  tabindex is set to "-1", I'm unable to use keyboard to go to the next element in my form.  I'm I missing something?
 
`
    <SelectList
         tabIndex={'0'}
         data={[...]} />
`

![image](https://user-images.githubusercontent.com/1115720/30176091-2e3919ba-93cf-11e7-8109-3ed2cec6403f.png)

Version:
![image](https://user-images.githubusercontent.com/1115720/30176439-6b9ae29c-93d0-11e7-908c-85bd5d9d8292.png)

**Comment by jquense** [comment]
definately a bug!

**Comment by jquense** [comment]
fixed in 4.0.1
