### ISSUE TITLE
localizer-simple-number build

### ISSUE THREAD

**Issue by jamesperi** [jquense/react-widgets#631]
Greetings, 

I am seeing an issue with the 4.0.0 version of localizer-simple-number, and I wanted to ensure it got some attention, for now I've gone back to using the rc-16 version and it's fine. The 4.0 version doesn't seem to have the build step, there is a localizer.js file, but no transpiled index.js

In the 4.0.0 version
```
{
  "name": "react-widgets-simple-number",
  "version": "4.0.0",
  "description": "A globalize.js localizer for react-widgets",
  "main": "localizer.js",
  "scripts": {
    "clean": "rimraf dist/* lib/*",
    "dist": "cross-env NODE_ENV=production webpack",
    "build": "babel localizer.js -o index.js",
    "prepublish": "npm run clean && npm run build && npm run dist"
  },
  "files": [
    "localizer.js",
    "dist"
  ],

```

In the rc-16 version:

`
"main": "index.js",
  "scripts": {
    "clean": "rimraf dist/* lib/*",
    "dist": "cross-env NODE_ENV=production webpack",
    "build": "babel localizer.js -o index.js",
    "prepublish": "npm run clean && npm run build && npm run dist"
  },
  "files": [
    "index.js",
    "dist"
  ],
`

Thank you for all your efforts, this is a really nice project!

Regards, 

Jim Peri

**Comment by jquense** [comment]
fixed in 4.0.1
