### ISSUE TITLE
Impossible to blur from Combobox on Safari iOS

### ISSUE THREAD

**Issue by tomyf** [jquense/react-widgets#632]
Hello,
I stumbled upon a weird behavior on the official demo from http://jquense.github.io/react-widgets/api/Combobox/#valueField, on the version 4.

### Bug description
On iOS, once the Combobox has the focus, when I'm clicking elsewhere or clicking the "Ok" button on the keyboard, the focus is lost and immediately set again on the field. Sometimes, after clicking 2-4 times on this button, I can exit the field, but sometimes, I'm completely stuck, even when I'm trying to click to focus an other field, the focus is set back to the combobox.

On my personal project, this bug is way more blocking as I can't escape this field **at all**, I don't know if Bootstrap is interfering with the event, but it could be...

`UserAgent = 5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60` (got from `navigator.appVersion`)

### UGLY workaround
I have an **ugly** hack that is to rebuild the component when catching the `onBlur` event doing the following : 
```javascript
{/* 
    state should contain key to rebuild the component 
    and value since the component cannot store the value
*/}
<Combobox
    key={this.state.key}
    data={SOME_DATA}
    value={this.state.value}
    onChange={value => this.setState({ value })}
    onBlur={() => this.setState({ key: ++this.state.key })}
/>
```

I tested Chrome on Android / Mac OSX, but this problem only appears on Safari iOS.
I'm available to test any fix :)

### Code Sandbox with minimal environment
After some time, I managed to create the following Sandbox : https://codesandbox.io/s/kwrjqkqpqv
I can reproduce the bug but it happens less frequently than on your demo site and way less than on my project.

Thanks,
Thomas

**Comment by jquense** [comment]
Hey there thanks for the report. I don't really have access to an IOS device unfortunately so I could use some help identifying where the problem lies :/

**Comment by tomyf** [comment]
Thanks for your reply.
Unfortunately, I couldn't understand why, but on iOS, the `handleFocusChanged`function from `Combobox` is triggered twice in some cases. I don't know why is this happening, and I'm not an expert on Safari debugging, which makes it harder to debug.

I haven't so much time at the moment, I hope I can have more time next week. Anyhow, if someone could help, that would be highly appreciated :)

**Comment by chipit24** [comment]
This is also an issue with Safari 11 on macOS.

This happens even on the demo page, at http://jquense.github.io/react-widgets/api/Combobox/#valueField. In Safari 11 on macOS, select the combobox and you won't be able to blur/unfocus it.

**Comment by dmason30** [comment]
There is also a similar issue on Microsoft Edge browser where you blur from the combobox once it refocuses but the second time it doesn't.

**Comment by chipit24** [comment]
Seems to be related: https://github.com/jquense/react-widgets/issues/113
