### ISSUE TITLE
AMD Support for 4.0.0

### ISSUE THREAD

**Issue by erikthinkiq** [jquense/react-widgets#633]
In the 4.0.0 release, the line `define.amd?define(["react","react-dom"],t)` correctly loads ReactWidgets in AMD, but none of the components are defined. All the keys are listed, but they're all undefined. See screenshot for details.
<img width="800" alt="react-widgets-4 0 0-amd" src="https://user-images.githubusercontent.com/15721213/30404744-e7a2c492-989c-11e7-83a5-80dffa43c326.png">

**Comment by jquense** [comment]
fixed in 4.0.1
