### ISSUE TITLE
4.0.0 does not export any components

### ISSUE THREAD

**Issue by chriswxyz** [jquense/react-widgets#634]
![image](https://user-images.githubusercontent.com/12154594/30455267-e3ed90de-9964-11e7-90e4-ff0321bc53ba.png)

This issue is not AMD specific (#633) or Typescript related (#629), but is causing both of those issues. Also, 4.0.0-rc.16 did not experience this.

Here's a minimal repro: https://github.com/chriswxyz/repro-400-export-issue

Appears to be related to this specific change: https://github.com/jquense/react-widgets/commit/08ee9c4b87ffca8a65b7d186dd4031722cc45496#diff-5b36e8c6c14c229ac7ef92d22a4cad1e

**Comment by jquense** [comment]
fixed in 4.0.1

**Comment by shepmaster** [comment]
@jquense Just to make sure it is purposeful, is it correct that 4.0.1 now depends directly on `webpack "3"` and `webpack-atoms "^3.0.2"`? 

I noticed because this requires webpack 3.5.3 and we are using webpack 3.3; anyone like us with an older webpack might end up with multiple versions installed.

**Comment by jquense** [comment]
oops thats a mistake, care to PR a fix?
