### ISSUE TITLE
Would it be possible for a Multiple SelectList which acts like booleans?

### ISSUE THREAD

**Issue by leroy0211** [jquense/react-widgets#638]
Would it be possible to have the SelectList with checkboxes (multiple), act like the non-multiple variant with booleans? 

In my use case we want to show a list of selections, and only let the user select 1 option. But he also must have the ability to uncheck that option. 

Or do I need to create my own?

**Comment by jquense** [comment]
You can wrap the selectList and coerce the value to a boolean if you want. Generally I don't think multiple checkboxes are a good way to present that tho, I'd just use a dropdown or a single checkbox

**Comment by leroy0211** [comment]
Well, it's something a client wants to have. He want's to display the available options without having to "open" a dropdown, and only wants the user to select one item with the possibility to uncheck that one. 

I've got something working with just plain React, but I'm not sure if I can make it work in a react-forms and react-widgets setup. 
But thanks anyway!
