### ISSUE TITLE
PropTypes  deprecation warning

### ISSUE THREAD

**Issue by chipit24** [jquense/react-widgets#640]
Using this library, you get:
> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by jquense** [comment]
The code here all does the correct this so this must be coming from a dependency, please post more details thanks

**Comment by actraiser** [comment]
This seems to be related to the 'react-component-manager' package

![Warning](https://user-images.githubusercontent.com/5455/30689269-c5dd2dfa-9ec0-11e7-8c65-4173e7b7305f.png)

**Comment by actraiser** [comment]
I noticed that react-widgets' package.json asks for "react-component-managers": "^2.0.0" as dependency, so yarn will install 2.0.0.  However, 3.0.2 is the latest available version of react-component-managers ([npm repo](https://www.npmjs.com/package/react-component-managers))

Might the solution be as simple as upgrading the dependency version?

-act
