### ISSUE TITLE
Combobox `valueField` doesn't work, it uses `textField` instead

### ISSUE THREAD

**Issue by leroy0211** [jquense/react-widgets#642]
When I use the `Combobox` component, the property `valueField` is ignored somehow. 

I am using this with Redux Forms.

Example: 
```
let options = [
    {label: 'Blue', value: 1},
    {label: 'Red', value: 2},
    {label: 'White', value: 3},
];

const DropdownRender = ({ input, options, meta: {touched, error} }) => (
    <div className={"form-group " + ((touched && error) ? 'has-error' :'') }>
        <Combobox {...input}
                  data={options}
                  valueField='value'
                  textField='label'
                  onChange={input.onChange}
        />
        {touched && error && <span>{error}</span>}
    </div>
);

```

Whenever I submit this, the submitted value is the `label` (Blue) instead of the `value` (1).

**Comment by jquense** [comment]
I'm not really sure how redux-form works here so it's a bit tough to know what be happening...it seems like it's not using the value from onChange

**Comment by leroy0211** [comment]
I think I know what went wrong. 
The `onChange` event gives back the complete option object. So for example it returns `{label: 'Blue', value: 1}`. I thought the `onChange` value would be converted to the value of the key provided in `valueField`. 

My fix was to use this: 

```
<Combobox {...input}
                  data={options}
                  valueField='value'
                  textField='label'
                  onChange={o => input.onChange(o.value)}  //<-- o.value would return me the int 1 for 'Blue'
                  onBlur={_ => input.onBlur()} // <-- also required 
        />
```
