### ISSUE TITLE
Disabling specific dates on Calendar/DateTimepicker

### ISSUE THREAD

**Issue by anyulled** [jquense/react-widgets#643]
I want to disable specific dates (holidays, weekends) on those components, as they are invalid input. Is there actually a way to achieve that?

**Comment by anyulled** [comment]
No problem. We just migrated to a other component, due lack of response

**Comment by jquense** [comment]
:thumbsup:

**Comment by Riser01** [comment]
which component did u move to

**Comment by giulianoMX** [comment]
Is disabling certain dates an option these days?

**Comment by wenit123** [comment]
Is it now able to filter by a certain day of the week?
