### ISSUE TITLE
util/Filter Module not found in DropdownList.js

### ISSUE THREAD

**Issue by gauravprwl14** [jquense/react-widgets#644]
hi,

when i install the latest version which is 4.0.0, i got error saying

``Module not found: Can't resolve './util/Filter' in 'node_modules/react-widgets/lib/DropdownList.js'``` 

because of that my whole code break, pls resolve this issue as soon as possible

**Comment by jquense** [comment]
Sounds like you have something wrong with your local setup or install. I'd try and nuke node_modules and reinstall
