### ISSUE TITLE
Input Cursor not moving in Combobox

### ISSUE THREAD

**Issue by gauravprwl14** [jquense/react-widgets#645]
hi, 

i am using 3.5.0 version of react-widgets. I having wried issue in combobox.

in my data array if two value are same and placed next to each other in the array,  than my input cursor does move.

```
let colors = ['orange', 'red', 'red', 'blue', 'purple', ];
<Combobox
      data={colors}
      defaultValue={"orange"}
  />
```

now try to scroll the list my pressing Down arrow button..... you won't be able to move beyond red color....

hope to hear from you as soon as possible

**Comment by jquense** [comment]
We don't support lists of duplicate items. Each must be unique
