### ISSUE TITLE
Unable to add a custom value with a Combobox

### ISSUE THREAD

**Issue by shepmaster** [jquense/react-widgets#647]
Combobox is described as (emphasis mine):

> Select an item from the list, or **input a custom value**

I must be doing something terribly wrong as I cannot figure out how to allow a custom value.

### Steps to reproduce

1. Visit http://jquense.github.io/react-widgets/api/Combobox/ (I used Chrome Version 61.0.3163.100 on macOS)
2. Type "Jake" into the combobox, followed by <kbd>Enter</kbd>

### What I expected to happen

The name "Jake" would be in the combobox

### What actually happens

The name "Jacinda" is in the combobox.

### What else

I looked through all the props, but nothing seemed to be directly relevant. I searched for "custom" on that page but didn't see anything obviously relevant.

**Comment by jquense** [comment]
"enter" selects the focused entry (the first one by default), there is nothing special you need to do enter a custom value, you type "jake" and...that's it, thats the selected value, move on to the next input :)

**Comment by shepmaster** [comment]
Hmm, I did not expect that!

> move on to the next input

The trick in our case is that there *isn't* a next input. We've a tag entry UI:

![tags](https://user-images.githubusercontent.com/174509/30824129-81be196a-a1fc-11e7-8c02-8a61afdf730d.gif)

We want to extend this with the ability to autocomplete from a list of tags or add a new one. As you can see, the style is pretty different from the `Multiselect` component, so we can't just reuse that, sadly.

Are there any secrets/tricks you can think of to make <kbd>Enter</kbd> (and ideally any blur) submit the current value instead? If not, it's not the end of the world, we will just need to roll our own <sup>1</sup>.

---

<sup>1</sup> — consider this another vote for exposing some of the internal parts of react-widgets so that we could reuse them instead of starting from scratch ^_^.

**Comment by jquense** [comment]
you don't need to do anything to submit the value it is "submitted" as you type, so what you want is to keep "enter" from selecting the focused value. You could listen to `onKeyDown` and preventDefault on the enter key. If you are feeling risky you can also use the undocumented Autocomplete component which is in the package (still a WIP). I'd probably also be open to a prop toggling the "focus first item by default" behavior if you want to put something together.

**Comment by shepmaster** [comment]
Thank you very much for all your help!

> You could listen to `onKeyDown` and `preventDefault` on the enter key

Am I correct in assuming I'll have to upgrade to version 4.0 in order to get access to `inputProps` to do this? If so, things aren't looking good for me, as upgrading to 4.0 brings in dom-helpers 3.x, which doesn't work in our React-on-Rails setup (c.f. react-bootstrap/dom-helpers#20, react-bootstrap/dom-helpers#23). 

I [don't see](https://github.com/jquense/react-widgets/blob/v3.5.0/src/Combobox.jsx#L189-L209) any ways of adding extra props in 3.5...

**Comment by jquense** [comment]
you can add the prop in v3 its just `<Combobox onKeyPress={this.myHandler}>`

**Comment by shepmaster** [comment]
Ah great, I'll try that (I was actually stuck on #634 when trying to update to 4.0.0).

**Comment by shepmaster** [comment]
Ah, sad times; I added a breakpoint in my `onKeyPress` handler, and it's called for other keys, but not for <kbb>Enter</kbd>. I'm guessing that it's intercepted earlier in the component and never has a chance to make it to the handler.

**Comment by jquense** [comment]
try `onKeyDown`

**Comment by shepmaster** [comment]
Whew! I think I got it!

```jsx
<Combobox autoFocus
          suggest
          filter="startsWith"
          data={['one', 'two']}
          onChange={this.updateTag}
          onSelect={this.createNow}
          onKeyDown={this.handleKeyDown}
          onBlur={this.createWithTagInState}
          messages={this.MESSAGES} />
```

with support code:

```js
  MESSAGES = {
    emptyFilter: "Create a new tag",
  }

  createNow = tag => {
    this.props.onCreate(tag);
    this.setState({ tag: null, hasStarted: false });
  };

  createWithTagInState = () => {
    this.createNow(this.state.tag);
  };

  updateTag = tag => {
    this.setState({ tag });
  }

  handleKeyDown = e => {
    if (e.key === 'Enter') {
      this.createWithTagInState();
    }
  };
```

Thank you very much! I think you may close this unless there's anything useful you want to reuse the issue for!

**Comment by shepmaster** [comment]
Although some playing with it shows that `onBlur` is not a great idea here. Selecting an item from the dropdown with the keyboard also causes a blur, which causes two actions to be triggered. That might be a small loss.
