### ISSUE TITLE
DOM-Helpers Library breaks with null when using iframe

### ISSUE THREAD

**Issue by tommy-dev** [jquense/react-widgets#649]
Possible bug:

/node_modules\react-widgets\node_modules\dom-helpers\query\matches.js calls document.body, which breaks when the body is null under this condition:

1. iframe inside a react component.
2. the iframe view has script tags in the head containing the react-widget scripts build (at this point the dom-helper matches.js tries to match the body in the iframe while it is in the head without the body)
3. fixed the problem by moving the script tags of the iframe view from the head to the bottom of the body tag.

Possible null check on document.body for matches.js?

![image](https://user-images.githubusercontent.com/13111256/30897124-e6e9525e-a397-11e7-8376-c29ac7744895.png)

**Comment by jquense** [comment]
Please open up an issuer and PR in that repo thanks!
