### ISSUE TITLE
DateTimePicker with unspecified time

### ISSUE THREAD

**Issue by jole78** [jquense/react-widgets#651]
Hi,

First of all, thanks for a great lib!

I'm trying to build a component that works this way.
When the user just selects a date (from the calendar popup) the time should be set to 00:00 (basically unspecified).
Then if the user manually updates the time (by typing into the input) the time is updated (basically specified).

I'm kinda getting this to work by disabling time in the DateTimePicker but here's what currently happens.

The value/default value is to null or whatever value came from a server call or something. 
1. The user selects a date (onChange is called with "Sun Oct 01 2017 11:01:08 GMT+0200 (CEST)" for example)...e.g. current date and time (here the preferred way would be to set time to 00:00).
2. The user clears the value (onChange is called with null).
3. The user selects a new date from the calendar (onChange is called with "Sun Oct 01 2017 00:00:00 GMT+0200 (CEST)" for example)...that's weird...now it works, it only updates the date.
4. The user manually updates time from the input (onChange is called with "Sun Oct 01 2017 00:01:00 GMT+0200 (CEST)" for example)...great...only time is updated (now it's specified)
5. The user selects a new date (onChange is called with "Sat Sep 30 2017 00:01:00 GMT+0200 (CEST)" for example)...great...only the date is affected...time remains the same.

So, the question is how can I get this behavior from start??
Any ideas?

version "4.0.2"

**Comment by jole78** [comment]
Here's also something possibly related that I fully don't understand.
If I specify the onCurrentDateChange and the onChange event handlers here's what happens

1. onCurrentDateChange Sun Oct 01 2017 00:00:00 GMT+0200 (CEST)
2. onChange Sun Oct 01 2017 11:30:16 GMT+0200 (CEST)

So first onCurrentDateChange gets called (without time which is what I want)...but then onChange is called with the current time...which I don't want.

**Comment by jole78** [comment]
@jquense 👋 you got any insights into this?

**Comment by jquense** [comment]
Hey there. There really isn't anyway to get the behavior your looking for from the start, becasue the JS `Date` object doesn't have a concept of a date without a time, or vice versa. Date parts are always merged with the currentDate so we can return a valid date. 

If you want it to default to midnight for this, I would control `currentDate` and reset set the time to 0:0:0 on `onCurrentDateChange`

**Comment by jole78** [comment]
hey, look at that @jquense it worked!!

`defaultCurrentDate={moment().startOf("day").toDate()}`

just showing you a quick and dirty solution there and there's probably a cleaner way than using moment but setting defaultCurrentDate was all it took...I guess. tnx a bunch, closing issue.
