### ISSUE TITLE
React 16 errors

### ISSUE THREAD

**Issue by austinh** [jquense/react-widgets#652]
ComboBox causes some errors when upgrading to React 16.0.0 (react-widgets 4.0.2)

```
Uncaught Error: Element ref was specified as a string (inner) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
  
react-dom.development.js:8305 The above error occurred in the <Uncontrolled(Combobox)> component:
```

**Comment by jquense** [comment]
I think you have multiple copies of react installed by accident

**Comment by austinh** [comment]
When I comment out all uses of react-widgets, the error goes away. I have also cleared node_modules and reinstalled all dependencies from scratch.

**Comment by ricardogcolombo** [comment]
Same error here, any clue how to fix this?

**Comment by vhfmag** [comment]
I just had this issue and solved it by removing a dependency (in my case, prop-types-ts) that was injecting a React 15 copy.
