### ISSUE TITLE
Missing JSX highlighting on docs

### ISSUE THREAD

**Issue by joshkel** [jquense/react-widgets#655]
The docs site is missing syntax highlighting for JSX code blocks. See, e.g., http://jquense.github.io/react-widgets/localization/.

Adding the following toward the top of `www/src/layouts/index.js`, below the imports, fixes syntax highlighting. I'm not familiar with Gatsby, so I don't know if this is the proper way to fix things or not.

```
require('prismjs');
require('prismjs/components/prism-jsx');
```

**Comment by jquense** [comment]
i'm not sure waht the best way to handle this is actually...the code [here](https://github.com/jquense/react-widgets/blob/master/www/plugins/gatsby-plugin-jsxtreme-markdown/loader.js#L33) is supposed to be handling this, and I think is in some places...
