### ISSUE TITLE
react-widgets-simple-number localizer not built correctly?

### ISSUE THREAD

**Issue by joshkel** [jquense/react-widgets#656]
When I try to import react-widgets-simple-number, I get the following error:

```
./node_modules/react-widgets-simple-number/localizer.js
Module parse failed: app\node_modules\react-widgets-simple-number\localizer.js Unexpected token (11:32)
You may need an appropriate loader to handle this file type.
| 
| export default function simpleNumber(options = {}) {
|   let { decimal, grouping } = { ...defaults, ...options }
| 
|   let localizer = {
 @ ./src/components/forms/NumberInput.js 31:22-60
 @ ./src/components/forms/Form.js
 @ ./src/components/ManualCollectionPointForm.js
 @ ./src/containers/TakeDataFreeFormManual.js
 @ ./src/containers/Root.js
 @ ./src/startApplication.js
 @ ./src/index.js
 @ multi webpack-dev-server/client?http://127.0.0.1:8000 webpack/hot/only-dev-server react-hot-loader/patch ./src/index
```

If I understand things correctly, the problem is that packages/localizer-simple-number/package.json's main refers to localizer.js, the ES6 source, instead of referring to a file that's been processed by Babel into something that can be directly imported. (The other localizers list main.js, so they appear to work correctly.)

I can submit a PR if you like, although I'm unclear on what purpose the Webpack build step and `dist` folders serve for the localizers, since they don't appear to be used.

Thanks!

**Comment by samalexander** [comment]
There is already a PR open for this issue [here](https://github.com/jquense/react-widgets/pull/653). Hopefully it will be merged soon.

**Comment by joshkel** [comment]
Thanks. I'll go ahead and close this, then.
