### ISSUE TITLE
Documentation for Multiselect is actually that for Combobox

### ISSUE THREAD

**Issue by zeroasterisk** [jquense/react-widgets#657]
All of the examples on the `Multiselect` documentation page import and demo `Combobox`

http://jquense.github.io/react-widgets/api/Multiselect/

`let { Combobox } = ReactWidgets;`

![ss](https://puu.sh/xPY5L/50eac08257.png)

**Comment by samalexander** [comment]
I think this is actually a bug where the props examples aren't re-rendered when changing between the widget tabs. For example, if you load the MultiSelect page [here](https://jquense.github.io/react-widgets/api/Multiselect/) and then switch to the NumberPicker tab, you will see that MultiSelect examples appear where it should be NumberPicker.
