### ISSUE TITLE
Documentation for version 3 should be available somewhere... Maybe a migration guide too?

### ISSUE THREAD

**Issue by zeroasterisk** [jquense/react-widgets#658]
If we can generate it ourselves, or access it via somewhere, it would be really nice to see.

Also, is there a migration guide from 3->4?  The CHANGELOG seems to be a bit lacking, but since v4 is "official" and the documentation if about v4, I want to upgrade, but I don't know what to expect about changing props, etc...

**Comment by jquense** [comment]
You'd have to pull the latest v3 tag and build the docs locally to see them. the migration guide is here: https://github.com/jquense/react-widgets/blob/master/www/src/pages/migration-v4.md
