### ISSUE TITLE
DateTimePicker crashes when you are manually clearing a date

### ISSUE THREAD

**Issue by diegys** [jquense/react-widgets#659]
Steps:
- set a date using the calendar/timepicker
- clear the date using backspace

**Comment by jquense** [comment]
Sorry I can't reproduce this, can you put to get her a jsfiddle demonstrating it?

**Comment by diegys** [comment]
It reproduces on the official site: http://jquense.github.io/react-widgets/api/DateTimePicker/
Try to clear the pre completed DateTimpePicker(Oct 5, 2017, 4:56:03 PM) : you will get an error in the console and the input will be populated with the deleted value on blur.

![bugdate picker](https://user-images.githubusercontent.com/2330535/31231177-c07c20a8-a9ee-11e7-8cba-472c681457b1.PNG)

**Comment by jquense** [comment]
you're right! should be a simple fix sorry about that

**Comment by diegys** [comment]
Np, I'm glad I can help.
I discovered this by trying to fix a weird bug at work(we were using react-widgets 3.4.6) and did a little research to see if an update could help. I happens only on the date time picker, on the regular date picker there is no problem.
The unminified error in 3.4.6 is: 
![image](https://user-images.githubusercontent.com/2330535/31231871-c9f92d68-a9f0-11e7-89e6-71693803655e.png)
