### ISSUE TITLE
Multiselect close upon selection

### ISSUE THREAD

**Issue by jrock17** [jquense/react-widgets#662]
Thanks for this great package.

The old version of multiselect would close once an item in the dropdown list was picked. The new version stays open until you explicitly click the arrow again or click outside the list.

Is there a prop to allow for closeOnSelect?

**Comment by jrock17** [comment]
Update: I tried controlling the open manually and closing with onToggle and onChange. But there is a strange behavior when once an item is selected (perhaps with onBlur?).

If at least once item is selected in the Multiselect, a second click anywhere on the screen (not just the input, dropdown or arrow) will trigger the onToggle. This prevents the user from clicking a submit button or anything else under the dropdown window.

**Comment by jrock17** [comment]
I also reported this in #665 with a screenshot.

**Comment by uendar** [comment]
@jrock17  did you figure it out how to fix this issue ?
