### ISSUE TITLE
Cannot set defaultView in DateTimePicker

### ISSUE THREAD

**Issue by spalladino** [jquense/react-widgets#663]
Greetings! I'm using version 4.0.2 with react 15.6.1, and I'm not being able to set property `defaultView` to DateTimePicker. Any value I set is ignored.

However, if I set `view` and manage it via `onViewChange`, it works, though an error is shown in the console, which seems to indicate that the property is being forwarded to an underlying `div` directly.
```
Warning: Unknown prop `onViewChange` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by spalladino** [comment]
Thanks!

**Comment by DobroBro** [comment]
@jquense Hello! Thx for your work.
This back was appeared again ...

> and I'm not being able to set property defaultView to DateTimePicker. Any value I set is ignored.

Version of package - 4.1.1, property defaultView is ignored.
