### ISSUE TITLE
Missing peer dep error

### ISSUE THREAD

**Issue by jurgenzz** [jquense/react-widgets#664]
Running `npm ls react` brings up following errors for your package:

```
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-widgets@4.0.2
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0, required by react-widgets@4.0.2
```

**Comment by jquense** [comment]
Have you installed a matching version of react or react-dom?

**Comment by jurgenzz** [comment]
I mean, didn't you upgrade to React 16? Why you are still requiring 15?

**Comment by jquense** [comment]
haven't updated or confirmed it works with 16 yet. happy to take a PR!

**Comment by jurgenzz** [comment]
Cool, as far as i can see i have installed only 16 and everything is working without errors, except this error during installs.

As i've very limited time myself, anyone up for PR?
