### ISSUE TITLE
onToggle triggers away from MultiSelect input area

### ISSUE THREAD

**Issue by jrock17** [jquense/react-widgets#665]
When using MultiSelect, the onToggle event fires no matter where you click on the page. I would expect it only to fire when you click inside the input area or arrow.

The below for example.

![ontoggle bug](https://user-images.githubusercontent.com/1270524/31627516-6b2a8dfc-b262-11e7-8218-991ea9904792.gif)

**Comment by jquense** [comment]
very weird!
