### ISSUE TITLE
_this.isMounted is not a function

### ISSUE THREAD

**Issue by Xepe** [jquense/react-widgets#668]
Hello, 

I am using the version 4.0.2 DateTimePicker with the following config:

```
<DateTimePicker 
    timeFormat="hh:mm A" 
    onChange={onChange} 
    date={false} 
    time={true}
    value={!value ? null : new Date(value)} />; 
```

When I type and the dropdown is open I get the following error:

> TimeList.js:93 Uncaught TypeError: _this.isMounted is not a function
>     at TimeList.js:93
>     at TimeList.js:237
> 

![image](https://user-images.githubusercontent.com/2806076/31753861-b1028ce0-b450-11e7-81fb-6b06cf8e669e.png)

Regards.

**Comment by jquense** [comment]
Thanks for the heads up!
