### ISSUE TITLE
Documentation for DateTimePicker doesn't include 'views' prop

### ISSUE THREAD

**Issue by flouc001** [jquense/react-widgets#669]
The documentation for [`DateTimePicker`](http://jquense.github.io/react-widgets/api/DateTimePicker/) does not include any entries on the `views` prop that is demonstrated in the example at the start. Given that limiting the scope of selection is a very useful feature I would expect it to be documented. Thanks, Cal :)

**Comment by jquense** [comment]
Hi there, views is a Calendar prop, which the picker uses. The docs should mention that the picker takes all of Calendars props as well

**Comment by flouc001** [comment]
Right I see the note at the top now. Not overly clear, maybe you want to add a note in the props dropdown? Or even have a comprehensive list with a double entry of the calendar props under `DateTimePicker`? A couple of devs have had the same experience as me. Thanks for pointing it out!

**Comment by jquense** [comment]
done!
