### ISSUE TITLE
Error on IE11 when trying Demo site

### ISSUE THREAD

**Issue by epannier** [jquense/react-widgets#676]
The components are not working on IE11 (at least mine) on the Demo site. When I click on the component nothing happens (every component is impacted). It works fine on Chrome and I'm quite sure it was working fine on IE last week.

The error on the console is always the same : Syntax error
File : app-11ba70280d30e299149c.js, line : 1867, column : 21

/***/ "./node_modules/gatsby-module-loader/index.js?name=component---src-layouts-index-js!./.cache/layouts/index.js":
/***/ (function(module, exports, __webpack_require__) {

module.exports = () => __webpack_require__.e/* import() */("component---src-layouts-index-js").then(__webpack_require__.bind(null, "./node_modules/babel-loader/lib/index.js?{\"presets\":[[\"/Users/jason/src/react-widgets/node_modules/babel-preset-jason/index.js\",{\"debug\":false,\"targets\":{\"browsers\":[\"> 1%\",\"last 4 versions\",\"not ie < 9\"]}}],[\"/Users/jason/src/react-widgets/www/node_modules/babel-preset-env/lib/index.js\",{\"loose\":true,\"uglify\":true,\"modules\":\"commonjs\",\"targets\":{\"browsers\":[\"> 1%\",\"last 2 versions\",\"IE >= 9\"]},\"exclude\":[\"transform-regenerator\",\"transform-es2015-typeof-symbol\"]}],\"/Users/jason/src/react-widgets/www/node_modules/babel-preset-stage-0/lib/index.js\",\"/Users/jason/src/react-widgets/www/node_modules/babel-preset-react/lib/index.js\"],\"plugins\":[\"/Users/jason/src/react-widgets/www/node_modules/babel-plugin-remove-graphql-queries/index.js\",\"/Users/jason/src/react-widgets/node_modules/babel-plugin-transform-decorators-legacy/lib/index.js\",\"/Users/jason/src/react-widgets/www/node_modules/babel-plugin-transform-object-assign/lib/index.js\"],\"cacheDirectory\":true}!./node_modules/css-literal-loader/lib/loader.js?{\"extension\":\".less\",\"tagName\":\"less\"}!./node_modules/imports-loader/index.js?define=>false,__VERSION__=>\"4.0.0\"!./.cache/layouts/index.js"))

I don't get this error with Chrome.

**Comment by jquense** [comment]
The site is probably missing a promise polyfill that webpack needs. I'm not all that concerned about the demo/docs site supporting ie11 if the library itself does.
