### ISSUE TITLE
Storybook not working

### ISSUE THREAD

**Issue by waynebrantley** [jquense/react-widgets#686]
Cannot run the storybook

Clone repo
```cd packages/storybook```
```npm install```
```npm run start-dev```

This yields many, many errors.
Things like missing dependencies and 'cant resolve 'react' in ../react-widgets/src'
Example missing dependencies:
```
    "date-arithmetic": "^3.1.0",
    "less-loader": "^4.0.5",
    "react-prop-types": "^0.4.0",
    "react-transition-group": "^2.2.1"
```

Are you still supporting the storybook - or is that no longer going to be used/maintained?
Was trying to see the ``Virtualized`` example work as we were having trouble making this work.  (Would like to fetch from remote )

**Comment by waynebrantley** [comment]
It appears I need latest version of yarn and then this project requires yarn to run at root.
However, after 
```npm run start-dev```

Still get an error of
```
ERROR in ./configure-globalize-old.js
Module not found: Error: Can't resolve 'react-widgets-globalize' in 'C:\Projects\react-widgets\packages\storybook'
 @ ./configure-globalize-old.js 3:0-34
 @ ./config.js
 @ multi C:/Projects/react-widgets/node_modules/@storybook/react/dist/server/config/polyfills.js C:/Projects/react-widgets/node_modules/@storybook/react/dist/server/config/globals.js C:/Projects/react-widgets/node_modules/webpack-hot-middlewar
e/client.js?reload=true ./config.js
```

But it is much closer to working!

**Comment by jquense** [comment]
The repo uses yarn workspaces to bootstrap it. You need yarn v1+ and to run yarn in the root folder and it will install everything correctly

**Comment by waynebrantley** [comment]
I pulled the latest repo from your update an hour ago.
Installed latest version of yarn (1.32).  I deleted my node_modules folder and ran yarn again, it installed all necessary dependencies without issue.    (Several warnings about unmet dependenices on globalize, moment, react-dom, prop-types.)

I then executed ```yarn run start-dev```
This resulted in the following error:

```
ERROR in ./configure-globalize-old.js
Module not found: Error: Can't resolve 'react-widgets-globalize' in 'C:\Projects\react-widgets\packages\storybook'
 @ ./configure-globalize-old.js 3:0-34
 @ ./config.js
 @ multi C:/Projects/react-widgets/node_modules/@storybook/react/dist/server/config/polyfills.js C:/Projects/react-widgets/node_modules/@storybook/react/dist/server/config/globals.js C:/Projects/react-widgets/node_modules/webpack-hot-middleware/client.js?reload=true ./config.js
```

**Comment by waynebrantley** [comment]
I pulled the latest repo from your update an hour ago.
Installed latest version of yarn (1.32).  I deleted my node_modules folder and ran yarn again, it installed all necessary dependencies without issue.    (Several warnings about unmet dependenices on globalize, moment, react-dom, prop-types.)

I then executed ```yarn run start-dev```
This resulted in the following error:

```
ERROR in ./configure-globalize-old.js
Module not found: Error: Can't resolve 'react-widgets-globalize' in 'C:\Projects\react-widgets\packages\storybook'
 @ ./configure-globalize-old.js 3:0-34
 @ ./config.js
 @ multi C:/Projects/react-widgets/node_modules/@storybook/react/dist/server/config/polyfills.js C:/Projects/react-widgets/node_modules/@storybook/react/dist/server/config/globals.js C:/Projects/react-widgets/node_modules/webpack-hot-middleware/client.js?reload=true ./config.js
```

**Comment by neo182** [comment]
I am also struggling with similar issues now. I followed the documention strickly and ended with the following error message : 

` Uncaught Error: Cannot find module "react/lib/ReactComponentTreeHook"
    at webpackMissingModule (ReactDebugTool.js:16)
    at Object.<anonymous> (ReactDebugTool.js:16)
    at Object.<anonymous> (ReactDebugTool.js:360)
    at __webpack_require__ (bootstrap 5a7504844ebc8e3289c1:677)
    at fn (bootstrap 5a7504844ebc8e3289c1:87)
    at Object.<anonymous> (ReactInstrumentation.js:19)
    at Object.hasOwn (ReactInstrumentation.js:23)
    at __webpack_require__ (bootstrap 5a7504844ebc8e3289c1:677)
    at fn (bootstrap 5a7504844ebc8e3289c1:87)
    at Object.<anonymous> (ReactReconciler.js:14) `
