### ISSUE TITLE
bug: createClass is not a function

### ISSUE THREAD

**Issue by vladra** [jquense/react-widgets#688]
Hi guys,

I was using react 15 and react-widgets 3.5 before update. Now I finally trying to update my packages. But React 16.0 (and 16.1) + react-widgets 4.1.1 throws an error to me.

It looks like this:
```
TypeError: _react2.default.createClass is not a function

uncontrollable                                       createUncontrollable.js:52
./node_modules/react-widgets/lib/DropdownList.js            DropdownList.js:741
__webpack_require__
fn
./node_modules/react-widgets/lib/index.js                          index.js:10
__webpack_require__
```

Have anyone encountered same issue? Thanks!

**Comment by jquense** [comment]
sounds like you have pacakges somewhere. I'd nuke node_modules and try a fresh install

**Comment by vladra** [comment]
I've tried this already (and several times more now). Also I've tried different versions of React 16. But unfortunately everything works for me only with React 15.

**Comment by vladra** [comment]
It seems I should open this issue in the `uncontrollable` package, since this problem is related to https://github.com/jquense/uncontrollable/blob/master/lib/createUncontrollable.js#L52

please confirm if I should change issue location
