### ISSUE TITLE
Picking a time in a DateTimePicker with defaulValue fails in the first attempt

### ISSUE THREAD

**Issue by ferrannp** [jquense/react-widgets#69]
I noticed this in last version 2.3.1 and it is a pretty annoying bug. You can reproduce it in your example page: http://jquense.github.io/react-widgets/docs/#/datetime-picker

Going to the page (and without touching anything else), go to a date that has a default value or that has already a value on it, like this one:

![pickingTimeBug](http://i.imgur.com/E1q1P1E.jpg)

Try to pick up a new time (writing it works), first time fails (it moves to old time and it doesn't close the popup). Second attempt works.

**Comment by ferrannp** [comment]
I am sorry to say I saw this bug again... Now is more difficult to reproduce (I don't see a pattern) but I could reproduce it in your page, one of the default dates was showing: 

Friday, March 20, 2015 6:18 PM

I select 9PM and it got back to 6PM without closing the popup. It fails much more in my component that in your page though.

**Comment by jquense** [comment]
oof wow this is a really annoying bug. I keep looking...

**Comment by ferrannp** [comment]
This info might help or not but before using 2.3.1 and 2.3.2, I was using 2.1.0 and I've never seen that bug in there.

**Comment by ferrannp** [comment]
Nice, I didn't see the bug anymore. However, I am not sure if it's related or not but... In this example, I set up the dates with a value programmatically (when users clicks a checkbox), now, when opening the time picker, the picker is not scrolled in the position it should be (showing selected time) so it's a bit confusing.

**Comment by jquense** [comment]
I think I found the correct way to handle this...and I am finally gonna get it REALLY fixed.
