### ISSUE TITLE
Is there a shorthand for an "ALL" select for Multiselect?

### ISSUE THREAD

**Issue by Ashwin117** [jquense/react-widgets#692]
I don't see it in the docs, but a shorthand for ALL would be nice. It should prevent additional selections since ALL should cover for it.

**Comment by jquense** [comment]
There isn't an API or prop for it. You can do it tho by setting the `data` to the `value` prop

**Comment by Ashwin117** [comment]
Sure of course that's a way to do it, but an 'ALL' value is typically a common Product requirement. For instance, I want to see the text 'ALL' or whatever I would want to configure

**Comment by jquense** [comment]
That's the sort of thing that is best handled in your  app via a wrapper components. It may be a fairly common thing but _how_ folks want to do it is rarely generalizable :) so it's best left to individuals  to handle according to their designs. On our side we try and make it easy to extend for such things. In this case one way to handle it is to have a wrapper add an "All" item and wrap the onChange to catch that special value, to set all the values
