### ISSUE TITLE
Sass-loader error: Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by estermer** [jquense/react-widgets#693]
So I am currently upgrading my Webpack to 3.8 and it required some upgraded dependencies such as `"node-sass": "^4.0.0"` and `"sass-loader": "^6.0.6"`.

I am getting a build error stating that react-widgets is using a base level rule improperly:

```bash
Module build failed: ModuleBuildError: Module build failed: 
&.rw-state-disabled {
^
      Base-level rules cannot contain the parent-selector-referencing character '&'.
Backtrace:
	src/_scss/react-widgets/scss/core.scss:139
```

Is there any fix or upgrade or configuration I am missing to get this to build properly?

Here is my webpack config for the scss laoder with the latest version of extract-text-webpack-plugin:

```js
{
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: ['css-loader', 'sass-loader'],
  }),
},
```

**Comment by jquense** [comment]
I'm not sure what the error refers to, but you might try upgrading react-widgets

**Comment by estermer** [comment]
I appreciate it, I had to do some upgrading to my local sass files for react widgets to the newest version and it helped.
