### ISSUE TITLE
Show date and time picker buttons separately.

### ISSUE THREAD

**Issue by lsm** [jquense/react-widgets#694]
@jquense Are you positive about the changes below?  Having them together is a little bit confusing (for me).

If yes I can send a PR real quick.

![peek 2017-11-10 10-51](https://user-images.githubusercontent.com/172359/32802115-f1873070-c933-11e7-9021-b87dae5a8bd2.gif)

**Comment by jquense** [comment]
I'm ok with the way the styles work now thanks!
