### ISSUE TITLE
Error: Can't resolve 'react-widgets/lib/localizers/moment' in 4.1.1

### ISSUE THREAD

**Issue by eriklharper** [jquense/react-widgets#697]
How can my components access the `momentLocalizer` function in the `4.1.1` build?  I'm upgrading to React 16 and along with it, this package and I'm having trouble finding where to import this function from in the newest 4.1.1 version.

**Comment by jquense** [comment]
It's not there anymore they moved to separate packages. Please read the docs for i18n or the migration doc in the repo here

**Comment by eriklharper** [comment]
I got it working, yes, thanks for the tip.  I just had to change the import statement to `import momentLocalizer from "react-widgets-moment";` and that did it! 👍
