### ISSUE TITLE
Calendar widget failing with following "Cannot read property 'map' of undefined"

### ISSUE THREAD

**Issue by jothi-pyt** [jquense/react-widgets#699]
Calendar widget in react-widgets latest failing at Month.js#119 

![screen shot 2017-11-28 at 8 11 29 pm](https://user-images.githubusercontent.com/23206756/33325489-6d4c2d06-d478-11e7-89c7-d0906fd606fb.png)

react v16
react-widget 4.1.0 ( latest )

**Comment by jquense** [comment]
can't reproduce on the current version

**Comment by tarim** [comment]
I also have same issue. with react v15.x

Thanks,

**Comment by ioanachi** [comment]
I also have this error. What can we do?

**Comment by papiliond** [comment]
Any progress with this issue? Thanks!

**Comment by joshparolin** [comment]
Just a heads up, I have customers experiencing this exact error as well who are located in Lisbon ('pt') and Barcelona ('ca'). Assuming this is a weird localization / compatibility issue. I tried to replicate using customer's exact settings in a virtual environment but couldn't replicate. However, customers continue to experience it on their end.
