### ISSUE TITLE
DateTimePicker localization not translating headers anymore

### ISSUE THREAD

**Issue by ferrannp** [jquense/react-widgets#70]
Trying Spanish language, I had this in an older version:

![old](http://i.imgur.com/h8kx2sd.jpg)

Which is ok, lu, ma, mi... are Spanish.

In version 2.3.1:
![new](http://i.imgur.com/x8sl6fv.jpg)

Footer is ok. But headers are not translated anymore.

Something am I doing wrong? Or is it a bug?

**Comment by jquense** [comment]
seems like a bug! let me check
