### ISSUE TITLE
Multiselect : Avoid Picker from growing in size, add vertical scrollbar and keep the dropUp condition.

### ISSUE THREAD

**Issue by mharocsc** [jquense/react-widgets#700]
Hi. I'm using your Multiselect component (which is great btw) that it's inside a fixed div in size, but when there's a lot of selected elements, the picker grows in size, and some items are lost inside my div (visually). 

I was able to fix the size of the picker, add a vertical scrollbar, this way I'm able to keep my div size and see all the selected elements... BUT doing this, when I open the dropdown is not visible anywhere. I  manipulated the z-index of the rw-popup class and I was able to pull-out the dropdown, but now my dropUp parameter doesn't work, because I had to change the position to fixed, to be able to see the dropbown, so my dropdown appears down and I need the dropdown up.

I hope I was clear with my issue. Do you guys, have a way to do all that? (limit size of the picker, add vertical scrollbar and keep the dropUp), without me manipulating the component classes and ruining all the component behavior? :(

**Comment by boriskogan81** [comment]
```
.rw-widget-container {
	max-height: 10vw;
	overflow-y: scroll;
}
```
Does not work.

**Comment by jquense** [comment]
yeah it probably isn't that simple. a lot of the styling there uses `display: table` in order to support ie9, if you don't need to do that you can try using flexbox. you're probably going to have to be fairly invasive with style overrides

**Comment by boriskogan81** [comment]
What approach do you recommend with Flexbox?

**Comment by jquense** [comment]
I don't have a specific solution for this, but we aren't planning to directly support this use case, if someone can figure out with css go for it!

**Comment by vinsx** [comment]
Workaround:
.rw-dropdownlist .rw-list {
  max-height: 85px !important;
  height: auto;
}

**Comment by connerludlow** [comment]
This worked for me:

`
.rw-widget-input  {
     display: block;
     height: 45px;
     max-height: 90px !important;
     overflow-y: scroll;
}
`

**Comment by pritam-sust** [comment]
This solution is worked for me. I removed the SelectIcon and also closed the DropdUp/Down option but it should work for both:
.rw-multiselect-taglist {
    max-height: 15.5rem;
    overflow-y: auto;
    border-bottom: 1px solid #eee;
    scrollbar-width: thin !important;
  }
