### ISSUE TITLE
Changelog for v4?

### ISSUE THREAD

**Issue by thom-nic** [jquense/react-widgets#702]
I can't find any changelog for v4.  Presumably since it's a semver-major change there are incompatibilities.

**Comment by jquense** [comment]
https://github.com/jquense/react-widgets/blob/master/www/src/pages/migration-v4.md

**Comment by thom-nic** [comment]
Thanks.  I was thrown off by the incomplete changelog in CHANGELOG.md.  I can't seem to find that guide on http://jquense.github.io/react-widgets/ either.  Thanks again.
