### ISSUE TITLE
Can I use my own css files to manipulate these widgets?

### ISSUE THREAD

**Issue by lvdang** [jquense/react-widgets#703]
Can I use my own css files to manipulate these widgets?

**Comment by jquense** [comment]
sure

**Comment by lvdang** [comment]
@jquense Sorry, I should have been more clear. How would I add my own css class and not use any default? Is there a prop I am missing?

**Comment by jquense** [comment]
You can add classes with the className prop like you might on other react components. There isn't anything fancy with the styling here, we add css classes to the widgets and have corresponding css. You can write or overwrite anything you want with your css!
