### ISSUE TITLE
Keep formatting when focused

### ISSUE THREAD

**Issue by ThatGuySam** [jquense/react-widgets#704]
First off, this library has made my life easier than you'll ever know. 

Whenever you click to focus into a NumberPicker field the input loses it's nice looking formatting.

Is there any option or common method to keep formatting when focused?

**Comment by jquense** [comment]
Check out the editFormat prop

**Comment by ThatGuySam** [comment]
editFormat would be perfect, unfortunately it's only used on DateTimePicker

https://github.com/jquense/react-widgets/search?utf8=%E2%9C%93&q=editFormat&type=

**Comment by jquense** [comment]
ah right. The main reason there isn't one now is that the parsing for numbers is "greedy" meaning you'll get a change callback for any valid number as it's typed. That behavior is a lot more challenging to implement if the value is in an arbitrary format. Practically its probably not likely to be implemented give those constraints but i'll leave this here. You may also want to use masked input like react-masked-input
