### ISSUE TITLE
Augmenting DropdownList to add allowCreate for TypeScript

### ISSUE THREAD

**Issue by mjlevine** [jquense/react-widgets#705]
Noob here, so please excuse the fact that this is probably not even the right way or place to ask this, please forgive.

I'm using react-widgets 4.1.1 and types/react-widgets 3.2.32.  I want to create a DropdownList that uses the allowCreate property.  It doesn't exist in the types file.  I've tried a number of suggestions for augmenting the definition of DropdownList to add allowCreate but am having no success.

I have added a `ExtendedDopdownList.d.ts` file that contains
```
declare module DropdownList {
  export interface DropdownList {
    allowCreate: string;
  }
}
```

and have tried a few other suggestions.  

Currently I get

>  Property 'allowCreate' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DropdownListProps, ComponentState>> & Re...'.

Has anyone had success augmenting types to support this library?  
Should I be asking this in the DefinitelyTyped project instead?

**Comment by teves-castro** [comment]
The types for this lib have fallen a bit behind the library itself, so I think the best way would be to create a PR on the DefinitelyTyped project instead.
