### ISSUE TITLE
Multiselect - how to display just number of selected items

### ISSUE THREAD

**Issue by paras-malhotra** [jquense/react-widgets#708]
Is there a way to just display the number of selected items in MultiSelect? For instance, if there are 2 items selected, instead of displaying the 2 selected items with the tag, it just displays "2 selected"?

**Comment by jquense** [comment]
Hey there. There isn't away to do that with the multiselect, that would dramatically change how one interacts with the widget (how would you deselect items). You really need almost an entirely different component for that

**Comment by paras-malhotra** [comment]
Makes sense, thanks for letting me know!
