### ISSUE TITLE
max (Date) also for time? (on DateTimePicker)

### ISSUE THREAD

**Issue by ferrannp** [jquense/react-widgets#71]
Hello! I was very happy about the "max" prop where you can limit the user to select future dates given a max. 

Although, I notice that user is not able to select any time from the time picker if the selected day is the "max" day. Time picker shows this:

![noTime.jpg](http://i.imgur.com/VCA58Vp.jpg)

If I have a max time like 04/19/2015 04:00, would be possible that the widget still lets me pick time from 00:00 to 04:00 when the chosen day is 19th?

**Comment by ferrannp** [comment]
Hello! Thanks for this, however I noticed something... Let's say I have to pickers: start and end. The max from start will be the "end" date & time. 

If I change the end day, the max from start gets update correctly... But not the time, even if I change the end time, the start time limit doesn't change.

**Comment by jquense** [comment]
found the issue! thanks for tracking all these down for me
