### ISSUE TITLE
Would you like a PR to set up semantic-release and commitlint?

### ISSUE THREAD

**Issue by jedwards1211** [jquense/react-widgets#712]
The changelog leaves a little to be desired... there's no information about what breaking changes are in v4, let alone any info about v4 to begin with, and many releases are missing any information.

I use `semantic-release` and `commitlint` to avoid this in my packages: `commitlint` forces me to write meaningful commit messages that describe what has changed and whether it's a bugfix, new feature, or breaking change, and `semantic-release` automatically publishes new versions of the package from my CI builds, and automatically writes the changelog associated with each release on GitHub from those commit messages.

Do you want me to make a PR to set up `semantic-release` and `commitlint`?  It would be easy, though I don't know if you're comfortable with automatic releases.

**Comment by jquense** [comment]
sure if you're up for it 👍
