### ISSUE TITLE
Include instructions for loading fonts with gulp and browserify

### ISSUE THREAD

**Issue by udalrich** [jquense/react-widgets#716]
I use `gulp` and `browserify` to bundle my application.  I figured out that, with`browserify-css` I can import the css with 

    import 'react-widgets/dist/css/react-widgets.css';

However, it is not clear to me how to load the fonts.  I can see that it is trying to load fonts from http://localhost:9000/ui/node_modules/react-widgets/dist/fonts/rw-widgets.woff?v=4.1.0 (where the page is loaded from http://localhost:9000/ui/index.html).  

If there is a way to change the location of the font to something like /assets/rw-widgets.woff, I know how to serve a specific directory, but with the path going all the way to node_modules, it becomes difficult to make that work.

**Comment by jquense** [comment]
font requires are relative to where the files are. I don't really know anything about browserify but you can always copy the files from node_modules to where ever you serve css from
