### ISSUE TITLE
Date fns Localizer

### ISSUE THREAD

**Issue by ecancino** [jquense/react-widgets#723]
Thanks for this great library!

I have created a localizer for my own needs with [date-fns](https://www.npmjs.com/package/date-fns) functions that i named [react-widgets-dates](https://github.com/ecancino/react-widgets-dates).

If it is of interest I could add it here to the packages in the same format as your own.   

Thank you!

**Comment by jquense** [comment]
i love that! please send a PR if you have time :) Thanks!
