### ISSUE TITLE
Methods for Multiselect onBlur handling

### ISSUE THREAD

**Issue by rnkdev** [jquense/react-widgets#727]
Hi guys, 

Just wondering what's the best way to handle onBlur event with Multiselect component. 

The reason for me asking this is because of the use case requirement I'm facing. I want to have the Multiselect to automatically create new value when the user has finished typing their entry and has moved on to another input controller (or leaves the Multiselect input interface). 

Currently the user has to press Enter button after entering their new data on the Multiselect. 

I saw this.handleBlur function written on the Multiselect.js, but I don't think this can be accessed by other component. 

Thank you

**Comment by jquense** [comment]
You can handle the blur event like normal with an onBlur prop!

**Comment by rnkdev** [comment]
Hi @jquense, yup this is great! I have tried it and it works with the use case I mentioned. 

Just realised it's not at the https://jquense.github.io/react-widgets/api/Multiselect/ docs, so I was a bit puzzled at first. 

Thanks for your prompt help.

**Comment by rnkdev** [comment]
Will close the issue, as I think it's been solved.

**Comment by MJfenix** [comment]
Hi @rnkdev Can you help me with how you were able to create those keywords in onBlur? I have the same use case as yours.

https://github.com/jquense/react-widgets/issues/737
