### ISSUE TITLE
Must access array elements with a number, not "undefined"

### ISSUE THREAD

**Issue by Xurma2** [jquense/react-widgets#728]
I get this error when setting the focus a second time.
I'm using the redux form along with the components

throw new Error('Must access array elements with a number, not "' + String(first) + '".');
https://github.com/erikras/redux-form/issues/3753
Firs I think its redux-form 

![image](https://user-images.githubusercontent.com/5157416/35168577-7a6cf0ea-fd6a-11e7-98b8-0b2d59c6ce70.png)

**Comment by jquense** [comment]
hi there, seems like an issue in redux-form, not sure why you'r opening the issue here...
