### ISSUE TITLE
Jest testing: DateTimePicker: prop type `defaultOpen` is invalid; it must be a function, usually from React.PropTypes.

### ISSUE THREAD

**Issue by ferrannp** [jquense/react-widgets#73]
First, sorry for so many opened issues recently! So I had a Jest test for a component that is using DateTimePicker and it stopped working with recent version, I'll paste you the excpetion:

    /node_modules/react-widgets/lib/index.js: /node_modules/react-widgets/lib/DateTimePicker.js:    Invariant Violation: DateTimePicker: prop type `defaultOpen` is invalid; it must be a function, usually from React.PropTypes.
     at invariant (/node_modules/react/lib/invariant.js:42:15)
     at validateTypeDef (/node_modules/react/lib/ReactCompositeComponent.js:405:48)
     at Object.RESERVED_SPEC_KEYS.propTypes (/node_modules/react/lib/ReactCompositeComponent.js:377:5)
     at mixSpecIntoComponent (/node_modules/react/lib/ReactCompositeComponent.js:510:31)
     at Object.ReactCompositeComponent.createClass (/node_modules/react/lib/ReactCompositeComponent.js:1385:5)
     at module.exports (/node_modules/uncontrollable/lib/uncontrollable.js:42:16)
     at /node_modules/react-widgets/lib/DateTimePicker.js:354:18

I am not sure why this is happening mmm, does even DateTimePicker has a defaultOpen prop? I am not using any ```defaultOpen``` or ```open``` prop when using ```DateTimePicker```.

**Comment by jquense** [comment]
This sounds like Jest is doing something weird to mock the component...

The `defaultOpen` is added automatically by `uncontrollable` which wraps each component and handles the controlled/uncontrolled stuff for specific props and handlers. It is set to a whatever the value of `propTypes.open` is. Normally that is a valid propType, my assumption is that Jest is stubbing out these properties poorly perhaps? I am not familiar with jest so I am not sure how to help, maybe you could let me know what the value is [here](https://github.com/jquense/uncontrollable/blob/master/src/uncontrollable.js#L35) during the test?

**Comment by ferrannp** [comment]
With a console.log in there I got:

```
{ [Function] isRequired: [Function] }
{ [Function] isRequired: [Function] }
{ [Function] isRequired: [Function] }
{ [Function] isRequired: [Function] }
{ [Function] isRequired: [Function] }
{ [Function] isRequired: [Function] }
undefined
undefined
```

I assume the ```undefined``` is the problem here... I tried to wrapped it up like this:

      if(type !== undefined) {
        invariant(typeof handler === "string" && handler.trim().length, "Uncontrollable - [%s]: the prop `%s` needs a valid handler key name in order to make it uncontrollable", Component.displayName, prop);
        obj[prop] = customPropType(handler, type);
        obj[defaultKey(prop)] = type;
      }

And this makes the test pass ok. Hope it helps.

**Comment by jquense** [comment]
would you mind sending a PR to: [uncontrollable](https://github.com/jquense/uncontrollable)

and one nitpick, you only need to wrap the final line, We still want the handler proptype to be set in this case, and `customPropType()` already checks the type exists/

```js
invariant(typeof handler === "string" && handler.trim().length, "Uncontrollable - [%s]: the prop `%s` needs a valid handler key name in order to make it uncontrollable", Component.displayName, prop);
obj[prop] = customPropType(handler, type);

//just here is fine
if( type !== undefined ) {
   obj[defaultKey(prop)] = type;
}
```
