### ISSUE TITLE
Unable to set currentDate properly when using redux-form

### ISSUE THREAD

**Issue by rovnyart** [jquense/react-widgets#733]
Originally posted it on stackoverflow but no answers there. I think this thing must be cleared somehow in doco, or at least here.

I have two DateTimePicker components in redux-form for filtering some data a period of time. I want to change the first picker currentDate when I change the second one, but I can't figure out how to do it. Here is my component code:

```
function DatePicker({ label, placeholder, className, required, time, min, max, input, meta, ...props }) {
  return (
    <div className={cn({ error: meta.error && meta.touched }).mix(className)()}>
      {label && <label htmlFor={input.name} className={cn('label', { required })()}>{label}</label>}
      <DateTimePicker
        value={(input.value && new Date(input.value)) || null} placeholder={placeholder} messages={messages}
        format={!time ? 'LL' : 'LLL'} editFormat={!time ? 'DD/MM/YYYY' : 'DD/MM/YYYY HH:mm'}
        time={time} min={min} max={max}
        onChange={(date) => {
          const newValue = date !== null && !time ? moment(date).format('YYYY-MM-DD') : date;
          input.onBlur(newValue);
          return input.onChange(newValue);
        {...props}
      />
      {meta.error && meta.touched && <InputError>{meta.error}</InputError>}
    </div>
  );
}
```
Here is how i use it inside redux-form

```
render() {
  const { beginDate, endDate } = this.props;
  const minStartDate = endDate ? new Date(endDate) : new Date(2017, 0, 1);
  const minEndDate = beginDate ? new Date(beginDate) : new Date(2017, 0, 1);
  const maxStartDate = endDate && new Date(endDate);
  return (
    <Field
      label="From" className="col-lg-4 col-md-6 col-sm-12"
      min={minStartDate} max={maxStartDate} time
      name="beginDate" component={DatePicker} step={60}
    />
    <Field
      label="To" className="col-lg-4 col-md-6 col-sm-12"
      min={minEndDate} time
      name="endDate" component={DatePicker} step={60}
    />
   );
  }
```
Now i want to change the currentDate prop, so I calculate it in render:

`const currentDate = endDate ? new Date(endDate) : new Date();`

And then i put it as a prop to Field component:

```
<Field
  label="From" className="col-lg-4 col-md-6 col-sm-12"
  min={minStartDate} max={maxStartDate} time
  name="beginDate" component={DatePicker} step={60}
  currentDate={currentDate}
/>
```
Now i'm getting a warning: Failed prop type: **_You have provided a currentDate prop to DateTimePicker without an onCurrentDateChange handler. This will render a read-only field. If the field should be mutable use defaultCurrentDate. Otherwise, set onCurrentDateChange_**

Okay, i have to set onCurrentDateChange. But what EXACTLY fo I have to write there? I tried everything. I tried it this way:

```
<Field
  label="From" className="col-lg-4 col-md-6 col-sm-12"
  min={minStartDate} max={maxStartDate} time
  name="beginDate" component={DatePicker} step={60}
  currentDate={currentDate}
  onCurrentDateChange={() => {}}
/>
```
I tried it in another place:

```
<DateTimePicker
  onCurrentDateChange={(date) => {
    const newValue = date !== null && !time ? moment(date).format('YYYY-MM-DD') : date;
    return input.onCurrentDateChange(newValue);
  }
  {...props}
/>
```
Nothing helpes me at all - the currentDate does change, but it doesn't allow me to change months with arrow buttons. I've read all of the issues and found [this](https://github.com/jquense/react-widgets/issues/434) one, whit was closed twice without any explanaition. So please, help me, anyone. What should i write in this onCurrentDateChange handler? There is no doco about it, no examples, nothing. Thanks a lot for help.

**Comment by jquense** [comment]
I don't know much about redux-form sorry :/

**Comment by Shadowman4205** [comment]
@rovnyart  Hello i used defaultCurrentDate instead of currentDate (and set it to max date) it seems ok now.
