### ISSUE TITLE
I'd like a prop to format the color of your component

### ISSUE THREAD

**Issue by Ashwin117** [jquense/react-widgets#735]
For example, for your calendar selection, the default is blue.
<img width="257" alt="screen shot 2018-01-26 at 2 31 14 am" src="https://user-images.githubusercontent.com/16282701/35435866-1fd649e8-0241-11e8-8735-bdabfd5db0db.png">

I want to make it whatever color I want.

**Comment by jquense** [comment]
you can do that! Components are styled very intentionally straightforwardly to allow overriding via css. almost every piece has it's own css class that can be tweaked via css. Or if you want more specific control you can build the styles from the included SCSS or Less files and adjust the variables to suit your needs.

**Comment by Ashwin117** [comment]
I see, so there is a CSS solution to it. It could be nice to have a prop for it?

**Comment by jquense** [comment]
its not really feasible to have both options since all styling is handled by css, having a prop would make theming and cascading styling complicated and most likely unhelpful
