### ISSUE TITLE
Time picker freezes on spring daylight savings day

### ISSUE THREAD

**Issue by asakaplan** [jquense/react-widgets#739]
I'm having an error where, if the datetime picker is used on a spring DST day (e.g. March 12, 2017), clicking on the time picker will crash the webpage. I found the offending code, but I'm a bit confused why it hasn't been an issue for others---is there a very simple work around?

<pre>
function createAccessor(method){
  return function(date, val){
    if (val === undefined)
      return date['get' + method]()
    date = new Date(date)
<b>    date['set' + method](val)</b>
    return date
  }
}
</pre>

`setMinutes` is called with a value of 60, which usually increments to the next hour. But it doesn't on daylight savings, as it always assumes it's the 'first' 2am. This makes the method that creates all times for a day run in an infinite loop as it cycles 2am -> 2:30am -> 2am. 

Any ideas?

**Comment by asakaplan** [comment]
For anyone with a similar problem, I used the following workaround:

```
//DST fix for browser that aren't super up to date
var _setMinutes = Date.prototype.setMinutes;
Object.defineProperty(Date.prototype, 'setMinutes', {
    value: function (minutes) {
        var original = _setMinutes.bind(this);

        if (minutes < 60) {
            original(minutes)
        }
        else {
            var startTime = this.getTime()
            original(minutes)
            if (this.getTime() <= startTime) {
                original(minutes + 60);
            }
        }
    }
});
```

There's a bit of discussion [here](https://bugzilla.mozilla.org/show_bug.cgi?id=742427) about the bug existing in javascript.

**Comment by jquense** [comment]
care to PR your fix upstream?

**Comment by asakaplan** [comment]
I could, but it didn't seem like a fix---more of a work around by modifying the setminutes function in Date. I could submit a pull request in a few hours if you want.

**Comment by jquense** [comment]
we don't use setMinutes directly so you can put the fix in the function in date-arithmetic where you noted the error in the first comment :)
