### ISSUE TITLE
duration prop applies to calendar dropdown but not for time dropdown

### ISSUE THREAD

**Issue by mmilo** [jquense/react-widgets#74]

**Comment by mmilo** [comment]
I don’t think this actually fixes the issue I was mentioning.

Basically if you pass a duration prop into the component with a value of 0. Clicking on the calendar button displays its dropdown with no animation, but clicking on the time button displays its dropdown with an animation with what appears to the default duration.

**Comment by jquense** [comment]
Sorry, it is fixed it's just tagged to the wrong commit here.  https://github.com/jquense/react-widgets/commit/581c58b63dcaa41930604d8d1586f0229fd17e9e

**Comment by mmilo** [comment]
Ahh cool, much obliged :+1:
