### ISSUE TITLE
Is it possible to have a multiselect with a search dropdown?

### ISSUE THREAD

**Issue by Ashwin117** [jquense/react-widgets#740]
My use case is to have a search bar and then issue an ajax request to populate the dropdown with all values that match the prefex of the search. But the dropdown should be multi-selectable. Does the library support such a use case or is it a feature that hasn't been put in?

**Comment by jquense** [comment]
The multiselect is already searchable by typing. If you want to laod more data as you type, listen to the `onSearch` event and make your ajax call, I suggest setting `busy` to true while you are waiting for the data
