### ISSUE TITLE
Problem with DropdownList on IOS

### ISSUE THREAD

**Issue by RussianDragon** [jquense/react-widgets#746]
Hi.
We have problem with DropdownList conponent
https://jquense.github.io/react-widgets/api/DropdownList/

It is not work in iframe on ios devaces.
MacBook - does not work at all.
IPhone - work is strange. Sometimes, after select, window scrolling to bottom. (maybe need zoom)

-------------------------
Добрый день.
У нас возникла проблема с DropdownList
Причем только в iframe на IOS.
MacBook - даже ваши тесовые примеры не открываются.
IPhone - работает странно. На вашем сайте с примерами, при наличии зума, после выбора элемента страницу кидает вниз. Иногда, также как и на MacBook просто не дает выбрать.

**Comment by jquense** [comment]
That sounds like something conflicting in your setup maybe? The widget works without issue on my macbook in a lot of different contexts

**Comment by RussianDragon** [comment]
We see this problems on three devices.
Without iframe work is ok, but if site (exemple: https://jquense.github.io/react-widgets/api/DropdownList/) open in iframe - we have problems.
this is hardly an environment

**Comment by jquense** [comment]
I don't think there is anything I can do about it's behavior in an iframe. that sounds like a React bug.
