### ISSUE TITLE
Is there a way for me to display something different on the UI than what I have as the value?

### ISSUE THREAD

**Issue by Ashwin117** [jquense/react-widgets#749]
For example, lets say I have a list of animals. When I select dog, cat, cow, moose, elephant, and dolphin, I've selected 6 items. On the UI, I want to display "6 selected" instead of all the 6 animals as too much space is taken. Is it possible to do this?

Thanks.

**Comment by jquense** [comment]
You can somewhat control this with the `ValueComponent` but it won't really meet the use-case above, that would change the fundamental UX of the Multiselect, and present some issues since the selected items don't appear in the list anymore so there would be no  way to deselect them.
