### ISSUE TITLE
How do you prevent the container from resizing when a bigger item is selected?

### ISSUE THREAD

**Issue by Ashwin117** [jquense/react-widgets#750]
Here's an example.
<img width="259" alt="screen shot 2018-02-07 at 2 19 42 pm" src="https://user-images.githubusercontent.com/16282701/35944733-6259f1f4-0c12-11e8-97a4-837547ca632d.png">

But after I select another item, the container expands to this:
<img width="325" alt="screen shot 2018-02-07 at 2 20 49 pm" src="https://user-images.githubusercontent.com/16282701/35944742-6dd645be-0c12-11e8-9c0e-3ac3c064128c.png">

Right now, this is pushing everything to the right and it looks unsightly.

How I prevent the resize? How do I get the **scrollable** feel to view the long items with a fixed container?
Thanks!

**Comment by jquense** [comment]
If you want a fixed or max with input, you can use css or styles to set a max-width. I don't know that anyone has made this work with a scrolling list tho

**Comment by Ashwin117** [comment]
Yeah I can't get it to work :(
