### ISSUE TITLE
Is it possible to change the color of the checkbox/radio buttons?

### ISSUE THREAD

**Issue by Ashwin117** [jquense/react-widgets#751]
It would be really awesome if there's a way to do this. It would really distinguish this library from its competitors :)

**Comment by jquense** [comment]
We are limited here by what is possible with css for the browsers we support without completely reimplement in checkboxes unfortunately. And traditionally the styling options for checkboxes/radios are pretty slim. We may want to add the ability for the advanced user to swap out the checkbox tag with a custom one if they desire but there hasn't been a big demand for that (and I've not needed it at work)
