### ISSUE TITLE
deselect DropdownList

### ISSUE THREAD

**Issue by mstruensee** [jquense/react-widgets#752]
any way to add a deselect option to DropdownList?
or an X remove icon like the tags have?

**Comment by jquense** [comment]
There isn't a button or anything (I'm not super happy with the UX of clear buttons in dropdowns). The general strategy would be like a normal select tag, add an empty option the user can select

**Comment by mstruensee** [comment]
that was my intermediate solution ... I was just trying to have it back to the "placeholder" look on the UI ...

**Comment by jquense** [comment]
I'm open to a different option, generally in my usage i add an EmptyOption via a wrapper that styles it appropriately but is implemented via the above strategy

**Comment by mstruensee** [comment]
I will give that a try, I really like how the UI looks with placeholder vs an empty option.  
I will let you know what I come up with.

**Comment by mstruensee** [comment]
In this specific scenario, "None selected" means all, so the empty value selects "All" on render.  I am happy with this for this scenario.

**Comment by jquense** [comment]
I was going to add the placeholder will show up if the valueField is `null` or `undefined` so you can have your valueField for the empty option be null but still have text in the dropdown

**Comment by mstruensee** [comment]
perfect! that is what was the main reason for the confusion, to me "null / undefined" was different that "none selected / none"

**Comment by jquense** [comment]
its sort of a happy coincidence it works, since we really have no concept of what an "empty" value is, but inorder to know when to show the placeholder we needed to check _something_, so yeah. `null`/`undefined` doesn't mean "none selected" but it does mean "show the placeholder"

**Comment by mstruensee** [comment]
👍
