### ISSUE TITLE
display time in input but disable dropdown to change it

### ISSUE THREAD

**Issue by mstruensee** [jquense/react-widgets#753]
current scenario is setting the time to zero o'c onChange, which reflects in the UI perfectly ... I want to show the time, but prevent users from changing it from zero o'c ... can a flag to display time but disable change be added DateTimePicker? (disabledTime??? as time defaults to true)

current fix: added scoped css to add default cursor to rw-select and adding cursor: not-allowed to button[aria-label='Select time'] (dealing with clicks currently)

**Comment by jquense** [comment]
I'm fairly sure you just ned to change the `format` to show the time. Disabling the button shouldn't* prevent values with time just prevent selecting a time

**Comment by mstruensee** [comment]
that worked, I set time={ false } and set the format to display time.  thanks!
