### ISSUE TITLE
Error on Dropdownlist on listComponent onEntering callback

### ISSUE THREAD

**Issue by Satherial** [jquense/react-widgets#755]
Hello,
we are trying to use the listComponent feature of the Dropdownlist to use a custom react component.
The error is:
**Uncaught TypeError: Cannot read property 'forceUpdate' of null**
While debugging we have found the error here:
```
shouldRenderPopup && _react2.default.createElement(
        _Popup2.default,
        {
          open: open,
          dropUp: dropUp,
          transition: popupTransition,
          onEntered: function onEntered() {
            return _this2.focus();
          },
          onEntering: function onEntering() {
            return _this2.refs.list.forceUpdate(); <== ERROR
          }
        },
        this.renderList(messages)
      )
```

list is null
Hanging on the breakpoint the custom list component is correctly rendered, but it disappears after the error.
The example custom list component we were using to test this feature renders a simple _table_ .

**Comment by jquense** [comment]
Yes, it's a known bug, lists are excepted to be able to have a ref. For the time being the workaround is to not use stateless function components for the list component

**Comment by Satherial** [comment]
ok thank you,

**Comment by eric19860517** [comment]
@jquense Could you please provide a sample for this?
