### ISSUE TITLE
How to specify order of groups in Multiselect

### ISSUE THREAD

**Issue by CCinCapital** [jquense/react-widgets#758]
Thanks for creating such a useful, and well written library.

I just had a quick question regarding specifying the order of grouped components in Multiselect.

I currently am using the Multiselect component to display countries, and have created groupings of countries using the `groupBy` prop.

As you can imagine sometimes we want to have quick access to countries that are closer to the customer. As such we currently have a `North America` group and a `Other Countries` group.

How can I make sure `North America` shows up on the top?

**Comment by jquense** [comment]
Sort order is maintained when grouping, meaning the groups will render in the order they are collected. If you sort by the grouped value (and optional another thing like name) that will be the order groups are rendered in. Lodash's sortByOrder method makes that nice and easy but you can use anything

**Comment by jquense** [comment]
Should be added, you probably need to separate your grouBy and your rendering of the group, by providing a group Component. So you can manually control how the names sort

**Comment by CCinCapital** [comment]
👍 Thanks for the help, appreciate it.
