### ISSUE TITLE
Wrong declaration of props

### ISSUE THREAD

**Issue by saharshg** [jquense/react-widgets#759]
The props { view and date } documented in Calendar and DateTimePicker of react-widgets are not working. The solution for this is to use 'initialView' prop instead of 'view' and 'calendar' prop instead of 'date'. 

```
<DateTimePicker
   calendar={true}
   initialView={'decade'}
/>
```

**Comment by jquense** [comment]
You may be an old version, `initialView` doesn't exist anymore in v4
