### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by krazyjakee** [jquense/react-widgets#760]
Trying out the demo for the DateTimePicker and I get `You are attempting to use a widget that requires localization`. There is no documentation for localizers as the URL provided 404s: http://jquense.github.io/react-widgets/docs/#/i18n

I shouldn't have to use a localizer as by default it should use the current locale.

**Comment by jquense** [comment]
http://jquense.github.io/react-widgets/localization/

> I shouldn't have to use a localizer as by default it should use the current locale.

Where did you see that? The note is accurate you must configure a localizer to use localized widgets, there is no "current locale" as all the supported browsers have almost no built in api's for doing these things

**Comment by krazyjakee** [comment]
Omg I got it working with the moment localizer. What a beautiful widget, thank you!

**Comment by dkumarx** [comment]
@jquense I am new to react-widget and would like to use DateTimePicker. But, I am not able to configure "moment localizer". I have followed your document and blogs as well but no luck. I am using standalone as libraries. 

Note: I am not using any NPM/Yarn or other boilerplate to build my React Application. I am using CDN link as standalone react app with Redux-Form. It would be much appreciated if you could help in this regards. Thanks in advance your kind attention and help.
