### ISSUE TITLE
DateTimePicker inputprops doesn't works

### ISSUE THREAD

**Issue by Gi972** [jquense/react-widgets#763]
Hello,

When I put `<DateTimePicker   inputProps={{readOnly:true}} />`

It doesn't work and when I try "readonly" I have a Warning: 
"Invalid DOM property `readonly`. Did you mean `readOnly`?" and it doesn't work also.

Thanks

**Comment by breadadams** [comment]
The `readOnly` prop needs to be set directly on the `DateTimePicker` @Gi972 - as specified [here](https://jquense.github.io/react-widgets/api/DateTimePicker/#readOnly). Although I had to [check the source](https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/DateTimePicker.js#L327) to figure it out.

**Comment by jquense** [comment]
I do think this should maybe work tho in cases where you want a readonly input but also have the buttons work.

**Comment by breadadams** [comment]
Aha yes, I hadn't realised that the `readonly` prop handled the button too. I could address it in #785 @jquense

**Comment by Gi972** [comment]
Hello guys,

Exactly readonly just for the input  and not for the both

Thanks for the fix.
