### ISSUE TITLE
How do I set max width for the multiselect widget?

### ISSUE THREAD

**Issue by boriskogan81** [jquense/react-widgets#768]
I'm trying to create a row of multiselect inputs, and want to control their widths. How can I do this? Passing a style={{maxWidth:"whatever"}} doesn't work, and neither does targeting .rw-widget-input with css.

**Comment by jquense** [comment]
There's shouldn't be anything special to set the width (or any other style honestly). Either approach is fine (styles, or css classes) you might have some other css on your page that is conflicting with your intended style? Like maybe its in a flex container.
