### ISSUE TITLE
Displaying a custom value in the multiselect input

### ISSUE THREAD

**Issue by boriskogan81** [jquense/react-widgets#769]
I would like to display the number of selected values inside the input field. For instance, if I select 5 options, I want the user to see "selected options: 5" when the multiselect is closed. Is this possible?

**Comment by jquense** [comment]
That is not possible at the moment, you can check past issues about it, but the short answer is that UX wouldn't work with the current behavior of the multiselect which hides selected items in the list once selected. If there are no specific tags to remove in the input the items could never be unselected.
