### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sytv38** [jquense/react-widgets#77]
Project build error: 
D:\Workspace\react-widgets>gulp
prompt: version? (old is 2.4.1):  D:\Workspace\react-widgets\node_modules\gulp\node_modules\orchestrator\index.js:44
                        throw new Error('Task '+name+' requires a function that is a function');
                              ^
Error: Task publish requires a function that is a function
    at Gulp.Orchestrator.add (D:\Workspace\react-widgets\node_modules\gulp\node_modules\orchestrator\index.js:44:10)
    at Object.<anonymous> (D:\Workspace\react-widgets\gulpfile.js:134:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\SY TRAN\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\SY TRAN\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:181:16)

**Comment by jquense** [comment]
I'm not sure what you are asking for here... I don't know what this error is or means.  if you are trying to use the publish tasks it's not gonna work for you.

**Comment by sytv38** [comment]
I using npm install rf-release because i'm not install by jquense/rf-release.
When run npm install with file package.json, it error:

D:\Workspace\react-widgets>npm install
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/jquense/rf-release) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/jquense/rf-release) undefined
npm ERR! git clone https://github.com/jquense/rf-release undefined
npm ERR! git clone https://github.com/jquense/rf-release undefined
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Workspace\react-widgets\npm-debug.log

**Comment by jquense** [comment]
Hi there, 

you can't swap out `jquense/rf-release` for npm install `rf-release` they are different packages (the first is a fork of the second), instead you need to fix the original issue, which is that git was not found on your path, which is (despite the warning) actually an issue with npm. See this: https://github.com/npm/npm/wiki/Troubleshooting#no-git
