### ISSUE TITLE
Changelog since 4?

### ISSUE THREAD

**Issue by nafg** [jquense/react-widgets#772]
CHANGELOG.md only has entries up to 3.5.0, and the last number of those are empty.
Github Releases has no information either, nor does the website (AFAICT).
I can't find anywhere to even answer the question, does 4.x have breaking changes vs. 3.x?
Please populate CHANGELOG.md, or delete it and populate Github Releases, or provide some other (discoverable) source of history (other than digging through all git commits).

Thanks!

**Comment by jquense** [comment]
I'd recommend checking out the commit history if your interested, at some point I'll go back to providing a changelog when I've some better way of generating it. Thanks!

**Comment by nafg** [comment]
Ok, can you at least write somewhere about major version changes (3.x ->
4.x)?

**Comment by jquense** [comment]
https://github.com/jquense/react-widgets/blob/master/www/src/pages/migration-v4.md

**Comment by nafg** [comment]
Thanks. I see that's published as
http://jquense.github.io/react-widgets/migration-v4/, however there's no
item for it in the nav.
