### ISSUE TITLE
DropdownList items hidden

### ISSUE THREAD

**Issue by jrock17** [jquense/react-widgets#778]
I've got a DropdownList inside of a profile header div. When activated, some of the choices are hidden by the end of the section. Any easy way to make sure rw-widget-picker always stays on top? I tried messing with z-index with no success.

![2018-04-03_16-22-50](https://user-images.githubusercontent.com/1270524/38280629-4c269fee-375b-11e8-8f78-be57834f24d8.png)

**Comment by jquense** [comment]
The popup's are absolutely positioned inside the component, which mean's they are susceptible to `overflow: hidden` on a parent element and z-index doesn't really help you here.. I'm not sure your use-case, but i would see if you could set that outer card's `overflow` to `visible`

**Comment by jrock17** [comment]
overflow: visible on the parent card did the trick. Thanks so much!
