### ISSUE TITLE
How to increase the height of the DateTimePicker input field?

### ISSUE THREAD

**Issue by pokharelmanish** [jquense/react-widgets#782]
This is the solution what i did but not sure if this is the right way to do it. 

```
.rw-input {
  height: 2.65em !important;
}
```
Any thought?

**Comment by jquense** [comment]
you can override via css like that (tho you probably don't need `!important`). or You can set the variables in the LESS or Sass files and compile a custom set of styles. For css i'd look at the original less files for a better sense of which selectors to override

**Comment by pokharelmanish** [comment]
I used this approach: 
```
input.rw-input {
  height: 2.7em;
}
```
This may help someone.
