### ISSUE TITLE
How do I set desired `id` prop on Dropdown root element?

### ISSUE THREAD

**Issue by jeron-diovis** [jquense/react-widgets#783]
I choose some `id` prop to set, and widget [overrides](https://github.com/jquense/react-widgets/blob/f72e572f2dbddac26a65e4214c7431131226c9e1/packages/react-widgets/src/DropdownList.js#L139) [it](https://github.com/jquense/react-widgets/blob/f72e572f2dbddac26a65e4214c7431131226c9e1/packages/react-widgets/src/DropdownList.js#L430).
First – why ever do this?
Second – how do I set the id I want? Should I create facade component around dropdown, wrapping it in extra div, or like this?

**Comment by jquense** [comment]
It doesn't override it, it uses it if one is not set

**Comment by jquense** [comment]
Ah i see, yes that is a bug. there should be no suffix added for this one
