### ISSUE TITLE
Cursor keeps jumping to end when Combobox is in Modal

### ISSUE THREAD

**Issue by gbartnick** [jquense/react-widgets#784]
I'm having an issue when using the Combobox component within a react-bootstrap Modal (https://react-bootstrap.github.io/components/modal/). When inserting characters within existing text, the cursor jumps to the end. 

This behavior seems similar to issue #461, but is still present.

**Comment by chiester** [comment]
I see this happening as well. Also, I have a form with several Dropdowns and some, but not all, of them scroll down the page when clicked.
