### ISSUE TITLE
Shift+Home doesn't mark the text in DropdownList and Multiselect search boxes.

### ISSUE THREAD

**Issue by ilyaborin22** [jquense/react-widgets#786]

**Comment by sirbabyface** [comment]
The same happens to me

**Comment by jquense** [comment]
PR welcome!

**Comment by joshlongerbeam** [comment]
Additional info for whomever works on this.

Shift+Home and Shift+End work correctly (highlight input text) in the Combobox, but only when the dropdown is not visible.

If the dropdown for any of the three mentioned components is visible, it's treated as a lone Home/End keypress which navigates to the top/bottom of the open list.
