### ISSUE TITLE
DateTime picker has incorrect time

### ISSUE THREAD

**Issue by waynebrantley** [jquense/react-widgets#787]
When the component is used in 'Date' mode - without time, it still has a time on it 'sometimes'.

If you type a date in, the time is 'zero' as it should be.
However, if you use the popup calendar to pick a date - the time will be populated with the current time.

Since the component is 'date' only, thinking it should have a time value of 'zero' no matter how you set the date?

**Comment by jquense** [comment]
> Since the component is 'date' only, thinking it should have a time value of 'zero' no matter how you set the date?

That sounds right...i wonder if there was a specific reason we did this...

**Comment by GodGinrai** [comment]
I'm experiencing this issue, too.  If I pass no value to the DateTimePicker, then it will give me a date with the current time when I choose a date, despite having time disabled.  If I pass a date with a 0'd out time as a value, then the time will properly be 0'd out when I pick a date.
