### ISSUE TITLE
DateTimePicker: Prevent keyboard input or copy pasting

### ISSUE THREAD

**Issue by jamesattard** [jquense/react-widgets#789]
It is not well documented how we can prevent keyboard input or copy pasting for the DateTimePicker and only constrain dropdown selection. Is this possible?

**Comment by itamarzil123** [comment]
Gi. did you find an answer? im looking for this functionality too

**Comment by jquense** [comment]
You can know ass `inputProps={{ readOnly: true }}` to the picker and it will apply that prop to the input, effectively giving this behavior
