### ISSUE TITLE
The "popup" part of some widgets may appear behind other elements

### ISSUE THREAD

**Issue by sylvain-hamel** [jquense/react-widgets#790]
The widgets that feature a "popup" (Combobox, DateTimePicker, etc..) have a problem where the "popup" may appear behind another element if the widget is contained in a parent that has a scroll bar. The issue seems to be that the "popup" is not a child of `body` so it cannot be on top of everything else.

**Comment by jquense** [comment]
yeah, popups are positioned absolutely for a few reasons (there are some past issues about it), unfortunately one of the tradeoffs is that overlays are caught by overflow.

**Comment by sylvain-hamel** [comment]
OK. You closed this issue. Does it you mean that you don't intend to fix it or to accept a PR for this?

**Comment by jquense** [comment]
There isn't anything to fix really, it's the trade-off we chose for better behavior elsewhere. The only other option is to fixed position it which will add other significant downsides (like fragile or incomplete focus handling). If anything was going to change we'd a comhensive rundown and accounting of the costs  to benefits!

**Comment by gaurav321garg** [comment]
Is there any workaround for this problem?
