### ISSUE TITLE
Breaking on IE10/IE9

### ISSUE THREAD

**Issue by HSzostak** [jquense/react-widgets#795]
Hey there!

**Problem:**

After the update on 'spy-on-component' package where the support for the new lifecycle hooks was added my CRA started throwing 'Syntax Error' on IE10/IE9. 
While debugging I found that the spy-on-component@1.1.0 is using 'const' and it isn't transpiled to ES5.

-----

I'm using CRA to develop/build my app and it won't transpile any package from the 'node_module' folder, so when it's building and deploying the app there is a bit of ES6(that is coming from the spy-on-component) that is being deployed.

It is possible to update the 'spy-on-component' package to be ES5 compliant?

**Comment by jquense** [comment]
can you open an issue there?

**Comment by HSzostak** [comment]
Sure thing!
