### ISSUE TITLE
Require individual widgets with require('react-widgets/somewidget')?

### ISSUE THREAD

**Issue by dandelany** [jquense/react-widgets#80]
Hi jquense! A few people in #reactjs were talking about how it would be awesome if react-widgets let you only load the widgets you needed. Lodash supports this eg.

```
var chunk = require('lodash/array/chunk');
```

I haven't looked at how they do it, and I have no clue how big of a change it would be to your codebase, but might be worth considering, especially if you plan to add more widgets. Thanks!

-dan

**Comment by tcurdt** [comment]
+1 that would be great

**Comment by jquense** [comment]
you totally can, I feel strongly about supporting that API. `require('react-widgets/lib/DropdownList')`

**Comment by dandelany** [comment]
Oh, great, thanks! Might be good to mention that in the docs somewhere (apologies if it's there already, I didn't see it). I too think it's a great API to support.

**Comment by jquense** [comment]
updated the docs, thanks for that I thought it was already there.
