### ISSUE TITLE
InputRef for numberpicker

### ISSUE THREAD

**Issue by Msirkovsky** [jquense/react-widgets#808]
Hi,

Is there a way how to get a reference to the DOM input for NumberPicker. I need call focus on this component, and I didn't find any better solution than find a DOM element and call focus.

Thank you

**Comment by markerikson** [comment]
Yeah, I'm not seeing any docs on how to do this either.

**Comment by jquense** [comment]
components should expose handles with `focus()` on them @markerikson these methods will handle all the focusing edge cases, tho NumberPicker doesn't really have any. 

Open to exposing DOM nodes via refs as well via inputRef or something.

**Comment by markerikson** [comment]
Yeah, we'll give that a shot.

**Comment by jquense** [comment]
there should be, but may be an oversight if it's actually missing

**Comment by markerikson** [comment]
Yeah, not seeing it (R-W 4.x currently, btw).

Able to temporarily work around that by adding an `onBlur` to a parent div and checking if it contains the active element or not.

Also did just get a `numberRef.current!.focus()` call to work, so that's good.
