### ISSUE TITLE
DateTimePicker Problems - Can't Type Any Date

### ISSUE THREAD

**Issue by dkrefta** [jquense/react-widgets#809]
Hello guys,
After I updated the react-widgets component my DateTimePicker are not acepting any date/number when I type, just if I use the datepicker.
 I saw that in the input of the DateTimePicker here https://jquense.github.io/react-widgets/api/DateTimePicker/ its not working too.

**Comment by jquense** [comment]
Bah, this is due to the change in v16.4 to getDerivedStateFromProps :/ fix incoming

**Comment by dkrefta** [comment]
Hmmm :( 
Any tip to handle with this right now? 
Thanks

**Comment by jquense** [comment]
yes upgrade to `4.3.2`

**Comment by dkrefta** [comment]
hmm, I updated but still with this problem. But I changed to 4.2.6 and now its working :)
