### ISSUE TITLE
SASS Styles are broken ==> included the fixes

### ISSUE THREAD

**Issue by laynef** [jquense/react-widgets#812]
Error in webpack with appropriate loaders:
```
$multiselect-tag-gutter-fallback: $input-height * $multiselect-gutter-pt !default;
                                     ^
Undefined operation: "calc(2.25rem + 2px) times 0.115".
```

Fixes to variables.scss
variables.scss

```
// Starts here
$multiselect-tag-gutter-fallback: calc($input-height * $multiselect-gutter-pt) !default;
$multiselect-tag-gutter:          calc($multiselect-tag-gutter-fallback - $input-border-width) !default;
$multiselect-tag-height:          calc($input-height * $multiselect-tag-height-pt) !default;
// Ends here
```

**Comment by RathanakSreang** [comment]
I also face the same issue. Does anyone found a solution?

**Comment by laynef** [comment]
I wrote the solution above. I made a patch in my own code base but I'm creating a PR

**Comment by Richard87** [comment]
This should be reopened, its not fixed yet :/  I just had the exact same problem.

**Comment by jafin** [comment]
error in @4.4.11    Is this still dependent on PR #927 being accepted to fix.

```
SassError: Undefined operation: "calc(1.5em + 0.75rem + 2px) times 0.115".
>> $multiselect-tag-gutter-fallback: $input-height * $multiselect-gutter-pt !de
   ----------------------------------^
```

**Comment by laynef** [comment]
I created a PR months ago for this, it's still pending

**Comment by flyfishMT** [comment]
I get this error in 4.4.11 simply importing the sass in a create-react-app:

`@import '~react-widgets/lib/scss/react-widgets';`

> Undefined operation: "calc(1.5em + 0.75rem + 2px) times 0.115".

**Comment by laynef** [comment]
You can see my solution here and see if that helps. I solved this a year ago and decided to make my own version of this library to solve this issue in my own projects. I suggest custom react components. Hope this helps: 

https://github.com/jquense/react-widgets/pull/927

**Comment by laynef** [comment]
> error in @4.4.11 Is this still dependent on PR #927 being accepted to fix.
> 
> ```
> SassError: Undefined operation: "calc(1.5em + 0.75rem + 2px) times 0.115".
> >> $multiselect-tag-gutter-fallback: $input-height * $multiselect-gutter-pt !de
>    ----------------------------------^
> ```
> 
> EDIT: Applied your patch above and fixed issue. Hoping the PR gets approved. I haven't looked into the lib, but your PR is less, does the less create the SASS for this project?

This project is written in less and uses webpack to transpile the SASS files which the transpiling with webpack is broken due to the types that need to be unified with calc. There are two variables that need to be unified using calc

**Comment by jquense** [comment]
Ya'll this  a problem with some other sass library (or your app) setting the input-height property. `$input-height` is not equal to `calc(2.25rem + 2px)` in react-widgets as you can see here: https://unpkg.com/browse/react-widgets@4.5.0/lib/scss/variables.scss If you want to use `calc` for input-height that's super ok, but you also need to change dependent variables as well in your sass theme.

My guess would be bootstrap is the offending library, otherwise build the sass file separately from bootstrap so that variable scope doesn't leak
