### ISSUE TITLE
DropdownList - Manipulate the typed string before it's filtered

### ISSUE THREAD

**Issue by vctormb** [jquense/react-widgets#814]
When I add the 'filter' props to enable the search bar, the component uses the 'contains' filter to search the option that the user wants. Is there a way to manipulate the typed string inside the search bar but keep using the 'contains' filter?
For example, I want to use the 'contains' filter but I need to remove the accents from the string typed by the user.

**Comment by mnboos** [comment]
You can pass a function to the filter property:

```
filter={(item, filterValue) => _.includes(_.toLower(this.materialToString(item)), _.toLower(filterValue))}
```
