### ISSUE TITLE
Virtualized DropdownList

### ISSUE THREAD

**Issue by jabidof** [jquense/react-widgets#815]
Great lib. I was using the non virtualized version but i have now a 2k number of records to display so I need to set up the virtualized version.
I thus did:
```
import DropdownList from 'react-widgets/lib/DropdownList';
import virtualize from 'react-widgets-virtualized';
const VirtualDropdownList = virtualize(DropdownList);
```
```
render () {
	return <VirtualDropdownList type='uniform'
		itemSizeGetter={()=> 30}
		defaultOpen
		data={tfi2018.sort(naturalCompare('tfiDes_4'))}
		textField='tfiDes_4' valueField='tfiNumber'
		onChange={::this.onTFINumberSelection}
		filter='contains'
		itemComponent={({ item }) => {
			const {tfiDes_4} = item;
			return <div>
				{tfiDes_4 || 'Choisissez!'}
			</div>;
		}}
	/>;
}
```

I get a systematic error with latest react-widget version:
_VirtualList.js:126 Uncaught TypeError: renderItem is not a function
    at VirtualList._this.renderItem (VirtualList.js:126)..._

_The above error occurred in the <ReactList> component:
    in ReactList (created by VirtualList)_...

_Uncaught TypeError: renderItem is not a function
    at VirtualList._this.renderItem (VirtualList.js:126)_...
_Warning: Failed prop type: The prop `renderItem` is marked as required in `VirtualList`, but its value is `undefined`_...

I tried to add a `renderItem` function in the above <VirtualDropdownList /> component without success.

I couldn't find more info in the documentation about the usage of 'react-widgets-virtualized'

Thanks for any feedback on this issue.

**Comment by jquense** [comment]
you are using it correctly...that erro reminds me of something i saw recently related to a babel compilation bug, but looking at the compiled code i don't see an issue. i'd make sure you have everything up to date version wise.

**Comment by jabidof** [comment]
Hi
You mean I should verify I have latest Babel and other related compilation modules up to date?
Thanks

**Comment by jabidof** [comment]
```
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-react-intl": "^2.4.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "babel-regenerator-runtime": "^6.5.0",

```
Doing an npm outdated or ncu will not propose an update for those packages.

Here are the react-widgets related packages I use:
```
    "react-widgets": "^4.3.2",
    "react-widgets-moment": "^4.0.12",
    "react-widgets-virtualized": "^4.0.15",
```

Thanks for any feedback

**Comment by jabidof** [comment]
FYI, I updated to latest packages I have and still getting the same error.
Let me know how I can help debugging this.

**Comment by papivaan** [comment]
Any updates related to this issue? Did you manage to solve this @jabidof ? I keep on getting the same error even though everything seems to be working just fine... Thank you in advance :)

**Comment by jabidof** [comment]
Unfortunately not so I used react-select2
