### ISSUE TITLE
groupBy order

### ISSUE THREAD

**Issue by mstruensee** [jquense/react-widgets#817]
Is there any way we can set the grouped by order?
Currently I am running into a scenario where I have 2 groupings, we'll say GOOD and BAD.  
GOOD = [A,B,C]
BAD = [D,E,F]

so the dropdown list will be 
GOOD
  A
  B
  C
BAD
 D
 E
 F

when I move A to BAD, the GOOD/BAD swap position/order because it is doing it via alphabetical order ...

BAD
 A
 D
 E
 F

GOOD
 B
 C

but I always want GOOD on top ... any trick I can use?

**Comment by jquense** [comment]
groupBy maintains the current order, so if your list is ordered by the group it will render that way.

**Comment by mstruensee** [comment]
got it, ordered the list to how I wanted the group by to show (GOOD always on top)
maybe a feature flag down the road for groupByOrder? just a thought.

thanks.
