### ISSUE TITLE
How to convert the value of DateTimePicker to a string?

### ISSUE THREAD

**Issue by itamarzil123** [jquense/react-widgets#818]
I did not find any documentation of the type of the object DateTimePicker created. is it a Date object? is it a Moment object? 

how do I convert this to a string ??

For example, I would like to check/validate the date and cannot do it without toString it somehow.
any thought?

**Comment by jquense** [comment]
The value expected in `value={date}` should be a js Date object, and the value that is returned from onChange is also a Date (or null if empty or unparsable). The second argument of the `onChange` handler is the string version of the date as displayed in the input.
