### ISSUE TITLE
Add support of globalize new API

### ISSUE THREAD

**Issue by reod** [jquense/react-widgets#82]
It seams that API of [globalize](https://github.com/jquery/globalize) has changed (i.e. there is no `Globalize.format()` method).

**Comment by jquense** [comment]
Hi there, thanks for the issue. The new Globailze is still in alpha, so I am not going to add in support until they hit some sort of stable `1.0` at which point I will switch to that. in the meantime version `0.1.1` still works great, and if you really want to support the new api you can completely swap out the Globalize functionality by changing the `parse` and various `format` props on the calendar, date and number widgets.

**Comment by Semora** [comment]
Globalize is stable now (v1.0.0)
