### ISSUE TITLE
DropdownList autoselect

### ISSUE THREAD

**Issue by olmobrutall** [jquense/react-widgets#821]
Hi @jquense, 

We are happy users of react-widgets for a few years.

In the latest update (from 4.2.6 to 4.3.2) the behavior of DropdownList's filter has changed: 

* Before the first element was always selected, so you started writing and whenever you find the element you're looking for, just press Enter and it's selected. 

* Now the first element in the list is not selected, so after writing you need to press [Down] and then [Enter]. More often than not you press [Enter], selecting nothing and then having to come back. Quite annoying. 

Thanks for your effort!

**Comment by jquense** [comment]
fixed either now or in the next version!
