### ISSUE TITLE
DateTimePicker - Uncaught TypeError: Cannot set property 'inputValue' of null

### ISSUE THREAD

**Issue by RomanKovalev** [jquense/react-widgets#822]
Hello.

Try to use DateTimePicker widget, but there is error.
The error screenshot below, after code.
Help please.

`import 'react-widgets/dist/css/react-widgets.css';

import React from "react";
import Datetime from "react-datetime";
import DateTimePicker from 'react-widgets/lib/DateTimePicker'
import Moment from 'moment'
import "react-datetime/css/react-datetime.css";
import "moment/locale/ru";
import store from "../reduxData/store";
import { connect } from "react-redux";
import {
    getBookingForm,
    getBookingSlots,
    refreshDatetimeFilter
} from "../reduxData/actions/filter";
import { resetOffersCount } from "../reduxData/actions/result";
import {css} from 'aphrodite/no-important';
import cssFilter from './styles/filter';
import momentLocalizer from "react-widgets-moment"

Moment.locale('en');
// momentLocalizer();
momentLocalizer(Moment)
`
export default class Filter extends React.Component {
    constructor(props) {
        super(props);
        this.submitSearch = this.submitSearch.bind(this);
        this.state = {
            value: this.props.initialValue,
            phrases: {
                en: {
                    since: 'Time since',
                    till: 'Time till',
                    submit: 'Search'
                },
                ru: {
                    since: 'Время с',
                     till: 'Время до',
                    submit: 'Подобрать',
                }
            }
        };
    }

    markEmptyDatetimeFields() {
        $.each($('.form-control'), (index, value) => {
            if (!$(value).val()) {
                $(value).css('border-color', 'red');
            } else {
                $(value).css('border-color', '#bfc6cf');
            }
        });
    }

    submitSearch(event) {
        event.preventDefault();
        this.markEmptyDatetimeFields();
        console.log("Hi there-0");
        console.log(this.timeSince);  //null, but should not to be null
        console.log(this.timeSince.state); //Error
        console.log(this.timeSince.state.inputValue);
        // if (!this.timeSince.state.inputValue || !this.timeTill.state.inputValue) {
        //     console.log("Hi there-1");
        //     return
        // }
        if (this.props.slotsInProgress || this.props.formsInProgress) {
            console.log("Hi there-2");
            return
        }
        console.log("Hi there-3");
        store.dispatch(
            getBookingForm(this.props.lang, this.props.type, this.props.objectId)
        );
        console.log("Hi there-4");
        store.dispatch(
            getBookingSlots(this.props.lang, {
                type: this.props.type,
                id: this.props.objectId,
                since: this.timeSince.state.inputValue,
                till: this.timeTill.state.inputValue
            })
        );
        console.log("Hi there-5");
        store.dispatch(
            refreshDatetimeFilter(
                this.timeSince.state.inputValue,
                this.timeTill.state.inputValue
            )
        );
        console.log("Hi there-6");
        store.dispatch(resetOffersCount());
    }
  isValidDate = current => {
        let yesterday = Datetime.moment().subtract(1, "day");
        return current.isAfter(yesterday);
    };

   render() {
      return (
            <form
                className={css(cssFilter.filterFormElement)}
                onSubmit={this.submitSearch}>

                <DateTimePicker
                    format="YYYY-MM-DD hh:mm"
                    containerClassName={css(cssFilter.reactDateTime)}
                    min={new Date()}
                    // currentDate={new Date()}
                    placeholder={this.state.phrases[this.props.lang].since}
                    locale={this.props.lang}
                    step={15}
                    ref={input => this.timeSince = input}
                    defaultValue={this.state.value}
                    isValidDate={this.isValidDate}
                    value={this.state.value}
                    onChange={value => this.setState({ value })}
                />

                <DateTimePicker
                    format="YYYY-MM-DD hh:mm"
                    containerClassName={css(cssFilter.reactDateTime)}
                    min={new Date()}
                    // currentDate={new Date()}
                    placeholder={this.state.phrases[this.props.lang].till}
                    locale={this.props.lang}
                    step={15}
                    ref={input=> this.timeTill = input}
                    defaultValue={this.state.value}
                    value={this.state.value}
                    onChange={value => this.setState({ value })}
                    isValidDate={this.isValidDate}
                />

               <input className={css(cssFilter.submitButton)}
                       type="submit"
                       value={this.state.phrases[this.props.lang].submit}
                       disabled={this.props.formsInProgress || this.props.slotsInProgress}
                />
            </form>
        );
    }
}

const mapStateToProps = state => (
    {
        formsInProgress: state.filter.formsInProgress,
        slotsInProgress: state.filter.slotsInProgress,
    }
)

export default connect(mapStateToProps)(Filter);

<a href="http://i.imgur.com/SXwpZDK.png">
  <img src="http://imgur.com/SXwpZDKl.png" />
</a>

**Comment by jquense** [comment]
The error looks like its coming from your code `inputValue` is not a react-widgets thing (doesn't exist in the codebase). Looks like you may have typo or an unexpectedly null value in state
