### ISSUE TITLE
Combobox Prop containerClassName Not Reaching ComboboxInput

### ISSUE THREAD

**Issue by DavidCao22** [jquense/react-widgets#824]
http://jquense.github.io/react-widgets/api/Combobox/#containerClassName

The `containerClassName` prop for the `Combobox` component is not propagating down all the way to the `ComboboxInput` field. Using the React devtools, I can see that the prop is passed from the `Combobox` -> `Widget` -> `div` (from `WidgetPicker`) and then stops there.

**Comment by jquense** [comment]
the containerClassName doesn't go on the input itself, but on the _container_ element, specifically the `rw-widget-container` element in a given widget. If you want to add a className to the input directly you can use `inputProps`. hope that helps!

**Comment by DavidCao22** [comment]
Ah, that does. I should probably read the documentation a bit closer 😂. Thank you!
