### ISSUE TITLE
Day number on calendar is weird

### ISSUE THREAD

**Issue by Ebuall** [jquense/react-widgets#827]
![weird-date](https://user-images.githubusercontent.com/10381141/43357842-4448a7aa-9290-11e8-88c5-aaff62ed8d9d.png)
It goes all the way from 01 to 365. Not sure if this is localizer issue

**Comment by jquense** [comment]
That looks like a localizer bug. Waht one are you using?

**Comment by Ebuall** [comment]
Im using date-fns US locale, just because I had it installed.
