### ISSUE TITLE
Components not rendering properly

### ISSUE THREAD

**Issue by edmardebarros** [jquense/react-widgets#828]
## Expected:
See the default ReactWidget component.
![DropdownList](https://image.ibb.co/gy16Fe/Screen_Shot_2018_07_31_at_16_31_42.png)
## Actual:
The component does not load the styles.
![DropdownList](https://image.ibb.co/ms00ae/Screen_Shot_2018_07_31_at_16_31_54.png)

It can be reproduced here:
[![Edit 3q2myy7k25](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3q2myy7k25)

**Comment by jquense** [comment]
you didn't include the stylesheet. please read the getting started guide on the docs site for more info thanks!
