### ISSUE TITLE
Multiselect scroll position keep getting reset after selecting item

### ISSUE THREAD

**Issue by fransiskapw** [jquense/react-widgets#829]
After selecting an item on Multiselect that has long item list, the scroll position of my Multiselect keeps getting reset to the top position (showing the first few items on the list). I use the same code as the example and somehow in the example the scroll position can be maintained. Am I missing something, how can I maintain the scroll position on Multiselect?

**Comment by jquense** [comment]
what browser and OS are you on? can you post a repro  codesandbox maybe?

**Comment by fransiskapw** [comment]
Here is the codesandbox link:
https://codesandbox.io/s/4z7lj43rw

I just realized, it only reset whenever I put onChange={value => this.setState(...)}
Any idea how to fix it?

Here's the info you requested
Browser: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
OS: macOS High Sierra version 10.13.1 (17B1003)

**Comment by ttamminen** [comment]
I have the same issue. Very tedious for the user to select multiple rows that are next to each other as the scroll position will reset after selecting the item. Any ideas on how to maintain or control the scroll state?

**Comment by Sinfulelf** [comment]
Ok, if we are open "react-widgets/lib/List.js", we will find the row
_______
_proto.componentDidUpdate = function componentDidUpdate() {
    this.move();
  };
_______
