### ISSUE TITLE
Dropdown List disable single item

### ISSUE THREAD

**Issue by mloginov** [jquense/react-widgets#83]
Hi.

Is it possible to disable single item in Dropdown List. Like ```<option disabled="disabled">``` ?

**Comment by jquense** [comment]
Hi there, Currently there is no way to disable individual list items in the dropdown. I may add that in the future, but as of right now there isn't a good way to do that performantly.

**Comment by mloginov** [comment]
Ok. Thanks.

**Comment by jquense** [comment]
@mloginov A few people have asked recently hoe you might accomplish this, so I threw together a gist: https://gist.github.com/jquense/c252e7abbcec036bf930 demonstrating how you can extend the widgets to get this behavior. Just posting it here in case you find it useful and for posterity
