### ISSUE TITLE
Manually entered dates will circumvent min/max settings

### ISSUE THREAD

**Issue by GodGinrai** [jquense/react-widgets#841]
If you set a min or max prop for the DateTimePicker, it should clamp any value typed into the input to the range you set.  It makes no sense to restrict being able to click days before a certain date if they can just type it in manually.

**Comment by jquense** [comment]
yes this is noted in the docs: http://jquense.github.io/react-widgets/api/DateTimePicker/#max originally there was a good technical reason for this, but that was a while ago and we can revisit for v5. in the meantime you can clamp the value via `onChange`

**Comment by GodGinrai** [comment]
Yes, that's what we're currently doing to solve the issue.  Please do revisit this for v5, because it makes a lot more sense for the widget to do it than the consumers of the widget.
