### ISSUE TITLE
[Calendar widget] The footerFormat setting is also used as a tooltip/title and aria-label format

### ISSUE THREAD

**Issue by cho-leukeleu** [jquense/react-widgets#842]
First of all thanks for these neat widgets!

Would it be possible to get/use a different setting for the `title` and `aria-label` attribute than the one used for the `footerFormat`?
It becomes very confusing in the case where the footer date gets a prefix like in the example you provide for this very setting. When you hover any day of the calendar it then says "Today is: ...".

**Comment by AdamFreemer** [comment]
Just following up on this issue, is there currently no way for a custom aria-label right now? It's part of the requirement I'm working on for 508 (accessible) compliance.
