### ISSUE TITLE
DateTimePicker autofill with user email.

### ISSUE THREAD

**Issue by RathanakSreang** [jquense/react-widgets#844]
How can I fill autofill issue when I input username then it autofill date value with email?

**Comment by jquense** [comment]
autofill is controlled by the browser, there isn't much we can do to control it, i would make sure your input isn't `name`d something that would hint to the browser that's it's an email field.

**Comment by RathanakSreang** [comment]
@jquense 
Here the code i use.
```
<Field name="issue_date"
                showTime={false}
                component={renderDateTimePicker}
                type="date"
                label="Issue Date"
                className="text-right"
                validate={[required]} />
```
Can you tell anything wrong with it?

**Comment by courtsimas** [comment]
What type of component is `Field`?  @RathanakSreang
