### ISSUE TITLE
max-width: 1px hack in dropdown-list.css potentially has issues with Chrome 69

### ISSUE THREAD

**Issue by vdh** [jquense/react-widgets#845]
As a caveat, this only shows up if someone applies custom styles to `.rw-widget` to be `display: inline-block` instead of the `block` default, so it's technically not a problem for unmodified React Widgets. But I thought it would be good to document this in case it catches someone by surprise.

**Edit:** I've also observed this happening when the `.rw-widget` is situated inside a Flex layout, so that would be a non-modified scenario where this occurs.

The `max-width: 1px;` hack on `.rw-dropdown-list-input` in [`react-widgets/src/less/dropdown-list.less`](https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/less/dropdown-list.less#L14) is causing issues in Chrome 69 where Chrome is following the `1px` instead whatever previous behaviour rendered it wider than that. I've still got Chrome 68.0.3440.106 and it still has the old behaviour, but my co-worder with Chrome 69 has noticed the issue. It's also visible in Firefox 61.0.2, but I'm not sure when that changed.

**Comment by michael-gillett** [comment]
We are facing the same issue
