### ISSUE TITLE
Provide prop to render the date/time text input to be readonly.

### ISSUE THREAD

**Issue by karlkras** [jquense/react-widgets#847]
I have the need (in multiple applications) to allow the user to only use the picker to select the date, and not allow typing directly into the text input. It seems currently the readonly setting effects both the input and the selection buttons.

**Comment by jquense** [comment]
`inputProps={{ readOnly: true }}`

**Comment by karlkras** [comment]
No, that makes the entire input (including the calendar selection) disabled/readonly. At least that's how it's working for me using the example page.

**Comment by karlkras** [comment]
Oh cool. Any docs on other inputProps that an be used? Didn't see (still don't) any reference to this in the home page demos.
