### ISSUE TITLE
NumberPicker with min value cannot be null

### ISSUE THREAD

**Issue by dubrowgn** [jquense/react-widgets#85]
Related to #19 

However, the assumption that `null` is an invalid value when `min` is defined does not always hold. It is a perfectly valid use case to want a positive number or no number at all (`null`). The current NumberPicker cannot handle this case.

**Comment by jquense** [comment]
Hi there. This is the sort of thing that's more semantics than anything else, whether a minimum should apply to "empty" values like `null`. I personally think min means "at least this", but allowing null with a min is more flexible than the current, so baring an important reason I'm not remembering related to parsing constraints, I'll change it in an upcoming release.

**Comment by dubrowgn** [comment]
I agree that it *could* make sense for `min` to imply not `null`. However, it seems to me that constraints on presence of value is really a different problem than constraints on the value itself. Perhaps a 'nullable' prop would make more sense, so that it can be controlled independently of `min`.

**Comment by jquense** [comment]
in either case it was a bad choice by me as a lib author to pick the less flexible interpretation. change upcoming. still deciding if it counts as a breaking change :/
