### ISSUE TITLE
DateTimePicker: Trigger for displaying calendar when clicking into text input?

### ISSUE THREAD

**Issue by karlkras** [jquense/react-widgets#851]
I'd like to provide the ability to pop the calendar when the user clicks into the text input of the DateTimePicker.
I've tried a number of things to do this, but none has been completely, er, complete.
The picker has an open prop that can be toggled true/false. This know.

So upon a click into text input, I have an onClick handler that will set the open prop to true, and have a corresponding onSelect handler to set it to false once an date cell has been selected... 
Problem here is I don't have an "onClickAway" available so if the user clicks into the text input and moves to another item on the form, the datetimepicker is hung there open. Not a great experience.

Any way to fully accomplish this?

**Comment by jquense** [comment]
I would use onBlur for that. If you are already listening to onToggle tho it should fire a close request when you blur out alrrady

**Comment by tailornirmal** [comment]
How it would work for multiple data time picker in a single form. I passed "calendar" to open property on DateTimePicker but my all date picker is getting open. 

Input click method is already in place.

Please help me on this.

`<DateTimePicker 
                  time={false}
                  onKeyDown={(e) => e.preventDefault() }
                  value={question.answers.length > 0 && question.answers[0] !== "" ? new Date(question.answers[0]) : null } 
                  onChange={value => this.handleChange(question, value)}
                  format="YYYY-MM-DD"
                  onClick={this.handleInputClick.bind(this, this.props.onClick)}
                  onToggle={this.handleToggle.bind(this, this.props.onToggle)}
                  open={open}`

**Comment by CROC0** [comment]
Here is my solution for the issue, it isn't elegant although it works. 

`
  const [open, setOpen] = useState(false);
  const hideDate = () => setOpen(false);
  const showDate = () => setOpen("date");

  const handleDateChange = value => {
    hideDate();
    setData({ ...data, targetDate: moment(value).valueOf() });
  };

<DateTimePicker
          onChange={value => handleDateChange(value)}
          time={false}
          value={new Date(data.targetDate)}
          open={open}
          inputProps={{ onClick: showDate }}
          onBlur={hideDate}
          onToggle={!open ? showDate : hideDate}
        />`
