### ISSUE TITLE
DateTimePicker doesn't move to the month if the min value is set to a date in the future

### ISSUE THREAD

**Issue by danielcardoso5** [jquense/react-widgets#852]
If the passed date to the min value is set to some months in the future, the component doesn't set that month as the default view when opening.

It makes it even impossible to navigate to that month using the arrow keys, only by using the month year selection we are able to go to the min date month.

**Comment by danielcardoso5** [comment]
@jquense was this issue fixed on a new release?

**Comment by vv185084** [comment]
This issue is not yet fixed
