### ISSUE TITLE
Add support for nested groups / partitioning of data in DropdownList

### ISSUE THREAD

**Issue by rishitank** [jquense/react-widgets#858]
Hi,
These packages are amazing, keep up the good work! I was thinking it would be a very useful feature if support for nested groups were implemented. An example could be a dropdown with a list of locations, grouped by country, but you may also want to further group this by region / state etc. If this functionality is already provided, then please point me in the right direction, thanks!

**Comment by jquense** [comment]
hi, deeply nested grouping isn't supported. I think that would, in general, not have a great UX. I do understand tho not everyone's needs are general though, so we try and provide API's that allow this sort of customization. You can provide a custom List component to dropdowns that can group as your describing but you'd have to build it. There isn't any documentation unfortunately but taking a look at how the existing List component implements sidle order grouping should be a good starting point.

**Comment by rishitank** [comment]
Update: I've extended the ListOption class and this appears to work as normal, however adding a className prop to the list option causes the className to be overwritten in your ListOption class, this seems to be a bug since the intended behaviour in ListOption seems to be the joining of various classes. However due to `Props.omitOwn(this);` it includes the className, and so when applying these props they override the joined classnames provided to the option. If this could be fixed that would be amazing, then nested groups can be a reality 😄
