### ISSUE TITLE
ComboBox's textField prop not working with Immutable.Records

### ISSUE THREAD

**Issue by pigulla** [jquense/react-widgets#86]
(This most likely applies to various components, not just the combobox.)

It seems the issue is caused by the [_dataText](https://github.com/jquense/react-widgets/blob/master/src/mixins/DataHelpersMixin.js#L23) function in the `DataHelpersMixin`. When checking the presence of the attribute specified by the `textField` prop, `_.has` uses `hasOwnProperty` which does not work with records:

```js
var Record = Immutable.Record({ foo: undefined }),
    r = new Record({ foo: 'bar' });

r.foo; // 'bar'
r.hasOwnProperty('foo'); // false
```

**Comment by jquense** [comment]
I am not super familiar with Immutable in general, but that seems odd that they wouldn't be 'own' properties,, are the properties on a lower prototype? `'foo' in r` is `true ` right? Perhaps that should actually be the check their anyway...

**Comment by pigulla** [comment]
It's implemented via [property getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get), so they are indeed not properties on its (or any other obejct's) prototype. However, since it's enumerable `'foo' in r` works just fine. Should I send a PR?

**Comment by jquense** [comment]
hmm getters should still be visible via `hasOwnProperty`, at least they seem to be in my little tests. Anyway it still needs to be addressed so yeah I'd take a PR :) thanks!
