### ISSUE TITLE
DropdownList should accept false as a valid prop type value for itemComponent

### ISSUE THREAD

**Issue by MrJadaml** [jquense/react-widgets#860]
It would be nice if `false` were a valid prop type for the `itemComponent` prop in the DropdownList component. React knows to omit any props with a non truthy value allowing for conditional rendering on itemComponents. While this can be done by providing an empty string, which is a valid prop type, it is not as explicit as just kicking back `false`.

>warning.js:33 Warning: Failed prop type: Invalid prop `itemComponent` of value `false` supplied to `DropdownList`, expected an element type (a string , component class, or function component).
    in DropdownList

**Comment by jquense** [comment]
what are you trying to accomplish with `false`, that `undefined` doesn't do?

**Comment by MrJadaml** [comment]
I was using a logical operator expression, so the return value was a boolean. I was able to rework things it to make use of `undefined` though.
