### ISSUE TITLE
Select Specific chat by default.

### ISSUE THREAD

**Issue by lsabbagh** [jquense/react-widgets#862]
I want to be able to open the chat box with specific chat opened, it's `id` can be passed with params.

**Comment by jquense** [comment]
i'm not sure what this means

**Comment by lsabbagh** [comment]
like that:
```
       <Intercom
            appID="vfolnonp"
            user_id= '...'
            email= 'wassim.lsabbagh@gmail.com'
            name= 'Wassim'
            customer_service_guy_Id='23423......' // add this one...
           />
```

So the user don't select which customer service chat to open, a specific one will be opened by default..

@jquense
