### ISSUE TITLE
Can't disable entire dropdown list and specific items

### ISSUE THREAD

**Issue by itsmequinn** [jquense/react-widgets#865]
DropdownList can take a boolean or Array as it's disabled prop. One disables the entire list and the other disables certain items. It would be nice to have separate props for these two use cases or two be able to pass a disabled property on an item object in the data array to disabled individual options. This would allow for the use case where the entire dropdown is disabled under some condition (perhaps while posting data to a server) and also allow for certain options to be disabled in the list based on some other logic.

**Comment by jquense** [comment]
Hi there, I'm not sure why you can't support both now or is this more of a convenience api thing? It doesn't make makes to do both at once since you can't open  or select anything in the dropdown when it's entirely disabled, so also disabling individual items wouldn't have an effect
