### ISSUE TITLE
Decimal NumberPicker is not working

### ISSUE THREAD

**Issue by fortezhuo** [jquense/react-widgets#866]
Hi,

I just found on demo page, NumberPicker that using decimal is not working.

How to reproduce : 
1. Use the demo page  http://jquense.github.io/react-widgets/api/NumberPicker/
2. On first sample, please try to input number that have decimal e.g. 15.20
3. While press dot (.) nothing happend

**Comment by bijjalachi** [comment]
IS there any fix forthe above bug

**Comment by bijjalachi** [comment]
Please post the solution if any one having to allow the decimals for the Numberpicker component
