### ISSUE TITLE
DateTimePicker doesn't move to the month while using arrows when selected date is in the past.

### ISSUE THREAD

**Issue by adam-szczombrowski** [jquense/react-widgets#874]
If the value passed to the picker is in the past it's impossible to move to other months by using arrow keys, only by using month selection I'm able to change the month.

**Comment by aedryan** [comment]
I am seeing this issue as well, it occurs when a user enters a date via the text input that is out of the min/max bounds.

**Comment by darrenklein** [comment]
@jquense do you have any thoughts on this issue? In my use of the DateTimePicker, I have a scenario where the `min` may be programatically set to be later than the current date of the calendar and so users can become stuck.

Thank you so much for all of your hard work on this project!
