### ISSUE TITLE
Multiselect height bug in Firefox

### ISSUE THREAD

**Issue by rkashapov** [jquense/react-widgets#875]
Firefox version: 63.0.1
OS: MacOS 10.14

![height bug in firefox](https://user-images.githubusercontent.com/3455996/47903694-134b5e80-de95-11e8-9b5f-ae43b86fffbb.gif)

**Comment by cho-leukeleu** [comment]
I think it would be fixed if we had: 
`
.rw-multiselect-taglist {
display: inline-block;
vertical-align: 0;
}
`
I only checked it on FF.
I might look into it and make a PR for it :)

**Comment by sarahsmo** [comment]
@cho-leukeleu Did you get a PR out for this?
