### ISSUE TITLE
onBlur event gives inconsistent value when clicked very quickly

### ISSUE THREAD

**Issue by jayiconcmo** [jquense/react-widgets#876]
Expanding on the onChange example for the DateTimePicker found [here](https://jquense.github.io/react-widgets/api/DateTimePicker/#onChange). Keeping in mind that the simplified code below doesn't take into account more complex code inside the onBlur event.

**SIMPLIFIED CODE**
```
import React, {Component} from 'react';
import {DateTimePicker} from 'react-widgets';

class _Date extends Component {
  constructor(...args) {
      super(...args)
      this.state = { value: null }
      this.onBlur = this.onBlur.bind(this);
      this.onChange = this.onChange.bind(this);
    }

  onChange({value}) {
    console.log('onChange value', value)
    this.setState({
      value
    });
  }

  onBlur({value}) {
    console.log('what is passed data', value);
    console.log('onblur value.target', value.target);
    console.log('drilled down', value.target.value);
    console.log('state var', this.state.value);
  }

  render() {
    return (
      <div>
        <p> This gives undefined </p>
        <DateTimePicker
          value={this.state.value}
          onChange={value => this.onChange({ value })}
          onBlur={value => this.onBlur({ value })}
        />
        <p> text to expand section
        <br />
        <br />
        <br />
        </p>
      </div>
    );
  }
}
export default _Date;
```

**OUTPUT When clicked FAST:**
![undefined_click](https://user-images.githubusercontent.com/14827580/47930280-74753100-de99-11e8-9b25-eb9a37d46ae8.png)

**OUTPUT When clicked SLOWER:**
![click_has_data](https://user-images.githubusercontent.com/14827580/47930494-2280db00-de9a-11e8-9a6e-04cb9dd54a80.png)

**Comment by slikts** [comment]
Sorry, what do you mean by clicking "fast"? A click is a singular event.

**Comment by jayiconcmo** [comment]
Hello 
I believe what I meant is that the undefined happens when a user is in the date field, clicks the date in the picker, then very quickly de-focuses the fields by clicking somewhere else - ie for example another part of the web page. When this is done the undefined happens as you see above.
