### ISSUE TITLE
DateTimePicker should more obviously differentiate between date picker button and time picker button

### ISSUE THREAD

**Issue by komali2** [jquense/react-widgets#878]
According to [most](https://uxplanet.org/7-basic-rules-for-button-design-63dcdf5676b4) [ux](https://www.freshconsulting.com/uiux-principle-19-buttons-should-look-like-buttons-links-should-look-like-links/) [researchers](https://www.smashingmagazine.com/2016/11/a-quick-guide-for-designing-better-buttons/), buttons should look like buttons. 

The DateTimePicker, in its current state, not only does *not* look like a button, even worse, it does not look like two buttons. 

[Previously](https://github.com/jquense/react-widgets/issues/694), this was brought up, you said "I am fine with this." Can you help me understand better? We had to stop using this repo because users were confused 100% of the time on interaction with this widget. It was the most common feedback we got. "Oh, I didn't know I could change time!" "Oh, I didn't even realize that was a button!" A shame, because you did so well designing this tool, it is so very functional and all other aspects are clean and beautiful. Can you help me understand why this design decision?

**Comment by papiro** [comment]
Agree with this. I just imported the component and decided within the first 15 seconds of using it that I would find a way to make it look like only the button which was being pushed was pushed and not both of them.

**Comment by ILyaCyclone** [comment]
Absolutely agree with this issue. I also was confised: "this button is for date picker, so where button for time picker?"

**Comment by jquense** [comment]
Happy to take a PR if anyone wants to change the default for v4. v5 has changed the date time picker significanatly so isn't relevant anymore.

In general the default styles are meant as basic, simple defaults. The intention is that most folks will change them significantly to make their app. That said more than happy to take contributions that provide better default ux.
