### ISSUE TITLE
Please consider using a CHANGELOG, GitHub releases, or even tagging the code

### ISSUE THREAD

**Issue by shepmaster** [jquense/react-widgets#881]
It's very difficult to tell what the diff is between e.g. 4.4.6 and 4.4.7. 

Ideally, there'd be a [CHANGELOG](https://keepachangelog.com/en/1.0.0/) file at the root of the repository. Some maintainers prefer to use [GitHub releases](https://github.com/jquense/react-widgets/releases).

Barring all of that, tagging the repository would allow users to pick apart what the changes were. It looks like some tags are sporadically published:

![image](https://user-images.githubusercontent.com/174509/48850402-96feb980-ed76-11e8-9489-788a912476c6.png)

**Comment by shepmaster** [comment]
Ugh, or maybe have a CHANGELOG file at the root of the repository that points to the separate projects, which I now see.

**Comment by jquense** [comment]
releases are tagged, i just forgot to push the newest ones. :P
