### ISSUE TITLE
react-widgets 4.4.7 isn't in version control?

### ISSUE THREAD

**Issue by shepmaster** [jquense/react-widgets#882]
Looking at NPM, it says that 4.4.7 is the current version:

![image](https://user-images.githubusercontent.com/174509/48850640-1ee4c380-ed77-11e8-8feb-0a659cb75f74.png)

Looking at the [current package.json](https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/package.json), it only has 4.4.6:

![image](https://user-images.githubusercontent.com/174509/48850683-2efca300-ed77-11e8-9a35-a2795dd271da.png)

**Comment by jquense** [comment]
forgot to push after releasing

**Comment by shepmaster** [comment]
> forgot to push after releasing

The master branch is not updated and I see no tags. Could you reopen the issue and close it once they are pushed?

**Comment by shepmaster** [comment]
Hm. They have prefixes, I see. I'm not a personal fan of monorepos so I guess I have more to learn.

**Comment by jquense** [comment]
ya they are prefixed b/c each package is individually versioned. otherwise the tags would conflict

**Comment by shepmaster** [comment]
It's a shame that the GitHub tag widget doesn't show these prefixed ones.

**Comment by jquense** [comment]
i'm honestly not sure why it isn't. usually it does. seems like a GH bug perhaps
