### ISSUE TITLE
How can I capture the input value of the DateTimePicker widget?

### ISSUE THREAD

**Issue by apenab** [jquense/react-widgets#886]
The only option that has occurred to me is this,

    
	function handleChange(value) {
	        if (value == "") {
	            props.onChange(null);
	        }
	       ...
	}
	<DateTimePicker
          ...
          inputProps={{
                 component: props => (
                      <input
                            {...props}
                            onChange={e => handleChange(e.target.value)}
                            className={`${props.className} form-control ${props.large ? "input-lg" : ""}`}/>
                    )
                }}/>

_but every time the function `handleChange` is executed, the component will be rendered again and I lose the focus of the input_

**Comment by jquense** [comment]
Not sure I understand the question here, why not use value and onChange on the dateTimePicker. That value is what's reflected in the input

**Comment by jquense** [comment]
there isn't really a way to do that at the moment. you could maybe add an `onKeyup` handler via `inputProps` but otherwise the local onChange will be bulldozed by the parent `onChange. If you wanted to send a PR composing them in DateInput i'd take that 👍
