### ISSUE TITLE
DateTimePicker Time not auto focused after picking a date

### ISSUE THREAD

**Issue by ryanMeredith** [jquense/react-widgets#887]
Once you choose a date on the Date Time Picker and open the time picker, the time picker has 12 am as the focused select. If you load the page and open the time picker it focuses on the correct (current) time.

Any clues on how to fix this. 

This happens in my personal code and on the examples on 
https://jquense.github.io/react-widgets/api/DateTimePicker/

Many thanks for all your hard work

Ryan

**Comment by drm-code** [comment]
Any updates?
