### ISSUE TITLE
Selected value not reflected in DropdownListInput when using an itemComponent.

### ISSUE THREAD

**Issue by papiro** [jquense/react-widgets#894]
The underlying input component (`DropdownListInput`) is showing `"[object Object]"` as its `value` after making a selection. You can see it on the demo page, by inspecting the DOM (http://jquense.github.io/react-widgets/api/DropdownList/#itemComponent). 

This defect foils my attempts to extrapolate the value of the selected option by using the `HTMLFormElement.elements` API. In fact, other than somehow getting the value from my React component, there's no other way for me to read the input value from the DOM node, since no `ref`/`innerRef'`/`forwardedRef` mechanism exists.

**Comment by jquense** [comment]
The input in a dropdown is an implementation detail for catching autocomplete, it's not meant to provide the current value as a general API and the inputs in general are not trying to be compatible with plain HTML form submission. When you need the value of the dropdown you should listen to `onChange`

**Comment by papiro** [comment]
I see. It's confusing because it shadows the `value` of the `DropdownList`. Thank you for your direction - will use `onChange` from here on in.

**Comment by jquense** [comment]
Yeah it's not ideal :/ maybe in the future we can more easily support this use case
