### ISSUE TITLE
Valid dates in Calendar

### ISSUE THREAD

**Issue by apenab** [jquense/react-widgets#895]
I have a calendar to which I will pass an arrangement of dates, these dates should be the only ones available in the calendar, the others should not be able to allow the user to click on them. 
I thought that my problem was solved using the prop `dayComponenent`, but it does not let me edit the `<td>` tag, which makes it impossible for me to add the class `rw-state-disabled rw-cell-not-allowed`, @jquense, any suggestions.....

**Comment by apenab** [comment]
I think my problem is solved using the prop `dayComponent`, @jquense if you have a better solution, please tell me

**Comment by flyfishMT** [comment]
I have this same use case for the DateTimePicker.  I'd like a prop - `validDates={arrayOfValidDates}`
