### ISSUE TITLE
React-Widgets Calendar component: navigatePrevIcon/navigateNextIcon not functional

### ISSUE THREAD

**Issue by dawnmist** [jquense/react-widgets#896]
The `Calendar` component does not pass the `navigatePrevIcon` and `navigateNextIcon` props through to the `Header` component: https://github.com/jquense/react-widgets/blob/b468f591dbe63225ec3dfbd2576bd08d3606d6f7/packages/react-widgets/src/Calendar.js#L478-L493

This means that when the header is drawn for the calendar view, the props for `navigatePrevIcon` and `navigateNextIcon` in the Header are undefined even when the user has specified those props for the Calendar component.

**Comment by gks66** [comment]
Any update? Got the same issue.

**Comment by jquense** [comment]
happy to take a PR!

**Comment by dawnmist** [comment]
Pull request created.
