### ISSUE TITLE
submit selected values 

### ISSUE THREAD

**Issue by tarim** [jquense/react-widgets#899]
Hi There,

I am using the Multiselect widget, and I am using data source comes with id and name.
`data={this.props.userList} valueField='id' textField='name' defaultValue='' />`
 When the user selected, the Multiselect display name on the UI, but when it submit, I want to send the ids, not the names. So, how we do it, please?

Thank you,

**Comment by bartlomiejstrzelczyk** [comment]
Im having the same problem, also you should rename thread title to 'valueField does not work'

**Comment by jquense** [comment]
Valyefield selects the unique identifier it doesn't change the value returned from on change. There are a few past issues about this but tl;dr; is pull the IDs out of the data values in onChange if that's all you are interested in
