### ISSUE TITLE
Feature Request: optionally enforce valid selection in Combobox

### ISSUE THREAD

**Issue by pigulla** [jquense/react-widgets#90]
The Combobox' docs explicitly state that
>  The widget value does not need to be in the data, widgets can have values that are not in their list.

However, there are use cases where that is not the desired behaviour.

In my particular use case, I need the user to select one of n valid values. So I can either

- use a DropwdownList and have him scroll through dozens of options *-or-*
- use a ComoBox to enable search-as-you-type but add boiler plate code to deal with invalid values

Is this something you would consider implementing?

**Comment by jquense** [comment]
You can check out issue #89 for a similiar discussion, and possible solutions. I don't want to add limits to the combobox as that is its key distinguishing feature.

As an addendum to that though, you can type/search in the dropdown list. there isn't an input or anything but typing while move the selection/focus to the next matching item.

In the future I may properly add a "show filter input" option to the dropdown, I am not sure its a good idea yet :P

**Comment by jquense** [comment]
hey @pigulla the newest release of the suite adds the ability to filter dropdown lists, which may be relevant to you. Check it out at http://jquense.github.io/react-widgets/docs/#/dropdown-list/filter

**Comment by pigulla** [comment]
Sweet! Thanks for the ping!
