### ISSUE TITLE
DateTimePicker onChange event.preventDefault does not revert input field value

### ISSUE THREAD

**Issue by softweave** [jquense/react-widgets#905]
I’m running into a problem reusing logic with react-widgets 4.4.8 that worked with react-widgets 3.4.6.

I have two DateTimePicker components whose values need to be coordinated so the open_date never is larger than the due_date. Using react-widgets 3.4.6 and redux-form 6.8.0, these onChange handlers accomplished this:

    onOpenDateChange(event, newValue, previousValue) {
      const { formValues, now } = this.props
      const { due_date } = formValues
      if (newValue >= due_date || newValue < now) {
        event.preventDefault() // don't accept change
      }
    }
    
    onDueDateChange(event, newValue, previousValue) {
      const { formValues } = this.props
      const { open_date } = formValues
      if (newValue <= open_date) {
        event.preventDefault() // don't accept change
      }
    }

If I entered invalid values in the DateTimePicker input field, the redux store was not updated and the rejected value would be replaced with the previous (valid) value in the input field. 

With react-widgets 4.4.8 and redux-form 6.8.0,  the redux store is not updated but the invalid value is not replaced in the input field. I’m wondering what I can do in version  4.4.8 to replace the invalid value in the input field with the previous value.

**Comment by courtsimas** [comment]
Can you get a reference to the component and manually set its value if the conditional is true?

**Comment by softweave** [comment]
I wound up using react-widgets 3.4.6 until we switched to fornix, upgraded to react-widgets 4.4.9 and rewrote the event logic. Thanks for the suggestion though.
