### ISSUE TITLE
Arrow only shows when focused

### ISSUE THREAD

**Issue by sarahsmo** [jquense/react-widgets#913]
Users can easily get confused on how to interact with the multiselect because the arrow only shows when you focus inside the element:
![image](https://user-images.githubusercontent.com/31173144/52963184-1b100f80-336d-11e9-87e2-203fe3492702.png)
![image](https://user-images.githubusercontent.com/31173144/52963197-22cfb400-336d-11e9-9bfd-ba8f6bcef342.png)

I want to change it so the arrow is always visible
![image](https://user-images.githubusercontent.com/31173144/52963228-35e28400-336d-11e9-840a-41de6ad5e15a.png)
that way the user knows its a dropdown

**Comment by jquense** [comment]
The reason that there isn't a caret all the time, is that it's not a dropdown and i wanted to differentiate between this and the dropdown. it's closer to an autocomplete, in that the first action is to type, not select. Happy to make this configurable, or controllable via css tho if you don't want the behaviopr

**Comment by sarahsmo** [comment]
@jquense Ok! I understand, I am going to close my PR. Do you think you could add something to make it configurable so we can show it if we want to?

**Comment by Lascurettes** [comment]
I can confirm that with our user testing that users were indeed confused by this. They saw it as a text-input that they don't necessarily know the values to fill in. They remarked that if they saw it as a dropdown or some other affordance that let them know it would have pre-filled choices, they would have clicked into it.

**Comment by jquense** [comment]
> Do you think you could add something to make it configurable so we can show it if we want to?

I don't have the time right now to make this change but if you are willing I think, the change would be to always render the icon, but have a default css selector the `:not(.rw-state-focus) .rw-select { display: none: }`

For v5 we can swap the default since the selector is simpler in the inverse
