### ISSUE TITLE
Can't run yarn bootstrap

### ISSUE THREAD

**Issue by juspky** [jquense/react-widgets#916]
When attempting to fix https://github.com/jquense/react-widgets/issues/915 I realized that I can't get this project running.

**Steps to reproduce**
Clone Repo
`yarn run bootsrap`

build-localizer.js seems to cause problems
[lerna-debug.log](https://github.com/jquense/react-widgets/files/2885420/lerna-debug.log)

**Comment by ghost1face** [comment]
Ever figured this out? Just ran into it, thought it may have been because I was using nvm, tried about 6 different versions of node and still no luck.

**Comment by juspky** [comment]
No unfortunately never got it running.
I thought my environment was the issue and stopped bothering since @olmobrutall  already fixed #915
