### ISSUE TITLE
Dropdown List -- Show selected item in list

### ISSUE THREAD

**Issue by cleverettgirl** [jquense/react-widgets#926]
I was wondering if there's a way (which I currently do not see in the docs/Github issues) to open a dropdown list the currently selected item. When I have a very long list and select something towards the bottom and want to change that selection, it starts at the top. Thanks in advance!

**Comment by crutchcorn** [comment]
Was there a solution to this issue?

**Comment by cleverettgirl** [comment]
@crutchcorn I think you just need to add a value={selectedOption}
