### ISSUE TITLE
Multiselect onCreate={false} results in failed PropType

### ISSUE THREAD

**Issue by dahjelle** [jquense/react-widgets#93]
Looking at the example for [Multiselect](https://jquense.github.io/react-widgets/docs/#/multiselect/customTags), it appears that the demo sets `onCreate` to `false` when "Allow custom tags" is not checked. However, this results in a warning:

```
Warning: Failed propType: Invalid prop `onCreate` of type `boolean` supplied to `Multiselect`, expected `function`. Check the render method of `Multiselect`.
```

It looks like changing the `propTypes` in `Multiselect.js` from

```javascript
  onCreate: React.PropTypes.func,
```

to

```javascript
  onCreate: React.PropTypes.oneOf([false, React.PropTypes.func]),
```

fixes this.

Is that what should be happening? Or is there a better way to restrict the multiselect to the provided values?

**Comment by dahjelle** [comment]
To be clear: setting `onCreate` to `false` does exactly what I want to do, it just generates an apparently spurious warning.

**Comment by jquense** [comment]
Oops, yeah bit of an oversight there. thanks for the heads up
