### ISSUE TITLE
integrate DropdownList with Formik

### ISSUE THREAD

**Issue by MareoRaft** [jquense/react-widgets#933]
I attempted to to use Formik with a DropdownList element like so:

    <DropdownList
        inputProps: {{
            name: 'myval',
            onChange: handleChange,
            onBlur: handleBlur,
            value: values.myval,
        }}
        data={CONSTANT.VALS}
    />

Unfortunately, Formik did not get updated with the new value when the user picks a new value from the dropdown list.  I have successfully used Formik on a plain-old `input` element and a plain-old `select` element.

Assuming inputProps passes the props down correctly, I feel that writing a wrapper around the handleChange function might be enough to fix the issue.  Do you have any insights into this?  Do you know of any examples I could follow?

**Comment by jquense** [comment]
no use inputProps. You should be able to pass the field props directly to dropdownlist and it will work. e.g `<Field>` would work out of the box

**Comment by QuangTrungK15** [comment]
i also has problem above, anyone who can help me please ? :(
