### ISSUE TITLE
Explicitly set widget-background to white

### ISSUE THREAD

**Issue by LinuCC** [jquense/react-widgets#94]
Some browsers use the OS's theming, for example firefox uses my dark GTK theme on Linux.
This leads to input that is dark by default.
react-widgets does not explicitly set the background-color of the widgets, but bootstrap itself does.
The input-fields get a bit inconsistent as a result:

![example](https://cloud.githubusercontent.com/assets/6419353/7254979/a166dcec-e846-11e4-9451-5a7955bda652.png)

Especially multi-selects get a bit ugly:

![example2](https://cloud.githubusercontent.com/assets/6419353/7255099/7aa4e3f0-e847-11e4-81f3-74cc478e2e0f.png)

Should be solved with something like

    .rw-widget .rw-input {
        background-color: #FFF;
    }

**Comment by brigand** [comment]
Don't css resets cover this?

**Comment by LinuCC** [comment]
Indeed, but bootstrap resets the defaults for its own elements, so I personally never had to include them manually.
The same is the case for every bootstrap-plugin I have used so far.
It makes sense (at least for me ;) ) to include this change for consistency, since many people use this plugin without changing the style and expect the theme to behave the same as bootstrap.

**Comment by jquense** [comment]
> It makes sense (at least for me ;) ) to include this change for consistency, since many people use this plugin without changing the style and expect the theme to behave the same as bootstrap.

I agree, in fact there is already an @input-bg LESS variable in the theme that just isn't getting used, so this might even just be an oversight by me, and not a design choice.
