### ISSUE TITLE
unpkg dist

### ISSUE THREAD

**Issue by malay-15** [jquense/react-widgets#941]
Hi,

I am using ReactJS using script tag (https://unpkg.com/react@16.7.0/umd/react.production.min.js and others). Is there any way to use MultiSelect widget using the unpkg packages?

Thanks in advance.

**Comment by jquense** [comment]
yes you can use the https://unpkg.com/react-widgets@4.4.11/dist/react-widgets.js for the browser build, but it's not recommended b/c it includes the entire suite. Use the modules for individual components
