### ISSUE TITLE
Adding support for flow

### ISSUE THREAD

**Issue by SukantPal** [jquense/react-widgets#942]
I think this project could integrate with Flow types. If you agree, I would like to submit a PR that will add flow.

**Comment by jquense** [comment]
Thanks for the offer but I don't I want to maintain flow types. If we added any types they should probably be typescript one since it's far more popular (and what I use so selfish preference as well)

**Comment by SukantPal** [comment]
I guess I'll be working on it in flow-typed project. Thanks.
