### ISSUE TITLE
Clicking (anywhere) does not close Multiselect or Dropdownlist

### ISSUE THREAD

**Issue by luketgriffith** [jquense/react-widgets#944]
Using latest version with a fresh install. We just upgraded our version of this package and React. Selecting correctly selects the item, but the components do not close. Also, clicking anywhere outside the components does not close them. This happens even when using a blank component with an empty list & no other options.

**Comment by jquense** [comment]
I'm not seeing that locally or in the docs, can you put together a repro?

**Comment by luketgriffith** [comment]
Well i'm unable to recreate it on anything that i can share here... Probably something in our project
