### ISSUE TITLE
DropdownList hover should change rw-state-focus element

### ISSUE THREAD

**Issue by brandoncc** [jquense/react-widgets#946]
Hi, thanks for this really nice project. I find it very weird that when you open a DropdownList, the first element is always selected (with the obvious border styling by default), and hovering has no effect on it. A traditional select dropdown will let you change the "active" option either with the keyboard or hovering an option, and each continues where the other left off. Your widget considers those two things completely separate.

Is there a reason for this, or was it merely an oversight?

In the meantime, I did this for anyone else who might have this concern:

```sass
.my-dropdown-parent:hover
  .rw-list-option.rw-state-focus
    border-color: transparent
```

Just know that it doesn't actually fix the problem, as the `state-focus`'d element is just not shown in a border while hovering over the element.

**Comment by jquense** [comment]
It's intentional bc focus can be distinct from hovering for keyboard navigation. That said they've been consolidated in the v5 betas if you wanna give that a try
