### ISSUE TITLE
Multiselect searchTerm resets with onChange

### ISSUE THREAD

**Issue by musitechnica** [jquense/react-widgets#947]
In Multiselect, it appears that searchTerm is always reset after the onChange handler finishes. Is it possible to allow for persistent searchTerm after triggering onChange? If a search for "foo" has 10 results and one is selected, how can "foo" persist so we can continue selecting from the remaining result set without having to retype the searchTerm? #

**Comment by musitechnica** [comment]
After some more digging, the problem still exists, but I think my perspective and understanding have changed. I don't know that searchTerm is involved at all. Essentially, I want the existing filter, if any, to persist after selecting an item. Is this possible?

**Comment by jquense** [comment]
Yes! You have complete control over when the `searchTerm` by _controlling_ it and passing it back in. In particular `onSearch` fires with a metadata object that gives context for why the new value is being set. you can choose to ignore `clear`'s by not passing them through, and then manually clear when the input loses focus or whatever other criteria you want
