### ISSUE TITLE
date-fns localizer not using right default formats

### ISSUE THREAD

**Issue by isab** [jquense/react-widgets#949]
Hi! I'm using the `DateTimePicker` with the `date-fns` localizer. I think these `defaultFormats` are all wrong. https://github.com/jquense/react-widgets/blob/master/packages/localizer-date-fns/localizer.js#L31

I had to replace most of the formats with valid `date-fns` formats.

original
```
export const defaultFormats = {
  date: 'P',
  time: 'pp',
  default: 'Pp',
  header: 'MMMM yyyy',
  footer: 'PPPP',
  weekday: 'cccccc',
  dayOfMonth: 'dd',
  month: 'MMM',
  year: 'yyyy',
  decade: decade,
  century: century,
}
```

my version
```
const formats = Object.assign(defaultFormats, {
  dayOfMonth: 'D',
  header: 'MMM YYYY',
  footer: 'dddd, MMMM D, YYYY',
  time: 'h:mmA',
  weekday: 'ddd'
});
```

`date-fns` formats from their docs:
https://date-fns.org/v1.30.1/docs/format

I could be doing something totally wrong too, but I wanted to check and see if anyone else was having this issue?

**Comment by jquense** [comment]
hi there, i don't use datefns personal so i'm unsure if they are correct or not :|

**Comment by FelixPriori** [comment]
> Hi! I'm using the `DateTimePicker` with the `date-fns` localizer. I think these `defaultFormats` are all wrong. https://github.com/jquense/react-widgets/blob/master/packages/localizer-date-fns/localizer.js#L31
> 
> I had to replace most of the formats with valid `date-fns` formats.
> 
> original
> 
> ```
> export const defaultFormats = {
>   date: 'P',
>   time: 'pp',
>   default: 'Pp',
>   header: 'MMMM yyyy',
>   footer: 'PPPP',
>   weekday: 'cccccc',
>   dayOfMonth: 'dd',
>   month: 'MMM',
>   year: 'yyyy',
>   decade: decade,
>   century: century,
> }
> ```
> 
> my version
> 
> ```
> const formats = Object.assign(defaultFormats, {
>   dayOfMonth: 'D',
>   header: 'MMM YYYY',
>   footer: 'dddd, MMMM D, YYYY',
>   time: 'h:mmA',
>   weekday: 'ddd'
> });
> ```
> 
> `date-fns` formats from their docs:
> https://date-fns.org/v1.30.1/docs/format
> 
> I could be doing something totally wrong too, but I wanted to check and see if anyone else was having this issue?

Thank you so much, I was having the same issue.
