### ISSUE TITLE
Multiselect does not open on container tap

### ISSUE THREAD

**Issue by jkrentz** [jquense/react-widgets#95]
When tapping to open a multiselect, you must tap the input element; tapping the container does not trigger it to open.

Testing with an iPad IOS 8.1

**Comment by jkrentz** [comment]
Found the issue here: https://github.com/facebook/react/issues/134

Works with ```onTouchStart={this._maybeHandle(this._focus.bind(null, true), true)}``` if this needs to work without styling changes. Easier workaround was to style rw-multiselect-wrapper with cursor: pointer.

**Comment by jquense** [comment]
wow that's a crazy bug/feature.  Thanks for tracking it down for me, I don't have an ios device so it's tough to troubleshoot. do you know if onTouchStart would cause a double click on non ios devices? perhaps it makes sense to conditionally set it based on the user agent (ugh)?

**Comment by jquense** [comment]
also does `React.initializeTouchEvents(true);` fix this as is? it's sort of an obscure react API...

**Comment by jquense** [comment]
fixed in `2.6.1`
