### ISSUE TITLE
Localization for DatePicker Fails in version 5

### ISSUE THREAD

**Issue by karijarnot** [jquense/react-widgets#952]
Since configure no longer exists in version 5, setting the Date Localizer no longer works.

The documentation is still for version 4.

How does one configure the date localizer in version 5, or when can we expect the docs to be updated with that information?

**Comment by jquense** [comment]
check out how the storybook configures itself: https://github.com/jquense/react-widgets/blob/v5/packages/storybook/configure-globalize-old.js 

docs will be updated for the full release of v5

**Comment by critdhenz** [comment]
Hi @jquense , I also got this error **Error: Can't resolve 'react-widgets/lib/configure'** because the file is not there?

Thank you.
