### ISSUE TITLE
Can't close list of items

### ISSUE THREAD

**Issue by jaynicka-arrieta** [jquense/react-widgets#953]
Don't know if this is just me, but when I try to click on the arrow to close the dropdown on a combobox, it does absolutely nothing. Another problem I'm having is that clicking on the text area opens the dropdown, which I don't want. 
![activity_list_problem](https://user-images.githubusercontent.com/20608390/62154558-cb3e5880-b2bb-11e9-83b2-cacda711ee39.gif)

**Comment by jquense** [comment]
looks like you are missing the css?
