### ISSUE TITLE
integrate Combobox with Formik 

### ISSUE THREAD

**Issue by ldalvarado** [jquense/react-widgets#954]
How can I integrate the combobox component into the formiik so far I only have this :

`<Combobox
                              inputProps={{
                                  name: 'id',
                                  onChange: handleChange,
                                  onBlur: handleBlur,
                                  value: values.id,
                              }}
                              data={this.dataPerfil}
                              required
                              valueField='value'
                              textField='name'
                              defaultValue={0}
                              valid="false"
                            />`

**Comment by jquense** [comment]
Don't pass anything to inputProps. Just pass them to the combo box.it also looks like you value field is I'd not `value` from what you have here
