### ISSUE TITLE
Error: Can't resolve 'react-widgets/lib/configure'

### ISSUE THREAD

**Issue by critdhenz** [jquense/react-widgets#955]
Please refer to this error **ERROR in ./node_modules/react-widgets-moment/index.js
Module not found: Error: Can't resolve 'react-widgets/lib/configure'**. SInce the configure file is no longer exist.

Thanks!

**Comment by williambauch** [comment]
same problem here.

**Comment by jquense** [comment]
not sure how v5 prereleases got to latest but it's fixed now

**Comment by critdhenz** [comment]
How did you fixed it? It is still an error on my end. I got the latest release. Thanks

**Comment by jquense** [comment]
The v5 releases are betas I'd use v4 still

**Comment by critdhenz** [comment]
Okay. Thank you.

**Comment by yeahmat** [comment]
if using v5,  this error will also arise if `react-widgets-moment` is out-of-date
