### ISSUE TITLE
react-widgets-date-fns support date-fns 2.0 stable release

### ISSUE THREAD

**Issue by kristho91** [jquense/react-widgets#960]
It would be nice if react-widgets-date-fns could support stable release of date-fns ^2.0

**Comment by jquense** [comment]
would love too, unfortunately i don't often use date-fn's so not sure where to begin updating the localizer. If you'd like send a PR i'd be happy to merge it 👍

**Comment by atomicpages** [comment]
#964 fixes this

**Comment by kristho91** [comment]
Sorry for reopening this, but it seems that this change has been reverted to a peerDep for date-fns 2.0.0-alpha.13 at some point.
date-fns is at ^2.16.1 in the devDeps. Could this be fixed again? :)

**Comment by kristho91** [comment]
@jquense Could you re-open this? :)
