### ISSUE TITLE
React deprecation warnings

### ISSUE THREAD

**Issue by kristho91** [jquense/react-widgets#970]
When using react-widgets 4.4.11 I am getting deprecation warnings in my log.

This is due to : https://github.com/jquense/uncontrollable/issues/32 .

Any way we can push this forward and fix this issue?

**Comment by leebradley** [comment]
Looks like the issue was fixed and released an hour ago in the uncontrollable library 🎉

The react-widgets uncontrollable seems pretty out of date though. The package.json is still referencing uncontrollable ^5.0.0. The version of uncontrollable with the fix is 7.0.2.
