### ISSUE TITLE
Multiselect component types assume an element

### ISSUE THREAD

**Issue by AaronBuxbaum** [jquense/react-widgets#973]
Multiselect types for internal components assume `React.ElementType`:
```
  tagComponent?: React.ElementType;

  tagOptionComponent?: React.ElementType;
```

when in fact, it works and makes sense to pass a `string` to these. `React.ReactNode` possibly?

**Comment by jquense** [comment]
ElementType should already include string as well as ComponentType?

**Comment by AaronBuxbaum** [comment]
this is a TS issue, not a react-widgets issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18051
