### ISSUE TITLE
name prop is not detected by Filed

### ISSUE THREAD

**Issue by Muhzn** [jquense/react-widgets#977]
I cannot access the filed using name. Unable to read or write value into the filed by accessing through the name
```
<Field
                  name="education"
                  component={DropdownList}
                  data={educationList}
                  valueField="value"
                  textField="edu"
/>
```
While inspecting, name="education"  is not found anywhere
```
<div class="rw-widget-input rw-widget-picker rw-widget-container">
<div class="rw-input rw-dropdown-list-input">
      <input tabindex="-1" class="rw-dropdown-list-autofill rw-detect-autofill rw-sr" value="">
</div>
<span class="rw-select">
<button role="presentational" aria-hidden="true" tabindex="-1" title="open dropdown" type="button" aria-disabled="false" aria-label="open dropdown" class="rw-btn rw-btn-select">
<span aria-hidden="true" class="rw-i rw-i-caret-down"></span>
</button>
</span>
</div>
```
Is there anything I am missing? or this is'nt the right way to access the field?

**Comment by jquense** [comment]
What is `Field`? It looks like that component is stealing `name` from the DropdownList

**Comment by Muhzn** [comment]
> What is `Field`? It looks like that component is stealing `name` from the DropdownList

`Field` is from `redux-form`.
I am following this tutorial
https://redux-form.com/6.0.0-rc.4/examples/react-widgets/

**Comment by jquense** [comment]
I don't really know anything about redux-form, but the `name` prop works on DropdownList, but the Field seems to be stealing it. Maybe check with that repo for some help on how to pass it through?
