### ISSUE TITLE
Unable to change icon on select button in combobox

### ISSUE THREAD

**Issue by Shelagh-Lewins** [jquense/react-widgets#984]
I'm using the Combobox component from this great library, but I can't figure out how to change the icon on the select button from caret down to search.

It seems like this should be possible; the[ doc](http://jquense.github.io/react-widgets/api/Combobox/) mentions the selectIcon option - but there is no example and I can't make anything work. If I do the following then the button simply shows the text 'search'.

```
<Combobox
	selectIcon="search"
/>
```

It looks from the css like the way to change the icon would be to change the class of the span inside the button element from .rw-i-caret-down to .rw-i-search, but again I can't see a way to do this.

I must be missing something obvious, but can't find anything in the docs or examples. How can I change the icon please?

**Comment by jquense** [comment]
this is configurable now (many years later)
