### ISSUE TITLE
configure option for font awesome prefix

### ISSUE THREAD

**Issue by onelson** [jquense/react-widgets#99]
I was hoping to import the react-widget less sources into my own so that I could override the icon font prefix setting - this worked ok until I realized the js was still throwing rw-i into the components it provided.

Perhaps you could expose a way for us to set the prefix on the js side?

**Comment by jquense** [comment]
Hey there thanks for the issue, 

I can try and think of a good API for that, though it may not be necessary.  the fonts bundled with react widgets just contain the 5 fonts I use so the bytes should be minimal. I suppose It'd still be nice to save a request... it might be easier however to just redefine the the really minimal font awesome styles I use to point to yours and just leave off the icons.less I provide

**Comment by onelson** [comment]
Got it. Good to know. I'll look at reimplementing the classes you've supplied and overriding. Thanks for the tip!
