### ISSUE TITLE
Multiselect: "create new" does not select the new option after created

### ISSUE THREAD

**Issue by damusix** [jquense/react-widgets#992]
Not sure if this is a bug or feature request.

Given the option of `allowCreate="onFilter"`
There should be an option to select the new option after it has been created.

**Comment by jquense** [comment]
There isn't a way to do that really the widget has no idea which item is the new one without trying to diff `data` the next time it changes after `onCreate`, A simpler approach would to pass the new item to `value` yourself

**Comment by damusix** [comment]
Let me try this

**Comment by jquense** [comment]
the demo's and example code also so how you might implement it

**Comment by damusix** [comment]
@jquense So tried this and still not able to get it to work
