### ISSUE TITLE
Manually editing a time loses default date in change event

### ISSUE THREAD

**Issue by benjiew** [jquense/react-widgets#994]
We noticed an odd scenario when testing the DateTimePicker today.

To reproduce if you enable the time picker but also initialise the defaultCurrentDate (in our case we want to keep the date part but not update it). We set the format to "hh:mm A".

When selecting a time from the picker, in the onChange event, the **date** parameter's date portion is set to the defaultCurrentDate value and the **str** parameter is whatever time has been selected which is as expected.

However if you manually enter a time, the **date** parameter's date portion is set to today's date and the **str** parameter is whatever time you have entered.

To get around this we've had to call dates.merge(null, date, defaultCurrentDate) in the onChange handler - so this is essentially called twice when selecting a time (following the handleTimeSelect handler).

**Comment by Oliv** [comment]
Hello there,

I ran into the exact same problem today, if the format has the date it works well, but if the format only has time it resets the date to today's date with manual editing.

Could you explain a little more your workaround (dates.merge(null, date, defaultCurrentDate)) ?

Best regards, Olivier
